emsr::extrapolation_table< AreaTp, AbsAreaTp > Class Template Reference
#include <extrapolation_table.h>
Public Member Functions
extrapolation_table ()
extrapolation_table (AreaTp y)
void append (AreaTp y)
std::size_t get_nn () const
std::tuple< AreaTp, AbsAreaTp > qelg ()
Detailed Description
template<typename AreaTp, typename AbsAreaTp>
class emsr::extrapolation_table< AreaTp, AbsAreaTp >
Definition at line 38 of file extrapolation_table.h.
Constructor & Destructor Documentation
extrapolation_table() [1/2]
template<typename AreaTp , typename AbsAreaTp >
emsr::extrapolation_table< AreaTp, AbsAreaTp >::extrapolation_table () [inline]
Definition at line 52 of file extrapolation_table.h.
      : m_nn(0),
        m_nres(0)
      {
        // Try to adjust tests for varing precision?
        // I don't think this is a precision-sensitive limit.
        //this->m_irreg_test = std::pow(AbsAreaTp{10},
        // -std::numeric_limits<AbsAreaTp>::digits10 / AbsAreaTp{4.0});
      }
extrapolation_table() [2/2]
template<typename AreaTp , typename AbsAreaTp >
emsr::extrapolation_table< AreaTp, AbsAreaTp >::extrapolation_table (AreaTp y) [inline], [explicit]
Definition at line 62 of file extrapolation_table.h.
      : m_nn(0),
        m_nres(0)
      { this->append(y); }
References emsr::extrapolation_table< AreaTp, AbsAreaTp >::append().
Member Function Documentation
append()
template<typename AreaTp , typename AbsAreaTp >
void emsr::extrapolation_table< AreaTp, AbsAreaTp >::append (AreaTp y) [inline]
Definition at line 68 of file extrapolation_table.h.
      {
        if (this->m_nn < this->m_rlist2.size())
          {
            this->m_rlist2[this->m_nn] = y;
            ++this->m_nn;
          }
      }
Referenced by emsr::extrapolation_table< AreaTp, AbsAreaTp >::extrapolation_table(), emsr::qagp_integrate(), emsr::qags_integrate(), emsr::qawf_integrate(), and emsr::qawo_integrate().
get_nn()
template<typename AreaTp , typename AbsAreaTp >
std::size_t emsr::extrapolation_table< AreaTp, AbsAreaTp >::get_nn () const [inline]
Definition at line 80 of file extrapolation_table.h.
      { return this->m_nn; }
Referenced by emsr::qagp_integrate(), emsr::qags_integrate(), emsr::qawf_integrate(), and emsr::qawo_integrate().
qelg()
template<typename AreaTp , typename AbsAreaTp >
std::tuple< AreaTp, AbsAreaTp > emsr::extrapolation_table< AreaTp, AbsAreaTp >::qelg
Definition at line 33 of file extrapolation_table.tcc.
    {
      const auto cur_n = this->m_nn - 1;
      const auto current = this->m_rlist2[cur_n];
      const auto s_eps = std::numeric_limits<AbsAreaTp>::epsilon();
      // Less than max to prevent overflow.
      const auto s_max = std::numeric_limits<AbsAreaTp>::max() / AbsAreaTp{100};
      auto absolute = s_max;
      auto relative = AbsAreaTp{5} * s_eps * std::abs(current);
      const auto newelm = cur_n / 2;
      const auto n_orig = cur_n;
      auto n_final = cur_n;
      const auto nres_orig = this->m_nres;
      auto result = current;
      auto abserr = s_max;
      if (cur_n < 2)
        {
          result = current;
          abserr = std::max(absolute, relative);
          return std::make_tuple(result, abserr);
        }
      this->m_rlist2[cur_n + 2] = this->m_rlist2[cur_n];
      this->m_rlist2[cur_n] = s_max;
      for (size_t ii = 0; ii < newelm; ++ii)
        {
          auto res = this->m_rlist2[cur_n - 2 * ii + 2];
          const auto e0 = this->m_rlist2[cur_n - 2 * ii - 2];
          const auto e1 = this->m_rlist2[cur_n - 2 * ii - 1];
          const auto e2 = res;
          const auto e1abs = std::abs(e1);
          const auto delta2 = e2 - e1;
          const auto err2 = std::abs(delta2);
          const auto tol2 = std::max(std::abs(e2), e1abs) * s_eps;
          const auto delta3 = e1 - e0;
          const auto err3 = std::abs(delta3);
          const auto tol3 = std::max(e1abs, std::abs(e0)) * s_eps;
          if (err2 <= tol2 && err3 <= tol3)
            {
              // If e0, e1 and e2 are equal to within machine accuracy,
              // convergence is assumed.
              result = res;
              absolute = err2 + err3;
              relative = 5 * s_eps * std::abs(res);
              abserr = std::max(absolute, relative);
              return std::make_tuple(result, abserr);
            }
          const auto e3 = this->m_rlist2[cur_n - 2 * ii];
          this->m_rlist2[cur_n - 2 * ii] = e1;
          const auto delta1 = e1 - e3;
          const auto err1 = std::abs(delta1);
          const auto tol1 = std::max(e1abs, std::abs(e3)) * s_eps;
          // If two elements are very close to each other, omit a part of
          // the table by adjusting the value of n.
          if (err1 <= tol1 || err2 <= tol2 || err3 <= tol3)
            {
              n_final = 2 * ii;
              break;
            }
          const auto ss = AbsAreaTp{1} / delta1 + AbsAreaTp{1} / delta2
                          - AbsAreaTp{1} / delta3;
          // Test to detect irregular behaviour in the table,
          // and eventually omit a part of the table by adjusting
          // the value of n.
          if (std::abs(ss * e1) <= this->m_irreg_test)
            {
              n_final = 2 * ii;
              break;
            }
          // Compute a new element and eventually adjust the value of result.
          res = e1 + AbsAreaTp{1} / ss;
          this->m_rlist2[cur_n - 2 * ii] = res;
          {
            const auto error = err2 + std::abs(res - e2) + err3;
            if (error <= abserr)
              {
                abserr = error;
                result = res;
              }
          }
        }
      // Shift the table.
      {
        const size_t limexp = 50 - 1;
        if (n_final == limexp)
          n_final = 2 * (limexp / 2);
      }
      if (n_orig % 2 == 1)
        {
          for (size_t ii = 0; ii <= newelm; ++ii)
            this->m_rlist2[ii * 2 + 1] = this->m_rlist2[ii * 2 + 3];
        }
      else
        {
          for (size_t ii = 0; ii <= newelm; ++ii)
            this->m_rlist2[ii * 2] = this->m_rlist2[ii * 2 + 2];
        }
      if (n_orig != n_final)
        {
          for (size_t ii = 0; ii <= n_final; ++ii)
            this->m_rlist2[ii] = this->m_rlist2[ii + n_orig - n_final];
        }
      this->m_nn = n_final + 1;
      if (nres_orig < 3)
        {
          this->m_res3la[nres_orig] = result;
          abserr = s_max;
        }
      else
        { // Compute error estimate.
          abserr = (std::abs(result - this->m_res3la[2])
                    + std::abs(result - this->m_res3la[1])
                    + std::abs(result - this->m_res3la[0]));
          this->m_res3la[0] = this->m_res3la[1];
          this->m_res3la[1] = this->m_res3la[2];
          this->m_res3la[2] = result;
        }
      /* In QUADPACK the variable table->nres is incremented at the top of
        qelg, so it increases on every call. This leads to the array
        res3la being accessed when its elements are still undefined, so I
        have moved the update to this point so that its value more
        useful. */
      this->m_nres = nres_orig + 1;
      abserr = std::max(abserr, 5 * s_eps * std::abs(result));
      return std::make_tuple(result, abserr);
    }
Referenced by emsr::qagp_integrate(), emsr::qags_integrate(), emsr::qawf_integrate(), and emsr::qawo_integrate().
The documentation for this class was generated from the following files:
include/emsr/extrapolation_table.h
include/emsr/extrapolation_table.tcc