emsr::midpoint_integral< Tp, FuncTp > Class Template Reference
#include <midpoint_integral.h>
Public Types
using AbsAreaTp = decltype(std::abs(AreaTp{}))
using AreaTp = decltype(RetTp{} *Tp{})
using RetTp = std::invoke_result_t< FuncTp, Tp >
Public Member Functions
midpoint_integral (FuncTp fun, Tp lower, Tp upper, Tp abs_tol, Tp rel_tol)
AbsAreaTp abs_error () const
template<typename FuncTp2 >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp2, Tp > > integrate (FuncTp2 fun, Tp lower, Tp upper)
AreaTp operator() ()
template<typename FuncTp2 >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp2, Tp > > operator() (FuncTp2 fun, Tp lower, Tp upper)
Detailed Description
template<typename Tp, typename FuncTp>
class emsr::midpoint_integral< Tp, FuncTp >
A globally adaptive recursive midpoint integrator.
Definition at line 73 of file midpoint_integral.h.
Member Typedef Documentation
AbsAreaTp
template<typename Tp , typename FuncTp >
using emsr::midpoint_integral< Tp, FuncTp >::AbsAreaTp = decltype(std::abs(AreaTp{}))
Definition at line 79 of file midpoint_integral.h.
AreaTp
template<typename Tp , typename FuncTp >
using emsr::midpoint_integral< Tp, FuncTp >::AreaTp = decltype(RetTp{} * Tp{})
Definition at line 78 of file midpoint_integral.h.
RetTp
template<typename Tp , typename FuncTp >
using emsr::midpoint_integral< Tp, FuncTp >::RetTp = std::invoke_result_t<FuncTp, Tp>
Definition at line 77 of file midpoint_integral.h.
Constructor & Destructor Documentation
midpoint_integral()
template<typename Tp , typename FuncTp >
emsr::midpoint_integral< Tp, FuncTp >::midpoint_integral (FuncTp fun, Tp lower, Tp upper, Tp abs_tol, Tp rel_tol) [inline]
Definition at line 81 of file midpoint_integral.h.
      : m_fun(fun), m_lower_lim(lower), m_upper_lim(upper),
        m_abs_tol(std::abs(abs_tol)), m_rel_tol(std::abs(rel_tol)),
        m_result(), m_abs_error()
      { }
Member Function Documentation
abs_error()
template<typename Tp , typename FuncTp >
AbsAreaTp emsr::midpoint_integral< Tp, FuncTp >::abs_error () const [inline]
Definition at line 90 of file midpoint_integral.h.
      { return this->m_abs_error; }
Referenced by emsr::midpoint_integral< Tp, FuncTp >::integrate(), and emsr::integrate_midpoint().
integrate()
template<typename Tp , typename FuncTp >
template<typename FuncTp2 >
adaptive_integral_t<Tp, std::invoke_result_t<FuncTp2, Tp> > emsr::midpoint_integral< Tp, FuncTp >::integrate (FuncTp2 fun, Tp lower, Tp upper) [inline]
Definition at line 95 of file midpoint_integral.h.
        {
          midpoint_integral<FuncTp2, Tp>
            mpi(fun, lower, upper,
                  this->m_abs_tol, this->m_rel_tol);
          return {mpi(), mpi.abs_error() };
        }
References emsr::midpoint_integral< Tp, FuncTp >::abs_error().
Referenced by emsr::midpoint_integral< Tp, FuncTp >::operator()().
operator()() [1/2]
template<typename Tp , typename FuncTp >
midpoint_integral< Tp, FuncTp >::AreaTp emsr::midpoint_integral< Tp, FuncTp >::operator()
Integrate the function by naive subdivision.
Definition at line 52 of file midpoint_integral.tcc.
    {
      auto sum_prev = this->m_step();
      for (std::size_t j = 1; j < s_max_iter; ++j)
        {
          const auto sum = this->m_step();
          this->m_abs_error = std::abs(sum - sum_prev);
          if (this->m_abs_error < this->m_rel_tol * std::abs(sum))
            return sum;
          if (j > 6
              && std::abs(sum) < this->m_rel_tol
              && std::abs(sum_prev) < this->m_rel_tol)
            return sum;
          sum_prev = sum;
        }
      return sum_prev;
    }
operator()() [2/2]
template<typename Tp , typename FuncTp >
template<typename FuncTp2 >
adaptive_integral_t<Tp, std::invoke_result_t<FuncTp2, Tp> > emsr::midpoint_integral< Tp, FuncTp >::operator() (FuncTp2 fun, Tp lower, Tp upper) [inline]
Definition at line 105 of file midpoint_integral.h.
        { return this->integrate(fun, lower, upper); }
References emsr::midpoint_integral< Tp, FuncTp >::integrate().
The documentation for this class was generated from the following files:
include/emsr/midpoint_integral.h
include/emsr/midpoint_integral.tcc