__gnu_cxx::fourier_transform_t< std::complex< _Tp > > Class Template Reference
#include <fourier_transform.h>
Public Member Functions
fourier_transform_t (std::size_t __n)
fourier_transform_t (const std::vector< std::complex< _Tp >> &__data)
std::complex< _Tp > operator[] (std::size_t __k) const
std::size_t size () const
Detailed Description
template<typename _Tp>
class __gnu_cxx::fourier_transform_t< std::complex< _Tp > >
Discrete Fourier transform specialization for transform of complex data.
Definition at line 190 of file fourier_transform.h.
Constructor & Destructor Documentation
fourier_transform_t() [1/2]
template<typename _Tp >
__gnu_cxx::fourier_transform_t< std::complex< _Tp > >::fourier_transform_t (std::size_t __n) [inline]
Definition at line 198 of file fourier_transform.h.
      : _M_xform{}
      { this->_M_xform.reserve(__n / 2 + 1); }
fourier_transform_t() [2/2]
template<typename _Tp >
__gnu_cxx::fourier_transform_t< std::complex< _Tp > >::fourier_transform_t (const std::vector< std::complex< _Tp >> & __data)
Member Function Documentation
operator[]()
template<typename _Tp >
std::complex<_Tp> __gnu_cxx::fourier_transform_t< std::complex< _Tp > >::operator[] (std::size_t __k) const [inline]
Definition at line 209 of file fourier_transform.h.
References __gnu_cxx::__discrete_fourier_transform(), __gnu_cxx::fast_fourier_transform(), __gnu_cxx::fast_sine_transform(), __gnu_cxx::inv_fast_fourier_transform(), and __gnu_cxx::inv_fast_sine_transform().
      { return this->_M_xform[__k]; }
size()
template<typename _Tp >
std::size_t __gnu_cxx::fourier_transform_t< std::complex< _Tp > >::size () const [inline]
Definition at line 205 of file fourier_transform.h.
      { return 2 * this->_M_xform.size() - 2; }
The documentation for this class was generated from the following file:
include/ext/fourier_transform.h