__gnu_cxx::simpson_integral< _Tp, _FuncTp > Class Template Reference
#include <simpson_integral.h>
Public Types
using _AbsAreaTp = decltype(std::abs(_AreaTp{}))
using _AreaTp = decltype(_RetTp{} *_Tp{})
using _RetTp = std::invoke_result_t< _FuncTp, _Tp >
Public Member Functions
simpson_integral (_FuncTp __fun, _Tp __a, _Tp __b, _Tp __abs_tol, _Tp __rel_tol)
_AbsAreaTp abs_error () const
template<typename _FuncTp2 >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp2, _Tp > > integrate (_FuncTp2 __fun, _Tp __a, _Tp __b)
_AreaTp operator() ()
template<typename _FuncTp2 >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp2, _Tp > > operator() (_FuncTp2 __fun, _Tp __a, _Tp __b)
Detailed Description
template<typename _Tp, typename _FuncTp>
class __gnu_cxx::simpson_integral< _Tp, _FuncTp >
A globally adaptive recursive Simpson integrator.
Definition at line 73 of file simpson_integral.h.
Member Typedef Documentation
_AbsAreaTp
template<typename _Tp, typename _FuncTp>
using __gnu_cxx::simpson_integral< _Tp, _FuncTp >::_AbsAreaTp = decltype(std::abs(_AreaTp{}))
Definition at line 79 of file simpson_integral.h.
_AreaTp
template<typename _Tp, typename _FuncTp>
using __gnu_cxx::simpson_integral< _Tp, _FuncTp >::_AreaTp = decltype(_RetTp{} * _Tp{})
Definition at line 78 of file simpson_integral.h.
_RetTp
template<typename _Tp, typename _FuncTp>
using __gnu_cxx::simpson_integral< _Tp, _FuncTp >::_RetTp = std::invoke_result_t<_FuncTp, _Tp>
Definition at line 77 of file simpson_integral.h.
Constructor & Destructor Documentation
simpson_integral()
template<typename _Tp, typename _FuncTp>
__gnu_cxx::simpson_integral< _Tp, _FuncTp >::simpson_integral (_FuncTp __fun, _Tp __a, _Tp __b, _Tp __abs_tol, _Tp __rel_tol) [inline]
Definition at line 81 of file simpson_integral.h.
References __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::operator()().
      : _M_fun(__fun), _M_lower_lim(__a), _M_upper_lim(__b),
        _M_abs_tol(std::abs(__abs_tol)), _M_rel_tol(std::abs(__rel_tol)),
        _M_result(), _M_abs_error()
      { }
Member Function Documentation
abs_error()
template<typename _Tp, typename _FuncTp>
_AbsAreaTp __gnu_cxx::simpson_integral< _Tp, _FuncTp >::abs_error () const [inline]
Definition at line 90 of file simpson_integral.h.
Referenced by __gnu_cxx::simpson_integral< _Tp, _FuncTp >::integrate(), and __gnu_cxx::integrate_simpson().
      { return this->_M_abs_error; }
integrate()
template<typename _Tp, typename _FuncTp>
template<typename _FuncTp2 >
adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp2, _Tp> > __gnu_cxx::simpson_integral< _Tp, _FuncTp >::integrate (_FuncTp2 __fun, _Tp __a, _Tp __b) [inline]
Definition at line 95 of file simpson_integral.h.
References __gnu_cxx::simpson_integral< _Tp, _FuncTp >::abs_error().
        {
          simpson_integral<_FuncTp2, _Tp>
            __simpi(__fun, __a, __b,
                    this->_M_abs_tol, this->_M_rel_tol);
          return {__simpi(), __simpi.abs_error() };
        }
operator()() [1/2]
template<typename _Tp , typename _FuncTp >
simpson_integral< _Tp, _FuncTp >::_AreaTp __gnu_cxx::simpson_integral< _Tp, _FuncTp >::operator() ()
Integrate the function by globally adaptive subdivision.
Definition at line 61 of file simpson_integral.tcc.
References __gnu_cxx::_Tp.
    {
      auto __simp_prev = this->_M_step();
      auto __sum_prev = __simp_prev;
      for (std::size_t __j = 1; __j <= _S_max_iter; ++__j)
        {
          const auto __simp = this->_M_step();
          const auto __sum = (_Tp{4} * __simp - __simp_prev) / _Tp{3};
          this->_M_abs_error = std::abs(__sum - __sum_prev);
          if (this->_M_abs_error < this->_M_rel_tol * std::abs(__sum))
            return __sum;
          if (__j > 6
                && std::abs(__sum) < this->_M_rel_tol
                && std::abs(__sum_prev) < this->_M_rel_tol)
            return __sum;
          __sum_prev = __sum;
          __simp_prev = __simp;
        }
      return __sum_prev;
    }
operator()() [2/2]
template<typename _Tp, typename _FuncTp>
template<typename _FuncTp2 >
adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp2, _Tp> > __gnu_cxx::simpson_integral< _Tp, _FuncTp >::operator() (_FuncTp2 __fun, _Tp __a, _Tp __b) [inline]
Definition at line 105 of file simpson_integral.h.
References __gnu_cxx::_Tp, and __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::integrate().
        { return this->integrate(__fun, __a, __b); }
The documentation for this class was generated from the following files:
include/ext/simpson_integral.h
include/ext/simpson_integral.tcc