__gnu_cxx::composite_simpson_integral< _Tp, _FuncTp > Class Template Reference
#include <simpson_integral.h>
Public Types
using _AbsAreaTp = decltype(std::abs(_AreaTp{}))
using _AreaTp = decltype(_RetTp{} *_Tp{})
using _RetTp = std::invoke_result_t< _FuncTp, _Tp >
Public Member Functions
composite_simpson_integral (_FuncTp __fun, _Tp __a, _Tp __b, std::size_t __num_segs)
template<typename _FuncTp2 >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp2, _Tp > > integrate (_FuncTp2 __fun, _Tp __a, _Tp __b)
_AreaTp operator() ()
Detailed Description
template<typename _Tp, typename _FuncTp>
class __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >
Definition at line 34 of file simpson_integral.h.
Member Typedef Documentation
_AbsAreaTp
template<typename _Tp, typename _FuncTp>
using __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::_AbsAreaTp = decltype(std::abs(_AreaTp{}))
Definition at line 40 of file simpson_integral.h.
_AreaTp
template<typename _Tp, typename _FuncTp>
using __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::_AreaTp = decltype(_RetTp{} * _Tp{})
Definition at line 39 of file simpson_integral.h.
_RetTp
template<typename _Tp, typename _FuncTp>
using __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::_RetTp = std::invoke_result_t<_FuncTp, _Tp>
Definition at line 38 of file simpson_integral.h.
Constructor & Destructor Documentation
composite_simpson_integral()
template<typename _Tp, typename _FuncTp>
__gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::composite_simpson_integral (_FuncTp __fun, _Tp __a, _Tp __b, std::size_t __num_segs) [inline]
Definition at line 42 of file simpson_integral.h.
References __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::operator()().
      : _M_fun(__fun), _M_lower_lim(__a), _M_upper_lim(__b),
        _M_num_segs(__num_segs), _M_result()
      { }
Member Function Documentation
integrate()
template<typename _Tp, typename _FuncTp>
template<typename _FuncTp2 >
fixed_integral_t<_Tp, std::invoke_result_t<_FuncTp2, _Tp> > __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::integrate (_FuncTp2 __fun, _Tp __a, _Tp __b) [inline]
Definition at line 52 of file simpson_integral.h.
References __gnu_cxx::_Tp.
Referenced by __gnu_cxx::simpson_integral< _Tp, _FuncTp >::operator()().
        {
          composite_simpson_integral<_FuncTp2, _Tp>
            __trapi(__fun, __a, __b, this->_M_num_segments);
          return {__trapi()};
        }
operator()()
template<typename _Tp , typename _FuncTp >
composite_simpson_integral< _Tp, _FuncTp >::_AreaTp __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::operator() ()
Integrate the function by naive subdivision.
Definition at line 33 of file simpson_integral.tcc.
References __gnu_cxx::_Tp.
Referenced by __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::composite_simpson_integral(), and __gnu_cxx::simpson_integral< _Tp, _FuncTp >::simpson_integral().
    {
      const auto __delta = (this->_M_upper_lim - this->_M_lower_lim)
                           / this->_M_num_segs / 2;
      auto __x = this->_M_lower_lim;
      auto __sum = this->_M_fun(__x);
      __x += __delta;
      __sum += _Tp{2} * this->_M_fun(__x);
      for (std::size_t __j = 1; __j < this->_M_num_segs; ++__j)
        {
          __x += __delta;
          __sum += _Tp{4} * this->_M_fun(__x);
          __x += __delta;
          __sum += _Tp{2} * this->_M_fun(__x);
        }
      __sum += this->_M_fun(this->_M_upper_lim);
      this->_M_result = __sum * __delta / _Tp{6};
      return this->_M_result;
    }
The documentation for this class was generated from the following files:
include/ext/simpson_integral.h
include/ext/simpson_integral.tcc