__gnu_cxx::extrapolation_table< _Tp > Class Template Reference
#include <extrapolation_table.h>
Public Member Functions
extrapolation_table ()
extrapolation_table (_Tp __y)
void append (_Tp __y)
std::size_t get_nn () const
std::tuple< _Tp, _Tp > qelg ()
Detailed Description
template<typename _Tp>
class __gnu_cxx::extrapolation_table< _Tp >
Definition at line 40 of file extrapolation_table.h.
Constructor & Destructor Documentation
extrapolation_table() [1/2]
template<typename _Tp>
__gnu_cxx::extrapolation_table< _Tp >::extrapolation_table () [inline]
Definition at line 54 of file extrapolation_table.h.
      : _M_nn(0),
        _M_nres(0)
      {
        // Try to adjust tests for varing precision?
        // I don't think this is a precision-sensitive limit.
        //this->_M_irreg_test = std::pow(10.0,
        // -std::numeric_limits<_Tp>::digits10 / 4.0);
      }
extrapolation_table() [2/2]
template<typename _Tp>
__gnu_cxx::extrapolation_table< _Tp >::extrapolation_table (_Tp __y) [inline], [explicit]
Definition at line 64 of file extrapolation_table.h.
References __gnu_cxx::extrapolation_table< _Tp >::append().
      : _M_nn(0),
        _M_nres(0)
      { this->append(__y); }
Member Function Documentation
append()
template<typename _Tp>
void __gnu_cxx::extrapolation_table< _Tp >::append (_Tp __y) [inline]
Definition at line 70 of file extrapolation_table.h.
References __gnu_cxx::extrapolation_table< _Tp >::qelg().
Referenced by __gnu_cxx::extrapolation_table< _Tp >::extrapolation_table(), __gnu_cxx::qagp_integrate(), __gnu_cxx::qags_integrate(), __gnu_cxx::qawf_integrate(), and __gnu_cxx::qawo_integrate().
      {
        if (this->_M_nn < this->_M_rlist2.size())
          {
            this->_M_rlist2[this->_M_nn] = __y;
            ++this->_M_nn;
          }
      }
get_nn()
template<typename _Tp>
std::size_t __gnu_cxx::extrapolation_table< _Tp >::get_nn () const [inline]
Definition at line 83 of file extrapolation_table.h.
Referenced by __gnu_cxx::qagp_integrate(), __gnu_cxx::qags_integrate(), __gnu_cxx::qawf_integrate(), and __gnu_cxx::qawo_integrate().
      { return this->_M_nn; }
qelg()
template<typename _Tp >
std::tuple< _Tp, _Tp > __gnu_cxx::extrapolation_table< _Tp >::qelg ()
Definition at line 35 of file extrapolation_table.tcc.
References __gnu_cxx::__abserr, __gnu_cxx::__result, and __gnu_cxx::_Tp.
Referenced by __gnu_cxx::extrapolation_table< _Tp >::append(), __gnu_cxx::qagp_integrate(), __gnu_cxx::qags_integrate(), __gnu_cxx::qawf_integrate(), and __gnu_cxx::qawo_integrate().
    {
      const auto __cur_n = this->_M_nn - 1;
      const auto __current = this->_M_rlist2[__cur_n];
      const auto _S_eps = std::numeric_limits<_Tp>::epsilon();
      // Less than max to prevent overflow.
      const auto _S_max = std::numeric_limits<_Tp>::max() / _Tp{100};
      auto __absolute = _S_max;
      auto __relative = 5 * _S_eps * std::abs(__current);
      const auto __newelm = __cur_n / 2;
      const auto __n_orig = __cur_n;
      auto __n_final = __cur_n;
      const auto __nres_orig = this->_M_nres;
      auto __result = __current;
      auto __abserr = _S_max;
      if (__cur_n < 2)
        {
          __result = __current;
          __abserr = std::max(__absolute, __relative);
          return std::make_tuple(__result, __abserr);
        }
      this->_M_rlist2[__cur_n + 2] = this->_M_rlist2[__cur_n];
      this->_M_rlist2[__cur_n] = _S_max;
      for (size_t __ii = 0; __ii < __newelm; ++__ii)
        {
          auto __res = this->_M_rlist2[__cur_n - 2 * __ii + 2];
          const auto __e0 = this->_M_rlist2[__cur_n - 2 * __ii - 2];
          const auto __e1 = this->_M_rlist2[__cur_n - 2 * __ii - 1];
          const auto __e2 = __res;
          const auto __e1abs = std::abs(__e1);
          const auto __delta2 = __e2 - __e1;
          const auto __err2 = std::abs(__delta2);
          const auto __tol2 = std::max(std::abs(__e2), __e1abs) * _S_eps;
          const auto __delta3 = __e1 - __e0;
          const auto __err3 = std::abs(__delta3);
          const auto __tol3 = std::max(__e1abs, std::abs(__e0)) * _S_eps;
          if (__err2 <= __tol2 && __err3 <= __tol3)
            {
              // If e0, e1 and e2 are equal to within machine accuracy,
              // convergence is assumed.
              __result = __res;
              __absolute = __err2 + __err3;
              __relative = 5 * _S_eps * std::abs(__res);
              __abserr = std::max(__absolute, __relative);
              return std::make_tuple(__result, __abserr);
            }
          const auto __e3 = this->_M_rlist2[__cur_n - 2 * __ii];
          this->_M_rlist2[__cur_n - 2 * __ii] = __e1;
          const auto __delta1 = __e1 - __e3;
          const auto __err1 = std::abs(__delta1);
          const auto __tol1 = std::max(__e1abs, std::abs(__e3)) * _S_eps;
          // If two elements are very close to each other, omit a part of
          // the table by adjusting the value of n.
          if (__err1 <= __tol1 || __err2 <= __tol2 || __err3 <= __tol3)
            {
              __n_final = 2 * __ii;
              break;
            }
          const auto __ss = _Tp{1} / __delta1 + _Tp{1} / __delta2
                          - _Tp{1} / __delta3;
          // Test to detect irregular behaviour in the table,
          // and eventually omit a part of the table by adjusting
          // the value of n.
          if (std::abs(__ss * __e1) <= this->_M_irreg_test)
            {
              __n_final = 2 * __ii;
              break;
            }
          // Compute a new element and eventually adjust the value of result.
          __res = __e1 + _Tp{1} / __ss;
          this->_M_rlist2[__cur_n - 2 * __ii] = __res;
          {
            const auto __error = __err2 + std::abs(__res - __e2) + __err3;
            if (__error <= __abserr)
              {
                __abserr = __error;
                __result = __res;
              }
          }
        }
      // Shift the table.
      {
        const size_t __limexp = 50 - 1;
        if (__n_final == __limexp)
          __n_final = 2 * (__limexp / 2);
      }
      if (__n_orig % 2 == 1)
        {
          for (size_t __ii = 0; __ii <= __newelm; ++__ii)
            this->_M_rlist2[__ii * 2 + 1] = this->_M_rlist2[__ii * 2 + 3];
        }
      else
        {
          for (size_t __ii = 0; __ii <= __newelm; ++__ii)
            this->_M_rlist2[__ii * 2] = this->_M_rlist2[__ii * 2 + 2];
        }
      if (__n_orig != __n_final)
        {
          for (size_t __ii = 0; __ii <= __n_final; ++__ii)
            this->_M_rlist2[__ii] = this->_M_rlist2[__ii + __n_orig - __n_final];
        }
      this->_M_nn = __n_final + 1;
      if (__nres_orig < 3)
        {
          this->_M_res3la[__nres_orig] = __result;
          __abserr = _S_max;
        }
      else
        { // Compute error estimate.
          __abserr = (std::abs(__result - this->_M_res3la[2])
                    + std::abs(__result - this->_M_res3la[1])
                    + std::abs(__result - this->_M_res3la[0]));
          this->_M_res3la[0] = this->_M_res3la[1];
          this->_M_res3la[1] = this->_M_res3la[2];
          this->_M_res3la[2] = __result;
        }
      /* In QUADPACK the variable table->nres is incremented at the top of
        qelg, so it increases on every call. This leads to the array
        res3la being accessed when its elements are still undefined, so I
        have moved the update to this point so that its value more
        useful. */
      this->_M_nres = __nres_orig + 1;
      __abserr = std::max(__abserr, 5 * _S_eps * std::abs(
      __result));
      return std::make_tuple(__result, __abserr);
    }
The documentation for this class was generated from the following files:
include/ext/extrapolation_table.h
include/ext/extrapolation_table.tcc