__gnu_cxx::integration_workspace< _Tp, _RetTp > Class Template Reference
#include <integration_workspace.h>
Public Member Functions
integration_workspace (std::size_t __cap)
_ErrorTp abs_error (std::size_t __ii=0) const
void append (_Tp __a, _Tp __b, _AreaTp __area, _ErrorTp __error, std::size_t __depth=0)
std::vector< interval >::iterator begin ()
std::size_t capacity () const
void clear ()
std::size_t curr_depth () const
std::size_t curr_index () const
size_t depth (std::size_t __ii=0) const
std::vector< interval >::iterator end ()
bool increment_curr_index ()
const std::vector< interval > & intervals () const
Return the vector of integration intervals.
bool large_interval () const
_Tp lower_lim (std::size_t __ii=0) const
std::size_t max_depth () const
std::size_t max_size () const
void pop ()
void push (const interval &__iv)
void reset_curr_index ()
_AreaTp result (std::size_t __ii=0) const
const interval & retrieve () const
_ErrorTp set_abs_error (std::size_t __ii, _ErrorTp __abserr)
void set_depth (std::size_t __ii, std::size_t __d)
std::size_t size () const
void sort_error ()
void split (_Tp __ab, _AreaTp __area1, _ErrorTp __error1, _AreaTp __area2, _ErrorTp __error2)
const interval & top () const
interval & top ()
_ErrorTp total_error () const
Return the sum of the absolute errors over all integration segments.
_AreaTp total_integral () const
Return the total integral: the sum of the results over all integration segments.
_Tp upper_lim (std::size_t __ii=0) const
Static Public Member Functions
static bool subinterval_too_small (_Tp __a1, _Tp __a2, _Tp __b2)
Detailed Description
template<typename _Tp, typename _RetTp>
class __gnu_cxx::integration_workspace< _Tp, _RetTp >
Definition at line 38 of file integration_workspace.h.
Constructor & Destructor Documentation
integration_workspace()
template<typename _Tp, typename _RetTp>
__gnu_cxx::integration_workspace< _Tp, _RetTp >::integration_workspace (std::size_t __cap) [inline]
Definition at line 84 of file integration_workspace.h.
References __gnu_cxx::_Tp, __gnu_cxx::integration_workspace< _Tp, _RetTp >::append(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::sort_error(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::split().
      : _M_curr_index{0},
        _M_max_depth{0},
        _M_max_size(__cap),
        _M_ival{}
      {
        _M_ival.reserve(__cap);
      }
Member Function Documentation
abs_error()
template<typename _Tp, typename _RetTp>
_ErrorTp __gnu_cxx::integration_workspace< _Tp, _RetTp >::abs_error (std::size_t __ii = 0) const [inline]
Return the absolute error for the segment at start + ii.
Definition at line 202 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index() + __ii].__abs_error; }
append()
template<typename _Tp , typename _RetTp >
void __gnu_cxx::integration_workspace< _Tp, _RetTp >::append (_Tp __a, _Tp __b, _AreaTp __area, _ErrorTp __error, std::size_t __depth = 0)
Definition at line 54 of file integration_workspace.tcc.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::split().
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::integration_workspace(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::sort_error().
    {
      interval __iv;
      __iv.__lower_lim = __a;
      __iv.__upper_lim = __b;
      __iv.__result = __area;
      __iv.__abs_error = __error;
      __iv.__depth = __depth;
      this->push(__iv);
    }
begin()
template<typename _Tp, typename _RetTp>
std::vector<interval>::iterator __gnu_cxx::integration_workspace< _Tp, _RetTp >::begin () [inline]
Return the current segment - the beginning of the vector + start as an iterator.
Definition at line 123 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::pop(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::push().
      { return this->_M_ival.begin() + this->curr_index(); }
capacity()
template<typename _Tp, typename _RetTp>
std::size_t __gnu_cxx::integration_workspace< _Tp, _RetTp >::capacity () const [inline]
Definition at line 115 of file integration_workspace.h.
      { return this->_M_ival.capacity(); }
clear()
template<typename _Tp, typename _RetTp>
void __gnu_cxx::integration_workspace< _Tp, _RetTp >::clear () [inline]
Definition at line 148 of file integration_workspace.h.
      {
        this->_M_curr_index = 0;
        this->_M_max_depth = 0;
        this->_M_ival.clear();
      }
curr_depth()
template<typename _Tp, typename _RetTp>
std::size_t __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_depth () const [inline]
Return the depth of the current segment.
Definition at line 245 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::large_interval().
      { return this->_M_ival[this->curr_index()].__depth; }
curr_index()
template<typename _Tp, typename _RetTp>
std::size_t __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index () const [inline]
Return the index of the current segment in the segment vector. The segments in [start, end) will be maintained in a heap.
Definition at line 257 of file integration_workspace.h.
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::abs_error(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::begin(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_depth(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::depth(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::lower_lim(), __gnu_cxx::operator<<(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::result(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::retrieve(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::set_abs_error(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::set_depth(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::top(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::upper_lim().
      { return this->_M_curr_index; }
depth()
template<typename _Tp, typename _RetTp>
size_t __gnu_cxx::integration_workspace< _Tp, _RetTp >::depth (std::size_t __ii = 0) const [inline]
Return the subdivision depth for the segment at start + ii.
Definition at line 209 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index() + __ii].__depth; }
end()
template<typename _Tp, typename _RetTp>
std::vector<interval>::iterator __gnu_cxx::integration_workspace< _Tp, _RetTp >::end () [inline]
Return the end iterator of the vector.
Definition at line 130 of file integration_workspace.h.
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::pop(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::push().
      { return this->_M_ival.end(); }
increment_curr_index()
template<typename _Tp , typename _RetTp >
bool __gnu_cxx::integration_workspace< _Tp, _RetTp >::increment_curr_index ()
Increase the heap start point until the current segment has a smaller depth than the current maximum depth. After each increment rebuild the heap from the new start point so the new start point is the largest error.
Usage: In the caller the smallest interval (at max depth) has the largest error. Before bisecting decrease the sum of the errors over the larger intervals (error_over_large_intervals) and perform extrapolation.
Definition at line 118 of file integration_workspace.tcc.
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::set_depth().
    {
      size_t __limit = this->max_size();
      size_t __last = this->size() - 1 ;
      size_t __jupbnd = __last > 1 + __limit / 2
                      ? __limit + 1 - __last
                      : __last;
      const auto __i_max = this->curr_index();
      for (auto __k = __i_max; __k <= __jupbnd; ++__k)
        {
          if (this->_M_ival[__k].__depth < this->max_depth())
            return true;
          else if (this->curr_index() + 1 < this->size())
            {
              ++this->_M_curr_index;
              this->sort_error();
            }
        }
      return false;
    }
intervals()
template<typename _Tp, typename _RetTp>
const std::vector<interval>& __gnu_cxx::integration_workspace< _Tp, _RetTp >::intervals () const [inline]
Return the vector of integration intervals.
Definition at line 296 of file integration_workspace.h.
Referenced by __gnu_cxx::operator<<().
      { return this->_M_ival; }
large_interval()
template<typename _Tp, typename _RetTp>
bool __gnu_cxx::integration_workspace< _Tp, _RetTp >::large_interval () const [inline]
Return true if the subdivision depth of the current segment is less than the maximum depth.
Definition at line 265 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_depth(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::max_depth().
      {
        if (this->curr_depth() < this->max_depth())
          return true;
        else
          return false;
      }
lower_lim()
template<typename _Tp, typename _RetTp>
_Tp __gnu_cxx::integration_workspace< _Tp, _RetTp >::lower_lim (std::size_t __ii = 0) const [inline]
Return the lower limit for the segment at start + ii.
Definition at line 181 of file integration_workspace.h.
References __gnu_cxx::_Tp, and __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index() + __ii].__lower_lim; }
max_depth()
template<typename _Tp, typename _RetTp>
std::size_t __gnu_cxx::integration_workspace< _Tp, _RetTp >::max_depth () const [inline]
Definition at line 249 of file integration_workspace.h.
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::large_interval(), and __gnu_cxx::operator<<().
      { return this->_M_max_depth; }
max_size()
template<typename _Tp, typename _RetTp>
std::size_t __gnu_cxx::integration_workspace< _Tp, _RetTp >::max_size () const [inline]
Definition at line 111 of file integration_workspace.h.
      { return this->_M_max_size; }
pop()
template<typename _Tp, typename _RetTp>
void __gnu_cxx::integration_workspace< _Tp, _RetTp >::pop () [inline]
Pop the current segment out of teh heap and erase it from the vector. N.B. this->begin() includes curr_index()!
Definition at line 171 of file integration_workspace.h.
References __gnu_cxx::_Tp, __gnu_cxx::integration_workspace< _Tp, _RetTp >::begin(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::end().
      {
        std::pop_heap(this->begin(), this->end());
        this->_M_ival.pop_back();
      }
push()
template<typename _Tp, typename _RetTp>
void __gnu_cxx::integration_workspace< _Tp, _RetTp >::push (const interval & __iv) [inline]
Push a new segment into the current heap. N.B. this->begin() includes curr_index()!
Definition at line 160 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::begin(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::end().
      {
        this->_M_ival.push_back(__iv);
        std::push_heap(this->begin(), this->end(), interval_comp{});
      }
reset_curr_index()
template<typename _Tp, typename _RetTp>
void __gnu_cxx::integration_workspace< _Tp, _RetTp >::reset_curr_index () [inline]
Reset the index of the current segment to zero. The entire segment vector will me made into a heap.
Definition at line 235 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::sort_error().
      {
        this->_M_curr_index = 0;
        this->sort_error();
      }
result()
template<typename _Tp, typename _RetTp>
_AreaTp __gnu_cxx::integration_workspace< _Tp, _RetTp >::result (std::size_t __ii = 0) const [inline]
Return the integration result for the segment at start + ii.
Definition at line 195 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index() + __ii].__result; }
retrieve()
template<typename _Tp, typename _RetTp>
const interval& __gnu_cxx::integration_workspace< _Tp, _RetTp >::retrieve () const [inline]
Definition at line 103 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index()]; }
set_abs_error()
template<typename _Tp, typename _RetTp>
_ErrorTp __gnu_cxx::integration_workspace< _Tp, _RetTp >::set_abs_error (std::size_t __ii, _ErrorTp __abserr) [inline]
Set the absolute error of the segment at start + ii to the given value. Only used by qagp.
Definition at line 217 of file integration_workspace.h.
References __gnu_cxx::__abserr, and __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index() + __ii].__abs_error =
      __abserr; }
set_depth()
template<typename _Tp, typename _RetTp>
void __gnu_cxx::integration_workspace< _Tp, _RetTp >::set_depth (std::size_t __ii, std::size_t __d) [inline]
Set the depth of segment at start + ii to the given value. Only used by qagp.
Definition at line 225 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::increment_curr_index().
      { this->_M_ival[this->curr_index() + __ii].__depth = __d; }
size()
template<typename _Tp, typename _RetTp>
std::size_t __gnu_cxx::integration_workspace< _Tp, _RetTp >::size () const [inline]
Definition at line 107 of file integration_workspace.h.
      { return this->_M_ival.size(); }
sort_error()
template<typename _Tp , typename _RetTp >
void __gnu_cxx::integration_workspace< _Tp, _RetTp >::sort_error ()
Rebuild the current heap. N.B. this->begin() includes curr_index()!
Definition at line 42 of file integration_workspace.tcc.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::append().
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::integration_workspace(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::reset_curr_index().
    {
      std::make_heap(this->begin(), this->end(), interval_comp{});
      return;
    }
split()
template<typename _Tp , typename _RetTp >
void __gnu_cxx::integration_workspace< _Tp, _RetTp >::split (_Tp __ab, _AreaTp __area1, _ErrorTp __error1, _AreaTp __area2, _ErrorTp __error2)
Definition at line 73 of file integration_workspace.tcc.
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::append(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::integration_workspace().
    {
      auto __iv = this->top();
      const auto __a1 = __iv.__lower_lim;
      const auto __b1 = __ab;
      const auto __a2 = __ab;
      const auto __b2 = __iv.__upper_lim;
      const auto __depth = __iv.__depth + 1;
      this->pop();
      interval __iv1;
      __iv1.__lower_lim = __a1;
      __iv1.__upper_lim = __b1;
      __iv1.__result = __area1;
      __iv1.__abs_error = __error1;
      __iv1.__depth = __depth;
      this->push(__iv1);
      interval __iv2;
      __iv2.__lower_lim = __a2;
      __iv2.__upper_lim = __b2;
      __iv2.__result = __area2;
      __iv2.__abs_error = __error2;
      __iv2.__depth = __depth;
      this->push(__iv2);
      if (__depth > this->_M_max_depth)
        this->_M_max_depth = __depth;
    }
subinterval_too_small()
template<typename _Tp, typename _RetTp>
static bool __gnu_cxx::integration_workspace< _Tp, _RetTp >::subinterval_too_small (_Tp __a1, _Tp __a2, _Tp __b2) [inline], [static]
Definition at line 303 of file integration_workspace.h.
References __gnu_cxx::_Tp, and __gnu_cxx::operator<<().
      {
        const auto _S_eps = _Tp{100} * std::numeric_limits<_Tp>::epsilon();
        const auto _S_min = _Tp{1000} * std::numeric_limits<_Tp>::min();
        const auto __tmp = (_Tp{1} + _S_eps) * (std::abs(__a2) + _S_min);
        return std::abs(__a1) <= __tmp
            && std::abs(__b2) <= __tmp;
      }
top() [1/2]
template<typename _Tp, typename _RetTp>
const interval& __gnu_cxx::integration_workspace< _Tp, _RetTp >::top () const [inline]
Return the current segment - the top of the heap - as an lvalue.
Definition at line 137 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index()]; }
top() [2/2]
template<typename _Tp, typename _RetTp>
interval& __gnu_cxx::integration_workspace< _Tp, _RetTp >::top () [inline]
Return the current segment - the top of the heap - as an rvalue.
Definition at line 144 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index()]; }
total_error()
template<typename _Tp, typename _RetTp>
_ErrorTp __gnu_cxx::integration_workspace< _Tp, _RetTp >::total_error () const [inline]
Return the sum of the absolute errors over all integration segments.
Definition at line 286 of file integration_workspace.h.
      {
        auto __tot_error = _ErrorTp{0};
        for (auto& __iv : this->_M_ival)
          __tot_error += __iv.__abs_error;
        return __tot_error;
      }
total_integral()
template<typename _Tp, typename _RetTp>
_AreaTp __gnu_cxx::integration_workspace< _Tp, _RetTp >::total_integral () const [inline]
Return the total integral: the sum of the results over all integration segments.
Definition at line 276 of file integration_workspace.h.
      {
        auto __result_sum = _AreaTp{0};
        for (const auto& __iv : this->_M_ival)
          __result_sum += __iv.__result;
        return __result_sum;
      }
upper_lim()
template<typename _Tp, typename _RetTp>
_Tp __gnu_cxx::integration_workspace< _Tp, _RetTp >::upper_lim (std::size_t __ii = 0) const [inline]
Return the upper limit for the segment at start + ii.
Definition at line 188 of file integration_workspace.h.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index().
      { return this->_M_ival[this->curr_index() + __ii].__upper_lim; }
The documentation for this class was generated from the following files:
include/ext/integration_workspace.h
include/ext/integration_workspace.tcc