__gnu_cxx::__detail Namespace Reference
Functions
template<typename _Tp , typename _InIter , typename _OutIter >
void __golub_welsch (_Tp __moment0, int __n, _InIter &__diag, _InIter &__subd, _OutIter &__pt, _OutIter &__wt)
Function Documentation
__golub_welsch()
template<typename _Tp , typename _InIter , typename _OutIter >
void __gnu_cxx::__detail::__golub_welsch (_Tp __moment0, int __n, _InIter & __diag, _InIter & __subd, _OutIter & __pt, _OutIter & __wt)
Build the absiscae and weights of a Gauss quadrature rule from a symmetric tridiagonal Jacobi matrix using the Golub-Welsch technique.
Sylvan Elhay, Jaroslav Kautsky, Algorithm 655: IQPACK, Fortran Subroutines for the Weights of Interpolatory Quadrature, ACM Transactions on Mathematical Software, Volume 13, Number 4, December 1987, pages 399-415.
Parameters
in n The number of knots.
in diag The diagonal of the Jacobi matrix in [0..n-1].
in,out subd The subdiagonal of the Jacobi matrix in [1 ... n-1]. On output subd is overwritten.
in moment0 The zero-th moment of the weight function.
out pt[n] The points of the integration rule.
out wt[n] The weights of the integration rule.
Definition at line 53 of file gauss_quadrature.tcc.
References __gnu_cxx::_S_tridiag_symm(), __gnu_cxx::_Tp, and __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::fixed_gauss_legendre_integral().
Referenced by __gnu_cxx::fixed_gauss_chebyshev_t_integral< _Tp >::fixed_gauss_chebyshev_t_integral(), __gnu_cxx::fixed_gauss_chebyshev_u_integral< _Tp >::fixed_gauss_chebyshev_u_integral(), __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::fixed_gauss_chebyshev_v_integral(), __gnu_cxx::fixed_gauss_chebyshev_w_integral< _Tp >::fixed_gauss_chebyshev_w_integral(), __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::fixed_gauss_exponential_integral(), __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::fixed_gauss_gegenbauer_integral(), __gnu_cxx::fixed_gauss_hermite_integral< _Tp >::fixed_gauss_hermite_integral(), __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral(), __gnu_cxx::fixed_gauss_laguerre_integral< _Tp >::fixed_gauss_laguerre_integral(), and __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::fixed_gauss_legendre_integral().
    {
      // Bail if the zero-th moment is not positive.
      if (__moment0 <= _Tp{0})
        std::__throw_domain_error("__golub_welsch: moment0 <= 0");
      // Set up vectors for matrix diagonalization.
      for (int i = 0; i < __n; ++i)
        __pt[i] = __diag[i];
      __wt[0] = std::sqrt(__moment0);
      for (int i = 1; i < __n; ++i)
        __wt[i] = _Tp{0};
      // Diagonalize the Jacobi matrix.
      _S_tridiag_symm(std::size_t(__n), __pt, __subd, __wt);
      for (int i = 0; i < __n; ++i)
        __wt[i] *= __wt[i];
      return;
    }