emsr::detail Namespace Reference
Functions
template<typename Tp , typename InIter , typename OutIter >
void golub_welsch (Tp moment0, int n, InIter &diag, InIter &subd, OutIter &pt, OutIter &wt)
Function Documentation
golub_welsch()
template<typename Tp , typename InIter , typename OutIter >
void emsr::detail::golub_welsch (Tp moment0, int n, InIter & diag, InIter & subd, OutIter & pt, OutIter & wt)
Build the absiscae and weights of a Gauss quadrature rule from a symmetric tridiagonal Jacobi matrix using the Golub-Welsch technique.
Sylvan Elhay, Jaroslav Kautsky, Algorithm 655: IQPACK, Fortran Subroutines for the Weights of Interpolatory Quadrature, ACM Transactions on Mathematical Software, Volume 13, Number 4, December 1987, pages 399-415.
Parameters
 in n The number of knots.
 in diag The diagonal of the Jacobi matrix in [0..n-1].
 in,out subd The subdiagonal of the Jacobi matrix in [1 ... n-1]. On output subd is overwritten.
 in moment0 The zero-th moment of the weight function.
 out pt[n] The points of the integration rule.
 out wt[n] The weights of the integration rule.
Definition at line 52 of file gauss_quadrature.tcc.
    {
      // Bail if the zero-th moment is not positive.
      if (moment0 <= Tp{0})
        throw std::domain_error("golub_welsch: moment0 <= 0");
      // Set up vectors for matrix diagonalization.
      for (int i = 0; i < n; ++i)
        pt[i] = diag[i];
      wt[0] = std::sqrt(moment0);
      for (int i = 1; i < n; ++i)
        wt[i] = Tp{0};
      // Diagonalize the Jacobi matrix.
      s_tridiag_symm(std::size_t(n), pt, subd, wt);
      for (int i = 0; i < n; ++i)
        wt[i] *= wt[i];
      return;
    }
References emsr::s_tridiag_symm(), and Tp.
Referenced by emsr::fixed_gauss_chebyshev_t_integral< Tp >::fixed_gauss_chebyshev_t_integral(), emsr::fixed_gauss_chebyshev_u_integral< Tp >::fixed_gauss_chebyshev_u_integral(), emsr::fixed_gauss_chebyshev_v_integral< Tp >::fixed_gauss_chebyshev_v_integral(), emsr::fixed_gauss_chebyshev_w_integral< Tp >::fixed_gauss_chebyshev_w_integral(), emsr::fixed_gauss_exponential_integral< Tp >::fixed_gauss_exponential_integral(), emsr::fixed_gauss_gegenbauer_integral< Tp >::fixed_gauss_gegenbauer_integral(), emsr::fixed_gauss_hermite_integral< Tp >::fixed_gauss_hermite_integral(), emsr::fixed_gauss_jacobi_integral< Tp >::fixed_gauss_jacobi_integral(), emsr::fixed_gauss_laguerre_integral< Tp >::fixed_gauss_laguerre_integral(), and emsr::fixed_gauss_legendre_integral< Tp >::fixed_gauss_legendre_integral().