__gnu_cxx Namespace Reference
Namespaces
 __detail
Classes
class __integration_error
class __phase_iterator
struct adaptive_integral_t
struct chebyshev_integral_t
class composite_midpoint_integral
class composite_simpson_integral
class composite_trapezoid_integral
struct compute_result_t
struct cquad_interval
struct cquad_interval_comp
struct cquad_workspace
struct error_tolerance_t
class extrapolation_table
struct fixed_gauss_chebyshev_t_integral
struct fixed_gauss_chebyshev_u_integral
struct fixed_gauss_chebyshev_v_integral
struct fixed_gauss_chebyshev_w_integral
struct fixed_gauss_exponential_integral
struct fixed_gauss_gegenbauer_integral
struct fixed_gauss_hermite_integral
struct fixed_gauss_jacobi_integral
struct fixed_gauss_laguerre_integral
struct fixed_gauss_legendre_integral
struct fixed_gauss_rational_integral
struct fixed_integral_t
struct fn_qaws
class fourier_transform_t
class fourier_transform_t< std::complex< _Tp > >
struct gauss_legendre_table
class integration_workspace
struct map_a_pinf
struct map_minf_b
struct map_minf_pinf
struct map_minf_pinf_symm
struct mapper
class midpoint_integral
struct oscillatory_integration_table
struct qaws_integration_table
class qk_integrator
struct qk_integrator< _Tp, _FuncTp, Kronrod_15 >
struct qk_integrator< _Tp, _FuncTp, Kronrod_21 >
struct qk_integrator< _Tp, _FuncTp, Kronrod_31 >
struct qk_integrator< _Tp, _FuncTp, Kronrod_41 >
struct qk_integrator< _Tp, _FuncTp, Kronrod_51 >
struct qk_integrator< _Tp, _FuncTp, Kronrod_61 >
class simpson_integral
class trapezoid_integral
Typedefs
using _AbsAreaTp = decltype(std::abs(_AreaTp{}))
using _AreaTp = decltype(_RetTp{} *_Tp{})
Enumerations
enum {
NO_ERROR,
MAX_ITER_ERROR,
ROUNDOFF_ERROR,
SINGULAR_ERROR,
EXTRAP_ROUNDOFF_ERROR,
DIVERGENCE_ERROR,
MAX_SUBDIV_ERROR,
TOLERANCE_ERROR,
UNKNOWN_ERROR
 }
enum Gauss_Legendre_Rule {
GL_2 = 2,
GL_4 = 4,
GL_6 = 6,
GL_8 = 8,
GL_10 = 10,
GL_12 = 12,
GL_14 = 14,
GL_16 = 16,
GL_18 = 18,
GL_20 = 20,
GL_32 = 32,
GL_64 = 64,
GL_96 = 96,
GL_100 = 100,
GL_128 = 128,
GL_256 = 256,
GL_512 = 512,
GL_1024 = 1024,
GL_3 = 3,
GL_5 = 5,
GL_7 = 7,
GL_9 = 9,
GL_11 = 11,
GL_13 = 13,
GL_15 = 15,
GL_17 = 17,
GL_19 = 19
 }
Functions
template<typename _Tp >
void __check_error (std::string_view __func, int __errcode, _Tp __result=std::numeric_limits< _Tp >::quiet_NaN(), _Tp __abserr=std::numeric_limits< _Tp >::quiet_NaN())
template<typename _Tp >
void __discrete_fourier_transform (bool __do_forward, std::vector< std::complex< _Tp >> &__z)
* __func (_Tp{}))
template<typename _Tp >
_Tp __rescale_error (_Tp __err, const _Tp __result_abs, const _Tp __result_asc)
template<typename _Tp >
bool __test_positivity (_Tp __result, _Tp __resabs)
template<typename _Tp >
void __throw_integration_error (const char *__what, int __errcode, _Tp __result=std::numeric_limits< _Tp >::quiet_NaN(), _Tp __abserr=std::numeric_limits< _Tp >::quiet_NaN()) __attribute__((__noreturn__))
template<typename _Tp , typename _FuncTp >
std::invoke_result_t< _FuncTp, _Tp > __wrap_func (_FuncTp __func, _Tp __x)
template<typename _RandAccIter , typename _RandAccIterRHS >
int _S_tridiag (std::size_t __n, _RandAccIter __supd, _RandAccIter __diag, _RandAccIter __subd, _RandAccIterRHS __rhs)
template<typename _RandAccIter , typename _RandAccIterRHS >
int _S_tridiag (size_t __n, _RandAccIter __supd, _RandAccIter __diag, _RandAccIter __subd, _RandAccIterRHS __rhs)
template<typename _RandAccIter , typename _RandAccIterRHS >
int _S_tridiag_symm (std::size_t __n, _RandAccIter &__diag, _RandAccIter &__subd, _RandAccIterRHS &__rhs)
Diagonalize a symmetric tridiagonal matrix.
template<typename _RetTp >
void _Vinvfx (const std::array< _RetTp, 33 > &__fx, _RetTp *__coeff, const int __depth)
template<typename _Tp >
std::vector< _Tp > compute_moments (std::size_t __N, _Tp __cc)
template<typename _Tp , typename _RetTp >
auto compute_result (const std::array< _Tp, 25 > &__r, const std::array< _RetTp, 13 > &__cheb12, const std::array< _RetTp, 25 > &__cheb24) -> compute_result_t< decltype(_Tp
template<typename _Tp , typename _FuncTp >
auto cquad_integrate (cquad_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__ws, _FuncTp __func, _Tp __a, _Tp __b, _Tp __epsabs, _Tp __epsrel) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp >
void downdate (_Tp *__coeff, std::ptrdiff_t __n, std::ptrdiff_t __depth, std::ptrdiff_t *__NaN, std::ptrdiff_t __num_NaNs)
template<typename _Tp >
void fast_fourier_transform (std::vector< std::complex< _Tp >> &__z)
template<typename _Tp >
void fast_fourier_transform (std::vector< _Tp > &__x)
template<typename _CmplxIter >
void fast_fourier_transform (const _CmplxIter &__from, const _CmplxIter &__to)
template<typename _Tp >
void fast_sine_transform (std::vector< _Tp > &__x)
for (size_t __i=0u;__i< __cheb12.size();++__i) __res12+ = __cheb24[__i] * __moment[__i]
if (std::abs(__cc) > _Tp{1.1})
template<typename _Tp , typename _FuncTp >
auto integrate (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024, Kronrod_Rule __qkintrule=Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_cauchy_principal_value (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __center, _Tp __max_abs_err, _Tp __max_rel_err, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_clenshaw_curtis (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_exp_sinh (_FuncTp __func, _Tp __a, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_chebyshev_t (int __n, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_chebyshev_u (int __n, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_chebyshev_v (int __n, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_chebyshev_w (int __n, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_exponential (int __n, _Tp __alf, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_gegenbauer (int __n, _Tp __lambda, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_hermite (int __n, _Tp __alf, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_jacobi (int __n, _Tp __alf, _Tp __bet, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_laguerre (int __n, _Tp __alf, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_legendre (int __n, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_fixed_gauss_rational (int __n, _Tp __alf, _Tp __bet, _FuncTp __func, _Tp __a, _Tp __b)
template<typename _Tp , typename _FuncTp >
auto integrate_kronrod_singular (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_lower_minf (_FuncTp __func, _Tp __lower, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024, Kronrod_Rule __qkintrule=Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_lower_pinf (_FuncTp __func, _Tp __lower, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024, Kronrod_Rule __qkintrule=Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_midpoint (_FuncTp __func, _Tp __a, _Tp __b, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
template<typename _Tp , typename _FuncTp >
auto integrate_minf_pinf (_FuncTp __func, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024, Kronrod_Rule __qkintrule=Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_minf_upper (_FuncTp __func, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024, Kronrod_Rule __qkintrule=Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _FuncTp , typename _FwdIter , typename _Tp >
auto integrate_multisingular (_FuncTp __func, _FwdIter __ptbeg, _FwdIter __ptend, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_oscillatory (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_patterson (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_pinf_upper (_FuncTp __func, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024, Kronrod_Rule __qkintrule=Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_simpson (_FuncTp __func, _Tp __a, _Tp __b, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
template<typename _Tp , typename _FuncTp >
auto integrate_singular (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_singular_endpoints (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __alpha, _Tp __beta, int __mu, int __nu, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_singular_lower_minf (_FuncTp __func, _Tp __lower, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_singular_lower_pinf (_FuncTp __func, _Tp __lower, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_singular_minf_pinf (_FuncTp __func, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_singular_minf_upper (_FuncTp __func, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto integrate_singular_pinf_upper (_FuncTp __func, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter=1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_sinh_sinh (_FuncTp __func, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_tanh_sinh (_FuncTp __func, _Tp __a, _Tp __b, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > integrate_trapezoid (_FuncTp __func, _Tp __a, _Tp __b, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
template<typename _Tp >
void inv_fast_fourier_transform (std::vector< std::complex< _Tp >> &__z)
template<typename _Tp >
void inv_fast_fourier_transform (std::vector< _Tp > &__x)
template<typename _CmplxIter >
void inv_fast_fourier_transform (const _CmplxIter &__from, const _CmplxIter &__to)
template<typename _Tp >
void inv_fast_sine_transform (std::vector< _Tp > &__x)
template<typename _Tp , typename _RetTp >
bool operator< (const cquad_interval< _Tp, _RetTp > &__ivl, const cquad_interval< _Tp, _RetTp > &__ivr)
template<typename _Tp , typename _RetTp >
std::ostream & operator<< (std::ostream &__out, const integration_workspace< _Tp, _RetTp > &__ws)
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto qag_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad=gauss_kronrod_integral< _Tp >(Kronrod_21)) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto qagi_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, _FuncTp __func, _Tp __max_abs_err, _Tp __max_rel_err) -> adaptive_integral_t< _Tp, decltype(map_minf_pinf< _Tp, _FuncTp >(__func)(_Tp
template<typename _Tp , typename _FuncTp >
auto qagil_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, _FuncTp __func, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err) -> adaptive_integral_t< _Tp, decltype(map_minf_b< _Tp, _FuncTp >(__func, __upper)(_Tp
template<typename _Tp , typename _FuncTp >
auto qagis_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, _FuncTp __func, _Tp __max_abs_err, _Tp __max_rel_err) -> adaptive_integral_t< _Tp, decltype(map_minf_pinf_symm< _Tp, _FuncTp >(__func)(_Tp
template<typename _Tp , typename _FuncTp >
auto qagiu_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, _FuncTp __func, _Tp __lower, _Tp __max_abs_err, _Tp __max_rel_err) -> adaptive_integral_t< _Tp, decltype(map_a_pinf< _Tp, _FuncTp >(__func, __lower)(_Tp
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto qagp_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, _FuncTp __func, std::vector< _Tp > __pts, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad=gauss_kronrod_integral< _Tp >(Kronrod_21)) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto qags_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad=gauss_kronrod_integral< _Tp >(Kronrod_15)) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
return qags_integrate< _Tp, _FuncTp2 > (__workspace, map_minf_pinf< _Tp, _FuncTp >(__func), _Tp{0}, _Tp{1}, __max_abs_err, __max_rel_err)
return qags_integrate< _Tp, _FuncTp2 > (__workspace, map_minf_pinf_symm< _Tp, _FuncTp >(__func), _Tp{0}, _Tp{1}, __max_abs_err, __max_rel_err)
return qags_integrate< _Tp, _FuncTp2 > (__workspace, map_minf_b< _Tp, _FuncTp >(__func, __upper), _Tp{0}, _Tp{1}, __max_abs_err, __max_rel_err)
return qags_integrate< _Tp, _FuncTp2 > (__workspace, map_a_pinf< _Tp, _FuncTp >(__func, __lower), _Tp{0}, _Tp{1}, __max_abs_err, __max_rel_err)
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto qawc_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __center, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad=gauss_kronrod_integral< _Tp >(Kronrod_15)) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto qawf_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__cycle_workspace, oscillatory_integration_table< _Tp > &__wf, _FuncTp __func, _Tp __lower, _Tp __max_abs_err) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto qawo_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, oscillatory_integration_table< _Tp > &__wf, _FuncTp __func, const _Tp __lower, const _Tp __max_abs_err, const _Tp __max_rel_err) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto qaws_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> &__workspace, qaws_integration_table< _Tp > &__table, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad=gauss_kronrod_integral< _Tp >(Kronrod_15)) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto qc25c (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __center, _Integrator __quad=gauss_kronrod_integral< _Tp >(Kronrod_15)) -> std::tuple< decltype(_Tp
template<typename _Tp , typename _FuncTp >
auto qc25f (oscillatory_integration_table< _Tp > &__wf, _FuncTp __func, _Tp __lower, _Tp __upper, std::size_t __depth) -> gauss_kronrod_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
std::tuple< _Tp, _Tp, bool > qc25s (qaws_integration_table< _Tp > &__t, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __a1, _Tp __mid, _Integrator __quad=gauss_kronrod_integral< _Tp >(Kronrod_15))
template<typename _Tp , typename _FuncTp >
auto qcheb_integrate (_FuncTp __func, _Tp __lower, _Tp __upper) -> chebyshev_integral_t< std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto qk_integrate (_FuncTp __func, _Tp __lower, _Tp __upper, Kronrod_Rule __qkintrule) -> gauss_kronrod_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp , typename _FuncTp >
auto qng_integrate (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err) -> gauss_kronrod_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
template<typename _Tp >
bool valid_tolerances (_Tp __max_abs_err, _Tp __max_rel_err)
Variables
auto __abserr = _AbsAreaTp{}
const auto __cc
bool __err_reliable = false
const auto __moment = compute_moments(__cheb24.size(), __cc)
auto __res12 = _AreaTp{0}
auto __res24 = _AreaTp{0}
auto __result = _AreaTp{}
* _RetTp {})>
_Tp
constexpr long double bee [68]
bool
else
template<typename _Tp , typename _Func >
decltype(std::invoke_result_t< _Func, _Tp >{} *_Tp{} gauss_hermite_integrate)(_Func __func, unsigned int __n)
template<typename _Tp , typename _Func >
decltype(std::invoke_result_t< _Func, _Tp >{} *_Tp{} gauss_laguerre_integrate)(_Func __func, unsigned int __n, _Tp __alpha)
const gauss_legendre_table< long double > gauss_legendre_precomp []
template<typename _Tp , typename _FuncTp >
decltype(std::invoke_result_t< _FuncTp, _Tp >{} *_Tp{} glfixed_integrate)(const gauss_legendre_table< _Tp > &__t, _FuncTp __func, _Tp __lower, _Tp __upper)
constexpr long double Lalpha [33]
constexpr long double Lgamma [33]
const std::size_t num_gauss_legendre_precomp
constexpr long double Tleft [33 *33]
constexpr long double Tright [33 *33]
constexpr long double V1inv [5 *5]
constexpr long double V2inv [9 *9]
constexpr long double V3inv [17 *17]
constexpr long double V4inv [33 *33]
constexpr long double w10 [5]
constexpr long double w100 [50]
constexpr long double w1024 [512]
constexpr long double w11 [6]
constexpr long double w12 [6]
constexpr long double w128 [64]
constexpr long double w13 [7]
constexpr long double w14 [7]
constexpr long double w15 [8]
constexpr long double w16 [8]
constexpr long double w17 [9]
constexpr long double w18 [9]
constexpr long double w19 [10]
constexpr long double w2 [1]
constexpr long double w20 [10]
constexpr long double w256 [128]
constexpr long double w3 [2]
constexpr long double w32 [16]
constexpr long double w4 [2]
constexpr long double w5 [3]
constexpr long double w512 [256]
constexpr long double w6 [3]
constexpr long double w64 [32]
constexpr long double w7 [4]
constexpr long double w8 [4]
constexpr long double w9 [5]
constexpr long double w96 [48]
constexpr long double x10 [5]
constexpr long double x100 [50]
constexpr long double x1024 [512]
constexpr long double x11 [6]
constexpr long double x12 [6]
constexpr long double x128 [64]
constexpr long double x13 [7]
constexpr long double x14 [7]
constexpr long double x15 [8]
constexpr long double x16 [8]
constexpr long double x17 [9]
constexpr long double x18 [9]
constexpr long double x19 [10]
constexpr long double x2 [1]
constexpr long double x20 [10]
constexpr long double x256 [128]
constexpr long double x3 [2]
constexpr long double x32 [16]
constexpr long double x4 [2]
constexpr long double x5 [3]
constexpr long double x512 [256]
constexpr long double x6 [3]
constexpr long double x64 [32]
constexpr long double x7 [4]
constexpr long double x8 [4]
constexpr long double x9 [5]
constexpr long double x96 [48]
constexpr long double xi [33]
Detailed Description
Gauss-Kronrod-Patterson quadrature coefficients for use in QUADPACK routine QNG. These coefficients were calculated with 101 decimal digit arithmetic by L. W. Fullerton, Bell Labs, Nov 1981.
Typedef Documentation
_AbsAreaTp
using __gnu_cxx::_AbsAreaTp = typedef decltype(std::abs(_AreaTp{}))
Definition at line 220 of file qawc_integrate.tcc.
_AreaTp
using __gnu_cxx::_AreaTp = typedef decltype(_RetTp{} * _Tp{})
Definition at line 219 of file qawc_integrate.tcc.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NO_ERROR
MAX_ITER_ERROR
ROUNDOFF_ERROR
SINGULAR_ERROR
EXTRAP_ROUNDOFF_ERROR
DIVERGENCE_ERROR
MAX_SUBDIV_ERROR
TOLERANCE_ERROR
UNKNOWN_ERROR
Definition at line 35 of file integration_error.h.
  {
    NO_ERROR,
    MAX_ITER_ERROR,
    ROUNDOFF_ERROR,
    SINGULAR_ERROR,
    EXTRAP_ROUNDOFF_ERROR,
    DIVERGENCE_ERROR,
    MAX_SUBDIV_ERROR,
    TOLERANCE_ERROR,
    UNKNOWN_ERROR
  };
Gauss_Legendre_Rule
enum __gnu_cxx::Gauss_Legendre_Rule
Enumerator
GL_2
GL_4
GL_6
GL_8
GL_10
GL_12
GL_14
GL_16
GL_18
GL_20
GL_32
GL_64
GL_96
GL_100
GL_128
GL_256
GL_512
GL_1024
GL_3
GL_5
GL_7
GL_9
GL_11
GL_13
GL_15
GL_17
GL_19
Definition at line 34 of file gauss_legendre_table.h.
  {
    GL_2 = 2,
    GL_4 = 4,
    GL_6 = 6,
    GL_8 = 8,
    GL_10 = 10,
    GL_12 = 12,
    GL_14 = 14,
    GL_16 = 16,
    GL_18 = 18,
    GL_20 = 20,
    GL_32 = 32,
    GL_64 = 64,
    GL_96 = 96,
    GL_100 = 100,
    GL_128 = 128,
    GL_256 = 256,
    GL_512 = 512,
    GL_1024 = 1024,
    GL_3 = 3,
    GL_5 = 5,
    GL_7 = 7,
    GL_9 = 9,
    GL_11 = 11,
    GL_13 = 13,
    GL_15 = 15,
    GL_17 = 17,
    GL_19 = 19
  };
Function Documentation
__check_error()
template<typename _Tp >
void __gnu_cxx::__check_error (std::string_view __func, int __errcode, _Tp __result = std::numeric_limits<_Tp>::quiet_NaN(), _Tp __abserr = std::numeric_limits<_Tp>::quiet_NaN())
Throws appropriate error if errcode nonzero
Definition at line 106 of file integration_error.h.
References __abserr, __result, __throw_integration_error(), _Tp, DIVERGENCE_ERROR, EXTRAP_ROUNDOFF_ERROR, MAX_ITER_ERROR, MAX_SUBDIV_ERROR, NO_ERROR, ROUNDOFF_ERROR, SINGULAR_ERROR, and TOLERANCE_ERROR.
Referenced by qagp_integrate(), qags_integrate(), and qawf_integrate().
    {
      std::ostringstream msg;
      msg << __func << ": ";
      if (__errcode > 2)
        --__errcode;
      switch(__errcode)
        {
        case NO_ERROR:
          return;
        case MAX_ITER_ERROR:
          msg << "Number of iterations was insufficient";
          break;
        case ROUNDOFF_ERROR:
          msg << "Cannot reach tolerance because of roundoff error";
          break;
        case SINGULAR_ERROR:
          msg << "Bad integrand behavior found in the integration interval";
          break;
        case EXTRAP_ROUNDOFF_ERROR:
          msg << "Roundoff error detected in the extrapolation";
          break;
        case DIVERGENCE_ERROR:
          msg << "Integral is divergent, or slowly convergent";
          break;
        case MAX_SUBDIV_ERROR:
          msg << "Maximum number of subdivisions reached";
          break;
        case TOLERANCE_ERROR:
          msg << "Cannot reach tolerance with maximum order rule";
          break;
        default:
          msg << "Could not integrate function";
        }
      __throw_integration_error(msg.str().c_str(), __errcode,
                                __result, __abserr);
    }
__discrete_fourier_transform()
template<typename _Tp >
void __gnu_cxx::__discrete_fourier_transform (bool __do_forward, std::vector< std::complex< _Tp >> & __z)
Discrete Fourier transform on complex data.
Definition at line 36 of file fourier_transform.tcc.
References __result, and _Tp.
Referenced by fast_fourier_transform(), inv_fast_fourier_transform(), and __gnu_cxx::fourier_transform_t< std::complex< _Tp > >::operator[]().
    {
      const auto __sign(__do_forward ? _Tp{+1} : _Tp{-1});
      const auto __len = __z.size();
      std::vector<std::complex<_Tp>> __result;
      __result.reserve(__len);
      // Do matrix multiplication.
      for (std::size_t __i = 0; __i < __len; ++__i)
        {
          __phase_iterator __coefficient_iter(__sign, __i, __len);
          __result.push_back(std::inner_product(__z.begin(), __z.end(),
                             __coefficient_iter, std::complex<_Tp>{0}));
        }
      // Rescale if forward.
      if (__do_forward)
        {
          const auto __norm = _Tp{1} / _Tp(__len);
          for (std::size_t __i = 0; __i < __len; ++__i)
            __result[__i] *= __norm;
        }
      // Copy data back (swap is fast!).
      __z.swap(__result);
    }
__func()
* __gnu_cxx::__func (_Tp{})
Referenced by __wrap_func(), cquad_integrate(), __gnu_cxx::fixed_gauss_chebyshev_t_integral< _Tp >::fixed_gauss_chebyshev_t_integral(), __gnu_cxx::fixed_gauss_chebyshev_u_integral< _Tp >::fixed_gauss_chebyshev_u_integral(), __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::fixed_gauss_chebyshev_v_integral(), __gnu_cxx::fixed_gauss_chebyshev_w_integral< _Tp >::fixed_gauss_chebyshev_w_integral(), __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::fixed_gauss_exponential_integral(), __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::fixed_gauss_gegenbauer_integral(), __gnu_cxx::fixed_gauss_hermite_integral< _Tp >::fixed_gauss_hermite_integral(), __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral(), __gnu_cxx::fixed_gauss_laguerre_integral< _Tp >::fixed_gauss_laguerre_integral(), __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::fixed_gauss_legendre_integral(), integrate_exp_sinh(), integrate_sinh_sinh(), integrate_tanh_sinh(), qagi_integrate(), qagil_integrate(), qagis_integrate(), qagiu_integrate(), qawc_integrate(), qawf_integrate(), qc25f(), qcheb_integrate(), qk_integrate(), qng_integrate(), and valid_tolerances().
__rescale_error()
template<typename _Tp >
_Tp __gnu_cxx::__rescale_error (_Tp __err, const _Tp __result_abs, const _Tp __result_asc)
Definition at line 153 of file integration_error.h.
References _Tp.
Referenced by qk_integrate(), and qng_integrate().
    {
      const auto _S_eps = std::numeric_limits<_Tp>::epsilon();
      const auto _S_min = std::numeric_limits<_Tp>::min();
      __err = std::abs(__err);
      if (__result_asc != 0 && __err != _Tp{0})
        {
          auto __scale = std::pow((_Tp{200} * __err / __result_asc), _Tp{1.5});
          if (__scale < _Tp{1})
            __err = __result_asc * __scale;
          else
            __err = __result_asc;
        }
      if (__result_abs > _S_min / (_Tp{50} * _S_eps))
        {
          auto __min_err = _Tp{50} * _S_eps * __result_abs;
          if (__min_err > __err)
            __err = __min_err;
        }
      return __err;
    }
__test_positivity()
template<typename _Tp >
bool __gnu_cxx::__test_positivity (_Tp __result, _Tp __resabs) [inline]
Definition at line 55 of file gauss_kronrod_integral.tcc.
Referenced by qagp_integrate(), qags_integrate(), and qawo_integrate().
    {
      return(std::abs(__result)
          >= (1 - 50 * std::numeric_limits<_Tp>::epsilon()) * __resabs);
    }
__throw_integration_error()
template<typename _Tp >
void __gnu_cxx::__throw_integration_error (const char * __what, int __errcode, _Tp __result = std::numeric_limits<_Tp>::quiet_NaN(), _Tp __abserr = std::numeric_limits<_Tp>::quiet_NaN())
Throws appropriate error if errcode nonzero
Definition at line 94 of file integration_error.h.
References __gnu_cxx::__integration_error< _Tp >::__integration_error().
Referenced by __check_error(), __gnu_cxx::__integration_error< _Tp >::abserr(), qag_integrate(), qagp_integrate(), qags_integrate(), qawc_integrate(), qawf_integrate(), qawo_integrate(), qaws_integrate(), and qng_integrate().
    {
      _GLIBCXX_THROW_OR_ABORT(
        __integration_error(__what, __errcode, __result, __abserr));
    }
__wrap_func()
template<typename _Tp , typename _FuncTp >
std::invoke_result_t<_FuncTp, _Tp> __gnu_cxx::__wrap_func (_FuncTp __func, _Tp __x)
Chances are, if the function returns Nan or inf, we stepped on a pole.
Definition at line 76 of file trapezoid_integral.tcc.
References __func(), and _Tp.
    {
      auto __y = __func(__x);
      if (std::isnan(__y) || std::isinf(__y))
        return _Tp{0};
      else
        return __y;
    }
_S_tridiag() [1/2]
template<typename _RandAccIter , typename _RandAccIterRHS >
int __gnu_cxx::_S_tridiag (std::size_t __n, _RandAccIter __supd, _RandAccIter __diag, _RandAccIter __subd, _RandAccIterRHS __rhs)
_S_tridiag() [2/2]
template<typename _RandAccIter , typename _RandAccIterRHS >
int __gnu_cxx::_S_tridiag (size_t __n, _RandAccIter __supd, _RandAccIter __diag, _RandAccIter __subd, _RandAccIterRHS __rhs)
Solve a tridiagonal system A x = b:
Parameters
in supd The superdiagonal of the matrix in [0, n - 2]
in diag The diagonal of the matrix in [0, n - 1]
in subd The subdiagonal of the matrix in [1, n - 1]
out rhs The right hand side in [0, n - 1], replaced by the solution vector x
Definition at line 41 of file matrix.tcc.
References _Tp.
    {
      using _Tp = std::decay_t<decltype(__subd[0])>;
      __subd[0] = __diag[0];
      if (__n == 0)
        return 0;
      if (__n == 1)
        {
          __rhs[0] /= __diag[0];
          return 0;
        }
      __diag[0] = __supd[0];
      __supd[0] = _Tp{0};
      __supd[__n - 1] = _Tp{0};
      for (auto __k = 0u; __k < __n - 1; ++__k)
        {
          const auto __k1 = __k + 1;
          if (std::abs(__subd[__k1]) >= std::abs(__subd[__k]))
            {
              std::swap(__subd[__k1], __subd[__k]);
              std::swap(__diag[__k1], __diag[__k]);
              std::swap(__supd[__k1], __supd[__k]);
              std::swap(__rhs[__k1], __rhs[__k]);
            }
          if (__subd[__k] == _Tp{0})
            return 1;
          {
            const auto __t = -__subd[__k1] / __subd[__k];
            __subd[__k1] = __diag[__k1] + __t * __diag[__k];
            __diag[__k1] = __supd[__k1] + __t * __supd[__k];
            __supd[__k1] = _Tp{0};
            __rhs[__k1] = __rhs[__k1] + __t * __rhs[__k];
          }
        }
      if (__subd[__n - 1] == _Tp{0})
        return 1;
      __rhs[__n - 1] = __rhs[__n - 1] / __subd[__n - 1];
      __rhs[__n - 2] = (__rhs[__n - 2] - __diag[__n - 2] * __rhs[__n - 1])
                     / __subd[__n - 2];
      for (std::ptrdiff_t __k = __n ; __k > 2; --__k)
        {
          const auto __kb = __k - 3;
          __rhs[__kb] = (__rhs[__kb] - __diag[__kb] * __rhs[__kb + 1]
                     - __supd[__kb] * __rhs[__kb + 2]) / __subd[__kb];
        }
      return 0;
    }
_S_tridiag_symm()
template<typename _RandAccIter , typename _RandAccIterRHS >
int __gnu_cxx::_S_tridiag_symm (std::size_t __n, _RandAccIter & __diag, _RandAccIter & __subd, _RandAccIterRHS & __rhs)
Diagonalize a symmetric tridiagonal matrix.
This routine is a slightly modified version of the EISPACK routine to perform the implicit QL algorithm on a symmetric tridiagonal matrix.
It has been modified to produce the product Q' * Z, where Z is an input vector and Q is the orthogonal matrix diagonalizing the input matrix. The changes consist (essentialy) of applying the orthogonal transformations directly to Z as they are generated.
Original C++ version by John Burkardt (GPL).
See also
Sylvan Elhay, Jaroslav Kautsky, Algorithm 655: IQPACK, FORTRAN Subroutines for the Weights of Interpolatory Quadrature, ACM Transactions on Mathematical Software, Volume 13, Number 4, December 1987, pages 399-415.
Roger Martin, James Wilkinson, The Implicit QL Algorithm, Numerische Mathematik, Volume 12, Number 5, December 1968, pages 377-383.
Parameters
in n The order of the matrix.
in,out diag The diagonal entries [0, n-1] of the matrix. On output, the information in diag is overwritten.
in,out subd The subdiagonal entries of the matrix, in entries [0, n-2]. On output, the information in subd is overwritten.
in,out rhs On input, a vector. On output, the value of Q' * Z, where Q is the matrix that diagonalizes the input symmetric tridiagonal matrix.
Definition at line 141 of file matrix.tcc.
References _Tp.
Referenced by __gnu_cxx::__detail::__golub_welsch().
    {
      using _Tp = std::decay_t<decltype(__subd[0])>;
      const int __max_iter = 50;
      int __upper = 0;
      const auto __prec = std::numeric_limits<_Tp>::epsilon();
      if (__n == 1)
        return 0;
      __subd[__n - 1] = _Tp{0};
      for (int __lower = 1; __lower <= int(__n); ++__lower)
        {
          int __j = 0;
          while (true)
            {
              for (__upper = __lower; __upper <= int(__n); ++__upper)
                {
                  if (__upper == int(__n))
                    break;
                  if (std::abs(__subd[__upper - 1])
                        <= __prec * (std::abs(__diag[__upper - 1])
                                   + std::abs(__diag[__upper])))
                    break;
                }
              auto __p = __diag[__lower - 1];
              if (__upper == __lower)
                break;
              if (__max_iter <= __j)
                std::__throw_runtime_error("_S_tridiag_symm:"
                                           " Iteration limit exceeded");
              ++__j;
              auto __g = (__diag[__lower] - __p)
                         / (_Tp{2} * __subd[__lower - 1]);
              auto __r = std::sqrt(__g * __g + _Tp{1});
              __g = __diag[__upper - 1] - __p
                  + __subd[__lower - 1]
                        / (__g + std::copysign(std::abs(__r), __g));
              auto __s = _Tp{1};
              auto __c = _Tp{1};
              __p = _Tp{0};
              const auto __mml = __upper - __lower;
              for (int __ii = 1; __ii <= __mml; __ii++)
                {
                  const auto __i = __upper - __ii;
                  auto __f = __s * __subd[__i - 1];
                  auto __b = __c * __subd[__i - 1];
                  if (std::abs(__g) <= std::abs(__f))
                    {
                      __c = __g / __f;
                      __r = std::sqrt(__c * __c + _Tp{1});
                      __subd[__i] = __f * __r;
                      __s = _Tp{1} / __r;
                      __c *= __s;
                    }
                  else
                    {
                      __s = __f / __g;
                      __r = std::sqrt(__s * __s + _Tp{1});
                      __subd[__i] = __g * __r;
                      __c = _Tp{1} / __r;
                      __s *= __c;
                    }
                  __g = __diag[__i] - __p;
                  __r = (__diag[__i - 1] - __g) * __s + _Tp{2} * __c * __b;
                  __p = __s * __r;
                  __diag[__i] = __g + __p;
                  __g = __c * __r - __b;
                  __f = __rhs[__i];
                  __rhs[__i] = __s * __rhs[__i - 1] + __c * __f;
                  __rhs[__i - 1] = __c * __rhs[__i - 1] - __s * __f;
                }
              __diag[__lower - 1] = __diag[__lower - 1] - __p;
              __subd[__lower - 1] = __g;
              __subd[__upper - 1] = _Tp{0};
            }
        }
      // Sorting.
      for (int __ii = 2; __ii <= __upper; ++__ii)
        {
          int __i = __ii - 1;
          int __k = __i;
          auto __p = __diag[__i - 1];
          for (int __j = __ii; __j <= int(__n); ++__j)
            if (__diag[__j - 1] < __p)
              {
                __k = __j;
                __p = __diag[__j - 1];
              }
          if (__k != __i)
            {
              __diag[__k - 1] = __diag[__i - 1];
              __diag[__i - 1] = __p;
              std::swap(__rhs[__i - 1], __rhs[__k - 1]);
            }
        }
      return 0;
    }
_Vinvfx()
template<typename _RetTp >
void __gnu_cxx::_Vinvfx (const std::array< _RetTp, 33 > & __fx, _RetTp * __coeff, const int __depth)
Compute the product of the fx with one of the inverse Vandermonde-like matrices.
Definition at line 41 of file cquad_integrate.tcc.
References _RetTp, V1inv, V2inv, V3inv, and V4inv.
Referenced by cquad_integrate().
    {
      switch (__depth)
        {
        case 0:
          for (int __i = 0; __i <= 4; ++__i)
            {
              __coeff[__i] = _RetTp{0};
              for (int __j = 0; __j <= 4; ++__j)
                __coeff[__i] += _RetTp(V1inv[__i * 5 + __j]) * __fx[__j * 8];
            }
          break;
        case 1:
          for (int __i = 0; __i <= 8; ++__i)
            {
              __coeff[__i] = _RetTp{0};
              for (int __j = 0; __j <= 8; ++__j)
                __coeff[__i] += _RetTp(V2inv[__i * 9 + __j]) * __fx[__j * 4];
            }
          break;
        case 2:
          for (int __i = 0; __i <= 16; ++__i)
            {
              __coeff[__i] = _RetTp{0};
              for (int __j = 0; __j <= 16; ++__j)
                __coeff[__i] += _RetTp(V3inv[__i * 17 + __j]) * __fx[__j * 2];
            }
          break;
        case 3:
          for (int __i = 0; __i <= 32; ++__i)
            {
              __coeff[__i] = _RetTp{0};
              for (int __j = 0; __j <= 32; ++__j)
                __coeff[__i] += _RetTp(V4inv[__i * 33 + __j]) * __fx[__j];
            }
          break;
        }
    }
compute_moments()
template<typename _Tp >
std::vector< _Tp > __gnu_cxx::compute_moments (std::size_t __N, _Tp __cc)
Compute Clenshaw-Curtis moments. An iterator range version would be nicer I think.
Definition at line 272 of file qawc_integrate.tcc.
References __cc, __moment, and _Tp.
    {
      std::vector<_Tp> __moment(__N);
      auto __a0 = std::log(std::abs((_Tp{1} - __cc) / (_Tp{1} + __cc)));
      auto __a1 = _Tp{2} + __a0 * __cc;
      __moment[0] = __a0;
      __moment[1] = __a1;
      for (size_t __k = 2; __k < __N; ++__k)
        {
          _Tp __a2;
          if ((__k % 2) == 0)
            __a2 = _Tp{2} * __cc * __a1 - __a0;
          else
            {
              const auto __km1 = _Tp(__k - 1);
              __a2 = _Tp{2} * __cc * __a1
                   - __a0
                   - _Tp{4} / (__km1 * __km1 - _Tp{1});
            }
          __moment[__k] = __a2;
          __a0 = __a1;
          __a1 = __a2;
        }
      return __moment;
    }
compute_result()
template<typename _Tp , typename _RetTp >
auto __gnu_cxx::compute_result (const std::array< _Tp, 25 > & __r, const std::array< _RetTp, 13 > & __cheb12, const std::array< _RetTp, 25 > & __cheb24) -> compute_result_t<decltype(_Tp
Definition at line 50 of file qaws_integrate.tcc.
Referenced by __gnu_cxx::fn_qaws< _Tp, _FuncTp >::eval_right(), qawf_integrate(), and qc25s().
                                    {} * _RetTp{})>;
cquad_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::cquad_integrate (cquad_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __ws, _FuncTp __func, _Tp __a, _Tp __b, _Tp __epsabs, _Tp __epsrel) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
CQUAD is a new doubly-adaptive general-purpose quadrature routine which can handle most types of singularities, non-numerical function values such as Inf or NaN, as well as some divergent integrals. It generally requires more function evaluations than the other integration routines in this library, yet fails less often for difficult integrands.
The underlying algorithm uses a doubly-adaptive scheme in which Clenshaw-Curtis quadrature rules of increasing degree are used to compute the integral in each interval. The L_2-norm of the difference between the underlying interpolatory polynomials of two successive rules is used as an error estimate. The interval is subdivided if the difference between two successive rules is too large or a rule of maximum degree has been reached.
The CQUAD algorithm divides the integration region into subintervals, and in each iteration, the subinterval with the largest estimated error is processed. The algorithm uses Clenshaw-Curtis quadrature rules of degree 4, 8, 16 and 32 over 5, 9, 17 and 33 nodes respectively. Each interval is initialized with the lowest-degree rule. When an interval is processed, the next-higher degree rule is evaluated and an error estimate is computed based on the L_2-norm of the difference between the underlying interpolating polynomials of both rules. If the highest-degree rule has already been used, or the interpolatory polynomials differ significantly, the interval is bisected.
Definition at line 146 of file cquad_integrate.tcc.
References __func(), __gnu_cxx::cquad_interval< _Tp, _RetTp >::_M_abs_error, __gnu_cxx::cquad_interval< _Tp, _RetTp >::_M_coeff, __gnu_cxx::cquad_interval< _Tp, _RetTp >::_M_lower_lim, __gnu_cxx::cquad_interval< _Tp, _RetTp >::_M_result, __gnu_cxx::cquad_interval< _Tp, _RetTp >::_M_upper_lim, _RetTp, _Tp, _Vinvfx(), __gnu_cxx::cquad_interval< _Tp, _RetTp >::depth, downdate(), __gnu_cxx::cquad_interval< _Tp, _RetTp >::fx, __gnu_cxx::cquad_interval< _Tp, _RetTp >::ndiv, __gnu_cxx::cquad_interval< _Tp, _RetTp >::rdepth, Tleft, Tright, and xi.
    {
      using _RetTp = std::invoke_result_t<_FuncTp, _Tp>;
      using _AreaTp = decltype(_RetTp{} * _Tp{});
      //using _AbsAreaTp = decltype(std::abs(_AreaTp{}));
      using _AbsRetTp = decltype(std::abs(_RetTp{}));
      // Some constants that we will need.
      constexpr std::ptrdiff_t __n[4] = { 4, 8, 16, 32 };
      constexpr std::ptrdiff_t __skip[4] = { 8, 4, 2, 1 };
      constexpr std::ptrdiff_t __idx[4] = { 0, 5, 14, 31 };
      constexpr std::ptrdiff_t __ndiv_max = 20;
      constexpr auto _S_eps = std::numeric_limits<_Tp>::epsilon();
      constexpr auto _S_NaN = std::numeric_limits<_Tp>::quiet_NaN();
      constexpr auto _S_inf = std::numeric_limits<_Tp>::infinity();
      constexpr _Tp _S_sqrt2 = M_SQRT2;
      constexpr auto __w = _S_sqrt2 / _Tp{2};
      // Actual variables (as opposed to constants above).
      bool __split;
      std::ptrdiff_t __num_NaNs, __NaN[32];
      _AbsRetTp __nc, __ncdiff;
      // Check for unreasonable accuracy demands.
      if (__epsabs < _Tp{0} || __epsrel < _Tp{0})
        std::__throw_domain_error("tolerances may not be negative");
      if (__epsabs <= _Tp{0} && __epsrel < _S_eps)
        std::__throw_domain_error("unreasonable accuracy requirement");
      // Create the first interval.
      __ws.clear();
      cquad_interval<_Tp, _RetTp> __iv;
      auto __m = (__a + __b) / _Tp{2};
      auto __h = (__b - __a) / _Tp{2};
      __num_NaNs = 0;
      for (std::ptrdiff_t __i = 0; __i <= __n[3]; ++__i)
        {
          __iv.fx[__i] = __func(__m + _Tp(xi[__i]) * __h);
          if (std::isinf(__iv.fx[__i]) || std::isnan(__iv.fx[__i]))
            {
              __NaN[__num_NaNs++] = __i;
              __iv.fx[__i] = _RetTp{0};
            }
        }
      _Vinvfx(__iv.fx, &(__iv._M_coeff[__idx[0]]), 0);
      _Vinvfx(__iv.fx, &(__iv._M_coeff[__idx[3]]), 3);
      _Vinvfx(__iv.fx, &(__iv._M_coeff[__idx[2]]), 2);
      for (std::ptrdiff_t __i = 0; __i < __num_NaNs; ++__i)
        __iv.fx[__NaN[__i]] = _S_NaN;
      __iv._M_lower_lim = __a;
      __iv._M_upper_lim = __b;
      __iv.depth = 3;
      __iv.rdepth = 1;
      __iv.ndiv = 0;
      __iv._M_result = _Tp{2} * __h * __iv._M_coeff[__idx[3]] * __w;
      __nc = _AbsRetTp{0};
      for (std::ptrdiff_t __i = __n[2] + 1; __i <= __n[3]; ++__i)
        {
          const auto __temp = std::abs(__iv._M_coeff[__idx[3] + __i]);
          __nc += __temp * __temp;
        }
      __ncdiff = __nc;
      for (std::ptrdiff_t __i = 0; __i <= __n[2]; ++__i)
        {
          const auto __temp = std::abs(__iv._M_coeff[__idx[2] + __i]
                                     - __iv._M_coeff[__idx[3] + __i]);
          __ncdiff += __temp * __temp;
          __nc += std::abs(__iv._M_coeff[__idx[3] + __i])
                * std::abs(__iv._M_coeff[__idx[3] + __i]);
        }
      __ncdiff = std::sqrt(__ncdiff);
      __nc = std::sqrt(__nc);
      __iv._M_abs_error = __ncdiff * _Tp{2} * __h;
      if (__ncdiff / __nc > _Tp{0.1} && __iv._M_abs_error < _Tp{2} * __h * __nc)
        __iv._M_abs_error = _Tp{2} * __h * __nc;
      __ws.push(__iv);
      // Main loop...
      auto __igral = __iv._M_result;
      auto __igral_final = _AreaTp{0};
      auto __err = __iv._M_abs_error;
      auto __err_final = _Tp{0};
      while (__ws.size() > 0 && __err > _Tp{0} &&
             !(__err <= std::abs(__igral) * __epsrel || __err <= __epsabs)
             && !(__err_final > std::abs(__igral) * __epsrel
                  && __err - __err_final < std::abs(__igral) * __epsrel)
             && !(__err_final > __epsabs && __err - __err_final < __epsabs))
        {
          // Put our finger on the interval with the largest error.
          auto& __iv = __ws.top();
          __m = (__iv._M_lower_lim + __iv._M_upper_lim) / _Tp{2};
          __h = (__iv._M_upper_lim - __iv._M_lower_lim) / _Tp{2};
          // Should we try to increase the degree?
          if (__iv.depth < 3)
            {
              // Keep tabs on some variables.
              auto __depth = ++__iv.depth;
              // Get the new (missing) function values.
              for (std::ptrdiff_t __i = __skip[__depth];
                        __i <= 32; __i += 2 * __skip[__depth])
                __iv.fx[__i] = __func(__m + _Tp(xi[__i]) * __h);
              __num_NaNs = 0;
              for (std::ptrdiff_t __i = 0; __i <= 32; __i += __skip[__depth])
                if (std::isinf(__iv.fx[__i]) || std::isnan(__iv.fx[__i]))
                  {
                    __NaN[__num_NaNs++] = __i;
                    __iv.fx[__i] = _RetTp{0};
                  }
              // Compute the new coefficients.
              _Vinvfx(__iv.fx, &(__iv._M_coeff[__idx[__depth]]), __depth);
              // Downdate any NaNs.
              if (__num_NaNs > 0)
                {
                  downdate(&(__iv._M_coeff[__idx[__depth]]),
                           __n[__depth], __depth, __NaN, __num_NaNs);
                  for (std::ptrdiff_t __i = 0; __i < __num_NaNs; ++__i)
                    __iv.fx[__NaN[__i]] = _S_NaN;
                }
              // Compute the error estimate.
              __nc = _AbsRetTp{0};
              for (std::ptrdiff_t __i = __n[__depth - 1] + 1;
                   __i <= __n[__depth]; ++__i)
                {
                  const auto __temp = std::abs(__iv._M_coeff[__idx[__depth] + __i]);
                  __nc += __temp * __temp;
                }
              __ncdiff = __nc;
              for (std::ptrdiff_t __i = 0; __i <= __n[__depth - 1]; ++__i)
                {
                  const auto __temp
                    = std::abs(__iv._M_coeff[__idx[__depth - 1] + __i]
                             - __iv._M_coeff[__idx[__depth] + __i]);
                  __ncdiff += __temp * __temp;
                  __nc += abs(__iv._M_coeff[__idx[__depth] + __i])
                        * abs(__iv._M_coeff[__idx[__depth] + __i]);
                }
              __ncdiff = std::sqrt(__ncdiff);
              __nc = std::sqrt(__nc);
              __iv._M_abs_error = __ncdiff * _Tp{2} * __h;
              // Compute the local integral.
              __iv._M_result = _Tp{2} * __h * __w
                             * __iv._M_coeff[__idx[__depth]];
              // Split the interval prematurely?
              __split = (__nc > _Tp{0} && __ncdiff / __nc > _Tp{0.1});
            }
          else // Maximum degree reached, just split.
            __split = true;
          // Should we drop this interval?
          if ((__m + __h * _Tp(xi[0])) >= (__m + __h * _Tp(xi[1]))
              || (__m + __h * _Tp(xi[31])) >= (__m + __h * _Tp(xi[32]))
              || __iv._M_abs_error < std::abs(__iv._M_result) * _S_eps * 10)
            {
              // Keep this interval's contribution.
              __err_final += __iv._M_abs_error;
              __igral_final += __iv._M_result;
              __ws.pop();
            }
          else if (__split) // Do we need to split this interval?
            {
              // Some values we will need often...
              auto __depth = __iv.depth;
              // Generate the interval on the left.
              cquad_interval<_Tp, _RetTp> __ivl;
              __ivl._M_lower_lim = __iv._M_lower_lim;
              __ivl._M_upper_lim = __m;
              __ivl.depth = 0;
              __ivl.rdepth = __iv.rdepth + 1;
              __ivl.fx[0] = __iv.fx[0];
              __ivl.fx[32] = __iv.fx[16];
              for (std::ptrdiff_t __i = __skip[0]; __i < 32; __i += __skip[0])
                __ivl.fx[__i] = __func((__ivl._M_lower_lim + __ivl._M_upper_lim)
                              / _Tp{2} + _Tp(xi[__i]) * __h / _Tp{2});
              __num_NaNs = 0;
              for (std::ptrdiff_t __i = 0; __i <= 32; __i += __skip[0])
                {
                  if (std::isinf(__ivl.fx[__i]) || std::isnan(__ivl.fx[__i]))
                    {
                      __NaN[__num_NaNs++] = __i;
                      __ivl.fx[__i] = _RetTp{0};
                    }
                }
              _Vinvfx(__ivl.fx, __ivl._M_coeff, 0);
              if (__num_NaNs > 0)
                {
                  downdate(__ivl._M_coeff, __n[0], 0, __NaN, __num_NaNs);
                  for (std::ptrdiff_t __i = 0; __i < __num_NaNs; ++__i)
                    __ivl.fx[__NaN[__i]] = _S_NaN;
                }
              for (std::ptrdiff_t __i = 0; __i <= __n[__depth]; ++__i)
                {
                  __ivl._M_coeff[__idx[__depth] + __i] = _Tp{0};
                  for (std::ptrdiff_t __j = __i; __j <= __n[__depth]; ++__j)
                    __ivl._M_coeff[__idx[__depth] + __i]
                        += _Tp(Tleft[__i * 33 + __j])
                           * __iv._M_coeff[__idx[__depth] + __j];
                }
              __ncdiff = _AbsRetTp{0};
              for (std::ptrdiff_t __i = 0; __i <= __n[0]; ++__i)
                {
                  const auto __temp
                    = std::abs(__ivl._M_coeff[__i]
                             - __ivl._M_coeff[__idx[__depth] + __i]);
                  __ncdiff += __temp * __temp;
                }
              for (std::ptrdiff_t __i = __n[0] + 1; __i <= __n[__depth]; ++__i)
                {
                  const auto __temp
                    = std::abs(__ivl._M_coeff[__idx[__depth] + __i]);
                  __ncdiff += __temp * __temp;
                }
              __ncdiff = std::sqrt(__ncdiff);
              __ivl._M_abs_error = __ncdiff * __h;
              // Check for divergence.
              __ivl.ndiv = __iv.ndiv
                         + (std::abs(__iv._M_coeff[0]) > 0
                         && std::abs(__ivl._M_coeff[0] / __iv._M_coeff[0]) > 2);
              if (__ivl.ndiv > __ndiv_max && 2 * __ivl.ndiv > __ivl.rdepth)
                {
                  //const auto __result = std::copysign(_S_inf, __igral);
                  return {_AreaTp(_S_inf), _S_inf};
                }
              // Compute the local integral.
              __ivl._M_result = __h * __w * __ivl._M_coeff[0];
              // Generate the interval on the right.
              cquad_interval<_Tp, _RetTp> __ivr;
              __ivr._M_lower_lim = __m;
              __ivr._M_upper_lim = __iv._M_upper_lim;
              __ivr.depth = 0;
              __ivr.rdepth = __iv.rdepth + 1;
              __ivr.fx[0] = __iv.fx[16];
              __ivr.fx[32] = __iv.fx[32];
              for (std::ptrdiff_t __i = __skip[0]; __i < 32; __i += __skip[0])
                __ivr.fx[__i] = __func((__ivr._M_lower_lim + __ivr._M_upper_lim)
                              / _Tp{2} + _Tp(xi[__i]) * __h / _Tp{2});
              __num_NaNs = 0;
              for (std::ptrdiff_t __i = 0; __i <= 32; __i += __skip[0])
                {
                  if (std::isinf(__ivr.fx[__i]) || std::isnan(__ivr.fx[__i]))
                    {
                      __NaN[__num_NaNs++] = __i;
                      __ivr.fx[__i] = _RetTp{0};
                    }
                }
              _Vinvfx (__ivr.fx, __ivr._M_coeff, 0);
              if (__num_NaNs > 0)
                {
                  downdate(__ivr._M_coeff, __n[0], 0, __NaN, __num_NaNs);
                  for (std::ptrdiff_t __i = 0; __i < __num_NaNs; ++__i)
                    __ivr.fx[__NaN[__i]] = _S_NaN;
                }
              for (std::ptrdiff_t __i = 0; __i <= __n[__depth]; ++__i)
                {
                  __ivr._M_coeff[__idx[__depth] + __i] = _Tp{0};
                  for (std::ptrdiff_t __j = __i; __j <= __n[__depth]; ++__j)
                    __ivr._M_coeff[__idx[__depth] + __i]
                        += _Tp(Tright[__i * 33 + __j])
                         * __iv._M_coeff[__idx[__depth] + __j];
                }
              __ncdiff = _AbsRetTp{0};
              for (std::ptrdiff_t __i = 0; __i <= __n[0]; ++__i)
                {
                  const auto __temp
                    = std::abs(__ivr._M_coeff[__i]
                            - __ivr._M_coeff[__idx[__depth] + __i]);
                  __ncdiff += __temp * __temp;
                }
              for (std::ptrdiff_t __i = __n[0] + 1; __i <= __n[__depth]; ++__i)
                {
                  const auto __temp
                    = std::abs(__ivr._M_coeff[__idx[__depth] + __i]);
                  __ncdiff += __temp * __temp;
                }
              __ncdiff = std::sqrt(__ncdiff);
              __ivr._M_abs_error = __ncdiff * __h;
              // Check for divergence.
              __ivr.ndiv = __iv.ndiv
                         + (std::abs(__iv._M_coeff[0]) > 0
                         && std::abs(__ivr._M_coeff[0] / __iv._M_coeff[0]) > 2);
              if (__ivr.ndiv > __ndiv_max && 2 * __ivr.ndiv > __ivr.rdepth)
                {
                  //const auto __result = std::copysign(_S_inf, __igral);
                  return {_AreaTp(_S_inf), _S_inf};
                }
              // Compute the local integral.
              __ivr._M_result = __h * __w * __ivr._M_coeff[0];
              __ws.pop();
              __ws.push(__ivl);
              __ws.push(__ivr);
            }
          else // Otherwise, just fix-up the heap.
            __ws.update();
          // Collect the value of the integral and error.
          __igral = __igral_final + __ws.total_integral();
          __err = __err_final + __ws.total_error();
        }
      return {__igral, __err};
    }
downdate()
template<typename _Tp >
void __gnu_cxx::downdate (_Tp * __coeff, std::ptrdiff_t __n, std::ptrdiff_t __depth, std::ptrdiff_t * __NaN, std::ptrdiff_t __num_NaNs)
Downdate the interpolation given by the n coefficients c by removing the nodes with indices in NaNs.
Definition at line 90 of file cquad_integrate.tcc.
References _Tp, bee, Lalpha, Lgamma, and xi.
Referenced by cquad_integrate().
    {
      constexpr std::ptrdiff_t __bidx[4] = { 0, 6, 16, 34 };
      _Tp __b_new[34], __alpha;
      for (std::ptrdiff_t __i = 0; __i <= __n + 1; ++__i)
        __b_new[__i] = bee[__bidx[__depth] + __i];
      for (std::ptrdiff_t __i = 0; __i < __num_NaNs; ++__i)
        {
          __b_new[__n + 1] = __b_new[__n + 1] / _Tp(Lalpha[__n]);
          __b_new[__n] = (__b_new[__n] + _Tp(xi[__NaN[__i]]) * __b_new[__n + 1])
                       / _Tp(Lalpha[__n - 1]);
          for (std::ptrdiff_t __j = __n - 1; __j > 0; --__j)
            __b_new[__j] = (__b_new[__j] + _Tp(xi[__NaN[__i]]) * __b_new[__j + 1]
                           - _Tp(Lgamma[__j + 1]) * __b_new[__j + 2])
                         / _Tp(Lalpha[__j - 1]);
          for (std::ptrdiff_t __j = 0; __j <= __n; ++__j)
            __b_new[__j] = __b_new[__j + 1];
          __alpha = __coeff[__n] / __b_new[__n];
          for (std::ptrdiff_t __j = 0; __j < __n; ++__j)
            __coeff[__j] -= __alpha * __b_new[__j];
          __coeff[__n] = _Tp{0};
          --__n;
        }
    }
fast_fourier_transform() [1/3]
template<typename _Tp >
void __gnu_cxx::fast_fourier_transform (std::vector< std::complex< _Tp >> & __z)
Fast Fourier Transform on complex data.
Definition at line 70 of file fourier_transform.tcc.
References __discrete_fourier_transform(), and _Tp.
Referenced by fast_fourier_transform(), fast_sine_transform(), and __gnu_cxx::fourier_transform_t< std::complex< _Tp > >::operator[]().
    {
      const auto __len = __z.size();
      if (__len % 2 == 1) // Too bad, we're odd.
        __discrete_fourier_transform(true, __z);
      else // Good, we're even.
        {
          // Let's divide and conquer!
          std::vector<std::complex<_Tp>> __odd;
          std::vector<std::complex<_Tp>> __even;
          const auto __halflen = __len / 2;
          __odd.reserve(__halflen);
          __even.reserve(__halflen);
          for (auto __run = __z.cbegin(); __run != __z.cend(); ++__run)
            {
              __even.push_back(*__run);
              ++__run;
              __odd.push_back(*__run);
            }
          fast_fourier_transform(__even);
          fast_fourier_transform(__odd);
          __phase_iterator __omega_iter(_Tp{1}, 1, __len);
          for (std::size_t __i = 0, __j = __halflen; __i < __halflen;
                ++__i, ++__j, ++__omega_iter)
            {
              __z[__i] = (__even[__i] + *__omega_iter * __odd[__i]) / _Tp{2};
              // The next line works because omega^(length/2) = -1.
              __z[__j] = (__even[__i] - *__omega_iter * __odd[__i]) / _Tp{2};
            }
        }
    }
fast_fourier_transform() [2/3]
template<typename _Tp >
void __gnu_cxx::fast_fourier_transform (std::vector< _Tp > & __x)
Fast Fourier Transform on real data.
Definition at line 144 of file fourier_transform.tcc.
References _Tp, and fast_fourier_transform().
    {
      const auto __len = __x.size();
      if (__len % 2 == 1) // Too bad, we're odd.
        std::__throw_domain_error("fast_fourier_transform: "
                                  "Real data must have even length.");
      else // Good, we're even.
        {
          // @todo I really want to just make a view to a complex vector.
          const auto __halflen = __len / 2;
          std::vector<std::complex<_Tp>> __z;
          __z.reserve(__halflen + 1);
          for (std::size_t __i = 0; __i < __halflen; ++__i)
            __z.emplace_back(__x[2 * __i], __x[2 * __i + 1]);
          fast_fourier_transform(__z);
          __z.emplace_back(__z[0]); // Use symmetry. We need N/2 transform.
          const auto _S_i2 = std::complex<_Tp>{0, 2};
          __phase_iterator __omega_iter(_Tp{+1}, 1, __halflen);
          for (std::size_t __i = 0; __i < __halflen; ++__i)
            {
              const auto __z1 = __z[__i];
              const auto __z2 = std::conj(__z[__halflen - __i]);
              const auto __f = (__z1 + __z2) / _Tp{2}
                             + *__omega_iter * (__z1 - __z2) / _S_i2;
              __x[2 * __i] = __f.real();
              __x[2 * __i + 1] = __f.imag();
            }
        }
    }
fast_fourier_transform() [3/3]
template<typename _CmplxIter >
void __gnu_cxx::fast_fourier_transform (const _CmplxIter & __from, const _CmplxIter & __to)
Fast Fourier Transform on input range.
Definition at line 259 of file fourier_transform.tcc.
References _Tp, and fast_fourier_transform().
    {
      using _Cmplx = typename _CmplxIter::value_type;
      using _Tp = typename _Cmplx::value_type;
      std::vector<std::complex<_Tp>> __z(__from, __to);
      fast_fourier_transform(__z);
      std::copy(__z.begin(), __z.end(), __from);
    }
fast_sine_transform()
template<typename _Tp >
void __gnu_cxx::fast_sine_transform (std::vector< _Tp > & __x)
Fast Sine Transform on real data.
Definition at line 215 of file fourier_transform.tcc.
References _Tp, and fast_fourier_transform().
Referenced by inv_fast_sine_transform(), and __gnu_cxx::fourier_transform_t< std::complex< _Tp > >::operator[]().
    {
      const auto __len = __x.size();
      const auto __halflen = __len / 2;
      const auto __n2 = __len - 1;
      __phase_iterator __omega_iter(_Tp{+1}, 1, __len);
      __x[0] = _Tp{0};
      for (std::size_t __k = 1; __k <= __halflen; ++__k, ++__omega_iter)
        {
          const auto __y1 = __omega_iter.sin()
                          * (__x[__k] + __x[__n2 - __k]);
          const auto __y2 = (__x[__k] - __x[__n2 - __k]) / _Tp{2};
          __x[__k] = __y1 + __y2;
          __x[__n2 - __k] = __y1 - __y2;
        }
      fast_fourier_transform(__x);
      __x[0] *= _Tp{0.5L};
      __x[1] = _Tp{0};
      auto __sum = _Tp{0};
      for (std::size_t __i = 2; __i < __halflen; __i += 2)
        {
          __sum += std::exchange(__x[__i], __x[__i + 1]);
          __x[__i + 1] = __sum;
        }
    }
for()
__gnu_cxx::for () = __cheb24[__i] * __moment[__i]
if()
__gnu_cxx::if (std::abs(__cc) , _Tp{1.1})
Definition at line 229 of file qawc_integrate.tcc.
                            {1.1})
        {
          auto __func_cauchy = [__func, __center](_Tp __x)
                                -> _Tp
                                { return __func(__x) / (__x - __center); };
          auto [__result, __abserr, __resabs, __resasc]
            = __quad(__func_cauchy, __lower, __upper);
          if (__abserr == __resasc)
            __err_reliable = false;
          else
            __err_reliable = true;
          return std::make_tuple(__result, __abserr, __err_reliable);
        }
integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024, Kronrod_Rule __qkintrule = Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate a smooth function from a to b.
Higher-order rules converge more rapidly for most functions, but may slow convergence for less well-behaved ones.
Parameters
func The function to be integrated.
lower The lower limit of integration.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
qkintrule is the Gauss-Kronrod integration rule.
Returns
A structure containing the integration result and the error.
Referenced by qk_integrate(), and valid_tolerances().
integrate_cauchy_principal_value()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_cauchy_principal_value (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __center, _Tp __max_abs_err, _Tp __max_rel_err, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate the principal value of a function with a Cauchy singularity.
Referenced by integrate_singular_pinf_upper().
integrate_clenshaw_curtis()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_clenshaw_curtis (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate a function using an adaptive Clenshaw-Curtis algorithm.
Template Parameters
_FuncTp A function type that takes a single real scalar argument and returns a real scalar.
_Tp A real type for the limits of integration and the step.
Referenced by integrate_singular_pinf_upper().
integrate_exp_sinh()
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_exp_sinh (_FuncTp __func, _Tp __a, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
 \int_{0}^{+\infty}f(x)dx 
 Making the change of variables:
 x = exp\left[\frac{\pi}{2}sinh(u)\right], dx = \frac{\pi}{2} cosh(u) exp\left[\frac{\pi}{2}sinh(u)\right]du 
 gives the following integral:
 \int_{0}^{+\infty}f(exp\left[\frac{\pi}{2}sinh(u)\right]) = \sum_{k=-n}^{+n} 
This function allows a non-zero lower limit a.
Parameters
func The function to be integrated.
a The lower limit of the semi-infinite integral.
Definition at line 223 of file double_exp_integrate.tcc.
References __func(), _RetTp, and _Tp.
Referenced by integrate_singular_pinf_upper().
    {
      using _RetTp = std::invoke_result_t<_FuncTp, _Tp>;
      using _AreaTp = decltype(_RetTp{} * _Tp{});
      int __n = 16;
      const auto _S_pi_4 = __gnu_cxx::math::__pi_quarter_v<_Tp>;
      // Find K = ln(ln(max_number))
      const auto __k_max = std::log(std::log(std::numeric_limits<_Tp>::max()))
                - _Tp{1};
      auto __h = __k_max / __n;
      auto __sum = _AreaTp{0};
      for (int __k = -__n; __k <= __n; ++__k)
        {
          const auto __u = __h * _Tp(__k);
          const auto __eu = std::exp(__u);
          const auto __cosh = __eu + _Tp{1} / __eu;
          const auto __sinh = __eu - _Tp{1} / __eu;
          const auto __esh = std::exp(_S_pi_4 * __sinh);
          const auto __dxdu = __cosh * __esh;
          __sum += __dxdu * __func(__a + __esh);
        }
      // Interlace values (don't go past the rightmost point).
      decltype(__sum) __prev_sum{};
      for (int __iter = 0; __iter < __max_iter; ++__iter)
        {
          __prev_sum = __sum;
          for (int __k = -__n; __k < __n; ++__k)
            {
              const auto __u = __h * _Tp(__k + 0.5);
              const auto __eu = std::exp(__u);
              const auto __cosh = __eu + _Tp{1} / __eu;
              const auto __sinh = __eu - _Tp{1} / __eu;
              const auto __esh = std::exp(_S_pi_4 * __sinh);
              const auto __dxdu = __cosh * __esh;
              __sum += __dxdu * __func(__a + __esh);
            }
          const auto __curr_sum = __sum;
          if (auto __abs_del = std::abs(__curr_sum - __prev_sum);
              __abs_del < __max_abs_err
              || __abs_del < std::abs(__max_rel_err * __curr_sum))
            break;
          __n *= 2;
          __h /= _Tp{2};
        }
      const auto __fact = _S_pi_4 * __h;
      const auto __tot_sum = __sum;
      return {__fact * __tot_sum, __fact * std::abs(__tot_sum - __prev_sum)};
    }
integrate_fixed_gauss_chebyshev_t()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_chebyshev_t (int __n, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 261 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_chebyshev_t_integral<_Tp> __integ(__n);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_chebyshev_u()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_chebyshev_u (int __n, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 271 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_chebyshev_u_integral<_Tp> __integ(__n);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_chebyshev_v()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_chebyshev_v (int __n, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 280 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_chebyshev_v_integral<_Tp> __integ(__n);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_chebyshev_w()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_chebyshev_w (int __n, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 289 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_chebyshev_w_integral<_Tp> __integ(__n);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_exponential()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_exponential (int __n, _Tp __alf, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 334 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_exponential_integral<_Tp> __integ(__n, __alf);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_gegenbauer()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_gegenbauer (int __n, _Tp __lambda, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 298 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_gegenbauer_integral<_Tp> __integ(__n, __lambda);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_hermite()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_hermite (int __n, _Tp __alf, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 325 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_hermite_integral<_Tp> __integ(__n, __alf);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_jacobi()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_jacobi (int __n, _Tp __alf, _Tp __bet, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 307 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_jacobi_integral<_Tp> __integ(__n, __alf, __bet);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_laguerre()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_laguerre (int __n, _Tp __alf, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 316 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_laguerre_integral<_Tp> __integ(__n, __alf);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_legendre()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_legendre (int __n, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 252 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_legendre_integral<_Tp> __integ(__n);
      return { __integ(__func, __a, __b) };
    }
integrate_fixed_gauss_rational()
template<typename _Tp , typename _FuncTp >
fixed_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_fixed_gauss_rational (int __n, _Tp __alf, _Tp __bet, _FuncTp __func, _Tp __a, _Tp __b)
Definition at line 343 of file gauss_quadrature.h.
Referenced by integrate_singular_pinf_upper().
    {
      fixed_gauss_rational_integral<_Tp> __integ(__n, __alf, __bet);
      return { __integ(__func, __a, __b) };
    }
integrate_kronrod_singular()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_kronrod_singular (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Adaptive Gauss-Kronrod integration optimized for discontinuous or singular functions
Parameters
func The function to be integrated.
lower The lower limit of integration.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
Returns
A structure containing the integration result and the error.
Referenced by integrate_pinf_upper().
integrate_lower_minf()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_lower_minf (_FuncTp __func, _Tp __lower, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024, Kronrod_Rule __qkintrule = Kronrod_21) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
     [inline]
Definition at line 225 of file integration.h.
References _Tp, integrate_lower_pinf(), and integrate_minf_upper().
    {
      return -integrate_minf_upper(__func, __lower,
                                   __max_abs_error, __max_rel_error,
                                   __max_iter, __qkintrule);
    }
integrate_lower_pinf()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_lower_pinf (_FuncTp __func, _Tp __lower, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024, Kronrod_Rule __qkintrule = Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate a smooth function from finite lower limit to +infinity.
Parameters
func The function to be integrated.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
qkintrule is the Gauss-Kronrod integration rule.
Returns
A structure containing the integration result and the error.
Referenced by integrate_lower_minf(), and integrate_pinf_upper().
integrate_midpoint()
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_midpoint (_FuncTp __func, _Tp __a, _Tp __b, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter) [inline]
Definition at line 129 of file midpoint_integral.h.
References __gnu_cxx::midpoint_integral< _Tp, _FuncTp >::abs_error().
Referenced by integrate_singular_pinf_upper().
    {
      midpoint_integral<_Tp, _FuncTp>
        __mpi(__func, __a, __b, __max_abs_err, __max_rel_err, __max_iter);
      return {__mpi(), __mpi.abs_error()};
    }
integrate_minf_pinf()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_minf_pinf (_FuncTp __func, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024, Kronrod_Rule __qkintrule = Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrates a smooth function from -infinity to +infinity.
Parameters
func The function to be integrated.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
qkintrule is the Gauss-Kronrod integration rule.
Returns
A structure containing the integration result and the error.
Referenced by valid_tolerances().
integrate_minf_upper()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_minf_upper (_FuncTp __func, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024, Kronrod_Rule __qkintrule = Kronrod_21) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate a smooth function from -infinity to finite b.
Parameters
func The function to be integrated.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
qkintrule is the Gauss-Kronrod integration rule.
Returns
A structure containing the integration result and the error.
Referenced by integrate_lower_minf(), and valid_tolerances().
integrate_multisingular()
template<typename _FuncTp , typename _FwdIter , typename _Tp >
auto __gnu_cxx::integrate_multisingular (_FuncTp __func, _FwdIter __ptbeg, _FwdIter __ptend, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Adaptively integrate a function with known singular/discontinuous points.
Template Parameters
_FuncTp A function type that takes a single real scalar argument and returns a real scalar.
_Tp A real type for the limits of integration and the step.
Referenced by integrate_singular_pinf_upper().
integrate_oscillatory()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_oscillatory (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate an oscillatory function.
Referenced by integrate_singular_pinf_upper().
integrate_patterson()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_patterson (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Adaptively integrate a function using a recursive Gauss-Kronrod quadrature called the Patterson algorithm.
Referenced by integrate_singular_pinf_upper().
integrate_pinf_upper()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_pinf_upper (_FuncTp __func, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024, Kronrod_Rule __qkintrule = Kronrod_21) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
     [inline]
Definition at line 261 of file integration.h.
References _Tp, integrate_kronrod_singular(), integrate_lower_pinf(), integrate_singular_minf_pinf(), and integrate_singular_minf_upper().
    {
      return -integrate_lower_pinf(__func, __upper,
                                   __max_abs_error, __max_rel_error,
                                   __max_iter, __qkintrule);
    }
integrate_simpson()
template<typename _Tp , typename _FuncTp >
adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp> > __gnu_cxx::integrate_simpson (_FuncTp __func, _Tp __a, _Tp __b, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter) [inline]
Definition at line 130 of file simpson_integral.h.
References __gnu_cxx::simpson_integral< _Tp, _FuncTp >::abs_error().
    {
      simpson_integral<_Tp, _FuncTp>
        __simpi(__func, __a, __b, __max_abs_err, __max_rel_err, __max_iter);
      return {__simpi(), __simpi.abs_error()};
    }
integrate_singular()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_singular (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate a potentially singular function.
Parameters
func The function to be integrated.
lower The lower limit of integration.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
Returns
A structure containing the integration result and the error.
Referenced by integrate_singular_pinf_upper().
integrate_singular_endpoints()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_singular_endpoints (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __alpha, _Tp __beta, int __mu, int __nu, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
The singular weight function is defined by:
 W(x) = (x-a)^\alpha (b-x)^\beta log^\mu (x-a) log^\nu (b-x) 
 where $ \alpha > -1 $, $ \beta > -1 $, and $ \mu = 0 $, 1, $ \nu = 0, 1 $.
The weight function can take four different forms depending on the values of and ,
 W(x) = (x-a)^\alpha (b-x)^\beta (\mu = 0, \nu = 0) W(x) = (x-a)^\alpha (b-x)^\beta log(x-a) (\mu = 1, \nu = 0) W(x) = (x-a)^\alpha (b-x)^\beta log(b-x) (\mu = 0, \nu = 1) W(x) = (x-a)^\alpha (b-x)^\beta log(x-a) log(b-x) (\mu = 1, \nu = 1) 
The QAWS algorithm is designed for integrands with algebraic-logarithmic singularities at the end-points of an integration region.
Referenced by integrate_singular_pinf_upper().
integrate_singular_lower_minf()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_singular_lower_minf (_FuncTp __func, _Tp __lower, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
     [inline]
Definition at line 325 of file integration.h.
References _Tp, integrate_singular_lower_pinf(), and integrate_singular_minf_upper().
    {
      return -integrate_singular_minf_upper(__func, __lower,
                                            __max_abs_error, __max_rel_error,
                                            __max_iter);
    }
integrate_singular_lower_pinf()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_singular_lower_pinf (_FuncTp __func, _Tp __lower, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrates a potentially singular function from a to +infinity
Parameters
func The function to be integrated.
lower The lower limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
Returns
A structure containing the integration result and the error.
Referenced by integrate_singular_lower_minf(), and integrate_singular_pinf_upper().
integrate_singular_minf_pinf()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_singular_minf_pinf (_FuncTp __func, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate a potentially singular function from -infinity to +infinity
Parameters
func The function to be integrated.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
Returns
A structure containing the integration result and the error.
Referenced by integrate_pinf_upper().
integrate_singular_minf_upper()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_singular_minf_upper (_FuncTp __func, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp >>
Integrate a potentially singular function from -infinity to b
Referenced by integrate_pinf_upper(), and integrate_singular_lower_minf().
integrate_singular_pinf_upper()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::integrate_singular_pinf_upper (_FuncTp __func, _Tp __upper, _Tp __max_abs_error, _Tp __max_rel_error, std::size_t __max_iter = 1024) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
     [inline]
Definition at line 356 of file integration.h.
References _Tp, integrate_cauchy_principal_value(), integrate_clenshaw_curtis(), integrate_exp_sinh(), integrate_fixed_gauss_chebyshev_t(), integrate_fixed_gauss_chebyshev_u(), integrate_fixed_gauss_chebyshev_v(), integrate_fixed_gauss_chebyshev_w(), integrate_fixed_gauss_exponential(), integrate_fixed_gauss_gegenbauer(), integrate_fixed_gauss_hermite(), integrate_fixed_gauss_jacobi(), integrate_fixed_gauss_laguerre(), integrate_fixed_gauss_legendre(), integrate_fixed_gauss_rational(), integrate_midpoint(), integrate_multisingular(), integrate_oscillatory(), integrate_patterson(), integrate_singular(), integrate_singular_endpoints(), integrate_singular_lower_pinf(), integrate_sinh_sinh(), integrate_tanh_sinh(), and integrate_trapezoid().
    {
      return -integrate_singular_lower_pinf(__func, __upper,
                                            __max_abs_error, __max_rel_error,
                                            __max_iter);
    }
integrate_sinh_sinh()
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_sinh_sinh (_FuncTp __func, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
 \int_{-\infty}^{+\infty}f(x)dx 
 Making the change of variables:
 x = sinh\left[\frac{\pi}{2}sinh(u)\right], dx = \frac{\pi}{2} cosh(u) cosh\left[\frac{\pi}{2}sinh(u)\right]du 
 gives the following integral:
 \int_{-\infty}^{+\infty}f(sinh\left[\frac{\pi}{2}sinh(u)\right]) = \sum_{k=-n}^{+n} 
Definition at line 137 of file double_exp_integrate.tcc.
References __func(), and _Tp.
Referenced by integrate_singular_pinf_upper().
    {
      const auto _S_pi_4 = __gnu_cxx::math::__pi_quarter_v<_Tp>;
      int __n = 16;
      __n /= 2;
      // Find K = ln(ln(max_number))
      const auto __k_max = std::log(std::log(std::numeric_limits<_Tp>::max()))
                - _Tp{1};
      auto __h = __k_max / __n;
      auto __sum = __func(_Tp{0});
      decltype(__sum) __sum1{}, __sum2{};
      for (int __k = -__n; __k < 0; ++__k)
        {
          const auto __u = __h * _Tp(__k);
          const auto __eu = std::exp(__u);
          const auto __cosh = __eu + _Tp{1} / __eu;
          const auto __sinh = __eu - _Tp{1} / __eu;
          const auto __esh = std::exp(_S_pi_4 * __sinh);
          const auto __x = (__esh - _Tp{1} / __esh) / _Tp{2};
          const auto __w = __esh + _Tp{1} / __esh;
          const auto __dxdu = __cosh * __w / _Tp{4};
          __sum1 += __dxdu * __func(+__x);
          __sum2 += __dxdu * __func(-__x);
        }
      decltype(__sum) __prev_sum{};
      for (int __iter = 0; __iter < __max_iter; ++__iter)
        {
          __prev_sum = __sum + __sum1 + __sum2;
          for (int __k = -__n; __k < 0; ++__k)
            {
              const auto __u = __h * _Tp(__k + 0.5);
              const auto __eu = std::exp(__u);
              const auto __cosh = __eu + _Tp{1} / __eu;
              const auto __sinh = __eu - _Tp{1} / __eu;
              const auto __esh = std::exp(_S_pi_4 * __sinh);
              const auto __x = (__esh - _Tp{1} / __esh) / _Tp{2};
              const auto __w = __esh + _Tp{1} / __esh;
              const auto __dxdu = __cosh * __w / _Tp{4};
              __sum1 += __dxdu * __func(+__x);
              __sum2 += __dxdu * __func(-__x);
            }
          const auto __curr_sum = __sum + __sum1 + __sum2;
          if (auto __abs_del = std::abs(__curr_sum - __prev_sum);
              __abs_del < __max_abs_err
              || __abs_del < std::abs(__max_rel_err * __curr_sum))
            break;
          __n *= 2;
          __h /= _Tp{2};
        }
      const auto __fact = _Tp{2} * _S_pi_4 * __h;
      const auto __tot_sum = __sum + __sum1 + __sum2;
      return {__fact * __tot_sum, __fact * std::abs(__tot_sum - __prev_sum)};
    }
integrate_tanh_sinh()
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_tanh_sinh (_FuncTp __func, _Tp __a, _Tp __b, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter)
 \int_{-1}^{+1}f(x)dx 
 Making the change of variables:
 x = tanh\left[\frac{\pi}{2}sinh(u)\right], dx = \frac{\pi}{2} \frac{cosh(u)}{cosh^2\left[\frac{\pi}{2}sinh(u)\right]}du 
 gives the following integral:
 \int_{-\infty}^{+\infty}f(tanh\left[\frac{\pi}{2}sinh(u)\right]) = \sum_{k=-n}^{+n} 
Definition at line 46 of file double_exp_integrate.tcc.
References __func(), and _Tp.
Referenced by integrate_singular_pinf_upper().
    {
      const auto _S_pi_4 = __gnu_cxx::math::__pi_quarter_v<_Tp>;
      int __n = 16;
      __n /= 2;
      // Find K = ln(ln(max_number))
      const auto __k_max = std::log(std::log(std::numeric_limits<_Tp>::max()))
                - _Tp{1};
      auto __h = __k_max / __n;
      auto __sum = __func((__a + __b) / _Tp{2}) / _Tp{2};
      decltype(__sum) __sum1{}, __sum2{};
      for (int __k = -__n; __k < 0; ++__k)
        {
          const auto __u = __h * _Tp(__k);
          const auto __eu = std::exp(__u);
          const auto __cosh = __eu + _Tp{1} / __eu;
          const auto __sinh = __eu - _Tp{1} / __eu;
          const auto __esh = std::exp(_S_pi_4 * __sinh);
          const auto __w = __esh + _Tp{1} / __esh;
          const auto __dxdu = __cosh / (__w * __w);
          const auto __x1 = (__b * __esh + __a / __esh) / __w;
          if (__x1 != __a && __x1 != __b)
            __sum1 += __dxdu * __func(__x1);
          const auto __x2 = (__a * __esh + __b / __esh) / __w;
          if (__x2 != __a && __x2 != __b)
            __sum2 += __dxdu * __func(__x2);
        }
      // Interlace values; don't go past the rightmost point.
      decltype(__sum) __prev_sum{};
      for (int __iter = 0; __iter < __max_iter; ++__iter)
        {
          __prev_sum = __sum + __sum1 + __sum2;
          for (int __k = -__n; __k < 0; ++__k)
            {
              const auto __u = __h * _Tp(__k + 0.5);
              const auto __eu = std::exp(__u);
              // A standard sinhcosh would be a nice idea along with sincos.
              const auto __cosh = __eu + _Tp{1} / __eu;
              const auto __sinh = __eu - _Tp{1} / __eu;
              const auto __esh = std::exp(_S_pi_4 * __sinh);
              const auto __w = __esh + _Tp{1} / __esh;
              const auto __dxdu = __cosh / (__w * __w);
              // natural: x1 = (s - 1/s) / (s + 1/s)
              const auto __x1 = (__b * __esh + __a / __esh) / __w;
              if (__x1 != __a && __x1 != __b)
                __sum1 += __dxdu * __func(__x1);
              // natural: x2 = (-s + 1/s) / (s + 1/s)
              const auto __x2 = (__a * __esh + __b / __esh) / __w;
              if (__x2 != __a && __x2 != __b)
                __sum2 += __dxdu * __func(__x2);
            }
          const auto __curr_sum = __sum + __sum1 + __sum2;
          if (auto __abs_del = std::abs(__curr_sum - __prev_sum);
              __abs_del < __max_abs_err
              || __abs_del < std::abs(__max_rel_err * __curr_sum))
            break;
          __n *= 2;
          __h /= _Tp{2};
        }
      const auto __fact = _Tp{2} * (__b - __a) * _S_pi_4 * __h;
      const auto __tot_sum = __sum + __sum1 + __sum2;
      return {__fact * __tot_sum, __fact * std::abs(__tot_sum - __prev_sum)};
    }
integrate_trapezoid()
template<typename _Tp , typename _FuncTp >
adaptive_integral_t< _Tp, std::invoke_result_t< _FuncTp, _Tp > > __gnu_cxx::integrate_trapezoid (_FuncTp __func, _Tp __a, _Tp __b, _Tp __max_abs_err, _Tp __max_rel_err, int __max_iter) [inline]
Definition at line 129 of file trapezoid_integral.h.
References __gnu_cxx::trapezoid_integral< _Tp, _FuncTp >::abs_error().
Referenced by integrate_singular_pinf_upper().
    {
      trapezoid_integral<_Tp, _FuncTp>
        __trapi(__func, __a, __b, __max_abs_err, __max_rel_err, __max_iter);
      return {__trapi(), __trapi.abs_error()};
    }
inv_fast_fourier_transform() [1/3]
template<typename _Tp >
void __gnu_cxx::inv_fast_fourier_transform (std::vector< std::complex< _Tp >> & __z)
Inverse Fast Fourier Transform on complex data.
Definition at line 107 of file fourier_transform.tcc.
References __discrete_fourier_transform(), and _Tp.
Referenced by inv_fast_fourier_transform(), and __gnu_cxx::fourier_transform_t< std::complex< _Tp > >::operator[]().
    {
      const std::size_t __len = __z.size();
      if (__len % 2 == 1) // Too bad, we're odd.
        __discrete_fourier_transform(false, __z);
      else // Good, we are even.
        {
          // Let's divide and conquer!
          std::vector<std::complex<_Tp>> __odd;
          std::vector<std::complex<_Tp>> __even;
          const auto __halflen = __len / 2;
          __odd.reserve(__halflen);
          __even.reserve(__halflen);
          for (auto __run = __z.cbegin(); __run != __z.cend(); ++__run)
            {
              __even.push_back(*__run);
              ++__run;
              __odd.push_back(*__run);
            }
          inv_fast_fourier_transform(__even);
          inv_fast_fourier_transform(__odd);
          __phase_iterator __omega_iter(_Tp{-1}, 1, __len);
          for (std::size_t __i = 0, __j = __halflen; __i < __halflen;
                ++__i, ++__j, ++__omega_iter)
            {
              __z[__i] = __even[__i] + *__omega_iter * __odd[__i];
              // The next line works because omega^(length/2) = -1.
              __z[__j] = __even[__i] - *__omega_iter * __odd[__i];
            }
        }
    }
inv_fast_fourier_transform() [2/3]
template<typename _Tp >
void __gnu_cxx::inv_fast_fourier_transform (std::vector< _Tp > & __x)
Inverse Fast Fourier Transform on real data.
Definition at line 179 of file fourier_transform.tcc.
References _Tp, and inv_fast_fourier_transform().
    {
      const auto __len = __x.size();
      if (__len % 2 == 1) // Too bad, we're odd.
        std::__throw_domain_error("inv_fast_fourier_transform: "
                                  "Real data must have even length.");
      else // Good, we're even.
        {
          // @todo I really want to just make a view to a complex vector.
          const auto __halflen = __len / 2;
          std::vector<std::complex<_Tp>> __z;
          __z.reserve(__halflen);
          const auto _S_i2 = std::complex<_Tp>{0, 2};
          __phase_iterator __omega_iter(_Tp{-1}, 1, __halflen);
          for (std::size_t __i = 0; __i < __halflen; ++__i)
            {
              const auto __z1 = std::complex<_Tp>(__x[2 * __i], __x[2 * __i + 1]);
              const auto __z2 = std::complex<_Tp>(__x[__len - 2 * __i - 2], -__x[__len - 2 * __i - 1]);
              const auto __ze = (__z1 + __z2) / _Tp{2};
              const auto __zo = -*__omega_iter * (__z1 - __z2) / _S_i2;
              __z.emplace_back(__ze + __zo);
            }
          inv_fast_fourier_transform(__z);
          for (std::size_t __i = 0; __i < __halflen; ++__i)
            {
              __x[2 * __i] = __z[__i].real();
              __x[2 * __i + 1] = __z[__i].imag();
            }
        }
    }
inv_fast_fourier_transform() [3/3]
template<typename _CmplxIter >
void __gnu_cxx::inv_fast_fourier_transform (const _CmplxIter & __from, const _CmplxIter & __to)
Inverse Fast Fourier Transform on input range.
Definition at line 273 of file fourier_transform.tcc.
References _Tp, and inv_fast_fourier_transform().
    {
      using _Cmplx = typename _CmplxIter::value_type;
      using _Tp = typename _Cmplx::value_type;
      std::vector<std::complex<_Tp>> __z(__from, __to);
      inv_fast_fourier_transform(__z);
      std::copy(__z.begin(), __z.end(), __from);
    }
inv_fast_sine_transform()
template<typename _Tp >
void __gnu_cxx::inv_fast_sine_transform (std::vector< _Tp > & __x)
Fast Sine Transform on real data.
Definition at line 246 of file fourier_transform.tcc.
References _Tp, and fast_sine_transform().
Referenced by __gnu_cxx::fourier_transform_t< std::complex< _Tp > >::operator[]().
    {
      fast_sine_transform(__x);
      const auto __norm = _Tp{2} / __x.size();
      for (std::size_t __i = 0; __i < __x.size(); ++__i)
        __x[__i] *= __norm;
    }
operator<()
template<typename _Tp , typename _RetTp >
bool __gnu_cxx::operator< (const cquad_interval< _Tp, _RetTp > & __ivl, const cquad_interval< _Tp, _RetTp > & __ivr)
Comparison of cquad intervals.
Definition at line 59 of file cquad_workspace.h.
References __gnu_cxx::cquad_interval< _Tp, _RetTp >::_M_abs_error.
    { return __ivl._M_abs_error < __ivr._M_abs_error; }
operator<<()
template<typename _Tp , typename _RetTp >
std::ostream & __gnu_cxx::operator<< (std::ostream & __out, const integration_workspace< _Tp, _RetTp > & __ws)
Output the integration workspace to a stream.
Definition at line 145 of file integration_workspace.tcc.
References __gnu_cxx::integration_workspace< _Tp, _RetTp >::curr_index(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::intervals(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::max_depth().
Referenced by __gnu_cxx::integration_workspace< _Tp, _RetTp >::subinterval_too_small().
    {
      auto __w = __out.width();
      __out << std::setw(0);
      __out << ' ' << std::setw(2) << __ws.max_depth() << '\n';
      __out << ' ' << std::setw(2) << __ws.curr_index() << '\n';
      for (const auto& __seg : __ws.intervals())
        __out << ' ' << std::setw(2) << __seg.__depth
              << ' ' << std::setw(__w) << __seg.__lower_lim
              << ' ' << std::setw(__w) << __seg.__upper_lim
              << ' ' << std::setw(__w) << __seg.__result
              << ' ' << std::setw(__w) << __seg.__abs_error
              << '\n';
      return __out;
    }
qag_integrate()
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto __gnu_cxx::qag_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad = gauss_kronrod_integral<_Tp>(Kronrod_21)) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
Integrates a function from finite a to finite b using an adaptive quadrature rule. The integration domain is recursively subdivided prioritized by the segment with the greatest absolute error estimate. Subdivision continues until a prescribed error target is reached or until a maximum number of divisions is performed.
Once either the absolute or relative error limit is reached, qag_integrate() returns
Template Parameters
_FuncTp A function type that takes a single real scalar argument and returns a real scalar.
_Tp A real type for the limits of integration and the step.
_Integrator A non-adaptive integrator that is able to return an error estimate in addition to the result.
Parameters
in __workspace The workspace that manages adaptive quadrature
in __func The single-variable function to be integrated
in __lower The lower limit of integration
in __upper The upper limit of integration
in __max_abs_err The limit on absolute error
in __max_rel_err The limit on relative error
in __quad The quadrature stepper taking a function object and two integration limits
Returns
A tuple with the first value being the integration result, and the second value being the estimated error.
Definition at line 71 of file qag_integrate.tcc.
References __abserr, __result, __throw_integration_error(), _Tp, MAX_ITER_ERROR, NO_ERROR, ROUNDOFF_ERROR, SINGULAR_ERROR, UNKNOWN_ERROR, and valid_tolerances().
    {
      const auto __max_iter = __workspace.capacity();
      // Try to adjust tests for varing precision.
      const auto _S_rel_err = std::pow(_Tp{10},
                                 -std::numeric_limits<_Tp>::digits / _Tp{10});
      if (!valid_tolerances(__max_abs_err, __max_rel_err))
        {
          std::ostringstream __msg;
          __msg << "qag_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << __max_abs_err << ") and relative ("
                << __max_rel_err << ") error limits.";
          std::__throw_runtime_error(__msg.str().c_str());
        }
      auto [__result0, __abserr0, __resabs0, __resasc0]
        = __quad(__func, __lower, __upper);
      auto __tolerance = std::max(__max_abs_err,
                                  __max_rel_err * std::abs(__result0));
      // Compute roundoff tolerance.
      const auto __round_off = _Tp{10} * __tolerance * __resabs0;
      if (__abserr0 <= __round_off && __abserr0 > __tolerance)
        __throw_integration_error("qag_integrate: "
                                  "Cannot reach tolerance because "
                                  "of roundoff error on first attempt",
                                  ROUNDOFF_ERROR, __result0, __abserr0);
      else if ((__abserr0 <= __tolerance && __abserr0 != __resasc0)
                || __abserr0 == _Tp{0})
        return {__result0, __abserr0};
      else if (__max_iter == 1)
        __throw_integration_error("qag_integrate: "
                                  "A maximum of one iteration was insufficient",
                                  MAX_ITER_ERROR, __result0, __abserr0);
      __workspace.clear();
      __workspace.append(__lower, __upper, __result0, __abserr0);
      auto __area = __result0;
      auto __errsum = __abserr0;
      int __error_type = NO_ERROR;
      std::size_t __iteration = 1;
      int __roundoff_type1 = 0, __roundoff_type2 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate
          const auto& __curr = __workspace.retrieve();
          const auto __a1 = __curr.__lower_lim;
          const auto __mid = (__curr.__lower_lim + __curr.__upper_lim) / _Tp{2};
          const auto __a2 = __mid;
          const auto __b2 = __curr.__upper_lim;
          auto [__area1, __error1, __resabs1, __resasc1]
            = __quad(__func, __a1, __mid);
          auto [__area2, __error2, __resabs2, __resasc2]
            = __quad(__func, __a2, __b2);
          const auto __area12 = __area1 + __area2;
          const auto __error12 = __error1 + __error2;
          const auto __delta = __area12 - __curr.__result;
          __area += __delta;
          __errsum += __error12 - __curr.__abs_error;
          __tolerance = std::max(__max_abs_err,
                                 __max_rel_err * std::abs(__area));
          if (__resasc1 != __error1 && __resasc2 != __error2)
            {
              if (std::abs(__delta) <= _S_rel_err * std::abs(__area12)
                  && __error12 >= _Tp{0.99} * __curr.__abs_error)
                ++__roundoff_type1;
              if (__iteration >= 10 && __error12 > __curr.__abs_error)
                ++__roundoff_type2;
            }
          if (__errsum > __tolerance)
            {
              if (__roundoff_type1 >= 6 || __roundoff_type2 >= 20)
                __error_type = ROUNDOFF_ERROR;
              // Set error flag in the case of bad integrand behaviour at
              // a point of the integration range.
              if (__workspace.subinterval_too_small(__a1, __a2, __b2))
                __error_type = SINGULAR_ERROR;
            }
          __workspace.split(__mid, __area1, __error1, __area2, __error2);
          ++__iteration;
        }
      while (__iteration < __max_iter
             && !__error_type
             && __errsum > __tolerance);
      auto __result = __workspace.total_integral();
      auto __abserr = __errsum;
      if (__errsum <= __tolerance)
        return {__result, __abserr};
      if (__error_type == NO_ERROR && __iteration >= __max_iter)
        __error_type = MAX_ITER_ERROR;
      __check_error<_Tp>(__func__, __error_type, __result, __abserr);
      __throw_integration_error("qag_integrate: Unknown error.",
                                UNKNOWN_ERROR, __result, __abserr);
    }
qagi_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qagi_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, _FuncTp __func, _Tp __max_abs_err, _Tp __max_rel_err) -> adaptive_integral_t<_Tp, decltype(map_minf_pinf<_Tp, _FuncTp>(__func)(_Tp
Integrate a potentially singular function defined over (-, +).
Definition at line 354 of file qags_integrate.tcc.
References __func(), _Tp, and qags_integrate< _Tp, _FuncTp2 >().
                                                                                {}))>
qagil_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qagil_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, _FuncTp __func, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err) -> adaptive_integral_t<_Tp, decltype(map_minf_b<_Tp, _FuncTp>(__func, __upper)(_Tp
Integrate a potentially singular function defined over (-, b].
Definition at line 389 of file qags_integrate.tcc.
References __func(), _Tp, and qags_integrate< _Tp, _FuncTp2 >().
                                                                                      {}))>
qagis_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qagis_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, _FuncTp __func, _Tp __max_abs_err, _Tp __max_rel_err) -> adaptive_integral_t<_Tp, decltype(map_minf_pinf_symm<_Tp, _FuncTp>(__func)(_Tp
Integrate a potentially singular symmetric function defined over (-, +).
Definition at line 372 of file qags_integrate.tcc.
References __func(), _Tp, and qags_integrate< _Tp, _FuncTp2 >().
                                                                                     {}))>
qagiu_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qagiu_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, _FuncTp __func, _Tp __lower, _Tp __max_abs_err, _Tp __max_rel_err) -> adaptive_integral_t<_Tp, decltype(map_a_pinf<_Tp, _FuncTp>(__func, __lower)(_Tp
Integrate a potentially singular function defined over [a, +).
Definition at line 406 of file qags_integrate.tcc.
References __func(), _Tp, and qags_integrate< _Tp, _FuncTp2 >().
Referenced by qawf_integrate().
                                                                                      {}))>
qagp_integrate()
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto __gnu_cxx::qagp_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, _FuncTp __func, std::vector< _Tp > __pts, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad = gauss_kronrod_integral<_Tp>(Kronrod_21)) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
Adaptively integrate a function with known singular/discontinuous points.
Template Parameters
_FuncTp A function type that takes a single real scalar argument and returns a real scalar.
_Tp A real type for the limits of integration and the step.
_Integrator A non-adaptive integrator that is able to return an error estimate in addition to the result.
Parameters
in __workspace The workspace that manages adaptive quadrature
in __func The single-variable function to be integrated
in __pts The sorted array of points including the integration limits and intermediate discontinuities/singularities
in __max_abs_err The limit on absolute error
in __max_rel_err The limit on relative error
in __quad The quadrature stepper taking a function object and two integration limits
Definition at line 60 of file qagp_integrate.tcc.
References __abserr, __check_error(), __result, __test_positivity(), __throw_integration_error(), _Tp, __gnu_cxx::extrapolation_table< _Tp >::append(), DIVERGENCE_ERROR, EXTRAP_ROUNDOFF_ERROR, __gnu_cxx::extrapolation_table< _Tp >::get_nn(), MAX_ITER_ERROR, NO_ERROR, __gnu_cxx::extrapolation_table< _Tp >::qelg(), ROUNDOFF_ERROR, SINGULAR_ERROR, UNKNOWN_ERROR, and valid_tolerances().
    {
      const auto _S_max = std::numeric_limits<_Tp>::max();
      const auto __max_iter = __workspace.capacity();
      const auto __n_ivals = __pts.size() - 1;
      // Try to adjust tests for varing precision.
      const auto _S_rel_err = std::pow(_Tp{10},
                                 -std::numeric_limits<_Tp>::digits / _Tp{10});
      bool __extrapolate = false;
      bool __allow_extrapolation = true;
      if (!valid_tolerances(__max_abs_err, __max_rel_err))
        {
          std::ostringstream __msg;
          __msg << "qagp_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << __max_abs_err << ") and relative ("
                << __max_rel_err << ") error limits.";
          std::__throw_runtime_error(__msg.str().c_str());
        }
      if (__pts.size() > __workspace.capacity())
        std::__throw_runtime_error("qagp_integrate: "
                                 "number of points exceeds size of workspace");
      // Check that the integration range and break points
      // are in ascending order.
      if (!std::is_sorted(std::begin(__pts), std::end(__pts)))
        std::__throw_runtime_error("qagp_integrate: "
                                   "points are not in an ascending sequence");
      __workspace.clear();
      // Perform the first integration.
      auto __result0 = _Tp{0};
      auto __abserr0 = _Tp{0};
      auto __resabs0 = _Tp{0};
      for (std::size_t __i = 0; __i < __n_ivals; ++__i)
        {
          const auto __lower = __pts[__i];
          const auto __upper = __pts[__i + 1];
          auto [__area0, __error0, __resabs0, __resasc0]
            = __quad(__func, __lower, __upper);
          __result0 += __area0;
          __abserr0 += __error0;
          __resabs0 += __resabs0;
          std::size_t __level = (__error0 == __resasc0 && __error0 != _Tp{0})
                                ? 1 : 0;
          __workspace.append(__lower, __upper, __area0, __error0, __level);
        }
      // Compute the initial error estimate.
      auto __errsum = _Tp{0};
      for (std::size_t __i = 0; __i < __n_ivals; ++__i)
        {
          if (__workspace.depth(__i) == 1)
            {
              __workspace.set_abs_error(__i, __abserr0);
              __workspace.set_depth(__i, 0);
            }
          __errsum += __workspace.abs_error(__i);
        }
      // We must re-sort because the errors were reassigned.
      __workspace.sort_error();
      auto __tolerance = std::max(__max_abs_err,
                                  __max_rel_err * std::abs(__result0));
      // Compute roundoff tolerance.
      const auto __round_off = _Tp{10} * __tolerance * __resabs0;
      if (__abserr0 <= __round_off && __abserr0 > __tolerance)
        __throw_integration_error("qagp_integrate: "
                                  "Cannot reach tolerance because "
                                  "of roundoff error on first attempt",
                                  ROUNDOFF_ERROR, __result0, __abserr0);
      else if (__abserr0 <= __tolerance)
        return {__result0, __abserr0};
      else if (__max_iter == 1)
        __throw_integration_error("qagp_integrate: "
                                  "A maximum of one iteration was insufficient",
                                  MAX_ITER_ERROR, __result0, __abserr0);
      extrapolation_table<_Tp> __table;
      __table.append(__result0);
      auto __res_ext = __result0;
      auto __err_ext = _S_max;
      auto __area = __result0;
      auto __iteration = __n_ivals - 1;
      auto __ktmin = 0u;
      auto __ertest = __tolerance;
      auto __error_over_large_intervals = __errsum;
      auto __reseps = _Tp{0}, __abseps = _Tp{0}, __correc = _Tp{0};
      int __error_type = NO_ERROR, __error_type2 = NO_ERROR;
      int __roundoff_type1 = 0, __roundoff_type2 = 0, __roundoff_type3 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& __curr = __workspace.retrieve();
          const auto __current_depth = __workspace.curr_depth() + 1;
          const auto __a1 = __curr.__lower_lim;
          const auto __mid = (__curr.__lower_lim + __curr.__upper_lim) / _Tp{2};
          const auto __a2 = __mid;
          const auto __b2 = __curr.__upper_lim;
          ++__iteration;
          auto [__area1, __error1, __resabs1, __resasc1]
            = __quad(__func, __a1, __mid);
          auto [__area2, __error2, __resabs2, __resasc2]
            = __quad(__func, __a2, __b2);
          const auto __area12 = __area1 + __area2;
          const auto __error12 = __error1 + __error2;
          const auto __last_e_i = __curr.__abs_error;
          const auto __delta = __area12 - __curr.__result;
          // Improve previous approximations to the integral and test for
          // accuracy.
          __area += __delta;
          __errsum += __error12 - __curr.__abs_error;
          __tolerance = std::max(__max_abs_err,
                                 __max_rel_err * std::abs(__area));
          if (__resasc1 != __error1 && __resasc2 != __error2)
            {
              if (std::abs(__delta) <= _S_rel_err * std::abs(__area12)
                  && __error12 >= _Tp{0.99} * __curr.__abs_error)
                {
                  if (!__extrapolate)
                    ++__roundoff_type1;
                  else
                    ++__roundoff_type2;
                }
              if (__iteration > 10 && __error12 > __curr.__abs_error)
                ++__roundoff_type3;
            }
          // Test for roundoff and eventually set error flag.
          if (__roundoff_type1 + __roundoff_type2 >= 10
           || __roundoff_type3 >= 20)
            __error_type = ROUNDOFF_ERROR;
          if (__roundoff_type2 >= 5)
            __error_type2 = MAX_ITER_ERROR;
          // Set error flag in the case of bad integrand behaviour at
          // a point of the integration range.
          if (__workspace.subinterval_too_small(__a1, __a2, __b2))
            __error_type = EXTRAP_ROUNDOFF_ERROR;
          // Split the current interval in two.
          __workspace.split(__mid, __area1, __error1, __area2, __error2);
          if (__errsum <= __tolerance)
            {
              const auto __result = __workspace.total_integral();
              __check_error(__func__, __error_type, __result, __errsum);
              return {__result, __errsum};
            }
          if (__error_type != NO_ERROR)
            break;
          if (__iteration >= __max_iter - 1)
            {
              __error_type = MAX_ITER_ERROR;
              break;
            }
          if (!__allow_extrapolation)
            continue;
          __error_over_large_intervals -= __last_e_i;
          if (__current_depth < __workspace.max_depth())
            __error_over_large_intervals += __error12;
          if (!__extrapolate)
            {
              // Test whether the interval to be bisected next is the
              // smallest interval.
              if (__workspace.large_interval())
                continue;
              else
                {
                  __extrapolate = true;
                  __workspace.increment_curr_index();
                }
            }
          // The smallest interval has the largest error. Before
          // bisecting decrease the sum of the errors over the larger
          // intervals (error_over_large_intervals) and perform
          // extrapolation.
          if (__error_type2 == NO_ERROR
           && __error_over_large_intervals > __ertest)
            if (__workspace.increment_curr_index())
              continue;
          // Perform extrapolation.
          __table.append(__area);
          if (__table.get_nn() < 3)
            {
              __workspace.reset_curr_index();
              __extrapolate = false;
              __error_over_large_intervals = __errsum;
              continue;
            }
          std::tie(__reseps, __abseps) = __table.qelg();
          ++__ktmin;
          if (__ktmin > 5 && __err_ext < 0.001 * __errsum)
            __error_type = DIVERGENCE_ERROR;
          if (__abseps < __err_ext)
            {
              __ktmin = 0;
              __err_ext = __abseps;
              __res_ext = __reseps;
              __correc = __error_over_large_intervals;
              __ertest = std::max(__max_abs_err,
                                  __max_rel_err * std::abs(__reseps));
              if (__err_ext <= __ertest)
                break;
            }
          // Prepare bisection of the smallest interval.
          if (__table.get_nn() == 1)
            __allow_extrapolation = false;
          if (__error_type == DIVERGENCE_ERROR)
            break;
          // Work on interval with largest error.
          __workspace.reset_curr_index();
          __extrapolate = false;
          __error_over_large_intervals = __errsum;
        }
      while (__iteration < __max_iter);
      auto __result = __res_ext;
      auto __abserr = __err_ext;
      if (__err_ext == _S_max)
        {
          const auto __result = __workspace.total_integral();
          __check_error(__func__, __error_type, __result, __errsum);
          return {__result, __errsum};
        }
      if (__error_type != NO_ERROR || __error_type2 != NO_ERROR)
        {
          if (__error_type2 != NO_ERROR)
            __err_ext += __correc;
          if (__error_type == NO_ERROR)
            __error_type = SINGULAR_ERROR;
          if (__result != _Tp{0} && __area != _Tp{0})
            {
              if (__err_ext / std::abs(__res_ext) > __errsum / std::abs(__area))
                {
                  const auto __result = __workspace.total_integral();
                  __check_error(__func__, __error_type, __result, __errsum);
                  return {__result, __errsum};
                }
            }
          else if (__err_ext > __errsum)
            {
              const auto __result = __workspace.total_integral();
              __check_error(__func__, __error_type, __result, __errsum);
              return {__result, __errsum};
            }
          else if (__area == _Tp{0})
            {
              __check_error<_Tp>(__func__, __error_type, __result,
      __abserr);
              std::__throw_runtime_error("qagp_integrate: Unknown error.");
            }
        }
      // Test on divergence.
      auto __positive_integrand = __test_positivity(__result0, __resabs0);
      auto __max_area = std::max(std::abs(__res_ext), std::abs(__area));
      if (!__positive_integrand && __max_area < _Tp{0.01} * __resabs0)
        {
          __check_error<_Tp>(__func__, __error_type, __result, __abserr);
          std::__throw_runtime_error("qagp_integrate: Unknown error.");
        }
      auto __ratio = __res_ext / __area;
      if (__ratio < _Tp{0.01} || __ratio > _Tp{100}
          || __errsum > std::abs(__area))
        __error_type = UNKNOWN_ERROR;
      if (__error_type == NO_ERROR)
        return {__result, __abserr};
      __check_error<_Tp>(__func__, __error_type, __result, __abserr);
      __throw_integration_error("qagp_integrate: Unknown error.",
                                UNKNOWN_ERROR, __result, __abserr);
    }
qags_integrate()
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto __gnu_cxx::qags_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad = gauss_kronrod_integral<_Tp>(Kronrod_15)) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
Adaptively integrate a potentially singular function from a to b using a recursive Gauss-Kronrod algorithm.
Template Parameters
_FuncTp A function type that takes a single real scalar argument and returns a real scalar.
_Tp A real type for the limits of integration and the step.
_Integrator A non-adaptive integrator that is able to return an error estimate in addition to the result.
Parameters
in __workspace The workspace that manages adaptive quadrature
in __func The single-variable function to be integrated
in __pts The sorted array of points including the integration limits and intermediate discontinuities/singularities
in __max_abs_err The limit on absolute error
in __max_rel_err The limit on relative error
in __quad The quadrature stepper taking a function object and two integration limits
Definition at line 66 of file qags_integrate.tcc.
References __abserr, __check_error(), __result, __test_positivity(), __throw_integration_error(), _Tp, __gnu_cxx::extrapolation_table< _Tp >::append(), DIVERGENCE_ERROR, EXTRAP_ROUNDOFF_ERROR, __gnu_cxx::extrapolation_table< _Tp >::get_nn(), MAX_ITER_ERROR, NO_ERROR, __gnu_cxx::extrapolation_table< _Tp >::qelg(), ROUNDOFF_ERROR, SINGULAR_ERROR, UNKNOWN_ERROR, and valid_tolerances().
    {
      const auto _S_max = std::numeric_limits<_Tp>::max();
      const auto __max_iter = __workspace.capacity();
      // Try to adjust tests for varing precision.
      const auto _S_rel_err = std::pow(_Tp{10},
                                 -std::numeric_limits<_Tp>::digits / _Tp{10});
      bool __extrapolate = false;
      bool __allow_extrapolation = true;
      if (!valid_tolerances(__max_abs_err, __max_rel_err))
        {
          std::ostringstream __msg;
          __msg << "qags_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << __max_abs_err << ") and relative ("
                << __max_rel_err << ") error limits.";
          std::__throw_runtime_error(__msg.str().c_str());
        }
      __workspace.clear();
      // Perform the first integration.
      auto [__result0, __abserr0, __resabs0, __resasc0]
        = __quad(__func, __lower, __upper);
      __workspace.append(__lower, __upper, __result0, __abserr0);
      auto __tolerance = std::max(__max_abs_err,
                                  __max_rel_err * std::abs(__result0));
      // Compute roundoff tolerance.
      const auto __round_off = _Tp{10} * __tolerance * __resabs0;
      if (__abserr0 <= __round_off && __abserr0 > __tolerance)
        __throw_integration_error("qags_integrate: "
                                  "Cannot reach tolerance because "
                                  "of roundoff error on first attempt",
                                  ROUNDOFF_ERROR, __result0, __abserr0);
      else if ((__abserr0 <= __tolerance && __abserr0 != __resasc0)
                || __abserr0 == _Tp{0})
        return {__result0, __abserr0};
      else if (__max_iter == 1)
        __throw_integration_error("qags_integrate: "
                                  "A maximum of one iteration was insufficient",
                                  MAX_ITER_ERROR, __result0, __abserr0);
      extrapolation_table<_Tp> __table;
      __table.append(__result0);
      auto __res_ext = __result0;
      auto __err_ext = _S_max;
      auto __area = __result0;
      auto __errsum = __abserr0;
      auto __iteration = 1u;
      auto __ktmin = 0u;
      auto __ertest = _Tp{0};
      auto __error_over_large_intervals = _Tp{0};
      auto __reseps = _Tp{0}, __abseps = _Tp{0}, __correc = _Tp{0};
      int __error_type = NO_ERROR, __error_type2 = NO_ERROR;
      int __roundoff_type1 = 0, __roundoff_type2 = 0, __roundoff_type3 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& __curr = __workspace.retrieve();
          const auto __current_depth = __workspace.curr_depth() + 1;
          const auto __a1 = __curr.__lower_lim;
          const auto __mid = (__curr.__lower_lim + __curr.__upper_lim) / _Tp{2};
          const auto __a2 = __mid;
          const auto __b2 = __curr.__upper_lim;
          ++__iteration;
          auto [__area1, __error1, __resabs1, __resasc1]
            = __quad(__func, __a1, __mid);
          auto [__area2, __error2, __resabs2, __resasc2]
            = __quad(__func, __a2, __b2);
          const auto __area12 = __area1 + __area2;
          const auto __error12 = __error1 + __error2;
          const auto __last_e_i = __curr.__abs_error;
          const auto __delta = __area12 - __curr.__result;
          // Improve previous approximations to the integral and test for
          // accuracy.
          __area += __delta;
          __errsum += __error12 - __curr.__abs_error;
          __tolerance = std::max(__max_abs_err,
                                 __max_rel_err * std::abs(__area));
          if (__resasc1 != __error1 && __resasc2 != __error2)
            {
              if (std::abs(__delta) <= _S_rel_err * std::abs(__area12)
                  && __error12 >= _Tp{0.99} * __curr.__abs_error)
                {
                  if (!__extrapolate)
                    ++__roundoff_type1;
                  else
                    ++__roundoff_type2;
                }
              if (__iteration > 10 && __error12 > __curr.__abs_error)
                ++__roundoff_type3;
            }
          // Test for roundoff and eventually set error flag.
          if (__roundoff_type1 + __roundoff_type2 >= 10
              || __roundoff_type3 >= 20)
            __error_type = ROUNDOFF_ERROR;
          if (__roundoff_type2 >= 5)
            __error_type2 = MAX_ITER_ERROR;
          // Set error flag in the case of bad integrand behaviour at
          // a point of the integration range.
          if (__workspace.subinterval_too_small(__a1, __a2, __b2))
            __error_type = EXTRAP_ROUNDOFF_ERROR;
          // Split the current interval in two.
          __workspace.split(__mid, __area1, __error1, __area2, __error2);
          if (__errsum <= __tolerance)
            {
              const auto __result = __workspace.total_integral();
              __check_error(__func__, __error_type, __result, __errsum);
              return {__result, __errsum};
            }
          if (__error_type != NO_ERROR)
            break;
          if (__iteration >= __max_iter - 1)
            {
              __error_type = MAX_ITER_ERROR;
              break;
            }
          if (__iteration == 2) // Set up variables on first iteration.
            {
              __error_over_large_intervals = __errsum;
              __ertest = __tolerance;
              __table.append(__area);
              continue;
            }
          if (!__allow_extrapolation)
            continue;
          __error_over_large_intervals -= __last_e_i;
          if (__current_depth < __workspace.max_depth())
            __error_over_large_intervals += __error12;
          if (!__extrapolate)
            {
              // Test whether the interval to be bisected next is the
              // smallest interval.
              if (__workspace.large_interval())
                continue;
              else
                {
                  __extrapolate = true;
                  __workspace.increment_curr_index();
                }
            }
          // The smallest interval has the largest error. Before
          // bisecting decrease the sum of the errors over the larger
          // intervals (error_over_large_intervals) and perform
          // extrapolation.
          if (__error_type2 == NO_ERROR
              && __error_over_large_intervals > __ertest)
            if (__workspace.increment_curr_index())
              continue;
          // Perform extrapolation.
          __table.append(__area);
          std::tie(__reseps, __abseps) = __table.qelg();
          ++__ktmin;
          if (__ktmin > 5 && __err_ext < 0.001 * __errsum)
            __error_type = DIVERGENCE_ERROR;
          if (__abseps < __err_ext)
            {
              __ktmin = 0;
              __err_ext = __abseps;
              __res_ext = __reseps;
              __correc = __error_over_large_intervals;
              __ertest = std::max(__max_abs_err,
                                  __max_rel_err * std::abs(__reseps));
              if (__err_ext <= __ertest)
                break;
            }
          // Prepare bisection of the smallest interval.
          if (__table.get_nn() == 1)
            __allow_extrapolation = false;
          if (__error_type == DIVERGENCE_ERROR)
            break;
          // Work on interval with largest error.
          __workspace.reset_curr_index();
          __extrapolate = false;
          __error_over_large_intervals = __errsum;
        }
      while (__iteration < __max_iter);
      auto __result = __res_ext;
      auto __abserr = __err_ext;
      if (__err_ext == _S_max)
        {
          const auto __result = __workspace.total_integral();
          __check_error(__func__, __error_type, __result, __errsum);
          return {__result, __errsum};
        }
      if (__error_type != NO_ERROR || __error_type2 != NO_ERROR)
        {
          if (__error_type2 != NO_ERROR)
            __err_ext += __correc;
          if (__error_type == NO_ERROR)
            __error_type = SINGULAR_ERROR;
          if (__res_ext != _Tp{0} && __area != _Tp{0})
            {
              if (__err_ext / std::abs(__res_ext) > __errsum / std::abs(__area))
                {
                  const auto __result = __workspace.total_integral();
                  __check_error(__func__, __error_type, __result, __errsum);
                  return {__result, __errsum};
                }
            }
          else if (__err_ext > __errsum)
            {
              const auto __result = __workspace.total_integral();
              __check_error(__func__, __error_type, __result, __errsum);
              return {__result, __errsum};
            }
          else if (__area == _Tp{0})
            {
              __check_error<_Tp>(__func__, __error_type, __result, __errsum);
              std::__throw_runtime_error("qags_integrate: Unknown error.");
            }
        }
      // Test on divergence.
      auto __positive_integrand = __test_positivity(__result0, __resabs0);
      auto __max_area = std::max(std::abs(__res_ext), std::abs(__area));
      if (!__positive_integrand && __max_area < _Tp{0.01} * __resabs0)
        {
          __check_error<_Tp>(__func__, __error_type, __area, __errsum);
          std::__throw_runtime_error("qags_integrate: Unknown error.");
        }
      auto __ratio = __res_ext / __area;
      if (__ratio < _Tp{0.01} || __ratio > _Tp{100}
          || __errsum > std::abs(__area))
        __error_type = UNKNOWN_ERROR;
      if (__error_type == NO_ERROR)
        return {__result, __abserr};
      __check_error<_Tp>(__func__, __error_type);
      __throw_integration_error("qags_integrate: Unknown error.",
                                UNKNOWN_ERROR, __result, __abserr);
    }
qags_integrate< _Tp, _FuncTp2 >() [1/4]
return __gnu_cxx::qags_integrate< _Tp, _FuncTp2 > (__workspace , map_minf_pinf< _Tp, _FuncTp > __func, _Tp{0} , _Tp{1} , __max_abs_err , __max_rel_err)
Referenced by qagi_integrate(), qagil_integrate(), qagis_integrate(), and qagiu_integrate().
qags_integrate< _Tp, _FuncTp2 >() [2/4]
return __gnu_cxx::qags_integrate< _Tp, _FuncTp2 > (__workspace , map_minf_pinf_symm< _Tp, _FuncTp > __func, _Tp{0} , _Tp{1} , __max_abs_err , __max_rel_err)
qags_integrate< _Tp, _FuncTp2 >() [3/4]
return __gnu_cxx::qags_integrate< _Tp, _FuncTp2 > (__workspace , map_minf_b< _Tp, _FuncTp > __func, __upper, _Tp{0} , _Tp{1} , __max_abs_err , __max_rel_err)
qags_integrate< _Tp, _FuncTp2 >() [4/4]
return __gnu_cxx::qags_integrate< _Tp, _FuncTp2 > (__workspace , map_a_pinf< _Tp, _FuncTp > __func, __lower, _Tp{0} , _Tp{1} , __max_abs_err , __max_rel_err)
qawc_integrate()
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto __gnu_cxx::qawc_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __center, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad = gauss_kronrod_integral<_Tp>(Kronrod_15)) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
Adaptive integration for Cauchy principal values:
 I = \int_a^b dx f(x) / (x - c) 
 The adaptive bisection algorithm of QAG is used, with modifications to ensure that subdivisions do not occur at the singular point x = c. When a subinterval contains the point x = c or is close to it then a special 25-point modified Clenshaw-Curtis rule is used to control the singularity. Further away from the singularity the algorithm uses a user-supplied integration rule (default 15-point Gauss-Kronrod).
Definition at line 61 of file qawc_integrate.tcc.
References __abserr, __err_reliable, __func(), __result, __throw_integration_error(), _RetTp, _Tp, MAX_ITER_ERROR, MAX_SUBDIV_ERROR, NO_ERROR, qc25c(), ROUNDOFF_ERROR, SINGULAR_ERROR, UNKNOWN_ERROR, and valid_tolerances().
    {
      using _RetTp = std::invoke_result_t<_FuncTp, _Tp>;
      using _AreaTp = decltype(_RetTp{} * _Tp{});
      using _AbsAreaTp = decltype(std::abs(_AreaTp{}));
      auto __result = _AreaTp{};
      auto __abserr = _AbsAreaTp{};
      const auto __limit = __workspace.capacity();
      // Try to adjust tests for varing precision.
      const auto _M_rel_err = std::pow(_Tp{10.0},
                                 -std::numeric_limits<_Tp>::digits / _Tp{10.0});
      int __sign = 1;
      if (__upper < __lower)
        {
          std::swap(__lower, __upper);
          __sign = -1;
        }
      if (!valid_tolerances(__max_abs_err, __max_rel_err))
        {
          std::ostringstream __msg;
          __msg << "qawc_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << __max_abs_err << ") and relative ("
                << __max_rel_err << ") error limits.";
          std::__throw_runtime_error(__msg.str().c_str());
        }
      if (__center == __lower || __center == __upper)
        std::__throw_runtime_error ("qawc_integrate: "
                                    "Cannot integrate with singularity "
                                    "on endpoint.");
      __workspace.clear();
      // Perform the first integration.
      auto [__result0, __abserr0, __err_reliable]
        = qc25c(__func, __lower, __upper, __center, __quad);
      __workspace.append(__lower, __upper, __result0, __abserr0);
      // Test on accuracy; Use 0.01 relative error as an extra safety
      // margin on the first iteration (ignored for subsequent iterations).
      auto __tolerance = std::max(__max_abs_err,
                                  __max_rel_err * std::abs(__result0));
      if (__abserr0 < __tolerance && __abserr0
          < _Tp{0.01} * std::abs(__result0))
        return {__sign * __result0, __abserr0};
      else if (__limit == 1)
        __throw_integration_error("qawc_integrate: "
                                  "A maximum of one iteration was insufficient",
                                 MAX_ITER_ERROR, __sign * __result0, __abserr0);
      auto __area = __result0;
      auto __errsum = __abserr0;
      auto __iteration = 1u;
      int __error_type = NO_ERROR;
      int __roundoff_type1 = 0, __roundoff_type2 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& __curr = __workspace.retrieve();
          const auto __a1 = __curr.__lower_lim;
          const auto __b2 = __curr.__upper_lim;
          auto __mid = (__curr.__lower_lim + __curr.__upper_lim) / _Tp{2};
          if (__center > __a1 && __center <= __mid)
            __mid = (__center + __b2) / _Tp{2};
          else if (__center > __mid && __center < __b2)
            __mid = (__a1 + __center) / _Tp{2};
          const auto __a2 = __mid;
          auto [__area1, __error1, __err_reliable1]
            = qc25c(__func, __a1, __mid, __center, __quad);
          auto [__area2, __error2, __err_reliable2]
            = qc25c(__func, __a2, __b2, __center, __quad);
          const auto __area12 = __area1 + __area2;
          const auto __error12 = __error1 + __error2;
          __errsum += __error12 - __curr.__abs_error;
          __area += __area12 - __curr.__result;
          if (__err_reliable1 && __err_reliable2)
            {
              const auto __delta = __curr.__result - __area12;
              if (std::abs (__delta) <= _M_rel_err * std::abs (__area12)
                   && __error12 >= 0.99 * __curr.__abs_error)
                ++__roundoff_type1;
              if (__iteration >= 10 && __error12 > __curr.__abs_error)
                ++__roundoff_type2;
            }
          __tolerance = std::max(__max_abs_err, __max_rel_err * std::abs(__area));
          if (__errsum > __tolerance)
            {
              if (__roundoff_type1 >= 6 || __roundoff_type2 >= 20)
                __error_type = ROUNDOFF_ERROR;
              // set error flag in the case of bad integrand behaviour at
              // a point of the integration range
              if (__workspace.subinterval_too_small(__a1, __a2, __b2))
                __error_type = SINGULAR_ERROR;
            }
          __workspace.split(__mid, __area1, __error1, __area2, __error2);
          ++__iteration;
        }
      while (__iteration < __limit && !__error_type && __errsum > __tolerance);
      __result = __sign * __workspace.total_integral();
      __abserr = __errsum;
      if (__iteration == __limit)
        __error_type = MAX_SUBDIV_ERROR;
      if (__errsum <= __tolerance)
        return {__result, __abserr};
      if (__error_type == NO_ERROR)
        return {__result, __abserr};
      __check_error<_Tp>(__func__, __error_type, __result, __abserr);
      __throw_integration_error("qawc_integrate: Unknown error.",
                                UNKNOWN_ERROR, __result, __abserr);
    }
qawf_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qawf_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __cycle_workspace, oscillatory_integration_table< _Tp > & __wf, _FuncTp __func, _Tp __lower, _Tp __max_abs_err) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
This function attempts to compute a Fourier integral of the function f over the semi-infinite interval [a,+)
Definition at line 44 of file qawf_integrate.tcc.
References __abserr, __check_error(), __func(), __result, __throw_integration_error(), _Tp, __gnu_cxx::extrapolation_table< _Tp >::append(), compute_result(), EXTRAP_ROUNDOFF_ERROR, __gnu_cxx::extrapolation_table< _Tp >::get_nn(), MAX_ITER_ERROR, NO_ERROR, qagiu_integrate(), qawo_integrate(), __gnu_cxx::extrapolation_table< _Tp >::qelg(), and UNKNOWN_ERROR.
    {
      std::size_t __ktmin = 0;
      std::size_t __iteration = 0;
      extrapolation_table<_Tp> __table;
      _Tp __cycle;
      auto __omega = __wf.omega;
      const _Tp __p = 0.9;
      _Tp __factor = 1;
      _Tp __initial_eps, __eps;
      int __error_type = NO_ERROR;
      int __status = 0;
      auto __result = _Tp{0};
      auto __abserr = _Tp{0};
      const auto _S_max = std::numeric_limits<_Tp>::max();
      const auto __limit = __workspace.capacity();
      __workspace.clear();
      __cycle_workspace.clear();
      //__wf.clear();
      // Test on accuracy.
      if (__max_abs_err <= _Tp{0})
        std::__throw_domain_error("absolute tolerance epsabs must be positive") ;
      if (__omega == _Tp{0})
        {
          if (__wf.circfun == oscillatory_integration_table<_Tp>::INTEG_SINE)
            // The function sin(w x) f(x) is always zero for w = 0.
            return {_Tp{0}, _Tp{0}};
          else
            // The function cos(w x) f(x) is always f(x) for w = 0.
            return qagiu_integrate(__cycle_workspace, __func, __lower, __max_abs_err,
                                   _Tp{0});
        }
      if (__max_abs_err * (_Tp{1} - __p) > std::numeric_limits<_Tp>::min())
        __eps = __max_abs_err * (_Tp{1} - __p);
      else
        __eps = __max_abs_err;
      __initial_eps = __eps;
      auto __area = _Tp{0};
      auto __errsum = _Tp{0};
      auto __res_ext = _Tp{0};
      auto __err_ext = _S_max;
      auto __correc = _Tp{0};
      auto __total_error = _Tp{0};
      auto __truncation_error = _Tp{0};
      __cycle = (2 * std::floor(std::abs(__omega)) + 1)
              * M_PI / std::abs(__omega);
      __wf.set_length(__cycle);
      for (__iteration = 0; __iteration < __limit; ++__iteration)
        {
          const auto __a1 = __lower + __iteration * __cycle;
          const auto __b1 = __a1 + __cycle;
          const auto __max_abs_err1 = __eps * __factor;
          auto __out1 = qawo_integrate(__cycle_workspace, __wf,
      __func, __a1,
                             __max_abs_err1, _Tp{0});
          auto __area1 = __out1.__result;
          auto __error1 = __out1.__abserr;
          __workspace.append(__a1, __b1, __area1, __error1);
          __factor *= __p;
          __area += __area1;
          __errsum += __error1;
          // Estimate the truncation error as 50 times the final term.
          __truncation_error = 50 * std::abs(__area1);
          __total_error = __errsum + __truncation_error;
          if (__total_error < __max_abs_err && __iteration > 4)
            goto compute_result;
          if (__error1 > __correc)
            __correc = __error1;
          if (__status)
            __eps = std::max(__initial_eps, __correc * (_Tp{1} - __p));
          if (__status && __total_error < 10 * __correc && __iteration > 3)
            goto compute_result;
          __table.append(__area);
          if (__table.get_nn() < 2)
            continue;
          _Tp __reseps, __erreps;
          std::tie(__reseps, __erreps) = __table.qelg();
          ++__ktmin;
          if (__ktmin >= 15 && __err_ext < _Tp{0.001L} * __total_error)
            __error_type = EXTRAP_ROUNDOFF_ERROR;
          if (__erreps < __err_ext)
            {
              __ktmin = 0;
              __err_ext = __erreps;
              __res_ext = __reseps;
              if (__err_ext + 10 * __correc <= __max_abs_err)
                break;
              if (__err_ext <= __max_abs_err && 10 * __correc >= __max_abs_err)
                break;
            }
        }
      if (__iteration == __limit)
        __error_type = MAX_ITER_ERROR;
      if (__err_ext == _S_max)
        goto compute_result;
      __err_ext += 10 * __correc;
      __result = __res_ext;
      __abserr = __err_ext;
      if (__error_type == NO_ERROR)
        return {__result, __abserr};
      if (__res_ext != _Tp{0} && __area != _Tp{0})
        {
          if (__err_ext / std::abs(__res_ext) > __errsum / std::abs(__area))
            goto compute_result;
        }
      else if (__err_ext > __errsum)
        goto compute_result;
      else if (__area == _Tp{0})
        goto return_error;
      if (__error_type == EXTRAP_ROUNDOFF_ERROR)
        __err_ext += __truncation_error;
      goto return_error;
    compute_result:
      __result = __area;
      __abserr = __total_error;
      if (__error_type == NO_ERROR)
        return {__result, __abserr};
    return_error:
      __check_error(__func__, __error_type, __result, __abserr);
      __throw_integration_error("qawf_integrate: Unknown error.",
      UNKNOWN_ERROR,
                                __result, __abserr);
    }
qawo_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qawo_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, oscillatory_integration_table< _Tp > & __wf, _FuncTp __func, const _Tp __lower, const _Tp __max_abs_err, const _Tp __max_rel_err) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
Definition at line 46 of file qawo_integrate.tcc.
References __abserr, __result, __test_positivity(), __throw_integration_error(), _Tp, __gnu_cxx::extrapolation_table< _Tp >::append(), DIVERGENCE_ERROR, EXTRAP_ROUNDOFF_ERROR, __gnu_cxx::extrapolation_table< _Tp >::get_nn(), MAX_ITER_ERROR, NO_ERROR, qc25f(), __gnu_cxx::extrapolation_table< _Tp >::qelg(), ROUNDOFF_ERROR, SINGULAR_ERROR, UNKNOWN_ERROR, and valid_tolerances().
Referenced by qawf_integrate().
    {
      const auto _S_max = std::numeric_limits<_Tp>::max();
      const auto _S_eps = std::numeric_limits<_Tp>::epsilon();
      const auto __limit = __workspace.capacity();
      // Try to adjust tests for varing precision. 10^{-5.3} for double.
      const auto _S_rel_err = std::pow(_Tp{10},
                                 -std::numeric_limits<_Tp>::digits / _Tp{10});
      bool __extrapolate = false;
      bool __extall = false;
      bool __allow_extrapolation = true;
      __workspace.clear();
      //__wf.clear();
      extrapolation_table<_Tp> __table;
      const auto __upper = __lower + __wf.get_length();
      const auto __abs_omega = std::abs(__wf.omega);
      auto __result = _Tp{0};
      auto __abserr = _Tp{0};
      if (!valid_tolerances(__max_abs_err, __max_rel_err))
        {
          std::ostringstream __msg;
          __msg << "qawo_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << __max_abs_err << ") and relative ("
                << __max_rel_err << ") error limits.";
          std::__throw_runtime_error(__msg.str().c_str());
        }
      // Perform the first integration.
      auto [__result0, __abserr0, __resabs0, __resasc0]
        = qc25f(__wf, __func, __lower, __upper, 0);
      __workspace.append(__lower, __upper, __result0, __abserr0);
      auto __tolerance = std::max(__max_abs_err,
                                  __max_rel_err * std::abs(__result0));
      if (__abserr0 <= _Tp{100} * _S_eps * __resabs0
          && __abserr0 > __tolerance)
        __throw_integration_error("qawo_integrate: "
                                  "Cannot reach tolerance because "
                                  "of roundoff error on first attempt",
                                  ROUNDOFF_ERROR, __result0, __abserr0);
      else if ((__abserr0 <= __tolerance && __abserr0 != __resasc0)
                || __abserr0 == _Tp{0})
        return {__result0, __abserr0};
      else if (__limit == 1)
        __throw_integration_error("qawo_integrate: "
                                  "A maximum of one iteration was insufficient",
                                  MAX_ITER_ERROR, __result0, __abserr0);
      if (0.5 * __abs_omega * std::abs(__upper - __lower) <= _Tp{2})
        {
          __table.append(__result0);
          __extall = true;
        }
      auto __res_ext = __result0;
      auto __err_ext = _S_max;
      auto __area = __result0;
      auto __errsum = __abserr0;
      auto __iteration = 1u;
      auto __ktmin = 0u;
      auto __ertest = _Tp{0};
      auto __error_over_large_intervals = _Tp{0};
      auto __correc = _Tp{0};
      int __roundoff_type1 = 0, __roundoff_type2 = 0, __roundoff_type3 = 0;
      int __error_type = NO_ERROR, __error_type2 = NO_ERROR;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& __curr = __workspace.retrieve();
          const auto __current_depth = __workspace.curr_depth() + 1;
          if (__current_depth >= __wf.n)
            {
              __error_type = -1; // exceeded limit of table.
              break;
            }
          const auto __a1 = __curr.__lower_lim;
          const auto __mid = (__curr.__lower_lim + __curr.__upper_lim) / _Tp{2};
          const auto __a2 = __mid;
          const auto __b2 = __curr.__upper_lim;
          ++__iteration;
          auto [__area1, __error1, __resabs1, __resasc1]
            = qc25f(__wf, __func, __a1, __mid, __current_depth);
          auto [__area2, __error2, __resabs2, __resasc2]
            = qc25f(__wf, __func, __a2, __b2, __current_depth);
          const auto __area12 = __area1 + __area2;
          const auto __error12 = __error1 + __error2;
          const auto __last_e_i = __curr.__abs_error;
          // Improve previous approximations to the integral and test
          // for accuracy.
          __area += __area12 - __curr.__result;
          __errsum += __error12 - __curr.__abs_error;
          __tolerance = std::max(__max_abs_err,
                                 __max_rel_err * std::abs(__area));
          if (__resasc1 != __error1 && __resasc2 != __error2)
            {
              const auto __delta = __curr.__result - __area12;
              if (std::abs(__delta) <= _S_rel_err * std::abs(__area12)
                         && __error12 >= _Tp{0.99} * __curr.__abs_error)
                {
                  if (!__extrapolate)
                    ++__roundoff_type1;
                  else
                    ++__roundoff_type2;
                }
              if (__iteration > 10 && __error12 > __curr.__abs_error)
                ++__roundoff_type3;
            }
          // Test for roundoff and eventually set error flag.
          if (__roundoff_type1 + __roundoff_type2 >= 10
           || __roundoff_type3 >= 20)
            __error_type = ROUNDOFF_ERROR;
          if (__roundoff_type2 >= 5)
            __error_type2 = MAX_ITER_ERROR;
          // Set error flag in the case of bad integrand behaviour at
          // a point of the integration range.
          if (__workspace.subinterval_too_small(__a1, __a2, __b2))
            __error_type = EXTRAP_ROUNDOFF_ERROR;
          // Split the current interval in two.
          __workspace.split(__mid, __area1, __error1, __area2, __error2);
          if (__errsum <= __tolerance)
            {
              __result = __workspace.total_integral();
              __abserr = __errsum;
              __check_error<_Tp>(__func__, __error_type, __result,
      __abserr);
              return {__result, __abserr};
            }
          if (__error_type != NO_ERROR)
            break;
          if (__iteration >= __limit - 1)
            {
              __error_type = MAX_ITER_ERROR;
              break;
            }
          // Set up variables on first iteration.
          if (__iteration == 2 && __extall)
            {
              __error_over_large_intervals = __errsum;
              __ertest = __tolerance;
              __table.append(__area);
              continue;
            }
          if (!__allow_extrapolation)
            continue;
          if (__extall)
            {
              __error_over_large_intervals -= __last_e_i;
              if (__current_depth < __workspace.max_depth())
                __error_over_large_intervals += __error12;
              if (__extrapolate)
                if (__error_type2 != NO_ERROR
                 && __error_over_large_intervals > __ertest)
                  if (__workspace.increment_curr_index())
                    continue;
            }
          if (__workspace.large_interval())
            continue;
          if (__extall)
            {
              __extrapolate = true;
              __workspace.increment_curr_index();
            }
          else
            {
              // Test whether the interval to be bisected next is the
              // smallest interval.
              auto __width = __workspace.upper_lim() - __workspace.lower_lim();
              if (0.25 * std::abs(__width) * __abs_omega > _Tp{2})
                continue;
              __extall = true;
              __error_over_large_intervals = __errsum;
              __ertest = __tolerance;
              continue;
            }
          if (__error_type2 != NO_ERROR
           && __error_over_large_intervals > __ertest)
            if (__workspace.increment_curr_index())
              continue;
          // Perform extrapolation.
          __table.append(__area);
          if (__table.get_nn() < 3)
            {
              __workspace.reset_curr_index();
              __extrapolate = false;
              __error_over_large_intervals = __errsum;
              continue;
            }
          _Tp __reseps, __abseps;
          std::tie(__reseps, __abseps) = __table.qelg();
          ++__ktmin;
          if (__ktmin > 5 && __err_ext < 0.001 * __errsum)
            __error_type = DIVERGENCE_ERROR;
          if (__abseps < __err_ext)
            {
              __ktmin = 0;
              __err_ext = __abseps;
              __res_ext = __reseps;
              __correc = __error_over_large_intervals;
              __ertest = std::max(__max_abs_err,
                                  __max_rel_err * std::abs(__reseps));
              if (__err_ext <= __ertest)
                break;
            }
          // Prepare bisection of the smallest interval.
          if (__table.get_nn() == 1)
            __allow_extrapolation = false;
          if (__error_type == DIVERGENCE_ERROR)
            break;
          // Work on interval with largest error.
          __workspace.reset_curr_index();
          __extrapolate = false;
          __error_over_large_intervals = __errsum;
        }
      while (__iteration < __limit);
      __result = __res_ext;
      __abserr = __err_ext;
      if (__err_ext == _S_max)
        {
          __result = __workspace.total_integral();
          __abserr = __errsum;
          __check_error<_Tp>(__func__, __error_type, __result, __abserr);
          return {__result, __abserr};
        }
      if (__error_type != NO_ERROR || __error_type2 != NO_ERROR)
        {
          if (__error_type2 != NO_ERROR)
            __err_ext += __correc;
          if (__error_type == NO_ERROR)
            __error_type = SINGULAR_ERROR;
          if (__result != 0 && __area != 0)
            {
              if (__err_ext / std::abs(__res_ext) > __errsum / std::abs(__area))
                {
                  __result = __workspace.total_integral();
                  __abserr = __errsum;
                  __check_error<_Tp>(__func__, __error_type,
                                     __result, __abserr);
                  return {__result, __abserr};
                }
            }
          else if (__err_ext > __errsum)
            {
              __result = __workspace.total_integral();
              __abserr = __errsum;
              __check_error<_Tp>(__func__, __error_type, __result,
      __abserr);
              return {__result, __abserr};
            }
          else if (__area == _Tp{0})
            {
              __check_error<_Tp>(__func__, __error_type, __result,
      __abserr);
              return {__result, __abserr};
            }
        }
      // Test on divergence.
      bool __positive_integrand = __test_positivity(__result0, __resabs0);
      auto __max_area = std::max(std::abs(__res_ext), std::abs(__area));
      if (!__positive_integrand && __max_area < _Tp{0.01} * __resabs0)
        {
          __check_error<_Tp>(__func__, __error_type, __result, __abserr);
          return {__result, __abserr};
        }
      auto __ratio = __res_ext / __area;
      if (__ratio < _Tp{0.01} || __ratio > _Tp{100}
          || __errsum > std::abs(__area))
        __error_type = UNKNOWN_ERROR;
      __check_error<_Tp>(__func__, __error_type, __result, __abserr);
      return {__result, __abserr};
    }
qaws_integrate()
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto __gnu_cxx::qaws_integrate (integration_workspace< _Tp, std::invoke_result_t< _FuncTp, _Tp >> & __workspace, qaws_integration_table< _Tp > & __table, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err, _Integrator __quad = gauss_kronrod_integral<_Tp>(Kronrod_15)) -> adaptive_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
The singular weight function is defined by:
 W(x) = (x-a)^\alpha (b-x)^\beta log^\mu (x-a) log^\nu (b-x) 
 where $ \alpha > -1 $, $ \beta > -1 $, and $ \mu = 0 $, 1, $ \nu = 0, 1 $.
The weight function can take four different forms depending on the values of and ,
 W(x) = (x-a)^\alpha (b-x)^\beta (\mu = 0, \nu = 0) W(x) = (x-a)^\alpha (b-x)^\beta log(x-a) (\mu = 1, \nu = 0) W(x) = (x-a)^\alpha (b-x)^\beta log(b-x) (\mu = 0, \nu = 1) W(x) = (x-a)^\alpha (b-x)^\beta log(x-a) log(b-x) (\mu = 1, \nu = 1) 
The QAWS algorithm is designed for integrands with algebraic-logarithmic singularities at the end-points of an integration region.
In order to work efficiently the algorithm requires a precomputed table of Chebyshev moments.
Definition at line 88 of file qaws_integrate.tcc.
References __abserr, __result, __throw_integration_error(), _Tp, MAX_ITER_ERROR, MAX_SUBDIV_ERROR, NO_ERROR, qc25s(), ROUNDOFF_ERROR, SINGULAR_ERROR, UNKNOWN_ERROR, and valid_tolerances().
    {
      // Try to adjust tests for varing precision.
      const auto _M_rel_err = std::pow(_Tp{10},
                                 -std::numeric_limits<_Tp>::digits / _Tp{10});
      if (__upper <= __lower)
        std::__throw_runtime_error("qaws_integrate: "
                                   "Limits must form an ascending sequence");
      if (!valid_tolerances(__max_abs_err, __max_rel_err))
        {
          std::ostringstream __msg;
          __msg << "qaws_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << __max_abs_err << ") and relative ("
                << __max_rel_err << ") error limits.";
          std::__throw_runtime_error(__msg.str().c_str());
        }
      const auto __limit = __workspace.capacity();
      __workspace.clear();
      // Perform the first integration.
      _Tp __result0, __abserr0;
      {
        const auto __a1 = __lower;
        const auto __mid = (__lower + __upper) / _Tp{2};
        const auto __b2 = __upper;
        auto [__area1, __error1, __err_reliable1]
          = qc25s(__table, __func, __lower, __upper, __a1, __mid, __quad);
        __workspace.append(__a1, __mid, __area1, __error1);
        auto [__area2, __error2, __err_reliable2]
          = qc25s(__table, __func, __lower, __upper, __mid, __b2, __quad);
        __workspace.append(__mid, __b2, __area2, __error2);
        __result0 = __area1 + __area2;
        __abserr0 = __error1 + __error2;
      }
      // Test on accuracy; Use 0.01 relative error as an extra safety
      // margin on the first iteration (ignored for subsequent iterations).
      auto __tolerance = std::max(__max_abs_err, __max_rel_err * std::abs(__result0));
      if (__abserr0 < __tolerance && __abserr0
          < _Tp{0.01} * std::abs(__result0))
        return {__result0, __abserr0};
      else if (__limit == 1)
        __throw_integration_error("qaws_integrate: "
                                  "A maximum of one iteration was insufficient",
                                  MAX_ITER_ERROR, __result0, __abserr0);
      auto __area = __result0;
      auto __errsum = __abserr0;
      auto __iteration = 2u;
      int __error_type = NO_ERROR;
      int __roundoff_type1 = 0, __roundoff_type2 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& __curr = __workspace.retrieve();
          const auto __a1 = __curr.__lower_lim;
          const auto __mid = (__curr.__lower_lim + __curr.__upper_lim) / _Tp{2};
          const auto __b2 = __curr.__upper_lim;
          auto [__area1, __error1, __err_reliable1]
            = qc25s(__table, __func, __lower, __upper, __a1, __mid, __quad);
          auto [__area2, __error2, __err_reliable2]
            = qc25s(__table, __func, __lower, __upper, __mid, __b2, __quad);
          const auto __area12 = __area1 + __area2;
          const auto __error12 = __error1 + __error2;
          __errsum += __error12 - __curr.__abs_error;
          __area += __area12 - __curr.__result;
          if (__err_reliable1 && __err_reliable2)
            {
              const auto __delta = __curr.__result - __area12;
              if (std::abs (__delta) <= _M_rel_err * std::abs(__area12)
                 && __error12 >= 0.99 * __curr.__abs_error)
                ++__roundoff_type1;
              if (__iteration >= 10 && __error12 > __curr.__abs_error)
                ++__roundoff_type2;
            }
          __tolerance = std::max(__max_abs_err, __max_rel_err * std::abs(__area));
          if (__errsum > __tolerance)
            {
              if (__roundoff_type1 >= 6 || __roundoff_type2 >= 20)
                __error_type = ROUNDOFF_ERROR;
              // set error flag in the case of bad integrand behaviour at
              // a point of the integration range
              if (__workspace.subinterval_too_small(__a1, __mid, __b2))
                __error_type = SINGULAR_ERROR;
            }
          __workspace.split(__mid, __area1, __error1, __area2, __error2);
          ++__iteration;
        }
      while (__iteration < __limit && !__error_type && __errsum > __tolerance);
      const auto __result = __workspace.total_integral();
      const auto __abserr = __errsum;
      if (__iteration == __limit)
        __error_type = MAX_SUBDIV_ERROR;
      if (__errsum <= __tolerance)
        return {__result, __abserr};
      if (__error_type == NO_ERROR)
        return {__result, __abserr};
      __check_error<_Tp>(__func__, __error_type, __result, __abserr);
      __throw_integration_error("qaws_integrate: Unknown error.",
                                UNKNOWN_ERROR, __result, __abserr);
    }
qc25c()
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
auto __gnu_cxx::qc25c (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __center, _Integrator __quad) -> std::tuple< decltype(_Tp
Adaptive integration for Cauchy principal values:
 I = \int_a^b dx f(x) / (x - c) 
 The adaptive bisection algorithm of QAG is used, with modifications to ensure that subdivisions do not occur at the singular point x = c. When a subinterval contains the point x = c or is close to it then a special 25-point modified Clenshaw-Curtis rule is used to control the singularity. Further away from the singularity the algorithm uses a user-supplied integration rule.
Definition at line 38 of file qawc_integrate.tcc.
Referenced by qawc_integrate().
                            {} * __func(_Tp{})), _Tp, bool>;
qc25f()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qc25f (oscillatory_integration_table< _Tp > & __wf, _FuncTp __func, _Tp __lower, _Tp __upper, std::size_t __depth) -> gauss_kronrod_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
Definition at line 377 of file qawo_integrate.tcc.
References __abserr, __func(), __moment, __result, _Tp, qcheb_integrate(), and qk_integrate().
Referenced by qawo_integrate().
    {
      const auto _S_max = std::numeric_limits<_Tp>::max();
      const auto __center = (__lower + __upper) / _Tp{2};
      const auto __half_length = (__upper - __lower) / _Tp{2};
      const auto __omega = __wf.omega;
      const auto __par = __omega * __half_length;
      if (std::abs(__par) < _Tp{2})
        {
          if (__wf.circfun == oscillatory_integration_table<_Tp>::INTEG_SINE)
            {
              auto __wfun = [__func, __omega](_Tp __x)
                            ->_Tp
                            { return std::sin(__omega * __x) * __func(__x); };
              return qk_integrate(__wfun, __lower, __upper, Kronrod_15);
            }
          else
            {
              auto __wfun = [__func, __omega](_Tp __x)
                            ->_Tp
                            { return std::cos(__omega * __x) * __func(__x); };
              return qk_integrate(__wfun, __lower, __upper, Kronrod_15);
            }
        }
      else
        {
          auto __chout = qcheb_integrate(__func, __lower, __upper);
          const auto& __cheb12 = __chout.__cheb12;
          const auto& __cheb24 = __chout.__cheb24;
          if (__depth >= __wf.n)
            {
              // Table overflow should not happen, check before calling.
              std::__throw_runtime_error("Table overflow in internal function");
            }
          const auto& __moment = __wf.get_moments(__depth);
          auto __res12_cos = __cheb12[12] * __moment[12];
          auto __res12_sin = _Tp{0};
          for (int __i = 0; __i < 6; ++__i)
            {
              const std::size_t __k = 10 - 2 * __i;
              __res12_cos += __cheb12[__k] * __moment[__k];
              __res12_sin += __cheb12[__k + 1] * __moment[__k + 1];
            }
          auto __res24_cos = __cheb24[24] * __moment[24];
          auto __res24_sin = _Tp{0};
          auto __result_abs = std::abs(__cheb24[24]);
          for (int __i = 0; __i < 12; ++__i)
            {
              const std::size_t __k = 22 - 2 * __i;
              __res24_cos += __cheb24[__k] * __moment[__k];
              __res24_sin += __cheb24[__k + 1] * __moment[__k + 1];
              __result_abs += std::abs(__cheb24[__k])
                            + std::abs(__cheb24[__k + 1]);
            }
          const auto __est_cos = std::abs(__res24_cos - __res12_cos);
          const auto __est_sin = std::abs(__res24_sin - __res12_sin);
          const auto __c = __half_length * std::cos(__center * __omega);
          const auto __s = __half_length * std::sin(__center * __omega);
          _Tp __result, __abserr, __resabs, __resasc;
          if (__wf.circfun == oscillatory_integration_table<_Tp>::INTEG_SINE)
            {
              __result = __c * __res24_sin + __s * __res24_cos;
              __abserr = std::abs(__c * __est_sin) + std::abs(__s * __est_cos);
            }
          else
            {
              __result = __c * __res24_cos - __s * __res24_sin;
              __abserr = std::abs(__c * __est_cos) + std::abs(__s * __est_sin);
            }
          __resabs = __result_abs * __half_length;
          __resasc = _S_max;
          return {__result, __abserr, __resabs, __resasc};
        }
    }
qc25s()
template<typename _Tp , typename _FuncTp , typename _Integrator = gauss_kronrod_integral<_Tp>>
std::tuple< _Tp, _Tp, bool > __gnu_cxx::qc25s (qaws_integration_table< _Tp > & __t, _FuncTp __func, _Tp __lower, _Tp __upper, _Tp __a1, _Tp __mid, _Integrator __quad = gauss_kronrod_integral<_Tp>(Kronrod_15))
Definition at line 224 of file qaws_integrate.tcc.
References __abserr, __err_reliable, __gnu_cxx::compute_result_t< _AreaTp >::__res12, __gnu_cxx::compute_result_t< _AreaTp >::__res24, __result, __gnu_cxx::qaws_integration_table< _Tp >::alpha, __gnu_cxx::qaws_integration_table< _Tp >::beta, compute_result(), __gnu_cxx::fn_qaws< _Tp, _FuncTp >::eval_left(), __gnu_cxx::fn_qaws< _Tp, _FuncTp >::eval_middle(), __gnu_cxx::fn_qaws< _Tp, _FuncTp >::eval_right(), __gnu_cxx::qaws_integration_table< _Tp >::mu, __gnu_cxx::qaws_integration_table< _Tp >::nu, qcheb_integrate(), __gnu_cxx::qaws_integration_table< _Tp >::rg, __gnu_cxx::qaws_integration_table< _Tp >::rh, __gnu_cxx::qaws_integration_table< _Tp >::ri, and __gnu_cxx::qaws_integration_table< _Tp >::rj.
Referenced by qaws_integrate().
    {
      fn_qaws<_Tp, _FuncTp> __fqaws(&__t, __func, __lower, __upper);
      if (__a1 == __lower && (__t.alpha != _Tp{0} || __t.mu != 0))
        {
          const auto __factor
            = std::pow(0.5 * (__b1 - __a1), __t.alpha + _Tp{1});
          auto __f = [__fqaws](_Tp __x)
                     -> _Tp { return __fqaws.eval_right(__x); };
          auto __chout = qcheb_integrate(__f, __a1, __b1);
          const auto& __cheb12 = __chout.__cheb12;
          const auto& __cheb24 = __chout.__cheb24;
          if (__t.mu == 0)
            {
              const auto __u = __factor;
              auto [__res12, __res24]
                = compute_result(__t.ri, __cheb12, __cheb24);
              const auto __result = __u * __res24;
              const auto __abserr = std::abs(__u * (__res24 - __res12));
              return std::make_tuple(__result, __abserr, false);
            }
          else
            {
              const auto __u = __factor * std::log(__b1 - __a1);
              const auto __v = __factor;
              auto [__res12a, __res24a]
                = compute_result(__t.ri, __cheb12, __cheb24);
              auto [__res12b, __res24b]
                = compute_result(__t.rg, __cheb12, __cheb24);
              const auto __result = __u * __res24a + __v * __res24b;
              const auto __abserr = std::abs(__u * (__res24a - __res12a))
                                  + std::abs(__v * (__res24b - __res12b));
              return std::make_tuple(__result, __abserr, false);
            }
        }
      else if (__b1 == __upper && (__t.beta != _Tp{0} || __t.nu != 0))
        {
          auto __factor = std::pow(0.5 * (__b1 - __a1), __t.beta + _Tp{1});
          auto __f = [__fqaws](_Tp __x)
                     -> _Tp { return __fqaws.eval_left(__x); };
          auto __chout = qcheb_integrate(__f, __a1, __b1);
          const auto& __cheb12 = __chout.__cheb12;
          const auto& __cheb24 = __chout.__cheb24;
          if (__t.nu == 0)
            {
              const auto __u = __factor;
              auto [__res12, __res24]
                = compute_result(__t.rj, __cheb12, __cheb24);
              const auto __result = __u * __res24;
              const auto __abserr = std::abs(__u * (__res24 - __res12));
              return std::make_tuple(__result, __abserr, false);
            }
          else
            {
              const auto __u = __factor * std::log(__b1 - __a1);
              const auto __v = __factor;
              auto [__res12a, __res24a]
                = compute_result(__t.rj, __cheb12, __cheb24);
              auto [__res12b, __res24b]
                = compute_result(__t.rh, __cheb12, __cheb24);
              const auto __result = __u * __res24a + __v * __res24b;
              const auto __abserr = std::abs(__u * (__res24a - __res12a))
                                  + std::abs(__v * (__res24b - __res12b));
              return std::make_tuple(__result, __abserr, false);
            }
        }
      else
        {
          auto __f = [__fqaws](_Tp __x)
                     ->_Tp
                     { return __fqaws.eval_middle(__x); };
          auto [__result, __abserr, __resabs, __resasc]
            = __quad(__f, __a1, __b1);
          bool __err_reliable;
          if (__abserr == __resasc)
            __err_reliable = false;
          else
            __err_reliable = true;
          return std::make_tuple(__result, __abserr, __err_reliable);
        }
    }
qcheb_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qcheb_integrate (_FuncTp __func, _Tp __lower, _Tp __upper) -> chebyshev_integral_t<std::invoke_result_t<_FuncTp, _Tp>>
Definition at line 38 of file qcheb_integrate.tcc.
References __gnu_cxx::chebyshev_integral_t< _RetTp >::__cheb12, __gnu_cxx::chebyshev_integral_t< _RetTp >::__cheb24, __func(), _RetTp, and _Tp.
Referenced by qc25f(), and qc25s().
    {
      using _RetTp = std::invoke_result_t<_FuncTp, _Tp>;
      chebyshev_integral_t<_RetTp> __out;
      auto& __cheb12 = __out.__cheb12;
      auto& __cheb24 = __out.__cheb24;
      _RetTp __fval[25], __v[12];
      // These are the values of cos(pi*k/24) for k=1..11 needed for the
      // Chebyshev expansion of f(x). These are the zeros of the Chebyshev
      // function of the second kind of order 23: U_23(x).
      constexpr _Tp
      __x[11]
      {
        9.914448613738104111442846968605486e-01L,
        9.659258262890682867486612158530536e-01L,
        9.238795325112867561257834975394469e-01L,
        8.660254037844386467595427060757126e-01L,
        7.933533402912351645734146973742314e-01L,
        7.071067811865475243919762573395221e-01L,
        6.087614290087206394044894932434070e-01L,
        4.999999999999999999855184455596035e-01L,
        3.826834323650897717110798781478690e-01L,
        2.588190451025207623287087436359508e-01L,
        1.305261922200515915256103766723547e-01L,
      };
      const auto __center = (__upper + __lower) / _Tp{2};
      const auto __half_length = (__upper - __lower) / _Tp{2};
      __fval[0] = __func(__upper) / _Tp{2};
      __fval[12] = __func(__center);
      __fval[24] = __func(__lower) / _Tp{2};
      for (int __i = 1; __i < 12; ++__i)
        {
          const std::size_t __j = 24 - __i;
          const auto __u = __half_length * __x[__i - 1];
          __fval[__i] = __func(__center + __u);
          __fval[__j] = __func(__center - __u);
        }
      for (int __i = 0; __i < 12; ++__i)
        {
          const std::size_t __j = 24 - __i;
          __v[__i] = __fval[__i] - __fval[__j];
          __fval[__i] = __fval[__i] + __fval[__j];
        }
      {
        const auto __alam1 = __v[0] - __v[8];
        const auto __alam2 = __x[5] * (__v[2] - __v[6] - __v[10]);
        __cheb12[3] = __alam1 + __alam2;
        __cheb12[9] = __alam1 - __alam2;
      }
      {
        const auto __alam1 = __v[1] - __v[7] - __v[9];
        const auto __alam2 = __v[3] - __v[5] - __v[11];
        {
          const auto __alam = __x[2] * __alam1 + __x[8] * __alam2;
          __cheb24[3] = __cheb12[3] + __alam;
          __cheb24[21] = __cheb12[3] - __alam;
        }
        {
          const auto __alam = __x[8] * __alam1 - __x[2] * __alam2;
          __cheb24[9] = __cheb12[9] + __alam;
          __cheb24[15] = __cheb12[9] - __alam;
        }
      }
      {
        const auto __part1 = __x[3] * __v[4];
        const auto __part2 = __x[7] * __v[8];
        const auto __part3 = __x[5] * __v[6];
        {
          const auto __alam1 = __v[0] + __part1 + __part2;
          const auto __alam2 = __x[1] * __v[2] + __part3 + __x[9] * __v[10];
          __cheb12[1] = __alam1 + __alam2;
          __cheb12[11] = __alam1 - __alam2;
        }
        {
          const _Tp __alam1 = __v[0] - __part1 + __part2;
          const _Tp __alam2 = __x[9] * __v[2] - __part3 + __x[1] * __v[10];
          __cheb12[5] = __alam1 + __alam2;
          __cheb12[7] = __alam1 - __alam2;
        }
      }
      {
        const auto __alam = (__x[0] * __v[1] + __x[2] * __v[3]
                          + __x[4] * __v[5] + __x[6] * __v[7]
                          + __x[8] * __v[9] + __x[10] * __v[11]);
        __cheb24[1] = __cheb12[1] + __alam;
        __cheb24[23] = __cheb12[1] - __alam;
      }
      {
        const auto __alam = (__x[10] * __v[1] - __x[8] * __v[3]
                          + __x[6] * __v[5] - __x[4] * __v[7]
                          + __x[2] * __v[9] - __x[0] * __v[11]);
        __cheb24[11] = __cheb12[11] + __alam;
        __cheb24[13] = __cheb12[11] - __alam;
      }
      {
        const auto __alam = (__x[4] * __v[1] - __x[8] * __v[3]
                          - __x[0] * __v[5] - __x[10] * __v[7]
                          + __x[2] * __v[9] + __x[6] * __v[11]);
        __cheb24[5] = __cheb12[5] + __alam;
        __cheb24[19] = __cheb12[5] - __alam;
      }
      {
        const auto __alam = (__x[6] * __v[1] - __x[2] * __v[3]
                          - __x[10] * __v[5] + __x[0] * __v[7]
                          - __x[8] * __v[9] - __x[4] * __v[11]);
        __cheb24[7] = __cheb12[7] + __alam;
        __cheb24[17] = __cheb12[7] - __alam;
      }
      for (int __i = 0; __i < 6; ++__i)
        {
          const std::size_t __j = 12 - __i;
          __v[__i] = __fval[__i] - __fval[__j];
          __fval[__i] = __fval[__i] + __fval[__j];
        }
      {
        const auto __alam1 = __v[0] + __x[7] * __v[4];
        const auto __alam2 = __x[3] * __v[2];
        __cheb12[2] = __alam1 + __alam2;
        __cheb12[10] = __alam1 - __alam2;
      }
      __cheb12[6] = __v[0] - __v[4];
      {
        const auto __alam = __x[1] * __v[1] + __x[5] * __v[3] + __x[9] * __v[5];
        __cheb24[2] = __cheb12[2] + __alam;
        __cheb24[22] = __cheb12[2] - __alam;
      }
      {
        const auto __alam = __x[5] * (__v[1] - __v[3] - __v[5]);
        __cheb24[6] = __cheb12[6] + __alam;
        __cheb24[18] = __cheb12[6] - __alam;
      }
      {
        const auto __alam = __x[9] * __v[1] - __x[5] * __v[3] + __x[1] * __v[5];
        __cheb24[10] = __cheb12[10] + __alam;
        __cheb24[14] = __cheb12[10] - __alam;
      }
      for (int __i = 0; __i < 3; ++__i)
        {
          const std::size_t __j = 6 - __i;
          __v[__i] = __fval[__i] - __fval[__j];
          __fval[__i] = __fval[__i] + __fval[__j];
        }
      __cheb12[4] = __v[0] + __x[7] * __v[2];
      __cheb12[8] = __fval[0] - __x[7] * __fval[2];
      {
        const auto __alam = __x[3] * __v[1];
        __cheb24[4] = __cheb12[4] + __alam;
        __cheb24[20] = __cheb12[4] - __alam;
      }
      {
        const auto __alam = __x[7] * __fval[1] - __fval[3];
        __cheb24[8] = __cheb12[8] + __alam;
        __cheb24[16] = __cheb12[8] - __alam;
      }
      __cheb12[0] = __fval[0] + __fval[2];
      {
        const auto __alam = __fval[1] + __fval[3];
        __cheb24[0] = __cheb12[0] + __alam;
        __cheb24[24] = __cheb12[0] - __alam;
      }
      __cheb12[12] = __v[0] - __v[2];
      __cheb24[12] = __cheb12[12];
      for (int __i = 1; __i < 12; ++__i)
        __cheb12[__i] *= _Tp{1} / _Tp{6};
      __cheb12[0] *= _Tp{1} / _Tp{12};
      __cheb12[12] *= _Tp{1} / _Tp{12};
      for (int __i = 1; __i < 24; ++__i)
        __cheb24[__i] *= _Tp{1} / _Tp{12};
      __cheb24[0] *= _Tp{1} / _Tp{24};
      __cheb24[24] *= _Tp{1} / _Tp{24};
      return __out;
    }
qk_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qk_integrate (_FuncTp __func, _Tp __lower, _Tp __upper, Kronrod_Rule __qkintrule) -> gauss_kronrod_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
Definition at line 496 of file gauss_kronrod_integral.tcc.
References __func(), __rescale_error(), _RetTp, _Tp, and integrate().
Referenced by qc25f().
    {
      gauss_kronrod_integral<_Tp> __gk_integ(__qkintrule);
      return __gk_integ.integrate(__func, __lower, __upper);
    }
qng_integrate()
template<typename _Tp , typename _FuncTp >
auto __gnu_cxx::qng_integrate (_FuncTp __func, _Tp __lower, _Tp __upper, _Tp __max_abs_err, _Tp __max_rel_err) -> gauss_kronrod_integral_t<_Tp, std::invoke_result_t<_FuncTp, _Tp>>
Definition at line 228 of file qng_integrate.tcc.
References __func(), __rescale_error(), __throw_integration_error(), _RetTp, _Tp, TOLERANCE_ERROR, and valid_tolerances().
    {
      using _RetTp = std::invoke_result_t<_FuncTp, _Tp>;
      using _AreaTp = decltype(_RetTp{} * _Tp{});
      _RetTp __fv1[5], __fv2[5], __fv3[5], __fv4[5];
      _RetTp __savfun[21];
      const auto __half_length = (__upper - __lower) / _Tp{2};
      const auto __abs_half_length = std::abs(__half_length);
      const auto __center = (__upper + __lower) / _Tp{2};
      const auto __f_center = __func(__center);
      if (!valid_tolerances(__max_abs_err, __max_rel_err))
        {
          std::ostringstream __msg;
          __msg << "qng_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << __max_abs_err << ") and relative ("
                << __max_rel_err << ") error limits.";
          std::__throw_runtime_error(__msg.str().c_str());
        }
      // Compute the integral using the 10- and 21-point formula.
      auto __res10 = _AreaTp{0};
      auto __res21 = _Tp(qng_w21b[5]) * __f_center;
      // Approximation to the integral of abs(f)
      auto __resabs = _Tp(qng_w21b[5]) * std::abs(__f_center);
      for (int __k = 0; __k < 5; ++__k)
        {
          const auto __abscissa = __half_length * _Tp(qng_x1[__k]);
          const auto __fval1 = __func(__center + __abscissa);
          const auto __fval2 = __func(__center - __abscissa);
          const auto __fval = __fval1 + __fval2;
          __res10 += _Tp(qng_w10[__k]) * __fval;
          __res21 += _Tp(qng_w21a[__k]) * __fval;
          __resabs += _Tp(qng_w21a[__k])
                    * (std::abs(__fval1) + std::abs(__fval2));
          __savfun[__k] = __fval;
          __fv1[__k] = __fval1;
          __fv2[__k] = __fval2;
        }
      for (int __k = 0; __k < 5; ++__k)
        {
          const auto __abscissa = __half_length * _Tp(qng_x2[__k]);
          const auto __fval1 = __func(__center + __abscissa);
          const auto __fval2 = __func(__center - __abscissa);
          const auto __fval = __fval1 + __fval2;
          __res21 += _Tp(qng_w21b[__k]) * __fval;
          __resabs += _Tp(qng_w21b[__k])
                    * (std::abs(__fval1) + std::abs(__fval2));
          __savfun[__k + 5] = __fval;
          __fv3[__k] = __fval1;
          __fv4[__k] = __fval2;
        }
      __resabs *= __abs_half_length;
      // Approximation to the integral of abs(f-I/(b-a)).
      const auto __mean = _Tp{0.5L} * __res21;
      auto __resasc = _Tp(qng_w21b[5]) * std::abs(__f_center - __mean);
      for (int __k = 0; __k < 5; ++__k)
        {
          __resasc +=
            (_Tp(qng_w21a[__k]) * (std::abs(__fv1[__k] - __mean)
                                 + std::abs(__fv2[__k] - __mean))
           + _Tp(qng_w21b[__k]) * (std::abs(__fv3[__k] - __mean)
                                 + std::abs(__fv4[__k] - __mean)));
        }
      __resasc *= __abs_half_length;
      // Test for convergence.
      auto __result_kronrod = __res21 * __half_length;
      auto __err = __rescale_error((__res21 - __res10) * __half_length,
                                   __resabs, __resasc);
      if (__err < __max_abs_err
       || __err < __max_rel_err * std::abs(__result_kronrod))
        return {__result_kronrod, __err, __resabs, __resasc};
      // Compute the integral using the 43-point formula.
      auto __res43 = _Tp(qng_w43b[11]) * __f_center;
      for (int __k = 0; __k < 10; ++__k)
        __res43 += __savfun[__k] * _Tp(qng_w43a[__k]);
      for (int __k = 0; __k < 11; ++__k)
        {
          const auto __abscissa = __half_length * _Tp(qng_x3[__k]);
          const auto __fval = __func(__center + __abscissa)
                            + __func(__center - __abscissa);
          __res43 += __fval * _Tp(qng_w43b[__k]);
          __savfun[__k + 10] = __fval;
        }
      // Test for convergence.
      __result_kronrod = __res43 * __half_length;
      __err = __rescale_error((__res43 - __res21) * __half_length,
                                 __resabs, __resasc);
      if (__err < __max_abs_err
       || __err < __max_rel_err * std::abs(__result_kronrod))
        return {__result_kronrod, __err, __resabs, __resasc};
      // Compute the integral using the 87-point formula.
      auto __res87 = _Tp(qng_w87b[22]) * __f_center;
      for (int __k = 0; __k < 21; ++__k)
        __res87 += __savfun[__k] * _Tp(qng_w87a[__k]);
      for (int __k = 0; __k < 22; ++__k)
        {
          const auto __abscissa = __half_length * _Tp(qng_x4[__k]);
          __res87 += _Tp(qng_w87b[__k]) * (__func(__center + __abscissa)
                                         + __func(__center - __abscissa));
        }
      // Test for convergence.
      __result_kronrod = __res87 * __half_length;
      __err = __rescale_error((__res87 - __res43) * __half_length,
                                __resabs, __resasc);
      if (__err < __max_abs_err
       || __err < __max_rel_err * std::abs(__result_kronrod))
        return {__result_kronrod, __err, __resabs, __resasc};
      // Failed to converge.
      __throw_integration_error("qng_integrate: "
                                "Failed to reach tolerance "
                                "with highest-order rule",
                                TOLERANCE_ERROR, __result_kronrod, __err);
    }
valid_tolerances()
template<typename _Tp >
bool __gnu_cxx::valid_tolerances (_Tp __max_abs_err, _Tp __max_rel_err) [inline]
Definition at line 145 of file integration.h.
References __func(), __gnu_cxx::error_tolerance_t< _Tp >::_S_valid_tolerances(), _Tp, integrate(), integrate_minf_pinf(), and integrate_minf_upper().
Referenced by qag_integrate(), qagp_integrate(), qags_integrate(), qawc_integrate(), qawo_integrate(), qaws_integrate(), and qng_integrate().
    {
      return error_tolerance_t<_Tp>::
             _S_valid_tolerances(__max_abs_err, __max_rel_err);
    }
Variable Documentation
__abserr
__gnu_cxx::__abserr = _AbsAreaTp{}
Definition at line 224 of file qawc_integrate.tcc.
Referenced by __check_error(), __gnu_cxx::__integration_error< _Tp >::abserr(), qag_integrate(), qagp_integrate(), qags_integrate(), qawc_integrate(), qawf_integrate(), qawo_integrate(), qaws_integrate(), qc25f(), qc25s(), __gnu_cxx::extrapolation_table< _Tp >::qelg(), and __gnu_cxx::integration_workspace< _Tp, _RetTp >::set_abs_error().
__cc
const auto __gnu_cxx::__cc
Initial value:
= (_Tp{2} * __center - __upper - __lower)
                      / (__upper - __lower)
Definition at line 226 of file qawc_integrate.tcc.
Referenced by compute_moments().
__err_reliable
__gnu_cxx::__err_reliable = false
Definition at line 221 of file qawc_integrate.tcc.
Referenced by qawc_integrate(), and qc25s().
__moment
const auto __gnu_cxx::__moment = compute_moments(__cheb24.size(), __cc)
Definition at line 248 of file qawc_integrate.tcc.
Referenced by compute_moments(), and qc25f().
__res12
auto __gnu_cxx::__res12 = _AreaTp{0}
Definition at line 250 of file qawc_integrate.tcc.
__res24
auto __gnu_cxx::__res24 = _AreaTp{0}
Definition at line 254 of file qawc_integrate.tcc.
__result
__gnu_cxx::__result = _AreaTp{}
Definition at line 223 of file qawc_integrate.tcc.
Referenced by __check_error(), __discrete_fourier_transform(), __gnu_cxx::__integration_error< _Tp >::abserr(), qag_integrate(), qagp_integrate(), qags_integrate(), qawc_integrate(), qawf_integrate(), qawo_integrate(), qaws_integrate(), qc25f(), qc25s(), and __gnu_cxx::extrapolation_table< _Tp >::qelg().
_RetTp
* __gnu_cxx::_RetTp {})>
Definition at line 53 of file qaws_integrate.tcc.
Referenced by _Vinvfx(), cquad_integrate(), __gnu_cxx::fixed_gauss_chebyshev_t_integral< _Tp >::fixed_gauss_chebyshev_t_integral(), __gnu_cxx::fixed_gauss_chebyshev_u_integral< _Tp >::fixed_gauss_chebyshev_u_integral(), __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::fixed_gauss_chebyshev_v_integral(), __gnu_cxx::fixed_gauss_chebyshev_w_integral< _Tp >::fixed_gauss_chebyshev_w_integral(), __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::fixed_gauss_exponential_integral(), __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::fixed_gauss_gegenbauer_integral(), __gnu_cxx::fixed_gauss_hermite_integral< _Tp >::fixed_gauss_hermite_integral(), __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral(), __gnu_cxx::fixed_gauss_laguerre_integral< _Tp >::fixed_gauss_laguerre_integral(), __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::fixed_gauss_legendre_integral(), integrate_exp_sinh(), qawc_integrate(), qcheb_integrate(), qk_integrate(), and qng_integrate().
_Tp
__gnu_cxx::_Tp
Definition at line 40 of file qawc_integrate.tcc.
Referenced by __check_error(), __discrete_fourier_transform(), __gnu_cxx::__detail::__golub_welsch(), __gnu_cxx::__phase_iterator< _Tp >::__phase_iterator(), __rescale_error(), __wrap_func(), _S_tridiag(), _S_tridiag_symm(), __gnu_cxx::error_tolerance_t< _Tp >::_S_valid_tolerances(), __gnu_cxx::__integration_error< _Tp >::abserr(), compute_moments(), __gnu_cxx::__phase_iterator< _Tp >::cos(), cquad_integrate(), downdate(), __gnu_cxx::__integration_error< _Tp >::error_code(), fast_fourier_transform(), fast_sine_transform(), __gnu_cxx::fixed_gauss_chebyshev_t_integral< _Tp >::fixed_gauss_chebyshev_t_integral(), __gnu_cxx::fixed_gauss_chebyshev_u_integral< _Tp >::fixed_gauss_chebyshev_u_integral(), __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::fixed_gauss_chebyshev_v_integral(), __gnu_cxx::fixed_gauss_chebyshev_w_integral< _Tp >::fixed_gauss_chebyshev_w_integral(), __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::fixed_gauss_exponential_integral(), __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::fixed_gauss_gegenbauer_integral(), __gnu_cxx::fixed_gauss_hermite_integral< _Tp >::fixed_gauss_hermite_integral(), __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral(), __gnu_cxx::fixed_gauss_laguerre_integral< _Tp >::fixed_gauss_laguerre_integral(), __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::fixed_gauss_legendre_integral(), __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table(), __gnu_cxx::oscillatory_integration_table< _Tp >::get_moments(), __gnu_cxx::gauss_legendre_table< _Tp >::get_point(), __gnu_cxx::qaws_integration_table< _Tp >::initialise(), __gnu_cxx::composite_trapezoid_integral< _Tp, _FuncTp >::integrate(), __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::integrate(), __gnu_cxx::composite_midpoint_integral< _Tp, _FuncTp >::integrate(), jac_quadrature< _Tp >::integrate(), integrate_exp_sinh(), integrate_lower_minf(), integrate_pinf_upper(), integrate_singular_lower_minf(), integrate_singular_pinf_upper(), integrate_sinh_sinh(), integrate_tanh_sinh(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::integration_workspace(), inv_fast_fourier_transform(), inv_fast_sine_transform(), jac_quadrature< _Tp >::jac_quadrature(), jacobi_deriv_array(), jacobi_value_array(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::lower_lim(), __gnu_cxx::map_a_pinf< _Tp, _FuncTp >::map_a_pinf(), __gnu_cxx::map_minf_b< _Tp, _FuncTp >::map_minf_b(), __gnu_cxx::map_minf_pinf< _Tp, _FuncTp >::map_minf_pinf(), __gnu_cxx::map_minf_pinf_symm< _Tp, _FuncTp >::map_minf_pinf_symm(), matvec(), __gnu_cxx::composite_midpoint_integral< _Tp, _FuncTp >::operator()(), __gnu_cxx::composite_simpson_integral< _Tp, _FuncTp >::operator()(), __gnu_cxx::composite_trapezoid_integral< _Tp, _FuncTp >::operator()(), __gnu_cxx::map_minf_pinf_symm< _Tp, _FuncTp >::operator()(), __gnu_cxx::map_minf_pinf< _Tp, _FuncTp >::operator()(), __gnu_cxx::midpoint_integral< _Tp, _FuncTp >::operator()(), __gnu_cxx::simpson_integral< _Tp, _FuncTp >::operator()(), __gnu_cxx::trapezoid_integral< _Tp, _FuncTp >::operator()(), __gnu_cxx::map_minf_b< _Tp, _FuncTp >::operator()(), __gnu_cxx::map_a_pinf< _Tp, _FuncTp >::operator()(), __gnu_cxx::__phase_iterator< _Tp >::operator++(), __gnu_cxx::oscillatory_integration_table< _Tp >::oscillatory_integration_table(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::pop(), __gnu_cxx::gauss_legendre_table< _Tp >::pt(), qag_integrate(), qagi_integrate(), qagil_integrate(), qagis_integrate(), qagiu_integrate(), qagp_integrate(), qags_integrate(), qawc_integrate(), qawf_integrate(), qawo_integrate(), qaws_integrate(), __gnu_cxx::qaws_integration_table< _Tp >::qaws_integration_table(), qc25f(), qcheb_integrate(), __gnu_cxx::extrapolation_table< _Tp >::qelg(), qk_integrate(), qng_integrate(), __gnu_cxx::oscillatory_integration_table< _Tp >::reset(), __gnu_cxx::__integration_error< _Tp >::result(), __gnu_cxx::qaws_integration_table< _Tp >::set(), __gnu_cxx::integration_workspace< _Tp, _RetTp >::subinterval_too_small(), __gnu_cxx::error_tolerance_t< _Tp >::test(), __gnu_cxx::error_tolerance_t< _Tp >::tolerance(), valid_tolerances(), and __gnu_cxx::gauss_legendre_table< _Tp >::wt().
bee
constexpr long double __gnu_cxx::bee[68]
Initial value:
{
   0.00000000000000e+00L, 2.28868854108532e-01L, 0.00000000000000e+00L,
  -8.15740215243451e-01L, 0.00000000000000e+00L, 5.31212715259731e-01L,
   0.00000000000000e+00L, 1.38538036812454e-02L, 0.00000000000000e+00L,
   3.74405228908818e-02L, 0.00000000000000e+00L, 2.12224115039342e-01L,
   0.00000000000000e+00L, -8.16362644507898e-01L, 0.00000000000000e+00L,
   5.35648426691481e-01L, 0.00000000000000e+00L, 1.52417902753662e-03L,
   0.00000000000000e+00L, 2.63058840550873e-03L, 0.00000000000000e+00L,
   4.15292106318904e-03L, 0.00000000000000e+00L, 6.97106011119775e-03L,
   0.00000000000000e+00L, 1.35535708431058e-02L, 0.00000000000000e+00L,
   3.52132898424856e-02L, 0.00000000000000e+00L, 2.06946714741884e-01L,
   0.00000000000000e+00L, -8.15674251283876e-01L, 0.00000000000000e+00L,
   5.38841175520580e-01L, 0.00000000000000e+00L, 1.84909689577590e-04L,
   0.00000000000000e+00L, 2.90936325007499e-04L, 0.00000000000000e+00L,
   3.84877750950089e-04L, 0.00000000000000e+00L, 4.86436656735046e-04L,
   0.00000000000000e+00L, 6.08688640346879e-04L, 0.00000000000000e+00L,
   7.66732830740331e-04L, 0.00000000000000e+00L, 9.82753336104205e-04L,
   0.00000000000000e+00L, 1.29359957505615e-03L, 0.00000000000000e+00L,
   1.76616363801885e-03L, 0.00000000000000e+00L, 2.53323433039089e-03L,
   0.00000000000000e+00L, 3.88872172121956e-03L, 0.00000000000000e+00L,
   6.58635106468291e-03L, 0.00000000000000e+00L, 1.30326736343254e-02L,
   0.00000000000000e+00L, 3.44353850696714e-02L, 0.00000000000000e+00L,
   2.05025409531915e-01L, 0.00000000000000e+00L, -8.14985893995401e-01L,
   0.00000000000000e+00L, 5.40679930965238e-01L,
}
Definition at line 56 of file cquad_const.tcc.
Referenced by downdate().
bool
__gnu_cxx::bool
Initial value:
{
      using _RetTp = std::invoke_result_t<_FuncTp, _Tp>
Definition at line 40 of file qawc_integrate.tcc.
else
__gnu_cxx::else
Initial value:
{
          auto [__cheb12, __cheb24] = qcheb_integrate(__func, __lower, __upper)
Definition at line 246 of file qawc_integrate.tcc.
gauss_hermite_integrate
template<typename _Tp , typename _Func >
decltype(std::invoke_result_t<_Func, _Tp>{} * _Tp{} __gnu_cxx::gauss_hermite_integrate) (_Func __func, unsigned int __n)
Definition at line 31 of file gauss_hermite_integrate.h.
  {
    using _RetTp = std::invoke_result_t<_Func, _Tp>;
    using _AreaTp = decltype(_RetTp{} * _Tp{});
    //using _AbsAreaTp = decltype(std::abs(_AreaTp{}));
    if(__n == 0)
      std::__throw_domain_error("gauss_hermite_integrate: "
                                "Hermite order must be greater than 0");
    else
     {
        const auto __rule = std::__detail::__hermite_zeros<_Tp>(__n);
        auto __sum = _AreaTp{};
        for (const auto& __pt : __rule)
          {
            const auto __x = __pt.__point;
            const auto __w = __pt.__weight;
            __sum += __w * __func(__x);
          }
        return __sum;
      }
  }
gauss_laguerre_integrate
template<typename _Tp , typename _Func >
decltype(std::invoke_result_t<_Func, _Tp>{} * _Tp{} __gnu_cxx::gauss_laguerre_integrate) (_Func __func, unsigned int __n, _Tp __alpha)
Definition at line 31 of file gauss_laguerre_integrate.h.
  {
    using _RetTp = std::invoke_result_t<_Func, _Tp>;
    using _AreaTp = decltype(_RetTp{} * _Tp{});
    //using _AbsAreaTp = decltype(std::abs(_AreaTp{}));
    if(__n == 0)
      std::__throw_domain_error("gauss_laguerre_integrate: "
                                "laguerre order must be greater than 0");
    else
     {
        auto __rule = std::__detail::__laguerre_zeros(__n, __alpha);
        auto __sum = _AreaTp{};
        for (const auto& __pt : __rule)
          {
            auto __x = __pt.__point;
            auto __w = __pt.__weight;
            __sum += __w * __func(__x);
          }
        return __sum;
      }
  }
gauss_legendre_precomp
const gauss_legendre_table<long double> __gnu_cxx::gauss_legendre_precomp[]
Initial value:
{
    gauss_legendre_table<long double>(2, x2, w2, true),
    gauss_legendre_table<long double>(3, x3, w3, true),
    gauss_legendre_table<long double>(4, x4, w4, true),
    gauss_legendre_table<long double>(5, x5, w5, true),
    gauss_legendre_table<long double>(6, x6, w6, true),
    gauss_legendre_table<long double>(7, x7, w7, true),
    gauss_legendre_table<long double>(8, x8, w8, true),
    gauss_legendre_table<long double>(9, x9, w9, true),
    gauss_legendre_table<long double>(10, x10, w10, true),
    gauss_legendre_table<long double>(11, x11, w11, true),
    gauss_legendre_table<long double>(12, x12, w12, true),
    gauss_legendre_table<long double>(13, x13, w13, true),
    gauss_legendre_table<long double>(14, x14, w14, true),
    gauss_legendre_table<long double>(15, x15, w15, true),
    gauss_legendre_table<long double>(16, x16, w16, true),
    gauss_legendre_table<long double>(17, x17, w17, true),
    gauss_legendre_table<long double>(18, x18, w18, true),
    gauss_legendre_table<long double>(19, x19, w19, true),
    gauss_legendre_table<long double>(20, x20, w20, true),
    gauss_legendre_table<long double>(32, x32, w32, true),
    gauss_legendre_table<long double>(64, x64, w64, true),
    gauss_legendre_table<long double>(96, x96, w96, true),
    gauss_legendre_table<long double>(100, x100, w100, true),
    gauss_legendre_table<long double>(128, x128, w128, true),
    gauss_legendre_table<long double>(256, x256, w256, true),
    gauss_legendre_table<long double>(512, x512, w512, true),
    gauss_legendre_table<long double>(1024, x1024, w1024, true),
  }
Definition at line 2797 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table(), __gnu_cxx::gauss_legendre_table< _Tp >::pt(), and __gnu_cxx::gauss_legendre_table< _Tp >::wt().
glfixed_integrate
template<typename _Tp , typename _FuncTp >
decltype(std::invoke_result_t<_FuncTp, _Tp>{} * _Tp{} __gnu_cxx::glfixed_integrate) (const gauss_legendre_table< _Tp > &__t, _FuncTp __func, _Tp __lower, _Tp __upper)
Definition at line 31 of file glfixed_integrate.tcc.
    {
      using _RetTp = std::invoke_result_t<_FuncTp, _Tp>;
      using _AreaTp = decltype(_RetTp{} * _Tp{});
      const int __n = __t.order;
      auto __m = (__n + 1) >> 1;
      auto __A = (__upper - __lower) / _Tp{2};
      auto __B = (__upper + __lower) / _Tp{2};
      if (__n & 1) // n is odd.
        {
          auto __sum = __t.wt(0) * __func(__B);
          for (int __i = 1; __i < __m; ++__i)
            {
              auto __Ax = __A * __t.pt(__i);
              __sum += __t.wt(__i) * (__func(__B + __Ax) + __func(__B - __Ax));
            }
          return __A * __sum;
        }
      else // n is even.
        {
          auto __sum = _AreaTp{0};
          for (int __i = 0; __i < __m; ++__i)
            {
              auto __Ax = __A * __t.pt(__i);
              __sum += __t.wt(__i) * (__func(__B + __Ax) + __func(__B - __Ax));
            }
          return __A * __sum;
        }
    }
Lalpha
constexpr long double __gnu_cxx::Lalpha[33]
Initial value:
{
   5.77350269189626e-01L, 5.16397779494322e-01L, 5.07092552837110e-01L,
   5.03952630678970e-01L, 5.02518907629606e-01L, 5.01745206004255e-01L,
   5.01280411827603e-01L, 5.00979432868120e-01L, 5.00773395667191e-01L,
   5.00626174321759e-01L, 5.00517330712619e-01L, 5.00434593736979e-01L,
   5.00370233297676e-01L, 5.00319182924304e-01L, 5.00278009473803e-01L,
   5.00244319584578e-01L, 5.00216403386025e-01L, 5.00193012939056e-01L,
   5.00173220168024e-01L, 5.00156323280355e-01L, 5.00141783641018e-01L,
   5.00129182278347e-01L, 5.00118189340972e-01L, 5.00108542278496e-01L,
   5.00100030010004e-01L, 5.00092481273333e-01L, 5.00085755939229e-01L,
   5.00079738458365e-01L, 5.00074332862969e-01L, 5.00069458915387e-01L,
   5.00065049112355e-01L, 5.00061046334395e-01L, 5.00057401986298e-01L,
}
Definition at line 84 of file cquad_const.tcc.
Referenced by downdate().
Lgamma
constexpr long double __gnu_cxx::Lgamma[33]
Initial value:
{
   0.0L, 0.0L, 5.16397779494322e-01L,
   5.07092552837110e-01L, 5.03952630678970e-01L,
   5.02518907629606e-01L, 5.01745206004255e-01L, 5.01280411827603e-01L,
   5.00979432868120e-01L, 5.00773395667191e-01L, 5.00626174321759e-01L,
   5.00517330712619e-01L, 5.00434593736979e-01L, 5.00370233297676e-01L,
   5.00319182924304e-01L, 5.00278009473803e-01L, 5.00244319584578e-01L,
   5.00216403386025e-01L, 5.00193012939056e-01L, 5.00173220168024e-01L,
   5.00156323280355e-01L, 5.00141783641018e-01L, 5.00129182278347e-01L,
   5.00118189340972e-01L, 5.00108542278496e-01L, 5.00100030010003e-01L,
   5.00092481273333e-01L, 5.00085755939229e-01L, 5.00079738458365e-01L,
   5.00074332862969e-01L, 5.00069458915387e-01L, 5.00065049112355e-01L,
   5.00061046334395e-01L,
}
Definition at line 100 of file cquad_const.tcc.
Referenced by downdate().
num_gauss_legendre_precomp
const std::size_t __gnu_cxx::num_gauss_legendre_precomp
Initial value:
= sizeof(gauss_legendre_precomp)
                      / sizeof(gauss_legendre_precomp[0])
Definition at line 2827 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table().
Tleft
constexpr long double __gnu_cxx::Tleft[33 *33]
Definition at line 932 of file cquad_const.tcc.
Referenced by cquad_integrate().
Tright
constexpr long double __gnu_cxx::Tright[33 *33]
Definition at line 1324 of file cquad_const.tcc.
Referenced by cquad_integrate().
V1inv
constexpr long double __gnu_cxx::V1inv[5 *5]
Initial value:
{
   0.47140452079103168293e-1L, 0.37712361663282534635L,
   0.56568542494923801952L,
   0.37712361663282534635L, 0.47140452079103168293e-1L,
  -0.81649658092772603273e-1L, -0.46188021535170061160L, 0.0L,
   0.46188021535170061160L, 0.81649658092772603273e-1L,
   0.15058465048420853962L,
   0.12046772038736683169L, -0.54210474174315074262L, 0.12046772038736683169L,
   0.15058465048420853962L, -0.21380899352993950775L, 0.30237157840738178177L,
  -0.0L,
  -0.30237157840738178177L, 0.21380899352993950775L, 0.10774960475223581324L,
  -0.21549920950447162648L, 0.21549920950447162648L, -0.21549920950447162648L,
   0.10774960475223581324L,
}
Definition at line 117 of file cquad_const.tcc.
Referenced by _Vinvfx().
V2inv
constexpr long double __gnu_cxx::V2inv[9 *9]
Definition at line 134 of file cquad_const.tcc.
Referenced by _Vinvfx().
V3inv
constexpr long double __gnu_cxx::V3inv[17 *17]
Definition at line 186 of file cquad_const.tcc.
Referenced by _Vinvfx().
V4inv
constexpr long double __gnu_cxx::V4inv[33 *33]
Definition at line 353 of file cquad_const.tcc.
Referenced by _Vinvfx().
w10
constexpr long double __gnu_cxx::w10[5]
Initial value:
{
    0.2955242247147528701738930L,
    0.2692667193099963550912269L,
    0.2190863625159820439955349L,
    0.1494513491505805931457763L,
    0.0666713443086881375935688L,
  }
Definition at line 167 of file gauss_legendre_table.h.
w100
constexpr long double __gnu_cxx::w100[50]
Definition at line 584 of file gauss_legendre_table.h.
w1024
constexpr long double __gnu_cxx::w1024[512]
Definition at line 2082 of file gauss_legendre_table.h.
w11
constexpr long double __gnu_cxx::w11[6]
Initial value:
{
    0.2729250867779006307144835L,
    0.2628045445102466621806889L,
    0.2331937645919904799185237L,
    0.1862902109277342514260976L,
    0.1255803694649046246346943L,
    0.0556685671161736664827537L,
  }
Definition at line 2678 of file gauss_legendre_table.h.
w12
constexpr long double __gnu_cxx::w12[6]
Initial value:
{
    0.2491470458134027850005624L,
    0.2334925365383548087608499L,
    0.2031674267230659217490645L,
    0.1600783285433462263346525L,
    0.1069393259953184309602547L,
    0.0471753363865118271946160L,
  }
Definition at line 188 of file gauss_legendre_table.h.
w128
constexpr long double __gnu_cxx::w128[64]
Definition at line 708 of file gauss_legendre_table.h.
w13
constexpr long double __gnu_cxx::w13[7]
Initial value:
{
    0.2325515532308739101945895L,
    0.2262831802628972384120902L,
    0.2078160475368885023125232L,
    0.1781459807619457382800467L,
    0.1388735102197872384636018L,
    0.0921214998377284479144218L,
    0.0404840047653158795200216L,
  }
Definition at line 2701 of file gauss_legendre_table.h.
w14
constexpr long double __gnu_cxx::w14[7]
Initial value:
{
    0.2152638534631577901958764L,
    0.2051984637212956039659241L,
    0.1855383974779378137417166L,
    0.1572031671581935345696019L,
    0.1215185706879031846894148L,
    0.0801580871597602098056333L,
    0.0351194603317518630318329L,
  }
Definition at line 211 of file gauss_legendre_table.h.
w15
constexpr long double __gnu_cxx::w15[8]
Initial value:
{
    0.2025782419255612728806202L,
    0.1984314853271115764561183L,
    0.1861610000155622110268006L,
    0.1662692058169939335532009L,
    0.1395706779261543144478048L,
    0.1071592204671719350118695L,
    0.0703660474881081247092674L,
    0.0307532419961172683546284L,
  }
Definition at line 2726 of file gauss_legendre_table.h.
w16
constexpr long double __gnu_cxx::w16[8]
Initial value:
{
    0.1894506104550684962853967L,
    0.1826034150449235888667637L,
    0.1691565193950025381893121L,
    0.1495959888165767320815017L,
    0.1246289712555338720524763L,
    0.0951585116824927848099251L,
    0.0622535239386478928628438L,
    0.0271524594117540948517806L,
  }
Definition at line 236 of file gauss_legendre_table.h.
w17
constexpr long double __gnu_cxx::w17[9]
Initial value:
{
    0.1794464703562065254582656L,
    0.1765627053669926463252710L,
    0.1680041021564500445099707L,
    0.1540457610768102880814316L,
    0.1351363684685254732863200L,
    0.1118838471934039710947884L,
    0.0850361483171791808835354L,
    0.0554595293739872011294402L,
    0.0241483028685479319601100L,
  }
Definition at line 2753 of file gauss_legendre_table.h.
w18
constexpr long double __gnu_cxx::w18[9]
Initial value:
{
    0.1691423829631435918406565L,
    0.1642764837458327229860538L,
    0.1546846751262652449254180L,
    0.1406429146706506512047313L,
    0.1225552067114784601845191L,
    0.1009420441062871655628140L,
    0.0764257302548890565291297L,
    0.0497145488949697964533349L,
    0.0216160135264833103133427L,
  }
Definition at line 263 of file gauss_legendre_table.h.
w19
constexpr long double __gnu_cxx::w19[10]
Initial value:
{
    0.1610544498487836959791636L,
    0.1589688433939543476499564L,
    0.1527660420658596667788554L,
    0.1426067021736066117757461L,
    0.1287539625393362276755158L,
    0.1115666455473339947160239L,
    0.0914900216224499994644621L,
    0.0690445427376412265807083L,
    0.0448142267656996003328382L,
    0.0194617882297264770363120L,
  }
Definition at line 2782 of file gauss_legendre_table.h.
w2
constexpr long double __gnu_cxx::w2[1]
Initial value:
{
    1.0000000000000000000000000L,
  }
Definition at line 103 of file gauss_legendre_table.h.
w20
constexpr long double __gnu_cxx::w20[10]
Initial value:
{
    0.1527533871307258506980843L,
    0.1491729864726037467878287L,
    0.1420961093183820513292983L,
    0.1316886384491766268984945L,
    0.1181945319615184173123774L,
    0.1019301198172404350367501L,
    0.0832767415767047487247581L,
    0.0626720483341090635695065L,
    0.0406014298003869413310400L,
    0.0176140071391521183118620L,
  }
Definition at line 292 of file gauss_legendre_table.h.
w256
constexpr long double __gnu_cxx::w256[128]
Definition at line 910 of file gauss_legendre_table.h.
w3
constexpr long double __gnu_cxx::w3[2]
Initial value:
{
    0.8888888888888888888888889L,
    0.5555555555555555555555556L,
  }
Definition at line 2606 of file gauss_legendre_table.h.
w32
constexpr long double __gnu_cxx::w32[16]
Initial value:
{
    0.0965400885147278005667648L,
    0.0956387200792748594190820L,
    0.0938443990808045656391802L,
    0.0911738786957638847128686L,
    0.0876520930044038111427715L,
    0.0833119242269467552221991L,
    0.0781938957870703064717409L,
    0.0723457941088485062253994L,
    0.0658222227763618468376501L,
    0.0586840934785355471452836L,
    0.0509980592623761761961632L,
    0.0428358980222266806568786L,
    0.0342738629130214331026877L,
    0.0253920653092620594557526L,
    0.0162743947309056706051706L,
    0.0070186100094700966004071L,
  }
Definition at line 328 of file gauss_legendre_table.h.
w4
constexpr long double __gnu_cxx::w4[2]
Initial value:
{
    0.6521451548625461426269361L,
    0.3478548451374538573730639L,
  }
Definition at line 116 of file gauss_legendre_table.h.
w5
constexpr long double __gnu_cxx::w5[3]
Initial value:
{
    0.5688888888888888888888889L,
    0.4786286704993664680412915L,
    0.2369268850561890875142640L,
  }
Definition at line 2621 of file gauss_legendre_table.h.
w512
constexpr long double __gnu_cxx::w512[256]
Definition at line 1304 of file gauss_legendre_table.h.
w6
constexpr long double __gnu_cxx::w6[3]
Initial value:
{
    0.4679139345726910473898703L,
    0.3607615730481386075698335L,
    0.1713244923791703450402961L,
  }
Definition at line 131 of file gauss_legendre_table.h.
w64
constexpr long double __gnu_cxx::w64[32]
Definition at line 386 of file gauss_legendre_table.h.
w7
constexpr long double __gnu_cxx::w7[4]
Initial value:
{
    0.4179591836734693877551020L,
    0.3818300505051189449503698L,
    0.2797053914892766679014678L,
    0.1294849661688696932706114L,
  }
Definition at line 2638 of file gauss_legendre_table.h.
w8
constexpr long double __gnu_cxx::w8[4]
Initial value:
{
    0.3626837833783619829651504L,
    0.3137066458778872873379622L,
    0.2223810344533744705443560L,
    0.1012285362903762591525314L,
  }
Definition at line 148 of file gauss_legendre_table.h.
w9
constexpr long double __gnu_cxx::w9[5]
Initial value:
{
    0.3302393550012597631645251L,
    0.3123470770400028400686304L,
    0.2606106964029354623187429L,
    0.1806481606948574040584720L,
    0.0812743883615744119718922L,
  }
Definition at line 2657 of file gauss_legendre_table.h.
w96
constexpr long double __gnu_cxx::w96[48]
Definition at line 476 of file gauss_legendre_table.h.
x10
constexpr long double __gnu_cxx::x10[5]
Initial value:
{
    0.1488743389816312108848260L,
    0.4333953941292471907992659L,
    0.6794095682990244062343274L,
    0.8650633666889845107320967L,
    0.9739065285171717200779640L,
  }
Definition at line 158 of file gauss_legendre_table.h.
x100
constexpr long double __gnu_cxx::x100[50]
Definition at line 530 of file gauss_legendre_table.h.
x1024
constexpr long double __gnu_cxx::x1024[512]
Definition at line 1566 of file gauss_legendre_table.h.
x11
constexpr long double __gnu_cxx::x11[6]
Initial value:
{
    0.0000000000000000000000000L,
    0.2695431559523449723315320L,
    0.5190961292068118159257257L,
    0.7301520055740493240934163L,
    0.8870625997680952990751578L,
    0.9782286581460569928039380L,
  }
Definition at line 2668 of file gauss_legendre_table.h.
x12
constexpr long double __gnu_cxx::x12[6]
Initial value:
{
    0.1252334085114689154724414L,
    0.3678314989981801937526915L,
    0.5873179542866174472967024L,
    0.7699026741943046870368938L,
    0.9041172563704748566784659L,
    0.9815606342467192506905491L,
  }
Definition at line 178 of file gauss_legendre_table.h.
x128
constexpr long double __gnu_cxx::x128[64]
Definition at line 640 of file gauss_legendre_table.h.
x13
constexpr long double __gnu_cxx::x13[7]
Initial value:
{
    0.0000000000000000000000000L,
    0.2304583159551347940655281L,
    0.4484927510364468528779129L,
    0.6423493394403402206439846L,
    0.8015780907333099127942065L,
    0.9175983992229779652065478L,
    0.9841830547185881494728294L,
  }
Definition at line 2690 of file gauss_legendre_table.h.
x14
constexpr long double __gnu_cxx::x14[7]
Initial value:
{
    0.1080549487073436620662447L,
    0.3191123689278897604356718L,
    0.5152486363581540919652907L,
    0.6872929048116854701480198L,
    0.8272013150697649931897947L,
    0.9284348836635735173363911L,
    0.9862838086968123388415973L,
  }
Definition at line 200 of file gauss_legendre_table.h.
x15
constexpr long double __gnu_cxx::x15[8]
Initial value:
{
    0.0000000000000000000000000L,
    0.2011940939974345223006283L,
    0.3941513470775633698972074L,
    0.5709721726085388475372267L,
    0.7244177313601700474161861L,
    0.8482065834104272162006483L,
    0.9372733924007059043077589L,
    0.9879925180204854284895657L,
  }
Definition at line 2714 of file gauss_legendre_table.h.
x16
constexpr long double __gnu_cxx::x16[8]
Initial value:
{
    0.0950125098376374401853193L,
    0.2816035507792589132304605L,
    0.4580167776572273863424194L,
    0.6178762444026437484466718L,
    0.7554044083550030338951012L,
    0.8656312023878317438804679L,
    0.9445750230732325760779884L,
    0.9894009349916499325961542L,
  }
Definition at line 224 of file gauss_legendre_table.h.
x17
constexpr long double __gnu_cxx::x17[9]
Initial value:
{
    0.0000000000000000000000000L,
    0.1784841814958478558506775L,
    0.3512317634538763152971855L,
    0.5126905370864769678862466L,
    0.6576711592166907658503022L,
    0.7815140038968014069252301L,
    0.8802391537269859021229557L,
    0.9506755217687677612227170L,
    0.9905754753144173356754340L,
  }
Definition at line 2740 of file gauss_legendre_table.h.
x18
constexpr long double __gnu_cxx::x18[9]
Initial value:
{
    0.0847750130417353012422619L,
    0.2518862256915055095889729L,
    0.4117511614628426460359318L,
    0.5597708310739475346078715L,
    0.6916870430603532078748911L,
    0.8037049589725231156824175L,
    0.8926024664975557392060606L,
    0.9558239495713977551811959L,
    0.9915651684209309467300160L,
  }
Definition at line 250 of file gauss_legendre_table.h.
x19
constexpr long double __gnu_cxx::x19[10]
Initial value:
{
    0.0000000000000000000000000L,
    0.1603586456402253758680961L,
    0.3165640999636298319901173L,
    0.4645707413759609457172671L,
    0.6005453046616810234696382L,
    0.7209661773352293786170959L,
    0.8227146565371428249789225L,
    0.9031559036148179016426609L,
    0.9602081521348300308527788L,
    0.9924068438435844031890177L,
  }
Definition at line 2768 of file gauss_legendre_table.h.
x2
constexpr long double __gnu_cxx::x2[1]
Initial value:
{
    0.5773502691896257645091488L,
  }
Definition at line 98 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table().
x20
constexpr long double __gnu_cxx::x20[10]
Initial value:
{
    0.0765265211334973337546404L,
    0.2277858511416450780804962L,
    0.3737060887154195606725482L,
    0.5108670019508270980043641L,
    0.6360536807265150254528367L,
    0.7463319064601507926143051L,
    0.8391169718222188233945291L,
    0.9122344282513259058677524L,
    0.9639719272779137912676661L,
    0.9931285991850949247861224L,
  }
Definition at line 278 of file gauss_legendre_table.h.
x256
constexpr long double __gnu_cxx::x256[128]
Definition at line 778 of file gauss_legendre_table.h.
x3
constexpr long double __gnu_cxx::x3[2]
Initial value:
{
    0.0000000000000000000000000L,
    0.7745966692414833770358531L,
  }
Definition at line 2600 of file gauss_legendre_table.h.
x32
constexpr long double __gnu_cxx::x32[16]
Initial value:
{
    0.0483076656877383162348126L,
    0.1444719615827964934851864L,
    0.2392873622521370745446032L,
    0.3318686022821276497799168L,
    0.4213512761306353453641194L,
    0.5068999089322293900237475L,
    0.5877157572407623290407455L,
    0.6630442669302152009751152L,
    0.7321821187402896803874267L,
    0.7944837959679424069630973L,
    0.8493676137325699701336930L,
    0.8963211557660521239653072L,
    0.9349060759377396891709191L,
    0.9647622555875064307738119L,
    0.9856115115452683354001750L,
    0.9972638618494815635449811L,
  }
Definition at line 308 of file gauss_legendre_table.h.
x4
constexpr long double __gnu_cxx::x4[2]
Initial value:
{
    0.3399810435848562648026658L,
    0.8611363115940525752239465L,
  }
Definition at line 110 of file gauss_legendre_table.h.
x5
constexpr long double __gnu_cxx::x5[3]
Initial value:
{
    0.0000000000000000000000000L,
    0.5384693101056830910363144L,
    0.9061798459386639927976269L,
  }
Definition at line 2614 of file gauss_legendre_table.h.
x512
constexpr long double __gnu_cxx::x512[256]
Definition at line 1044 of file gauss_legendre_table.h.
x6
constexpr long double __gnu_cxx::x6[3]
Initial value:
{
    0.2386191860831969086305017L,
    0.6612093864662645136613996L,
    0.9324695142031520278123016L,
  }
Definition at line 124 of file gauss_legendre_table.h.
x64
constexpr long double __gnu_cxx::x64[32]
Definition at line 350 of file gauss_legendre_table.h.
x7
constexpr long double __gnu_cxx::x7[4]
Initial value:
{
    0.0000000000000000000000000L,
    0.4058451513773971669066064L,
    0.7415311855993944398638648L,
    0.9491079123427585245261897L,
  }
Definition at line 2630 of file gauss_legendre_table.h.
x8
constexpr long double __gnu_cxx::x8[4]
Initial value:
{
    0.1834346424956498049394761L,
    0.5255324099163289858177390L,
    0.7966664774136267395915539L,
    0.9602898564975362316835609L,
  }
Definition at line 140 of file gauss_legendre_table.h.
x9
constexpr long double __gnu_cxx::x9[5]
Initial value:
{
    0.0000000000000000000000000L,
    0.3242534234038089290385380L,
    0.6133714327005903973087020L,
    0.8360311073266357942994298L,
    0.9681602395076260898355762L,
  }
Definition at line 2648 of file gauss_legendre_table.h.
x96
constexpr long double __gnu_cxx::x96[48]
Definition at line 424 of file gauss_legendre_table.h.
xi
constexpr long double __gnu_cxx::xi[33]
Initial value:
{
  -1.0L, -0.99518472667219688624L,
  -0.98078528040323044912L, -0.95694033573220886493L,
  -0.92387953251128675612L, -0.88192126434835502970L,
  -0.83146961230254523708L, -0.77301045336273696082L,
  -0.70710678118654752440L, -0.63439328416364549822L,
  -0.55557023301960222475L, -0.47139673682599764857L,
  -0.38268343236508977173L, -0.29028467725446236764L,
  -0.19509032201612826785L, -0.098017140329560601995L,
   0.0L, 0.098017140329560601995L,
   0.19509032201612826785L, 0.29028467725446236764L,
   0.38268343236508977173L, 0.47139673682599764857L,
   0.55557023301960222475L, 0.63439328416364549822L,
   0.70710678118654752440L, 0.77301045336273696082L,
   0.83146961230254523708L, 0.88192126434835502970L,
   0.92387953251128675612L, 0.95694033573220886493L,
   0.98078528040323044912L, 0.99518472667219688624L,
   1.0L,
}
Definition at line 34 of file cquad_const.tcc.
Referenced by cquad_integrate(), and downdate().