emsr Namespace Reference
Namespaces
 detail
Classes
struct adaptive_integral_t
struct chebyshev_integral_t
class composite_midpoint_integral
class composite_simpson_integral
class composite_trapezoid_integral
struct compute_result_t
struct cquad_interval
struct cquad_interval_comp
struct cquad_workspace
struct error_tolerance_t
class extrapolation_table
struct fixed_gauss_chebyshev_t_integral
struct fixed_gauss_chebyshev_u_integral
struct fixed_gauss_chebyshev_v_integral
struct fixed_gauss_chebyshev_w_integral
struct fixed_gauss_exponential_integral
struct fixed_gauss_gegenbauer_integral
struct fixed_gauss_hermite_integral
struct fixed_gauss_jacobi_integral
struct fixed_gauss_laguerre_integral
struct fixed_gauss_legendre_integral
struct fixed_gauss_rational_integral
struct fixed_integral_t
struct fn_qaws
class fourier_transform_t
class fourier_transform_t< std::complex< Tp > >
struct gauss_legendre_table
class integration_error
class integration_workspace
struct map_a_pinf
struct map_minf_b
struct map_minf_pinf
struct map_minf_pinf_symm
struct mapper
class midpoint_integral
struct oscillatory_integration_table
class phase_iterator
struct qaws_integration_table
class qk_integrator
struct qk_integrator< Tp, FuncTp, Kronrod_15 >
struct qk_integrator< Tp, FuncTp, Kronrod_21 >
struct qk_integrator< Tp, FuncTp, Kronrod_31 >
struct qk_integrator< Tp, FuncTp, Kronrod_41 >
struct qk_integrator< Tp, FuncTp, Kronrod_51 >
struct qk_integrator< Tp, FuncTp, Kronrod_61 >
class simpson_integral
class trapezoid_integral
Enumerations
enum {
NO_ERROR
, MAX_ITER_ERROR
, ROUNDOFF_ERROR
, SINGULAR_ERROR
,
EXTRAP_ROUNDOFF_ERROR
, DIVERGENCE_ERROR
, MAX_SUBDIV_ERROR
, TOLERANCE_ERROR
,
UNKNOWN_ERROR
 }
enum Gauss_Legendre_Rule {
GL_2 = 2
, GL_4 = 4
, GL_6 = 6
, GL_8 = 8
,
GL_10 = 10
, GL_12 = 12
, GL_14 = 14
, GL_16 = 16
,
GL_18 = 18
, GL_20 = 20
, GL_32 = 32
, GL_64 = 64
,
GL_96 = 96
, GL_100 = 100
, GL_128 = 128
, GL_256 = 256
,
GL_512 = 512
, GL_1024 = 1024
, GL_3 = 3
, GL_5 = 5
,
GL_7 = 7
, GL_9 = 9
, GL_11 = 11
, GL_13 = 13
,
GL_15 = 15
, GL_17 = 17
, GL_19 = 19
 }
Functions
template<typename AreaTp , typename AbsAreaTp >
void check_error (std::string_view func, int errcode, AreaTp result, AbsAreaTp abserr)
template<typename Tp >
std::vector< Tp > compute_moments (std::size_t N, Tp cc)
template<typename Tp , typename RetTp >
auto compute_result (const std::array< Tp, 25 > &r, const std::array< RetTp, 13 > &cheb12, const std::array< RetTp, 25 > &cheb24) -> compute_result_t< decltype(Tp{} *RetTp{})>
template<typename Tp , typename FuncTp >
auto cquad_integrate (cquad_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &ws, FuncTp func, Tp a, Tp b, Tp epsabs, Tp epsrel) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp >
void discrete_fourier_transform (bool do_forward, std::vector< std::complex< Tp >> &z)
template<typename Tp >
void downdate (Tp *coeff, std::ptrdiff_t n, std::ptrdiff_t depth, std::ptrdiff_t *NaN, std::ptrdiff_t num_NaNs)
template<typename CmplxIter >
void fast_fourier_transform (const CmplxIter &from, const CmplxIter &to)
template<typename Tp >
void fast_fourier_transform (std::vector< std::complex< Tp >> &z)
template<typename Tp >
void fast_fourier_transform (std::vector< Tp > &x)
template<typename Tp >
void fast_sine_transform (std::vector< Tp > &x)
template<typename Tp , typename FuncTp >
auto integrate (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024, Kronrod_Rule qkintrule=Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_cauchy_principal_value (FuncTp func, Tp lower, Tp upper, Tp center, Tp max_abs_err, Tp max_rel_err, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_clenshaw_curtis (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_exp_sinh (FuncTp func, Tp lower, Tp max_abs_err, Tp max_rel_err, int max_iter)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_chebyshev_t (int n, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_chebyshev_u (int n, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_chebyshev_v (int n, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_chebyshev_w (int n, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_exponential (int n, Tp alf, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_gegenbauer (int n, Tp lambda, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_hermite (int n, Tp alf, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_jacobi (int n, Tp alf, Tp bet, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_laguerre (int n, Tp alf, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_legendre (int n, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_fixed_gauss_rational (int n, Tp alf, Tp bet, FuncTp func, Tp lower, Tp upper)
template<typename Tp , typename FuncTp >
auto integrate_kronrod_singular (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_lower_minf (FuncTp func, Tp lower, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024, Kronrod_Rule qkintrule=Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_lower_pinf (FuncTp func, Tp lower, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024, Kronrod_Rule qkintrule=Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_midpoint (FuncTp func, Tp a, Tp b, Tp max_abs_err, Tp max_rel_err, int max_iter)
template<typename Tp , typename FuncTp >
auto integrate_minf_pinf (FuncTp func, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024, Kronrod_Rule qkintrule=Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_minf_upper (FuncTp func, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024, Kronrod_Rule qkintrule=Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename FuncTp , typename FwdIter , typename Tp >
auto integrate_multisingular (FuncTp func, FwdIter ptbeg, FwdIter ptend, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_oscillatory (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_patterson (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_pinf_upper (FuncTp func, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024, Kronrod_Rule qkintrule=Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_simpson (FuncTp __func, Tp __a, Tp __b, Tp __max_abs_err, Tp __max_rel_err, int __max_iter)
template<typename Tp , typename FuncTp >
auto integrate_singular (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_singular_endpoints (FuncTp func, Tp lower, Tp upper, Tp alpha, Tp beta, int mu, int nu, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_singular_lower_minf (FuncTp func, Tp lower, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_singular_lower_pinf (FuncTp func, Tp lower, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_singular_minf_pinf (FuncTp func, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_singular_minf_upper (FuncTp func, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto integrate_singular_pinf_upper (FuncTp func, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter=1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_sinh_sinh (FuncTp func, Tp max_abs_err, Tp max_rel_err, int max_iter)
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_tanh_sinh (FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err, int max_iter)
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > integrate_trapezoid (FuncTp func, Tp a, Tp b, Tp max_abs_err, Tp max_rel_err, int max_iter)
template<typename CmplxIter >
void inv_fast_fourier_transform (const CmplxIter &from, const CmplxIter &to)
template<typename Tp >
void inv_fast_fourier_transform (std::vector< std::complex< Tp >> &z)
template<typename Tp >
void inv_fast_fourier_transform (std::vector< Tp > &x)
template<typename Tp >
void inv_fast_sine_transform (std::vector< Tp > &x)
template<typename Tp , typename RetTp >
bool operator< (const cquad_interval< Tp, RetTp > &ivl, const cquad_interval< Tp, RetTp > &ivr)
template<typename Tp , typename RetTp >
std::ostream & operator<< (std::ostream &out, const integration_workspace< Tp, RetTp > &ws)
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto qag_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err, Integrator quad=gauss_kronrod_integral< Tp >(Kronrod_21)) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto qagi_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, FuncTp func, Tp max_abs_err, Tp max_rel_err) -> adaptive_integral_t< Tp, decltype(map_minf_pinf< Tp, FuncTp >(func)(Tp{}))>
template<typename Tp , typename FuncTp >
auto qagil_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, FuncTp func, Tp upper, Tp max_abs_err, Tp max_rel_err) -> adaptive_integral_t< Tp, decltype(map_minf_b< Tp, FuncTp >(func, upper)(Tp{}))>
template<typename Tp , typename FuncTp >
auto qagis_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, FuncTp func, Tp max_abs_err, Tp max_rel_err) -> adaptive_integral_t< Tp, decltype(map_minf_pinf_symm< Tp, FuncTp >(func)(Tp{}))>
template<typename Tp , typename FuncTp >
auto qagiu_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, FuncTp func, Tp lower, Tp max_abs_err, Tp max_rel_err) -> adaptive_integral_t< Tp, decltype(map_a_pinf< Tp, FuncTp >(func, lower)(Tp{}))>
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto qagp_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, FuncTp func, std::vector< Tp > pts, Tp max_abs_err, Tp max_rel_err, Integrator quad=gauss_kronrod_integral< Tp >(Kronrod_21)) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto qags_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err, Integrator quad=gauss_kronrod_integral< Tp >(Kronrod_15)) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto qawc_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, FuncTp func, Tp lower, Tp upper, Tp center, Tp max_abs_err, Tp max_rel_err, Integrator quad=gauss_kronrod_integral< Tp >(Kronrod_15)) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto qawf_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &cycle_workspace, oscillatory_integration_table< Tp > &wf, FuncTp func, Tp lower, Tp max_abs_err) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto qawo_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, oscillatory_integration_table< Tp > &wf, FuncTp func, const Tp lower, const Tp max_abs_err, const Tp max_rel_err) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto qaws_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> &workspace, qaws_integration_table< Tp > &table, FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err, Integrator quad=gauss_kronrod_integral< Tp >(Kronrod_15)) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto qc25c (FuncTp func, Tp lower, Tp upper, Tp center, Integrator quad=gauss_kronrod_integral< Tp >(Kronrod_15)) -> std::tuple< decltype(Tp{} *func(Tp{})), Tp, bool >
template<typename Tp , typename FuncTp >
auto qc25f (oscillatory_integration_table< Tp > &wf, FuncTp func, Tp lower, Tp upper, std::size_t depth) -> gauss_kronrod_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
std::tuple< Tp, Tp, bool > qc25s (qaws_integration_table< Tp > &t, FuncTp func, Tp lower, Tp upper, Tp a1, Tp mid, Integrator quad=gauss_kronrod_integral< Tp >(Kronrod_15))
template<typename Tp , typename FuncTp >
auto qcheb_integrate (FuncTp func, Tp lower, Tp upper) -> chebyshev_integral_t< std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto qk_integrate (FuncTp func, Tp lower, Tp upper, Kronrod_Rule qkintrule) -> gauss_kronrod_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename Tp , typename FuncTp >
auto qng_integrate (FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err) -> gauss_kronrod_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
template<typename AreaTp , typename AbsAreaTp >
AbsAreaTp rescale_error (AreaTp err, const AbsAreaTp result_abs, const AbsAreaTp result_asc)
template<typename RandAccIter , typename RandAccIterRHS >
int s_tridiag (size_t n, RandAccIter supd, RandAccIter diag, RandAccIter subd, RandAccIterRHS rhs)
template<typename RandAccIter , typename RandAccIterRHS >
int s_tridiag (std::size_t n, RandAccIter supd, RandAccIter diag, RandAccIter subd, RandAccIterRHS rhs)
template<typename RandAccIter , typename RandAccIterRHS >
int s_tridiag_symm (std::size_t n, RandAccIter &diag, RandAccIter &subd, RandAccIterRHS &rhs)
Diagonalize a symmetric tridiagonal matrix.
template<typename AreaTp , typename AbsAreaTp >
bool test_positivity (AreaTp result, AbsAreaTp resabs)
template<typename Tp >
bool valid_tolerances (Tp max_abs_err, Tp max_rel_err)
template<typename RetTp >
void Vinvfx (const std::array< RetTp, 33 > &fx, RetTp *coeff, const int depth)
template<typename Tp , typename FuncTp >
std::invoke_result_t< FuncTp, Tp > wrap_func (FuncTp func, Tp x)
Variables
constexpr long double bee [68]
template<typename Tp , typename Func >
decltype(std::invoke_result_t< Func, Tp >{} *Tp{} gauss_hermite_integrate)(Func func, unsigned int n)
template<typename Tp , typename Func >
decltype(std::invoke_result_t< Func, Tp >{} *Tp{} gauss_laguerre_integrate)(Func func, unsigned int n, Tp alpha)
const gauss_legendre_table< long double > gauss_legendre_precomp []
template<typename Tp , typename FuncTp >
decltype(std::invoke_result_t< FuncTp, Tp >{} *Tp{} glfixed_integrate)(const gauss_legendre_table< Tp > &t, FuncTp func, Tp lower, Tp upper)
constexpr long double Lalpha [33]
constexpr long double Lgamma [33]
const std::size_t num_gauss_legendre_precomp
constexpr long double Tleft [33 *33]
constexpr long double Tright [33 *33]
constexpr long double V1inv [5 *5]
constexpr long double V2inv [9 *9]
constexpr long double V3inv [17 *17]
constexpr long double V4inv [33 *33]
constexpr long double w10 [5]
constexpr long double w100 [50]
constexpr long double w1024 [512]
constexpr long double w11 [6]
constexpr long double w12 [6]
constexpr long double w128 [64]
constexpr long double w13 [7]
constexpr long double w14 [7]
constexpr long double w15 [8]
constexpr long double w16 [8]
constexpr long double w17 [9]
constexpr long double w18 [9]
constexpr long double w19 [10]
constexpr long double w2 [1]
constexpr long double w20 [10]
constexpr long double w256 [128]
constexpr long double w3 [2]
constexpr long double w32 [16]
constexpr long double w4 [2]
constexpr long double w5 [3]
constexpr long double w512 [256]
constexpr long double w6 [3]
constexpr long double w64 [32]
constexpr long double w7 [4]
constexpr long double w8 [4]
constexpr long double w9 [5]
constexpr long double w96 [48]
constexpr long double x10 [5]
constexpr long double x100 [50]
constexpr long double x1024 [512]
constexpr long double x11 [6]
constexpr long double x12 [6]
constexpr long double x128 [64]
constexpr long double x13 [7]
constexpr long double x14 [7]
constexpr long double x15 [8]
constexpr long double x16 [8]
constexpr long double x17 [9]
constexpr long double x18 [9]
constexpr long double x19 [10]
constexpr long double x2 [1]
constexpr long double x20 [10]
constexpr long double x256 [128]
constexpr long double x3 [2]
constexpr long double x32 [16]
constexpr long double x4 [2]
constexpr long double x5 [3]
constexpr long double x512 [256]
constexpr long double x6 [3]
constexpr long double x64 [32]
constexpr long double x7 [4]
constexpr long double x8 [4]
constexpr long double x9 [5]
constexpr long double x96 [48]
constexpr long double xi [33]
Detailed Description
Gauss-Kronrod-Patterson quadrature coefficients for use in QUADPACK routine QNG. These coefficients were calculated with 101 decimal digit arithmetic by L. W. Fullerton, Bell Labs, Nov 1981.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NO_ERROR
MAX_ITER_ERROR
ROUNDOFF_ERROR
SINGULAR_ERROR
EXTRAP_ROUNDOFF_ERROR
DIVERGENCE_ERROR
MAX_SUBDIV_ERROR
TOLERANCE_ERROR
UNKNOWN_ERROR
Definition at line 33 of file integration_error.h.
  {
    NO_ERROR,
    MAX_ITER_ERROR,
    ROUNDOFF_ERROR,
    SINGULAR_ERROR,
    EXTRAP_ROUNDOFF_ERROR,
    DIVERGENCE_ERROR,
    MAX_SUBDIV_ERROR,
    TOLERANCE_ERROR,
    UNKNOWN_ERROR
  };
Gauss_Legendre_Rule
enum emsr::Gauss_Legendre_Rule
Enumerator
GL_2
GL_4
GL_6
GL_8
GL_10
GL_12
GL_14
GL_16
GL_18
GL_20
GL_32
GL_64
GL_96
GL_100
GL_128
GL_256
GL_512
GL_1024
GL_3
GL_5
GL_7
GL_9
GL_11
GL_13
GL_15
GL_17
GL_19
Definition at line 32 of file gauss_legendre_table.h.
  {
    GL_2 = 2,
    GL_4 = 4,
    GL_6 = 6,
    GL_8 = 8,
    GL_10 = 10,
    GL_12 = 12,
    GL_14 = 14,
    GL_16 = 16,
    GL_18 = 18,
    GL_20 = 20,
    GL_32 = 32,
    GL_64 = 64,
    GL_96 = 96,
    GL_100 = 100,
    GL_128 = 128,
    GL_256 = 256,
    GL_512 = 512,
    GL_1024 = 1024,
    GL_3 = 3,
    GL_5 = 5,
    GL_7 = 7,
    GL_9 = 9,
    GL_11 = 11,
    GL_13 = 13,
    GL_15 = 15,
    GL_17 = 17,
    GL_19 = 19
  };
Function Documentation
check_error()
template<typename AreaTp , typename AbsAreaTp >
void emsr::check_error (std::string_view func, int errcode, AreaTp result, AbsAreaTp abserr)
Throws appropriate error if errcode nonzero
Definition at line 81 of file integration_error.h.
    {
      std::ostringstream msg;
      msg << func << ": ";
      if (errcode > 2)
        --errcode;
      switch(errcode)
        {
        case NO_ERROR:
          return;
        case MAX_ITER_ERROR:
          msg << "Number of iterations was insufficient";
          break;
        case ROUNDOFF_ERROR:
          msg << "Cannot reach tolerance because of roundoff error";
          break;
        case SINGULAR_ERROR:
          msg << "Bad integrand behavior found in the integration interval";
          break;
        case EXTRAP_ROUNDOFF_ERROR:
          msg << "Roundoff error detected in the extrapolation";
          break;
        case DIVERGENCE_ERROR:
          msg << "Integral is divergent, or slowly convergent";
          break;
        case MAX_SUBDIV_ERROR:
          msg << "Maximum number of subdivisions reached";
          break;
        case TOLERANCE_ERROR:
          msg << "Cannot reach tolerance with maximum order rule";
          break;
        default:
          msg << "Could not integrate function";
        }
      throw integration_error(msg.str().c_str(), errcode, result, abserr);
    }
References DIVERGENCE_ERROR, EXTRAP_ROUNDOFF_ERROR, MAX_ITER_ERROR, MAX_SUBDIV_ERROR, NO_ERROR, ROUNDOFF_ERROR, SINGULAR_ERROR, and TOLERANCE_ERROR.
Referenced by qag_integrate(), qagp_integrate(), qags_integrate(), qawc_integrate(), qawf_integrate(), qawo_integrate(), and qaws_integrate().
compute_moments()
template<typename Tp >
std::vector< Tp > emsr::compute_moments (std::size_t N, Tp cc)
Compute Clenshaw-Curtis moments. An iterator range version would be nicer I think.
Definition at line 272 of file qawc_integrate.tcc.
    {
      std::vector<Tp> moment(N);
      auto a0 = std::log(std::abs((Tp{1} - cc) / (Tp{1} + cc)));
      auto a1 = Tp{2} + a0 * cc;
      moment[0] = a0;
      moment[1] = a1;
      for (size_t k = 2; k < N; ++k)
        {
          Tp a2;
          if ((k % 2) == 0)
            a2 = Tp{2} * cc * a1 - a0;
          else
            {
              const auto km1 = Tp(k - 1);
              a2 = Tp{2} * cc * a1
                   - a0
                   - Tp{4} / (km1 * km1 - Tp{1});
            }
          moment[k] = a2;
          a0 = a1;
          a1 = a2;
        }
      return moment;
    }
References Tp.
compute_result()
template<typename Tp , typename RetTp >
auto emsr::compute_result (const std::array< Tp, 25 > & r, const std::array< RetTp, 13 > & cheb12, const std::array< RetTp, 25 > & cheb24) -> compute_result_t<decltype(Tp{} * RetTp{})>
Definition at line 402 of file qaws_integrate.tcc.
                                   {} * RetTp{})>
    {
      using AreaTp = decltype(RetTp{} * Tp{});
      auto res12 = AreaTp{};
      for (size_t i = 0; i < cheb12.size(); ++i)
        res12 += r[i] * cheb12[i];
      auto res24 = AreaTp{};
      for (size_t i = 0; i < cheb24.size(); ++i)
        res24 += r[i] * cheb24[i];
      return compute_result_t<AreaTp>{res12, res24};
    }
Referenced by qawf_integrate(), and qc25s().
cquad_integrate()
template<typename Tp , typename FuncTp >
auto emsr::cquad_integrate (cquad_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & ws, FuncTp func, Tp a, Tp b, Tp epsabs, Tp epsrel) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
CQUAD is a new doubly-adaptive general-purpose quadrature routine which can handle most types of singularities, non-numerical function values such as Inf or NaN, as well as some divergent integrals. It generally requires more function evaluations than the other integration routines in this library, yet fails less often for difficult integrands.
The underlying algorithm uses a doubly-adaptive scheme in which Clenshaw-Curtis quadrature rules of increasing degree are used to compute the integral in each interval. The L_2-norm of the difference between the underlying interpolatory polynomials of two successive rules is used as an error estimate. The interval is subdivided if the difference between two successive rules is too large or a rule of maximum degree has been reached.
The CQUAD algorithm divides the integration region into subintervals, and in each iteration, the subinterval with the largest estimated error is processed. The algorithm uses Clenshaw-Curtis quadrature rules of degree 4, 8, 16 and 32 over 5, 9, 17 and 33 nodes respectively. Each interval is initialized with the lowest-degree rule. When an interval is processed, the next-higher degree rule is evaluated and an error estimate is computed based on the L_2-norm of the difference between the underlying interpolating polynomials of both rules. If the highest-degree rule has already been used, or the interpolatory polynomials differ significantly, the interval is bisected.
Definition at line 149 of file cquad_integrate.tcc.
    {
      using RetTp = std::invoke_result_t<FuncTp, Tp>;
      using AreaTp = decltype(RetTp{} * Tp{});
      //using AbsAreaTp = decltype(std::abs(AreaTp{}));
      using AbsRetTp = decltype(std::abs(RetTp{}));
      // Some constants that we will need.
      constexpr std::ptrdiff_t n[4] = { 4, 8, 16, 32 };
      constexpr std::ptrdiff_t skip[4] = { 8, 4, 2, 1 };
      constexpr std::ptrdiff_t idx[4] = { 0, 5, 14, 31 };
      constexpr std::ptrdiff_t ndiv_max = 20;
      constexpr auto s_eps = std::numeric_limits<Tp>::epsilon();
      constexpr auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
      constexpr auto s_inf = std::numeric_limits<Tp>::infinity();
      constexpr Tp s_sqrt2 = M_SQRT2;
      constexpr auto w = s_sqrt2 / Tp{2};
      // Actual variables (as opposed to constants above).
      bool split;
      std::ptrdiff_t num_NaNs, NaN[32];
      AbsRetTp nc, ncdiff;
      // Check for unreasonable accuracy demands.
      if (epsabs < Tp{0} || epsrel < Tp{0})
        throw std::domain_error("tolerances may not be negative");
      if (epsabs <= Tp{0} && epsrel < s_eps)
        throw std::domain_error("unreasonable accuracy requirement");
      // Create the first interval.
      ws.clear();
      cquad_interval<Tp, RetTp> iv;
      auto m = (a + b) / Tp{2};
      auto h = (b - a) / Tp{2};
      num_NaNs = 0;
      for (std::ptrdiff_t i = 0; i <= n[3]; ++i)
        {
          iv.fx[i] = func(m + Tp(xi[i]) * h);
          if (std::isinf(iv.fx[i]) || std::isnan(iv.fx[i]))
            {
              NaN[num_NaNs++] = i;
              iv.fx[i] = RetTp{0};
            }
        }
      Vinvfx(iv.fx, &(iv.m_coeff[idx[0]]), 0);
      Vinvfx(iv.fx, &(iv.m_coeff[idx[3]]), 3);
      Vinvfx(iv.fx, &(iv.m_coeff[idx[2]]), 2);
      for (std::ptrdiff_t i = 0; i < num_NaNs; ++i)
        iv.fx[NaN[i]] = s_NaN;
      iv.m_lower_lim = a;
      iv.m_upper_lim = b;
      iv.depth = 3;
      iv.rdepth = 1;
      iv.ndiv = 0;
      iv.m_result = Tp{2} * h * iv.m_coeff[idx[3]] * w;
      nc = AbsRetTp{0};
      for (std::ptrdiff_t i = n[2] + 1; i <= n[3]; ++i)
        {
          const auto temp = std::abs(iv.m_coeff[idx[3] + i]);
          nc += temp * temp;
        }
      ncdiff = nc;
      for (std::ptrdiff_t i = 0; i <= n[2]; ++i)
        {
          const auto temp = std::abs(iv.m_coeff[idx[2] + i]
                                     - iv.m_coeff[idx[3] + i]);
          ncdiff += temp * temp;
          nc += std::abs(iv.m_coeff[idx[3] + i])
                * std::abs(iv.m_coeff[idx[3] + i]);
        }
      ncdiff = std::sqrt(ncdiff);
      nc = std::sqrt(nc);
      iv.m_abs_error = ncdiff * Tp{2} * h;
      if (ncdiff / nc > Tp{0.1} && iv.m_abs_error < Tp{2} * h * nc)
        iv.m_abs_error = Tp{2} * h * nc;
      ws.push(iv);
      // Main loop...
      auto igral = iv.m_result;
      auto igral_final = AreaTp{0};
      auto err = iv.m_abs_error;
      auto err_final = Tp{0};
      while (ws.size() > 0 && err > Tp{0} &&
             !(err <= std::abs(igral) * epsrel || err <= epsabs)
             && !(err_final > std::abs(igral) * epsrel
                  && err - err_final < std::abs(igral) * epsrel)
             && !(err_final > epsabs && err - err_final < epsabs))
        {
          // Put our finger on the interval with the largest error.
          auto& iv = ws.top();
          m = (iv.m_lower_lim + iv.m_upper_lim) / Tp{2};
          h = (iv.m_upper_lim - iv.m_lower_lim) / Tp{2};
          // Should we try to increase the degree?
          if (iv.depth < 3)
            {
              // Keep tabs on some variables.
              auto depth = ++iv.depth;
              // Get the new (missing) function values.
              for (std::ptrdiff_t i = skip[depth];
                        i <= 32; i += 2 * skip[depth])
                iv.fx[i] = func(m + Tp(xi[i]) * h);
              num_NaNs = 0;
              for (std::ptrdiff_t i = 0; i <= 32; i += skip[depth])
                if (std::isinf(iv.fx[i]) || std::isnan(iv.fx[i]))
                  {
                    NaN[num_NaNs++] = i;
                    iv.fx[i] = RetTp{0};
                  }
              // Compute the new coefficients.
              Vinvfx(iv.fx, &(iv.m_coeff[idx[depth]]), depth);
              // Downdate any NaNs.
              if (num_NaNs > 0)
                {
                  downdate(&(iv.m_coeff[idx[depth]]),
                           n[depth], depth, NaN, num_NaNs);
                  for (std::ptrdiff_t i = 0; i < num_NaNs; ++i)
                    iv.fx[NaN[i]] = s_NaN;
                }
              // Compute the error estimate.
              nc = AbsRetTp{0};
              for (std::ptrdiff_t i = n[depth - 1] + 1;
                   i <= n[depth]; ++i)
                {
                  const auto temp = std::abs(iv.m_coeff[idx[depth] + i]);
                  nc += temp * temp;
                }
              ncdiff = nc;
              for (std::ptrdiff_t i = 0; i <= n[depth - 1]; ++i)
                {
                  const auto temp
                    = std::abs(iv.m_coeff[idx[depth - 1] + i]
                             - iv.m_coeff[idx[depth] + i]);
                  ncdiff += temp * temp;
                  nc += abs(iv.m_coeff[idx[depth] + i])
                        * abs(iv.m_coeff[idx[depth] + i]);
                }
              ncdiff = std::sqrt(ncdiff);
              nc = std::sqrt(nc);
              iv.m_abs_error = ncdiff * Tp{2} * h;
              // Compute the local integral.
              iv.m_result = Tp{2} * h * w
                             * iv.m_coeff[idx[depth]];
              // Split the interval prematurely?
              split = (nc > Tp{0} && ncdiff / nc > Tp{0.1});
            }
          else // Maximum degree reached, just split.
            split = true;
          // Should we drop this interval?
          if ((m + h * Tp(xi[0])) >= (m + h * Tp(xi[1]))
              || (m + h * Tp(xi[31])) >= (m + h * Tp(xi[32]))
              || iv.m_abs_error < std::abs(iv.m_result) * s_eps * 10)
            {
              // Keep this interval's contribution.
              err_final += iv.m_abs_error;
              igral_final += iv.m_result;
              ws.pop();
            }
          else if (split) // Do we need to split this interval?
            {
              // Some values we will need often...
              auto depth = iv.depth;
              // Generate the interval on the left.
              cquad_interval<Tp, RetTp> ivl;
              ivl.m_lower_lim = iv.m_lower_lim;
              ivl.m_upper_lim = m;
              ivl.depth = 0;
              ivl.rdepth = iv.rdepth + 1;
              ivl.fx[0] = iv.fx[0];
              ivl.fx[32] = iv.fx[16];
              for (std::ptrdiff_t i = skip[0]; i < 32; i += skip[0])
                ivl.fx[i] = func((ivl.m_lower_lim + ivl.m_upper_lim)
                              / Tp{2} + Tp(xi[i]) * h / Tp{2});
              num_NaNs = 0;
              for (std::ptrdiff_t i = 0; i <= 32; i += skip[0])
                {
                  if (std::isinf(ivl.fx[i]) || std::isnan(ivl.fx[i]))
                    {
                      NaN[num_NaNs++] = i;
                      ivl.fx[i] = RetTp{0};
                    }
                }
              Vinvfx(ivl.fx, ivl.m_coeff, 0);
              if (num_NaNs > 0)
                {
                  downdate(ivl.m_coeff, n[0], 0, NaN, num_NaNs);
                  for (std::ptrdiff_t i = 0; i < num_NaNs; ++i)
                    ivl.fx[NaN[i]] = s_NaN;
                }
              for (std::ptrdiff_t i = 0; i <= n[depth]; ++i)
                {
                  ivl.m_coeff[idx[depth] + i] = Tp{0};
                  for (std::ptrdiff_t j = i; j <= n[depth]; ++j)
                    ivl.m_coeff[idx[depth] + i]
                        += Tp(Tleft[i * 33 + j])
                           * iv.m_coeff[idx[depth] + j];
                }
              ncdiff = AbsRetTp{0};
              for (std::ptrdiff_t i = 0; i <= n[0]; ++i)
                {
                  const auto temp
                    = std::abs(ivl.m_coeff[i]
                             - ivl.m_coeff[idx[depth] + i]);
                  ncdiff += temp * temp;
                }
              for (std::ptrdiff_t i = n[0] + 1; i <= n[depth]; ++i)
                {
                  const auto temp
                    = std::abs(ivl.m_coeff[idx[depth] + i]);
                  ncdiff += temp * temp;
                }
              ncdiff = std::sqrt(ncdiff);
              ivl.m_abs_error = ncdiff * h;
              // Check for divergence.
              ivl.ndiv = iv.ndiv
                         + (std::abs(iv.m_coeff[0]) > 0
                         && std::abs(ivl.m_coeff[0] / iv.m_coeff[0]) > 2);
              if (ivl.ndiv > ndiv_max && 2 * ivl.ndiv > ivl.rdepth)
                {
                  //const auto result = std::copysign(s_inf, igral);
                  return {AreaTp(s_inf), s_inf};
                }
              // Compute the local integral.
              ivl.m_result = h * w * ivl.m_coeff[0];
              // Generate the interval on the right.
              cquad_interval<Tp, RetTp> ivr;
              ivr.m_lower_lim = m;
              ivr.m_upper_lim = iv.m_upper_lim;
              ivr.depth = 0;
              ivr.rdepth = iv.rdepth + 1;
              ivr.fx[0] = iv.fx[16];
              ivr.fx[32] = iv.fx[32];
              for (std::ptrdiff_t i = skip[0]; i < 32; i += skip[0])
                ivr.fx[i] = func((ivr.m_lower_lim + ivr.m_upper_lim)
                              / Tp{2} + Tp(xi[i]) * h / Tp{2});
              num_NaNs = 0;
              for (std::ptrdiff_t i = 0; i <= 32; i += skip[0])
                {
                  if (std::isinf(ivr.fx[i]) || std::isnan(ivr.fx[i]))
                    {
                      NaN[num_NaNs++] = i;
                      ivr.fx[i] = RetTp{0};
                    }
                }
              Vinvfx (ivr.fx, ivr.m_coeff, 0);
              if (num_NaNs > 0)
                {
                  downdate(ivr.m_coeff, n[0], 0, NaN, num_NaNs);
                  for (std::ptrdiff_t i = 0; i < num_NaNs; ++i)
                    ivr.fx[NaN[i]] = s_NaN;
                }
              for (std::ptrdiff_t i = 0; i <= n[depth]; ++i)
                {
                  ivr.m_coeff[idx[depth] + i] = Tp{0};
                  for (std::ptrdiff_t j = i; j <= n[depth]; ++j)
                    ivr.m_coeff[idx[depth] + i]
                        += Tp(Tright[i * 33 + j])
                         * iv.m_coeff[idx[depth] + j];
                }
              ncdiff = AbsRetTp{0};
              for (std::ptrdiff_t i = 0; i <= n[0]; ++i)
                {
                  const auto temp
                    = std::abs(ivr.m_coeff[i]
                            - ivr.m_coeff[idx[depth] + i]);
                  ncdiff += temp * temp;
                }
              for (std::ptrdiff_t i = n[0] + 1; i <= n[depth]; ++i)
                {
                  const auto temp
                    = std::abs(ivr.m_coeff[idx[depth] + i]);
                  ncdiff += temp * temp;
                }
              ncdiff = std::sqrt(ncdiff);
              ivr.m_abs_error = ncdiff * h;
              // Check for divergence.
              ivr.ndiv = iv.ndiv
                         + (std::abs(iv.m_coeff[0]) > 0
                         && std::abs(ivr.m_coeff[0] / iv.m_coeff[0]) > 2);
              if (ivr.ndiv > ndiv_max && 2 * ivr.ndiv > ivr.rdepth)
                {
                  //const auto result = std::copysign(s_inf, igral);
                  return {AreaTp(s_inf), s_inf};
                }
              // Compute the local integral.
              ivr.m_result = h * w * ivr.m_coeff[0];
              ws.pop();
              ws.push(ivl);
              ws.push(ivr);
            }
          else // Otherwise, just fix-up the heap.
            ws.update();
          // Collect the value of the integral and error.
          igral = igral_final + ws.total_integral();
          err = err_final + ws.total_error();
        }
      return {igral, err};
    }
References emsr::cquad_interval< Tp, RetTp >::depth, emsr::cquad_interval< Tp, RetTp >::fx, emsr::cquad_interval< Tp, RetTp >::m_coeff, emsr::cquad_interval< Tp, RetTp >::m_lower_lim, emsr::cquad_interval< Tp, RetTp >::m_result, emsr::cquad_interval< Tp, RetTp >::m_upper_lim, emsr::cquad_interval< Tp, RetTp >::ndiv, emsr::cquad_interval< Tp, RetTp >::rdepth, Tp, Vinvfx(), and xi.
discrete_fourier_transform()
template<typename Tp >
void emsr::discrete_fourier_transform (bool do_forward, std::vector< std::complex< Tp >> & z)
Discrete Fourier transform on complex data.
Definition at line 34 of file fourier_transform.tcc.
    {
      const auto sign(do_forward ? Tp{+1} : Tp{-1});
      const auto len = z.size();
      std::vector<std::complex<Tp>> result;
      result.reserve(len);
      // Do matrix multiplication.
      for (std::size_t i = 0; i < len; ++i)
        {
          phase_iterator coefficient_iter(sign, i, len);
          result.push_back(std::inner_product(z.begin(), z.end(),
                             coefficient_iter, std::complex<Tp>{0}));
        }
      // Rescale if forward.
      if (do_forward)
        {
          const auto norm = Tp{1} / Tp(len);
          for (std::size_t i = 0; i < len; ++i)
            result[i] *= norm;
        }
      // Copy data back (swap is fast!).
      z.swap(result);
    }
References Tp.
Referenced by fast_fourier_transform(), and inv_fast_fourier_transform().
downdate()
template<typename Tp >
void emsr::downdate (Tp * coeff, std::ptrdiff_t n, std::ptrdiff_t depth, std::ptrdiff_t * NaN, std::ptrdiff_t num_NaNs)
Downdate the interpolation given by the n coefficients c by removing the nodes with indices in NaNs.
Definition at line 93 of file cquad_integrate.tcc.
    {
      constexpr std::ptrdiff_t bidx[4] = { 0, 6, 16, 34 };
      Tp b_new[34], alpha;
      for (std::ptrdiff_t i = 0; i <= n + 1; ++i)
        b_new[i] = bee[bidx[depth] + i];
      for (std::ptrdiff_t i = 0; i < num_NaNs; ++i)
        {
          b_new[n + 1] = b_new[n + 1] / Tp(Lalpha[n]);
          b_new[n] = (b_new[n] + Tp(xi[NaN[i]]) * b_new[n + 1])
                       / Tp(Lalpha[n - 1]);
          for (std::ptrdiff_t j = n - 1; j > 0; --j)
            b_new[j] = (b_new[j] + Tp(xi[NaN[i]]) * b_new[j + 1]
                           - Tp(Lgamma[j + 1]) * b_new[j + 2])
                         / Tp(Lalpha[j - 1]);
          for (std::ptrdiff_t j = 0; j <= n; ++j)
            b_new[j] = b_new[j + 1];
          alpha = coeff[n] / b_new[n];
          for (std::ptrdiff_t j = 0; j < n; ++j)
            coeff[j] -= alpha * b_new[j];
          coeff[n] = Tp{0};
          --n;
        }
    }
References bee, Lalpha, Lgamma, Tp, and xi.
fast_fourier_transform() [1/3]
template<typename CmplxIter >
void emsr::fast_fourier_transform (const CmplxIter & from, const CmplxIter & to)
Fast Fourier Transform on input range.
Definition at line 257 of file fourier_transform.tcc.
    {
      using Cmplx = typename CmplxIter::value_type;
      using Tp = typename Cmplx::value_type;
      std::vector<std::complex<Tp>> z(from, to);
      fast_fourier_transform(z);
      std::copy(z.begin(), z.end(), from);
    }
References fast_fourier_transform(), and Tp.
fast_fourier_transform() [2/3]
template<typename Tp >
void emsr::fast_fourier_transform (std::vector< std::complex< Tp >> & z)
Fast Fourier Transform on complex data.
Definition at line 68 of file fourier_transform.tcc.
    {
      const auto len = z.size();
      if (len % 2 == 1) // Too bad, we're odd.
        discrete_fourier_transform(true, z);
      else // Good, we're even.
        {
          // Let's divide and conquer!
          std::vector<std::complex<Tp>> odd;
          std::vector<std::complex<Tp>> even;
          const auto halflen = len / 2;
          odd.reserve(halflen);
          even.reserve(halflen);
          for (auto run = z.cbegin(); run != z.cend(); ++run)
            {
              even.push_back(*run);
              ++run;
              odd.push_back(*run);
            }
          fast_fourier_transform(even);
          fast_fourier_transform(odd);
          phase_iterator omega_iter(Tp{1}, 1, len);
          for (std::size_t i = 0, j = halflen; i < halflen;
                ++i, ++j, ++omega_iter)
            {
              z[i] = (even[i] + *omega_iter * odd[i]) / Tp{2};
              // The next line works because omega^(length/2) = -1.
              z[j] = (even[i] - *omega_iter * odd[i]) / Tp{2};
            }
        }
    }
References discrete_fourier_transform(), and Tp.
Referenced by fast_fourier_transform(), and fast_sine_transform().
fast_fourier_transform() [3/3]
template<typename Tp >
void emsr::fast_fourier_transform (std::vector< Tp > & x)
Fast Fourier Transform on real data.
Definition at line 142 of file fourier_transform.tcc.
    {
      const auto len = x.size();
      if (len % 2 == 1) // Too bad, we're odd.
        throw std::domain_error("fast_fourier_transform: "
                                  "Real data must have even length.");
      else // Good, we're even.
        {
          // @todo I really want to just make a view to a complex vector.
          const auto halflen = len / 2;
          std::vector<std::complex<Tp>> z;
          z.reserve(halflen + 1);
          for (std::size_t i = 0; i < halflen; ++i)
            z.emplace_back(x[2 * i], x[2 * i + 1]);
          fast_fourier_transform(z);
          z.emplace_back(z[0]); // Use symmetry. We need N/2 transform.
          const auto s_i2 = std::complex<Tp>{0, 2};
          phase_iterator omega_iter(Tp{+1}, 1, halflen);
          for (std::size_t i = 0; i < halflen; ++i)
            {
              const auto z1 = z[i];
              const auto z2 = std::conj(z[halflen - i]);
              const auto f = (z1 + z2) / Tp{2}
                             + *omega_iter * (z1 - z2) / s_i2;
              x[2 * i] = f.real();
              x[2 * i + 1] = f.imag();
            }
        }
    }
References fast_fourier_transform(), and Tp.
fast_sine_transform()
template<typename Tp >
void emsr::fast_sine_transform (std::vector< Tp > & x)
Fast Sine Transform on real data.
Definition at line 213 of file fourier_transform.tcc.
    {
      const auto len = x.size();
      const auto halflen = len / 2;
      const auto n2 = len - 1;
      phase_iterator omega_iter(Tp{+1}, 1, len);
      x[0] = Tp{0};
      for (std::size_t k = 1; k <= halflen; ++k, ++omega_iter)
        {
          const auto y1 = omega_iter.sin()
                          * (x[k] + x[n2 - k]);
          const auto y2 = (x[k] - x[n2 - k]) / Tp{2};
          x[k] = y1 + y2;
          x[n2 - k] = y1 - y2;
        }
      fast_fourier_transform(x);
      x[0] *= Tp{0.5L};
      x[1] = Tp{0};
      auto sum = Tp{0};
      for (std::size_t i = 2; i < halflen; i += 2)
        {
          sum += std::exchange(x[i], x[i + 1]);
          x[i + 1] = sum;
        }
    }
References fast_fourier_transform(), and Tp.
Referenced by inv_fast_sine_transform().
integrate()
template<typename Tp , typename FuncTp >
auto emsr::integrate (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024, Kronrod_Rule qkintrule = Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate a smooth function from a to b.
Higher-order rules converge more rapidly for most functions, but may slow convergence for less well-behaved ones.
Parameters
func The function to be integrated.
lower The lower limit of integration.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
qkintrule is the Gauss-Kronrod integration rule.
Returns
A structure containing the integration result and the error.
integrate_cauchy_principal_value()
template<typename Tp , typename FuncTp >
auto emsr::integrate_cauchy_principal_value (FuncTp func, Tp lower, Tp upper, Tp center, Tp max_abs_err, Tp max_rel_err, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate the principal value of a function with a Cauchy singularity.
integrate_clenshaw_curtis()
template<typename Tp , typename FuncTp >
auto emsr::integrate_clenshaw_curtis (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate a function using an adaptive Clenshaw-Curtis algorithm.
Template Parameters
FuncTp A function type that takes a single real scalar argument and returns a real scalar.
Tp A real type for the limits of integration and the step.
integrate_exp_sinh()
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_exp_sinh (FuncTp func, Tp lower, Tp max_abs_err, Tp max_rel_err, int max_iter)
 \int_{0}^{+\infty}f(x)dx 
 Making the change of variables:
 x = exp\left[\frac{\pi}{2}sinh(u)\right], dx = \frac{\pi}{2} cosh(u) exp\left[\frac{\pi}{2}sinh(u)\right]du 
 gives the following integral:
 \int_{0}^{+\infty}f(exp\left[\frac{\pi}{2}sinh(u)\right]) = \sum_{k=-n}^{+n} 
This function allows a non-zero lower limit a.
Parameters
func The function to be integrated.
a The lower limit of the semi-infinite integral.
Definition at line 261 of file double_exp_integrate.tcc.
    {
      using integ_t = adaptive_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      using absarea_t = typename integ_t::AbsAreaTp;
      using RetTp = std::invoke_result_t<FuncTp, Tp>;
      using AreaTp = decltype(RetTp{} * Tp{});
      const auto s_pi_4 = Tp{3.141592653589793238462643383279502884195L} / 4;
      if (std::isnan(lower)
          || std::isnan(max_abs_err) || std::isnan(max_rel_err))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN, absarea_t{} * s_NaN};
        }
      else
        {
          int n = 16;
          // Find K = ln(ln(max_number))
          const auto k_max
                      = std::log(std::log(std::numeric_limits<Tp>::max()))
                      - Tp{1};
          auto h = k_max / n;
          auto sum = AreaTp{0};
          for (int k = -n; k <= n; ++k)
            {
              const auto u = h * Tp(k);
              const auto eu = std::exp(u);
              const auto cosh = eu + Tp{1} / eu;
              const auto sinh = eu - Tp{1} / eu;
              const auto esh = std::exp(s_pi_4 * sinh);
              const auto dxdu = cosh * esh;
              sum += dxdu * func(lower + esh);
            }
          // Interlace values (don't go past the rightmost point).
          auto prev_sum = sum;
          for (int iter = 0; iter < max_iter; ++iter)
            {
              for (int k = -n; k < n; ++k)
                {
                  const auto u = h * Tp(k + 0.5);
                  const auto eu = std::exp(u);
                  const auto cosh = eu + Tp{1} / eu;
                  const auto sinh = eu - Tp{1} / eu;
                  const auto esh = std::exp(s_pi_4 * sinh);
                  const auto dxdu = cosh * esh;
                  sum += dxdu * func(lower + esh);
                }
              n *= 2;
              h /= Tp{2};
              if (auto abs_del = std::abs(sum - prev_sum);
                  abs_del < max_abs_err
                  || abs_del < std::abs(max_rel_err * sum)
                  || iter + 1 == max_iter) // Keep prev_sum even if at max_iters.
                break;
              prev_sum = sum;
            }
          const auto fact = s_pi_4 * h;
          return {fact * sum, fact * std::abs(sum - Tp{2} * prev_sum)};
        }
    }
References Tp.
integrate_fixed_gauss_chebyshev_t()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_chebyshev_t (int n, FuncTp func, Tp lower, Tp upper)
Definition at line 274 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_chebyshev_t_integral<Tp> integ(n);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_chebyshev_u()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_chebyshev_u (int n, FuncTp func, Tp lower, Tp upper)
Definition at line 298 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_chebyshev_u_integral<Tp> integ(n);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_chebyshev_v()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_chebyshev_v (int n, FuncTp func, Tp lower, Tp upper)
Definition at line 321 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_chebyshev_v_integral<Tp> integ(n);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_chebyshev_w()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_chebyshev_w (int n, FuncTp func, Tp lower, Tp upper)
Definition at line 344 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_chebyshev_w_integral<Tp> integ(n);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_exponential()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_exponential (int n, Tp alf, FuncTp func, Tp lower, Tp upper)
Definition at line 460 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper) || std::isnan(alf))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_exponential_integral<Tp> integ(n, alf);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_gegenbauer()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_gegenbauer (int n, Tp lambda, FuncTp func, Tp lower, Tp upper)
Definition at line 367 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper) || std::isnan(lambda))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_gegenbauer_integral<Tp> integ(n, lambda);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_hermite()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_hermite (int n, Tp alf, FuncTp func, Tp lower, Tp upper)
Definition at line 437 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper) || std::isnan(alf))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_hermite_integral<Tp> integ(n, alf);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_jacobi()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_jacobi (int n, Tp alf, Tp bet, FuncTp func, Tp lower, Tp upper)
Definition at line 390 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper)
          || std::isnan(alf) || std::isnan(bet))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_jacobi_integral<Tp> integ(n, alf, bet);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_laguerre()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_laguerre (int n, Tp alf, FuncTp func, Tp lower, Tp upper)
Definition at line 414 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper) || std::isnan(alf))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_laguerre_integral<Tp> integ(n, alf);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_legendre()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_legendre (int n, FuncTp func, Tp lower, Tp upper)
Definition at line 251 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_legendre_integral<Tp> integ(n);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_fixed_gauss_rational()
template<typename Tp , typename FuncTp >
fixed_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_fixed_gauss_rational (int n, Tp alf, Tp bet, FuncTp func, Tp lower, Tp upper)
Definition at line 483 of file gauss_quadrature.h.
    {
      using integ_t = fixed_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      if (std::isnan(lower) || std::isnan(upper)
          || std::isnan(alf) || std::isnan(bet))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}};
      else
        {
          fixed_gauss_rational_integral<Tp> integ(n, alf, bet);
          return { integ(func, lower, upper) };
        }
    }
References Tp.
integrate_kronrod_singular()
template<typename Tp , typename FuncTp >
auto emsr::integrate_kronrod_singular (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Adaptive Gauss-Kronrod integration optimized for discontinuous or singular functions
Parameters
func The function to be integrated.
lower The lower limit of integration.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
Returns
A structure containing the integration result and the error.
integrate_lower_minf()
template<typename Tp , typename FuncTp >
auto emsr::integrate_lower_minf (FuncTp func, Tp lower, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024, Kronrod_Rule qkintrule = Kronrod_21) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>> [inline]
Definition at line 219 of file integration.h.
    {
      return -integrate_minf_upper(func, lower,
                                   max_abs_error, max_rel_error,
                                   max_iter, qkintrule);
    }
References integrate_minf_upper().
integrate_lower_pinf()
template<typename Tp , typename FuncTp >
auto emsr::integrate_lower_pinf (FuncTp func, Tp lower, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024, Kronrod_Rule qkintrule = Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate a smooth function from finite lower limit to +infinity.
Parameters
func The function to be integrated.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
qkintrule is the Gauss-Kronrod integration rule.
Returns
A structure containing the integration result and the error.
Referenced by integrate_pinf_upper().
integrate_midpoint()
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_midpoint (FuncTp func, Tp a, Tp b, Tp max_abs_err, Tp max_rel_err, int max_iter) [inline]
Definition at line 128 of file midpoint_integral.h.
    {
      using integ_t = adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      using absarea_t = typename integ_t::AbsAreaTp;
      if (std::isnan(lower) || std::isnan(upper)
          || std::isnan(max_abs_err) || std::isnan(max_rel_err))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN, absarea_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}, absarea_t{}};
      else
        {
          midpoint_integral<Tp, FuncTp>
            mpi(func, lower, upper, max_abs_err, max_rel_err, max_iter);
          return {mpi(), mpi.abs_error()};
        }
    }
References emsr::midpoint_integral< Tp, FuncTp >::abs_error().
integrate_minf_pinf()
template<typename Tp , typename FuncTp >
auto emsr::integrate_minf_pinf (FuncTp func, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024, Kronrod_Rule qkintrule = Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrates a smooth function from -infinity to +infinity.
Parameters
func The function to be integrated.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
qkintrule is the Gauss-Kronrod integration rule.
Returns
A structure containing the integration result and the error.
integrate_minf_upper()
template<typename Tp , typename FuncTp >
auto emsr::integrate_minf_upper (FuncTp func, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024, Kronrod_Rule qkintrule = Kronrod_21) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate a smooth function from -infinity to finite b.
Parameters
func The function to be integrated.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
qkintrule is the Gauss-Kronrod integration rule.
Returns
A structure containing the integration result and the error.
Referenced by integrate_lower_minf().
integrate_multisingular()
template<typename FuncTp , typename FwdIter , typename Tp >
auto emsr::integrate_multisingular (FuncTp func, FwdIter ptbeg, FwdIter ptend, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Adaptively integrate a function with known singular/discontinuous points.
Template Parameters
FuncTp A function type that takes a single real scalar argument and returns a real scalar.
Tp A real type for the limits of integration and the step.
integrate_oscillatory()
template<typename Tp , typename FuncTp >
auto emsr::integrate_oscillatory (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate an oscillatory function.
integrate_patterson()
template<typename Tp , typename FuncTp >
auto emsr::integrate_patterson (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Adaptively integrate a function using a recursive Gauss-Kronrod quadrature called the Patterson algorithm.
integrate_pinf_upper()
template<typename Tp , typename FuncTp >
auto emsr::integrate_pinf_upper (FuncTp func, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024, Kronrod_Rule qkintrule = Kronrod_21) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>> [inline]
Definition at line 255 of file integration.h.
    {
      return -integrate_lower_pinf(func, upper,
                                   max_abs_error, max_rel_error,
                                   max_iter, qkintrule);
    }
References integrate_lower_pinf().
integrate_simpson()
template<typename Tp , typename FuncTp >
adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp> > emsr::integrate_simpson (FuncTp __func, Tp __a, Tp __b, Tp __max_abs_err, Tp __max_rel_err, int __max_iter) [inline]
Definition at line 129 of file simpson_integral.h.
    {
      simpson_integral<Tp, FuncTp>
        __simpi(__func, __a, __b, __max_abs_err, __max_rel_err, __max_iter);
      return {__simpi(), __simpi.abs_error()};
    }
References emsr::simpson_integral< Tp, FuncTp >::abs_error().
integrate_singular()
template<typename Tp , typename FuncTp >
auto emsr::integrate_singular (FuncTp func, Tp lower, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate a potentially singular function.
Parameters
func The function to be integrated.
lower The lower limit of integration.
upper The upper limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
Returns
A structure containing the integration result and the error.
integrate_singular_endpoints()
template<typename Tp , typename FuncTp >
auto emsr::integrate_singular_endpoints (FuncTp func, Tp lower, Tp upper, Tp alpha, Tp beta, int mu, int nu, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
The singular weight function is defined by:
 W(x) = (x-a)^\alpha (b-x)^\beta log^\mu (x-a) log^\nu (b-x) 
 where $ \alpha > -1 $, $ \beta > -1 $, and $ \mu = 0 $, 1, $ \nu = 0, 1 $.
The weight function can take four different forms depending on the values of \mu and \nu,
 W(x) = (x-a)^\alpha (b-x)^\beta (\mu = 0, \nu = 0) W(x) = (x-a)^\alpha (b-x)^\beta log(x-a) (\mu = 1, \nu = 0) W(x) = (x-a)^\alpha (b-x)^\beta log(b-x) (\mu = 0, \nu = 1) W(x) = (x-a)^\alpha (b-x)^\beta log(x-a) log(b-x) (\mu = 1, \nu = 1) 
The QAWS algorithm is designed for integrands with algebraic-logarithmic singularities at the end-points of an integration region.
integrate_singular_lower_minf()
template<typename Tp , typename FuncTp >
auto emsr::integrate_singular_lower_minf (FuncTp func, Tp lower, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>> [inline]
Definition at line 319 of file integration.h.
    {
      return -integrate_singular_minf_upper(func, lower,
                                            max_abs_error, max_rel_error,
                                            max_iter);
    }
References integrate_singular_minf_upper().
integrate_singular_lower_pinf()
template<typename Tp , typename FuncTp >
auto emsr::integrate_singular_lower_pinf (FuncTp func, Tp lower, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrates a potentially singular function from a to +infinity
Parameters
func The function to be integrated.
lower The lower limit of integration.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
Returns
A structure containing the integration result and the error.
Referenced by integrate_singular_pinf_upper().
integrate_singular_minf_pinf()
template<typename Tp , typename FuncTp >
auto emsr::integrate_singular_minf_pinf (FuncTp func, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate a potentially singular function from -infinity to +infinity
Parameters
func The function to be integrated.
max_abs_error The absolute error limit.
max_rel_error The relative error limit.
max_iter is the maximum number of iterations allowed
Returns
A structure containing the integration result and the error.
integrate_singular_minf_upper()
template<typename Tp , typename FuncTp >
auto emsr::integrate_singular_minf_upper (FuncTp func, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp >>
Integrate a potentially singular function from -infinity to b
Referenced by integrate_singular_lower_minf().
integrate_singular_pinf_upper()
template<typename Tp , typename FuncTp >
auto emsr::integrate_singular_pinf_upper (FuncTp func, Tp upper, Tp max_abs_error, Tp max_rel_error, std::size_t max_iter = 1024) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>> [inline]
Definition at line 350 of file integration.h.
    {
      return -integrate_singular_lower_pinf(func, upper,
                                            max_abs_error, max_rel_error,
                                            max_iter);
    }
References integrate_singular_lower_pinf().
integrate_sinh_sinh()
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_sinh_sinh (FuncTp func, Tp max_abs_err, Tp max_rel_err, int max_iter)
 \int_{-\infty}^{+\infty}f(x)dx 
 Making the change of variables:
 x = sinh\left[\frac{\pi}{2}sinh(u)\right], dx = \frac{\pi}{2} cosh(u) cosh\left[\frac{\pi}{2}sinh(u)\right]du 
 gives the following integral:
 \int_{-\infty}^{+\infty}f(sinh\left[\frac{\pi}{2}sinh(u)\right]) = \sum_{k=-n}^{+n} 
Definition at line 158 of file double_exp_integrate.tcc.
    {
      using integ_t = adaptive_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      using absarea_t = typename integ_t::AbsAreaTp;
      const auto s_pi_4 = Tp{3.141592653589793238462643383279502884195L} / 4;
      if (std::isnan(max_abs_err) || std::isnan(max_rel_err))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN, absarea_t{} * s_NaN};
        }
      else
        {
          int n = 16;
          n /= 2;
          // Find K = ln(ln(max_number))
          const auto k_max
                      = std::log(std::log(std::numeric_limits<Tp>::max()))
                      - Tp{1};
          auto h = k_max / n;
          auto sum = func(Tp{0});
          decltype(sum) sum1{}, sum2{};
          for (int k = -n; k < 0; ++k)
            {
              const auto u = h * Tp(k);
              const auto eu = std::exp(u);
              const auto cosh = eu + Tp{1} / eu;
              const auto sinh = eu - Tp{1} / eu;
              const auto esh = std::exp(s_pi_4 * sinh);
              const auto x = (esh - Tp{1} / esh) / Tp{2};
              const auto w = esh + Tp{1} / esh;
              const auto dxdu = cosh * w / Tp{4};
              sum1 += dxdu * func(+x);
              sum2 += dxdu * func(-x);
            }
          auto prev_sum = sum + sum1 + sum2;
          for (int iter = 0; iter < max_iter; ++iter)
            {
              for (int k = -n; k < 0; ++k)
                {
                  const auto u = h * Tp(k + 0.5);
                  const auto eu = std::exp(u);
                  const auto cosh = eu + Tp{1} / eu;
                  const auto sinh = eu - Tp{1} / eu;
                  const auto esh = std::exp(s_pi_4 * sinh);
                  const auto x = (esh - Tp{1} / esh) / Tp{2};
                  const auto w = esh + Tp{1} / esh;
                  const auto dxdu = cosh * w / Tp{4};
                  sum1 += dxdu * func(+x);
                  sum2 += dxdu * func(-x);
                }
              n *= 2;
              h /= Tp{2};
              const auto curr_sum = sum + sum1 + sum2;
              if (auto abs_del = std::abs(curr_sum - prev_sum);
                  abs_del < max_abs_err
                  || abs_del < std::abs(max_rel_err * curr_sum)
                  || iter + 1 == max_iter) // Keep prev_sum even if at max_iters.
                break;
              prev_sum = curr_sum;
            }
          const auto fact = Tp{2} * s_pi_4 * h;
          const auto tot_sum = sum + sum1 + sum2;
          return {fact * tot_sum,
                  fact * std::abs(tot_sum - Tp{2} * prev_sum)};
        }
    }
References Tp.
integrate_tanh_sinh()
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_tanh_sinh (FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err, int max_iter)
 \int_{-1}^{+1}f(x)dx 
 Making the change of variables:
 x = tanh\left[\frac{\pi}{2}sinh(u)\right], dx = \frac{\pi}{2} \frac{cosh(u)}{cosh^2\left[\frac{\pi}{2}sinh(u)\right]}du 
 gives the following integral:
 \int_{-\infty}^{+\infty}f(tanh\left[\frac{\pi}{2}sinh(u)\right]) = \sum_{k=-n}^{+n} 
Definition at line 47 of file double_exp_integrate.tcc.
    {
      using integ_t = adaptive_integral_t<Tp,
                                     std::invoke_result_t<FuncTp, Tp>>;
      using area_t = typename integ_t::AreaTp;
      using absarea_t = typename integ_t::AbsAreaTp;
      const auto s_pi_4 = Tp{3.141592653589793238462643383279502884195L} / 4;
      if (std::isnan(lower) || std::isnan(upper)
          || std::isnan(max_abs_err) || std::isnan(max_rel_err))
        {
          const auto s_NaN = std::numeric_limits<Tp>::quiet_NaN();
          return {area_t{} * s_NaN, absarea_t{} * s_NaN};
        }
      else if (lower == upper)
        return {area_t{}, absarea_t{}};
      else
        {
          int n = 16;
          n /= 2;
          // Find K = ln(ln(max_number))
          const auto k_max
                      = std::log(std::log(std::numeric_limits<Tp>::max()))
                      - Tp{1};
          auto h = k_max / n;
          auto sum = func((lower + upper) / Tp{2}) / Tp{2};
          decltype(sum) sum1{}, sum2{};
          for (int k = -n; k < 0; ++k)
            {
              const auto u = h * Tp(k);
              const auto eu = std::exp(u);
              const auto cosh = eu + Tp{1} / eu;
              const auto sinh = eu - Tp{1} / eu;
              const auto esh = std::exp(s_pi_4 * sinh);
              const auto w = esh + Tp{1} / esh;
              const auto dxdu = cosh / (w * w);
              const auto x1 = (upper * esh + lower / esh) / w;
              if (x1 != lower && x1 != upper)
                sum1 += dxdu * func(x1);
              const auto x2 = (lower * esh + upper / esh) / w;
              if (x2 != lower && x2 != upper)
                sum2 += dxdu * func(x2);
            }
          // Interlace values; don't go past the rightmost point.
          auto prev_sum = sum + sum1 + sum2;
          for (int iter = 0; iter < max_iter; ++iter)
            {
              for (int k = -n; k < 0; ++k)
                {
                  const auto u = h * Tp(k + 0.5);
                  const auto eu = std::exp(u);
                  // A standard sinhcosh would be a nice idea along with sincos.
                  const auto cosh = eu + Tp{1} / eu;
                  const auto sinh = eu - Tp{1} / eu;
                  const auto esh = std::exp(s_pi_4 * sinh);
                  const auto w = esh + Tp{1} / esh;
                  const auto dxdu = cosh / (w * w);
                  // natural: x1 = (s - 1/s) / (s + 1/s)
                  const auto x1 = (upper * esh + lower / esh) / w;
                  if (x1 != lower && x1 != upper)
                    sum1 += dxdu * func(x1);
                  // natural: x2 = (-s + 1/s) / (s + 1/s)
                  const auto x2 = (lower * esh + upper / esh) / w;
                  if (x2 != lower && x2 != upper)
                    sum2 += dxdu * func(x2);
                }
              n *= 2;
              h /= Tp{2};
              const auto curr_sum = sum + sum1 + sum2;
              if (auto abs_del = std::abs(curr_sum - prev_sum);
                  abs_del < max_abs_err
                  || abs_del < std::abs(max_rel_err * curr_sum)
                  || iter + 1 == max_iter) // Keep prev_sum even if at max_iters.
                break;
              prev_sum = curr_sum;
            }
          const auto fact = Tp{2} * (upper - lower) * s_pi_4 * h;
          const auto tot_sum = sum + sum1 + sum2;
          return {fact * tot_sum,
                  fact * std::abs(tot_sum - Tp{2} * prev_sum)};
        }
    }
References Tp, and x2.
integrate_trapezoid()
template<typename Tp , typename FuncTp >
adaptive_integral_t< Tp, std::invoke_result_t< FuncTp, Tp > > emsr::integrate_trapezoid (FuncTp func, Tp a, Tp b, Tp max_abs_err, Tp max_rel_err, int max_iter) [inline]
Definition at line 129 of file trapezoid_integral.h.
    {
      trapezoid_integral<Tp, FuncTp>
        trapi(func, a, b, max_abs_err, max_rel_err, max_iter);
      return {trapi(), trapi.abs_error()};
    }
References emsr::trapezoid_integral< Tp, FuncTp >::abs_error().
inv_fast_fourier_transform() [1/3]
template<typename CmplxIter >
void emsr::inv_fast_fourier_transform (const CmplxIter & from, const CmplxIter & to)
Inverse Fast Fourier Transform on input range.
Definition at line 271 of file fourier_transform.tcc.
    {
      using Cmplx = typename CmplxIter::value_type;
      using Tp = typename Cmplx::value_type;
      std::vector<std::complex<Tp>> z(from, to);
      inv_fast_fourier_transform(z);
      std::copy(z.begin(), z.end(), from);
    }
References inv_fast_fourier_transform(), and Tp.
inv_fast_fourier_transform() [2/3]
template<typename Tp >
void emsr::inv_fast_fourier_transform (std::vector< std::complex< Tp >> & z)
Inverse Fast Fourier Transform on complex data.
Definition at line 105 of file fourier_transform.tcc.
    {
      const std::size_t len = z.size();
      if (len % 2 == 1) // Too bad, we're odd.
        discrete_fourier_transform(false, z);
      else // Good, we are even.
        {
          // Let's divide and conquer!
          std::vector<std::complex<Tp>> odd;
          std::vector<std::complex<Tp>> even;
          const auto halflen = len / 2;
          odd.reserve(halflen);
          even.reserve(halflen);
          for (auto run = z.cbegin(); run != z.cend(); ++run)
            {
              even.push_back(*run);
              ++run;
              odd.push_back(*run);
            }
          inv_fast_fourier_transform(even);
          inv_fast_fourier_transform(odd);
          phase_iterator omega_iter(Tp{-1}, 1, len);
          for (std::size_t i = 0, j = halflen; i < halflen;
                ++i, ++j, ++omega_iter)
            {
              z[i] = even[i] + *omega_iter * odd[i];
              // The next line works because omega^(length/2) = -1.
              z[j] = even[i] - *omega_iter * odd[i];
            }
        }
    }
References discrete_fourier_transform(), and Tp.
Referenced by inv_fast_fourier_transform().
inv_fast_fourier_transform() [3/3]
template<typename Tp >
void emsr::inv_fast_fourier_transform (std::vector< Tp > & x)
Inverse Fast Fourier Transform on real data.
Definition at line 177 of file fourier_transform.tcc.
    {
      const auto len = x.size();
      if (len % 2 == 1) // Too bad, we're odd.
        throw std::domain_error("inv_fast_fourier_transform: "
                                  "Real data must have even length.");
      else // Good, we're even.
        {
          // @todo I really want to just make a view to a complex vector.
          const auto halflen = len / 2;
          std::vector<std::complex<Tp>> z;
          z.reserve(halflen);
          const auto s_i2 = std::complex<Tp>{0, 2};
          phase_iterator omega_iter(Tp{-1}, 1, halflen);
          for (std::size_t i = 0; i < halflen; ++i)
            {
              const auto z1 = std::complex<Tp>(x[2 * i], x[2 * i + 1]);
              const auto z2 = std::complex<Tp>(x[len - 2 * i - 2], -x[len - 2 * i - 1]);
              const auto ze = (z1 + z2) / Tp{2};
              const auto zo = -*omega_iter * (z1 - z2) / s_i2;
              z.emplace_back(ze + zo);
            }
          inv_fast_fourier_transform(z);
          for (std::size_t i = 0; i < halflen; ++i)
            {
              x[2 * i] = z[i].real();
              x[2 * i + 1] = z[i].imag();
            }
        }
    }
References inv_fast_fourier_transform(), and Tp.
inv_fast_sine_transform()
template<typename Tp >
void emsr::inv_fast_sine_transform (std::vector< Tp > & x)
Fast Sine Transform on real data.
Definition at line 244 of file fourier_transform.tcc.
    {
      fast_sine_transform(x);
      const auto norm = Tp{2} / x.size();
      for (std::size_t i = 0; i < x.size(); ++i)
        x[i] *= norm;
    }
References fast_sine_transform(), and Tp.
operator<()
template<typename Tp , typename RetTp >
bool emsr::operator< (const cquad_interval< Tp, RetTp > & ivl, const cquad_interval< Tp, RetTp > & ivr)
Comparison of cquad intervals.
Definition at line 58 of file cquad_workspace.h.
    { return ivl.m_abs_error < ivr.m_abs_error; }
References emsr::cquad_interval< Tp, RetTp >::m_abs_error.
operator<<()
template<typename Tp , typename RetTp >
std::ostream & emsr::operator<< (std::ostream & out, const integration_workspace< Tp, RetTp > & ws)
Output the integration workspace to a stream.
Definition at line 142 of file integration_workspace.tcc.
    {
      auto w = out.width();
      out << std::setw(0);
      out << ' ' << std::setw(2) << ws.max_depth() << '\n';
      out << ' ' << std::setw(2) << ws.curr_index() << '\n';
      for (const auto& seg : ws.intervals())
        out << ' ' << std::setw(2) << seg.depth
              << ' ' << std::setw(w) << seg.lower_lim
              << ' ' << std::setw(w) << seg.upper_lim
              << ' ' << std::setw(w) << seg.result
              << ' ' << std::setw(w) << seg.abs_error
              << '\n';
      return out;
    }
References emsr::integration_workspace< Tp, RetTp >::curr_index(), emsr::integration_workspace< Tp, RetTp >::intervals(), and emsr::integration_workspace< Tp, RetTp >::max_depth().
qag_integrate()
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto emsr::qag_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err, Integrator quad = gauss_kronrod_integral<Tp>(Kronrod_21)) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
Integrates a function from finite a to finite b using an adaptive quadrature rule. The integration domain is recursively subdivided prioritized by the segment with the greatest absolute error estimate. Subdivision continues until a prescribed error target is reached or until a maximum number of divisions is performed.
Once either the absolute or relative error limit is reached, qag_integrate() returns
Template Parameters
FuncTp A function type that takes a single real scalar argument and returns a real scalar.
Tp A real type for the limits of integration and the step.
Integrator A non-adaptive integrator that is able to return an error estimate in addition to the result.
Parameters
 in workspace The workspace that manages adaptive quadrature
 in func The single-variable function to be integrated
 in lower The lower limit of integration
 in upper The upper limit of integration
 in max_abs_err The limit on absolute error
 in max_rel_err The limit on relative error
 in quad The quadrature stepper taking a function object and two integration limits
Returns
A tuple with the first value being the integration result, and the second value being the estimated error.
Definition at line 70 of file qag_integrate.tcc.
    {
      const auto max_iter = workspace.capacity();
      // Try to adjust tests for varing precision.
      const auto s_rel_err = std::pow(Tp{10},
                                 -std::numeric_limits<Tp>::digits / Tp{10});
      if (!valid_tolerances(max_abs_err, max_rel_err))
        {
          std::ostringstream msg;
          msg << "qag_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << max_abs_err << ") and relative ("
                << max_rel_err << ") error limits.";
          throw std::runtime_error(msg.str().c_str());
        }
      auto [result0, abserr0, resabs0, resasc0]
        = quad(func, lower, upper);
      auto tolerance = std::max(max_abs_err, max_rel_err * std::abs(result0));
      // Compute roundoff tolerance.
      const auto round_off = Tp{10} * tolerance * resabs0;
      if (abserr0 <= round_off && abserr0 > tolerance)
        throw integration_error("qag_integrate: "
                                "Cannot reach tolerance because "
                                "of roundoff error on first attempt",
                                ROUNDOFF_ERROR, result0, abserr0);
      else if ((abserr0 <= tolerance && abserr0 != resasc0)
                || abserr0 == Tp{0})
        return {result0, abserr0};
      else if (max_iter == 1)
        throw integration_error("qag_integrate: "
                                "A maximum of one iteration was insufficient",
                                MAX_ITER_ERROR, result0, abserr0);
      workspace.clear();
      workspace.append(lower, upper, result0, abserr0);
      auto area = result0;
      auto errsum = abserr0;
      int error_type = NO_ERROR;
      std::size_t iteration = 1;
      int roundoff_type1 = 0, roundoff_type2 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate
          const auto& curr = workspace.retrieve();
          const auto a1 = curr.lower_lim;
          const auto mid = (curr.lower_lim + curr.upper_lim) / Tp{2};
          const auto a2 = mid;
          const auto b2 = curr.upper_lim;
          auto [area1, error1, resabs1, resasc1]
            = quad(func, a1, mid);
          auto [area2, error2, resabs2, resasc2]
            = quad(func, a2, b2);
          const auto area12 = area1 + area2;
          const auto error12 = error1 + error2;
          const auto delta = area12 - curr.result;
          area += delta;
          errsum += error12 - curr.abs_error;
          tolerance = std::max(max_abs_err,
                                 max_rel_err * std::abs(area));
          if (resasc1 != error1 && resasc2 != error2)
            {
              if (std::abs(delta) <= s_rel_err * std::abs(area12)
                  && error12 >= Tp{0.99} * curr.abs_error)
                ++roundoff_type1;
              if (iteration >= 10 && error12 > curr.abs_error)
                ++roundoff_type2;
            }
          if (errsum > tolerance)
            {
              if (roundoff_type1 >= 6 || roundoff_type2 >= 20)
                error_type = ROUNDOFF_ERROR;
              // Set error flag in the case of bad integrand behaviour at
              // a point of the integration range.
              if (workspace.subinterval_too_small(a1, a2, b2))
                error_type = SINGULAR_ERROR;
            }
          workspace.split(mid, area1, error1, area2, error2);
          ++iteration;
        }
      while (iteration < max_iter
             && !error_type
             && errsum > tolerance);
      auto result = workspace.total_integral();
      auto abserr = errsum;
      if (errsum <= tolerance)
        return {result, abserr};
      if (error_type == NO_ERROR && iteration >= max_iter)
        error_type = MAX_ITER_ERROR;
      check_error(__func__, error_type, result, abserr);
      throw integration_error("qag_integrate: Unknown error.",
                              UNKNOWN_ERROR, result, abserr);
    }
References check_error(), MAX_ITER_ERROR, NO_ERROR, ROUNDOFF_ERROR, SINGULAR_ERROR, Tp, UNKNOWN_ERROR, and valid_tolerances().
qagi_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qagi_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, FuncTp func, Tp max_abs_err, Tp max_rel_err) -> adaptive_integral_t<Tp, decltype(map_minf_pinf<Tp, FuncTp>(func)(Tp{}))>
Integrate a potentially singular function defined over (-\infty, +\infty).
Definition at line 356 of file qags_integrate.tcc.
                                                                          {}))>
    {
      using FuncTp2 = decltype(map_minf_pinf<Tp, FuncTp>(func));
      return qags_integrate<Tp, FuncTp2>(workspace,
                                map_minf_pinf<Tp, FuncTp>(func),
                                Tp{0}, Tp{1}, max_abs_err, max_rel_err);
    }
qagil_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qagil_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, FuncTp func, Tp upper, Tp max_abs_err, Tp max_rel_err) -> adaptive_integral_t<Tp, decltype(map_minf_b<Tp, FuncTp>(func, upper)(Tp{}))>
Integrate a potentially singular function defined over (-\infty, b].
Definition at line 391 of file qags_integrate.tcc.
                                                                              {}))>
    {
      using FuncTp2 = decltype(map_minf_b<Tp, FuncTp>(func, Tp{}));
      return qags_integrate<Tp, FuncTp2>(workspace,
                                map_minf_b<Tp, FuncTp>(func, upper),
                                Tp{0}, Tp{1}, max_abs_err, max_rel_err);
    }
qagis_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qagis_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, FuncTp func, Tp max_abs_err, Tp max_rel_err) -> adaptive_integral_t<Tp, decltype(map_minf_pinf_symm<Tp, FuncTp>(func)(Tp{}))>
Integrate a potentially singular symmetric function defined over (-\infty, +\infty).
Definition at line 374 of file qags_integrate.tcc.
                                                                               {}))>
    {
      using FuncTp2 = decltype(map_minf_pinf_symm<Tp, FuncTp>(func));
      return qags_integrate<Tp, FuncTp2>(workspace,
                                map_minf_pinf_symm<Tp, FuncTp>(func),
                                Tp{0}, Tp{1}, max_abs_err, max_rel_err);
    }
qagiu_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qagiu_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, FuncTp func, Tp lower, Tp max_abs_err, Tp max_rel_err) -> adaptive_integral_t<Tp, decltype(map_a_pinf<Tp, FuncTp>(func, lower)(Tp{}))>
Integrate a potentially singular function defined over [a, +\infty).
Definition at line 408 of file qags_integrate.tcc.
                                                                              {}))>
    {
      using FuncTp2 = decltype(map_a_pinf<Tp, FuncTp>(func, Tp{}));
      return qags_integrate<Tp, FuncTp2>(workspace,
                                map_a_pinf<Tp, FuncTp>(func, lower),
                                Tp{0}, Tp{1}, max_abs_err, max_rel_err);
    }
Referenced by qawf_integrate().
qagp_integrate()
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto emsr::qagp_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, FuncTp func, std::vector< Tp > pts, Tp max_abs_err, Tp max_rel_err, Integrator quad = gauss_kronrod_integral<Tp>(Kronrod_21)) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
Adaptively integrate a function with known singular/discontinuous points.
Template Parameters
FuncTp A function type that takes a single real scalar argument and returns a real scalar.
Tp A real type for the limits of integration and the step.
Integrator A non-adaptive integrator that is able to return an error estimate in addition to the result.
Parameters
 in workspace The workspace that manages adaptive quadrature
 in func The single-variable function to be integrated
 in pts The sorted array of points including the integration limits and intermediate discontinuities/singularities
 in max_abs_err The limit on absolute error
 in max_rel_err The limit on relative error
 in quad The quadrature stepper taking a function object and two integration limits
Definition at line 59 of file qagp_integrate.tcc.
    {
      using AreaTp = std::invoke_result_t<FuncTp, Tp>;
      using AbsAreaTp = decltype(std::abs(AreaTp{}));
      const auto s_max = std::numeric_limits<Tp>::max();
      const auto max_iter = workspace.capacity();
      const auto n_ivals = pts.size() - 1;
      // Try to adjust tests for varing precision.
      const auto s_rel_err = std::pow(Tp{10},
                                 -std::numeric_limits<Tp>::digits / Tp{10});
      bool extrapolate = false;
      bool allow_extrapolation = true;
      if (!valid_tolerances(max_abs_err, max_rel_err))
        {
          std::ostringstream msg;
          msg << "qagp_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << max_abs_err << ") and relative ("
                << max_rel_err << ") error limits.";
          throw std::runtime_error(msg.str().c_str());
        }
      if (pts.size() > workspace.capacity())
        throw std::runtime_error("qagp_integrate: "
                                 "number of points exceeds size of workspace");
      // Check that the integration range and break points
      // are in ascending order.
      if (!std::is_sorted(std::begin(pts), std::end(pts)))
        throw std::runtime_error("qagp_integrate: "
                                   "points are not in an ascending sequence");
      workspace.clear();
      // Perform the first integration.
      auto result0 = Tp{0};
      auto abserr0 = Tp{0};
      auto resabs0 = Tp{0};
      for (std::size_t i = 0; i < n_ivals; ++i)
        {
          const auto lower = pts[i];
          const auto upper = pts[i + 1];
          auto [area0, error0, resabs0, resasc0]
            = quad(func, lower, upper);
          result0 += area0;
          abserr0 += error0;
          resabs0 += resabs0;
          std::size_t level = (error0 == resasc0 && error0 != Tp{0})
                                ? 1 : 0;
          workspace.append(lower, upper, area0, error0, level);
        }
      // Compute the initial error estimate.
      auto errsum = Tp{0};
      for (std::size_t i = 0; i < n_ivals; ++i)
        {
          if (workspace.depth(i) == 1)
            {
              workspace.set_abs_error(i, abserr0);
              workspace.set_depth(i, 0);
            }
          errsum += workspace.abs_error(i);
        }
      // We must re-sort because the errors were reassigned.
      workspace.sort_error();
      auto tolerance = std::max(max_abs_err,
                                  max_rel_err * std::abs(result0));
      // Compute roundoff tolerance.
      const auto round_off = Tp{10} * tolerance * resabs0;
      if (abserr0 <= round_off && abserr0 > tolerance)
        throw integration_error("qagp_integrate: "
                                "Cannot reach tolerance because "
                                "of roundoff error on first attempt",
                                ROUNDOFF_ERROR, result0, abserr0);
      else if (abserr0 <= tolerance)
        return {result0, abserr0};
      else if (max_iter == 1)
        throw integration_error("qagp_integrate: "
                                "A maximum of one iteration was insufficient",
                                MAX_ITER_ERROR, result0, abserr0);
      extrapolation_table<AreaTp, AbsAreaTp> table;
      table.append(result0);
      auto res_ext = result0;
      auto err_ext = s_max;
      auto area = result0;
      auto iteration = n_ivals - 1;
      auto ktmin = 0u;
      auto ertest = tolerance;
      auto error_over_large_intervals = errsum;
      auto reseps = Tp{0}, abseps = Tp{0}, correc = Tp{0};
      int error_type = NO_ERROR, error_type2 = NO_ERROR;
      int roundoff_type1 = 0, roundoff_type2 = 0, roundoff_type3 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& curr = workspace.retrieve();
          const auto current_depth = workspace.curr_depth() + 1;
          const auto a1 = curr.lower_lim;
          const auto mid = (curr.lower_lim + curr.upper_lim) / Tp{2};
          const auto a2 = mid;
          const auto b2 = curr.upper_lim;
          ++iteration;
          auto [area1, error1, resabs1, resasc1]
            = quad(func, a1, mid);
          auto [area2, error2, resabs2, resasc2]
            = quad(func, a2, b2);
          const auto area12 = area1 + area2;
          const auto error12 = error1 + error2;
          const auto last_e_i = curr.abs_error;
          const auto delta = area12 - curr.result;
          // Improve previous approximations to the integral and test for
          // accuracy.
          area += delta;
          errsum += error12 - curr.abs_error;
          tolerance = std::max(max_abs_err,
                                 max_rel_err * std::abs(area));
          if (resasc1 != error1 && resasc2 != error2)
            {
              if (std::abs(delta) <= s_rel_err * std::abs(area12)
                  && error12 >= Tp{0.99} * curr.abs_error)
                {
                  if (!extrapolate)
                    ++roundoff_type1;
                  else
                    ++roundoff_type2;
                }
              if (iteration > 10 && error12 > curr.abs_error)
                ++roundoff_type3;
            }
          // Test for roundoff and eventually set error flag.
          if (roundoff_type1 + roundoff_type2 >= 10
           || roundoff_type3 >= 20)
            error_type = ROUNDOFF_ERROR;
          if (roundoff_type2 >= 5)
            error_type2 = MAX_ITER_ERROR;
          // Set error flag in the case of bad integrand behaviour at
          // a point of the integration range.
          if (workspace.subinterval_too_small(a1, a2, b2))
            error_type = EXTRAP_ROUNDOFF_ERROR;
          // Split the current interval in two.
          workspace.split(mid, area1, error1, area2, error2);
          if (errsum <= tolerance)
            {
              const auto result = workspace.total_integral();
              check_error(__func__, error_type, result, errsum);
              return {result, errsum};
            }
          if (error_type != NO_ERROR)
            break;
          if (iteration >= max_iter - 1)
            {
              error_type = MAX_ITER_ERROR;
              break;
            }
          if (!allow_extrapolation)
            continue;
          error_over_large_intervals -= last_e_i;
          if (current_depth < workspace.max_depth())
            error_over_large_intervals += error12;
          if (!extrapolate)
            {
              // Test whether the interval to be bisected next is the
              // smallest interval.
              if (workspace.large_interval())
                continue;
              else
                {
                  extrapolate = true;
                  workspace.increment_curr_index();
                }
            }
          // The smallest interval has the largest error. Before
          // bisecting decrease the sum of the errors over the larger
          // intervals (error_over_large_intervals) and perform
          // extrapolation.
          if (error_type2 == NO_ERROR
           && error_over_large_intervals > ertest)
            if (workspace.increment_curr_index())
              continue;
          // Perform extrapolation.
          table.append(area);
          if (table.get_nn() < 3)
            {
              workspace.reset_curr_index();
              extrapolate = false;
              error_over_large_intervals = errsum;
              continue;
            }
          std::tie(reseps, abseps) = table.qelg();
          ++ktmin;
          if (ktmin > 5 && err_ext < 0.001 * errsum)
            error_type = DIVERGENCE_ERROR;
          if (abseps < err_ext)
            {
              ktmin = 0;
              err_ext = abseps;
              res_ext = reseps;
              correc = error_over_large_intervals;
              ertest = std::max(max_abs_err,
                                  max_rel_err * std::abs(reseps));
              if (err_ext <= ertest)
                break;
            }
          // Prepare bisection of the smallest interval.
          if (table.get_nn() == 1)
            allow_extrapolation = false;
          if (error_type == DIVERGENCE_ERROR)
            break;
          // Work on interval with largest error.
          workspace.reset_curr_index();
          extrapolate = false;
          error_over_large_intervals = errsum;
        }
      while (iteration < max_iter);
      auto result = res_ext;
      auto abserr = err_ext;
      if (err_ext == s_max)
        {
          const auto result = workspace.total_integral();
          check_error(__func__, error_type, result, errsum);
          return {result, errsum};
        }
      if (error_type != NO_ERROR || error_type2 != NO_ERROR)
        {
          if (error_type2 != NO_ERROR)
            err_ext += correc;
          if (error_type == NO_ERROR)
            error_type = SINGULAR_ERROR;
          if (result != Tp{0} && area != Tp{0})
            {
              if (err_ext / std::abs(res_ext) > errsum / std::abs(area))
                {
                  const auto result = workspace.total_integral();
                  check_error(__func__, error_type, result, errsum);
                  return {result, errsum};
                }
            }
          else if (err_ext > errsum)
            {
              const auto result = workspace.total_integral();
              check_error(__func__, error_type, result, errsum);
              return {result, errsum};
            }
          else if (area == Tp{0})
            {
              check_error(__func__, error_type, result, abserr);
              throw std::runtime_error("qagp_integrate: Unknown error.");
            }
        }
      // Test on divergence.
      auto positive_integrand = test_positivity(result0, resabs0);
      auto max_area = std::max(std::abs(res_ext), std::abs(area));
      if (!positive_integrand && max_area < Tp{0.01} * resabs0)
        {
          check_error(__func__, error_type, result, abserr);
          throw std::runtime_error("qagp_integrate: Unknown error.");
        }
      auto ratio = res_ext / area;
      if (ratio < Tp{0.01} || ratio > Tp{100}
          || errsum > std::abs(area))
        error_type = UNKNOWN_ERROR;
      if (error_type == NO_ERROR)
        return {result, abserr};
      check_error(__func__, error_type, result, abserr);
      throw integration_error("qagp_integrate: Unknown error.",
                              UNKNOWN_ERROR, result, abserr);
    }
References emsr::extrapolation_table< AreaTp, AbsAreaTp >::append(), check_error(), DIVERGENCE_ERROR, EXTRAP_ROUNDOFF_ERROR, emsr::extrapolation_table< AreaTp, AbsAreaTp >::get_nn(), MAX_ITER_ERROR, NO_ERROR, emsr::extrapolation_table< AreaTp, AbsAreaTp >::qelg(), ROUNDOFF_ERROR, SINGULAR_ERROR, test_positivity(), Tp, UNKNOWN_ERROR, and valid_tolerances().
qags_integrate()
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto emsr::qags_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err, Integrator quad = gauss_kronrod_integral<Tp>(Kronrod_15)) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
Adaptively integrate a potentially singular function from a to b using a recursive Gauss-Kronrod algorithm.
Template Parameters
FuncTp A function type that takes a single real scalar argument and returns a real scalar.
Tp A real type for the limits of integration and the step.
Integrator A non-adaptive integrator that is able to return an error estimate in addition to the result.
Parameters
 in workspace The workspace that manages adaptive quadrature
 in func The single-variable function to be integrated
 in pts The sorted array of points including the integration limits and intermediate discontinuities/singularities
 in max_abs_err The limit on absolute error
 in max_rel_err The limit on relative error
 in quad The quadrature stepper taking a function object and two integration limits
Definition at line 65 of file qags_integrate.tcc.
    {
      using AreaTp = std::invoke_result_t<FuncTp, Tp>;
      using AbsAreaTp = decltype(std::abs(AreaTp{}));
      const auto s_max = std::numeric_limits<Tp>::max();
      const auto max_iter = workspace.capacity();
      // Try to adjust tests for varing precision.
      const auto s_rel_err = std::pow(Tp{10},
                                 -std::numeric_limits<Tp>::digits / Tp{10});
      bool extrapolate = false;
      bool allow_extrapolation = true;
      if (!valid_tolerances(max_abs_err, max_rel_err))
        {
          std::ostringstream msg;
          msg << "qags_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << max_abs_err << ") and relative ("
                << max_rel_err << ") error limits.";
          throw std::runtime_error(msg.str().c_str());
        }
      workspace.clear();
      // Perform the first integration.
      auto [result0, abserr0, resabs0, resasc0]
        = quad(func, lower, upper);
      workspace.append(lower, upper, result0, abserr0);
      auto tolerance = std::max(max_abs_err,
                                  max_rel_err * std::abs(result0));
      // Compute roundoff tolerance.
      const auto round_off = Tp{10} * tolerance * resabs0;
      if (abserr0 <= round_off && abserr0 > tolerance)
        throw integration_error("qags_integrate: "
                                "Cannot reach tolerance because "
                                "of roundoff error on first attempt",
                                ROUNDOFF_ERROR, result0, abserr0);
      else if ((abserr0 <= tolerance && abserr0 != resasc0)
                || abserr0 == Tp{0})
        return {result0, abserr0};
      else if (max_iter == 1)
        throw integration_error("qags_integrate: "
                                "A maximum of one iteration was insufficient",
                                MAX_ITER_ERROR, result0, abserr0);
      extrapolation_table<AreaTp, AbsAreaTp> table;
      table.append(result0);
      auto res_ext = result0;
      auto err_ext = s_max;
      auto area = result0;
      auto errsum = abserr0;
      auto iteration = 1u;
      auto ktmin = 0u;
      auto ertest = Tp{0};
      auto error_over_large_intervals = Tp{0};
      auto reseps = AreaTp{0}, abseps = AbsAreaTp{0}, correc = AbsAreaTp{0};
      int error_type = NO_ERROR, error_type2 = NO_ERROR;
      int roundoff_type1 = 0, roundoff_type2 = 0, roundoff_type3 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& curr = workspace.retrieve();
          const auto current_depth = workspace.curr_depth() + 1;
          const auto a1 = curr.lower_lim;
          const auto mid = (curr.lower_lim + curr.upper_lim) / Tp{2};
          const auto a2 = mid;
          const auto b2 = curr.upper_lim;
          ++iteration;
          auto [area1, error1, resabs1, resasc1]
            = quad(func, a1, mid);
          auto [area2, error2, resabs2, resasc2]
            = quad(func, a2, b2);
          const auto area12 = area1 + area2;
          const auto error12 = error1 + error2;
          const auto last_e_i = curr.abs_error;
          const auto delta = area12 - curr.result;
          // Improve previous approximations to the integral and test for
          // accuracy.
          area += delta;
          errsum += error12 - curr.abs_error;
          tolerance = std::max(max_abs_err,
                                 max_rel_err * std::abs(area));
          if (resasc1 != error1 && resasc2 != error2)
            {
              if (std::abs(delta) <= s_rel_err * std::abs(area12)
                  && error12 >= Tp{0.99} * curr.abs_error)
                {
                  if (!extrapolate)
                    ++roundoff_type1;
                  else
                    ++roundoff_type2;
                }
              if (iteration > 10 && error12 > curr.abs_error)
                ++roundoff_type3;
            }
          // Test for roundoff and eventually set error flag.
          if (roundoff_type1 + roundoff_type2 >= 10
              || roundoff_type3 >= 20)
            error_type = ROUNDOFF_ERROR;
          if (roundoff_type2 >= 5)
            error_type2 = MAX_ITER_ERROR;
          // Set error flag in the case of bad integrand behaviour at
          // a point of the integration range.
          if (workspace.subinterval_too_small(a1, a2, b2))
            error_type = EXTRAP_ROUNDOFF_ERROR;
          // Split the current interval in two.
          workspace.split(mid, area1, error1, area2, error2);
          if (errsum <= tolerance)
            {
              const auto result = workspace.total_integral();
              check_error(__func__, error_type, result, errsum);
              return {result, errsum};
            }
          if (error_type != NO_ERROR)
            break;
          if (iteration >= max_iter - 1)
            {
              error_type = MAX_ITER_ERROR;
              break;
            }
          if (iteration == 2) // Set up variables on first iteration.
            {
              error_over_large_intervals = errsum;
              ertest = tolerance;
              table.append(area);
              continue;
            }
          if (!allow_extrapolation)
            continue;
          error_over_large_intervals -= last_e_i;
          if (current_depth < workspace.max_depth())
            error_over_large_intervals += error12;
          if (!extrapolate)
            {
              // Test whether the interval to be bisected next is the
              // smallest interval.
              if (workspace.large_interval())
                continue;
              else
                {
                  extrapolate = true;
                  workspace.increment_curr_index();
                }
            }
          // The smallest interval has the largest error. Before
          // bisecting decrease the sum of the errors over the larger
          // intervals (error_over_large_intervals) and perform
          // extrapolation.
          if (error_type2 == NO_ERROR
              && error_over_large_intervals > ertest)
            if (workspace.increment_curr_index())
              continue;
          // Perform extrapolation.
          table.append(area);
          std::tie(reseps, abseps) = table.qelg();
          ++ktmin;
          if (ktmin > 5 && err_ext < 0.001 * errsum)
            error_type = DIVERGENCE_ERROR;
          if (abseps < err_ext)
            {
              ktmin = 0;
              err_ext = abseps;
              res_ext = reseps;
              correc = error_over_large_intervals;
              ertest = std::max(max_abs_err,
                                  max_rel_err * std::abs(reseps));
              if (err_ext <= ertest)
                break;
            }
          // Prepare bisection of the smallest interval.
          if (table.get_nn() == 1)
            allow_extrapolation = false;
          if (error_type == DIVERGENCE_ERROR)
            break;
          // Work on interval with largest error.
          workspace.reset_curr_index();
          extrapolate = false;
          error_over_large_intervals = errsum;
        }
      while (iteration < max_iter);
      auto result = res_ext;
      auto abserr = err_ext;
      if (err_ext == s_max)
        {
          const auto result = workspace.total_integral();
          check_error(__func__, error_type, result, errsum);
          return {result, errsum};
        }
      if (error_type != NO_ERROR || error_type2 != NO_ERROR)
        {
          if (error_type2 != NO_ERROR)
            err_ext += correc;
          if (error_type == NO_ERROR)
            error_type = SINGULAR_ERROR;
          if (res_ext != Tp{0} && area != Tp{0})
            {
              if (err_ext / std::abs(res_ext) > errsum / std::abs(area))
                {
                  const auto result = workspace.total_integral();
                  check_error(__func__, error_type, result, errsum);
                  return {result, errsum};
                }
            }
          else if (err_ext > errsum)
            {
              const auto result = workspace.total_integral();
              check_error(__func__, error_type, result, errsum);
              return {result, errsum};
            }
          else if (area == Tp{0})
            {
              check_error(__func__, error_type, result, errsum);
              throw std::runtime_error("qags_integrate: Unknown error.");
            }
        }
      // Test on divergence.
      auto positive_integrand = test_positivity(result0, resabs0);
      auto max_area = std::max(std::abs(res_ext), std::abs(area));
      if (!positive_integrand && max_area < Tp{0.01} * resabs0)
        {
          check_error(__func__, error_type, area, errsum);
          throw std::runtime_error("qags_integrate: Unknown error.");
        }
      auto ratio = std::abs(res_ext / area); // FIXME: Added abs for complex type issues.
      if (ratio < Tp{0.01} || ratio > Tp{100}
          || errsum > std::abs(area))
        error_type = UNKNOWN_ERROR;
      if (error_type == NO_ERROR)
        return {result, abserr};
      check_error(__func__, error_type, decltype(result)(), decltype(abserr)());
      throw integration_error("qags_integrate: Unknown error.",
                              UNKNOWN_ERROR, result, abserr);
    }
References emsr::extrapolation_table< AreaTp, AbsAreaTp >::append(), check_error(), DIVERGENCE_ERROR, EXTRAP_ROUNDOFF_ERROR, emsr::extrapolation_table< AreaTp, AbsAreaTp >::get_nn(), MAX_ITER_ERROR, NO_ERROR, emsr::extrapolation_table< AreaTp, AbsAreaTp >::qelg(), ROUNDOFF_ERROR, SINGULAR_ERROR, test_positivity(), Tp, UNKNOWN_ERROR, and valid_tolerances().
qawc_integrate()
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto emsr::qawc_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, FuncTp func, Tp lower, Tp upper, Tp center, Tp max_abs_err, Tp max_rel_err, Integrator quad = gauss_kronrod_integral<Tp>(Kronrod_15)) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
Adaptive integration for Cauchy principal values:
 I = \int_a^b dx f(x) / (x - c) 
 The adaptive bisection algorithm of QAG is used, with modifications to ensure that subdivisions do not occur at the singular point x = c. When a subinterval contains the point x = c or is close to it then a special 25-point modified Clenshaw-Curtis rule is used to control the singularity. Further away from the singularity the algorithm uses a user-supplied integration rule (default 15-point Gauss-Kronrod).
Definition at line 61 of file qawc_integrate.tcc.
    {
      using RetTp = std::invoke_result_t<FuncTp, Tp>;
      using AreaTp = decltype(RetTp{} * Tp{});
      using AbsAreaTp = decltype(std::abs(AreaTp{}));
      auto result = AreaTp{};
      auto abserr = AbsAreaTp{};
      const auto limit = workspace.capacity();
      // Try to adjust tests for varing precision.
      const auto m_rel_err = std::pow(Tp{10.0},
                                 -std::numeric_limits<Tp>::digits / Tp{10.0});
      int sign = 1;
      if (upper < lower)
        {
          std::swap(lower, upper);
          sign = -1;
        }
      if (!valid_tolerances(max_abs_err, max_rel_err))
        {
          std::ostringstream msg;
          msg << "qawc_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << max_abs_err << ") and relative ("
                << max_rel_err << ") error limits.";
          throw std::runtime_error(msg.str().c_str());
        }
      if (center == lower || center == upper)
        throw std::runtime_error ("qawc_integrate: "
                                    "Cannot integrate with singularity "
                                    "on endpoint.");
      workspace.clear();
      // Perform the first integration.
      auto [result0, abserr0, err_reliable]
        = qc25c(func, lower, upper, center, quad);
      workspace.append(lower, upper, result0, abserr0);
      // Test on accuracy; Use 0.01 relative error as an extra safety
      // margin on the first iteration (ignored for subsequent iterations).
      auto tolerance = std::max(max_abs_err,
                                  max_rel_err * std::abs(result0));
      if (abserr0 < tolerance && abserr0
          < Tp{0.01} * std::abs(result0))
        return {sign * result0, abserr0};
      else if (limit == 1)
        throw integration_error("qawc_integrate: "
                                "A maximum of one iteration was insufficient",
                                MAX_ITER_ERROR, sign * result0, abserr0);
      auto area = result0;
      auto errsum = abserr0;
      auto iteration = 1u;
      int error_type = NO_ERROR;
      int roundoff_type1 = 0, roundoff_type2 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& curr = workspace.retrieve();
          const auto a1 = curr.lower_lim;
          const auto b2 = curr.upper_lim;
          auto mid = (curr.lower_lim + curr.upper_lim) / Tp{2};
          if (center > a1 && center <= mid)
            mid = (center + b2) / Tp{2};
          else if (center > mid && center < b2)
            mid = (a1 + center) / Tp{2};
          const auto a2 = mid;
          auto [area1, error1, err_reliable1]
            = qc25c(func, a1, mid, center, quad);
          auto [area2, error2, err_reliable2]
            = qc25c(func, a2, b2, center, quad);
          const auto area12 = area1 + area2;
          const auto error12 = error1 + error2;
          errsum += error12 - curr.abs_error;
          area += area12 - curr.result;
          if (err_reliable1 && err_reliable2)
            {
              const auto delta = curr.result - area12;
              if (std::abs (delta) <= m_rel_err * std::abs (area12)
                   && error12 >= 0.99 * curr.abs_error)
                ++roundoff_type1;
              if (iteration >= 10 && error12 > curr.abs_error)
                ++roundoff_type2;
            }
          tolerance = std::max(max_abs_err, max_rel_err * std::abs(area));
          if (errsum > tolerance)
            {
              if (roundoff_type1 >= 6 || roundoff_type2 >= 20)
                error_type = ROUNDOFF_ERROR;
              // set error flag in the case of bad integrand behaviour at
              // a point of the integration range
              if (workspace.subinterval_too_small(a1, a2, b2))
                error_type = SINGULAR_ERROR;
            }
          workspace.split(mid, area1, error1, area2, error2);
          ++iteration;
        }
      while (iteration < limit && !error_type && errsum > tolerance);
      result = sign * workspace.total_integral();
      abserr = errsum;
      if (iteration == limit)
        error_type = MAX_SUBDIV_ERROR;
      if (errsum <= tolerance)
        return {result, abserr};
      if (error_type == NO_ERROR)
        return {result, abserr};
      check_error(__func__, error_type, result, abserr);
      throw integration_error("qawc_integrate: Unknown error.",
                              UNKNOWN_ERROR, result, abserr);
    }
References check_error(), MAX_ITER_ERROR, MAX_SUBDIV_ERROR, NO_ERROR, qc25c(), ROUNDOFF_ERROR, SINGULAR_ERROR, Tp, UNKNOWN_ERROR, and valid_tolerances().
qawf_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qawf_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & cycle_workspace, oscillatory_integration_table< Tp > & wf, FuncTp func, Tp lower, Tp max_abs_err) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
This function attempts to compute a Fourier integral of the function f over the semi-infinite interval [a,+\infty)
Definition at line 44 of file qawf_integrate.tcc.
    {
      using AreaTp = std::invoke_result_t<FuncTp, Tp>;
      using AbsAreaTp = decltype(std::abs(AreaTp{}));
      std::size_t ktmin = 0;
      std::size_t iteration = 0;
      extrapolation_table<AreaTp, AbsAreaTp> table;
      Tp cycle;
      auto omega = wf.omega;
      const Tp p = 0.9;
      Tp factor = 1;
      Tp initial_eps, eps;
      int error_type = NO_ERROR;
      int status = 0;
      auto result = Tp{0};
      auto abserr = Tp{0};
      const auto s_max = std::numeric_limits<Tp>::max();
      const auto limit = workspace.capacity();
      workspace.clear();
      cycle_workspace.clear();
      //wf.clear();
      // Test on accuracy.
      if (max_abs_err <= Tp{0})
        throw std::domain_error("absolute tolerance epsabs must be positive") ;
      if (omega == Tp{0})
        {
          if (wf.circfun == oscillatory_integration_table<Tp>::INTEG_SINE)
            // The function sin(w x) f(x) is always zero for w = 0.
            return {Tp{0}, Tp{0}};
          else
            // The function cos(w x) f(x) is always f(x) for w = 0.
            return qagiu_integrate(cycle_workspace, func, lower, max_abs_err,
                                   Tp{0});
        }
      if (max_abs_err * (Tp{1} - p) > std::numeric_limits<Tp>::min())
        eps = max_abs_err * (Tp{1} - p);
      else
        eps = max_abs_err;
      initial_eps = eps;
      auto area = Tp{0};
      auto errsum = Tp{0};
      auto res_ext = Tp{0};
      auto err_ext = s_max;
      auto correc = Tp{0};
      auto total_error = Tp{0};
      auto truncation_error = Tp{0};
      cycle = (2 * std::floor(std::abs(omega)) + 1)
              * M_PI / std::abs(omega);
      wf.set_length(cycle);
      for (iteration = 0; iteration < limit; ++iteration)
        {
          const auto a1 = lower + iteration * cycle;
          const auto b1 = a1 + cycle;
          const auto max_abs_err1 = eps * factor;
          auto out1 = qawo_integrate(cycle_workspace, wf, func, a1,
                             max_abs_err1, Tp{0});
          auto area1 = out1.result;
          auto error1 = out1.abserr;
          workspace.append(a1, b1, area1, error1);
          factor *= p;
          area += area1;
          errsum += error1;
          // Estimate the truncation error as 50 times the final term.
          truncation_error = 50 * std::abs(area1);
          total_error = errsum + truncation_error;
          if (total_error < max_abs_err && iteration > 4)
            goto compute_result;
          if (error1 > correc)
            correc = error1;
          if (status)
            eps = std::max(initial_eps, correc * (Tp{1} - p));
          if (status && total_error < 10 * correc && iteration > 3)
            goto compute_result;
          table.append(area);
          if (table.get_nn() < 2)
            continue;
          Tp reseps, erreps;
          std::tie(reseps, erreps) = table.qelg();
          ++ktmin;
          if (ktmin >= 15 && err_ext < Tp{0.001L} * total_error)
            error_type = EXTRAP_ROUNDOFF_ERROR;
          if (erreps < err_ext)
            {
              ktmin = 0;
              err_ext = erreps;
              res_ext = reseps;
              if (err_ext + 10 * correc <= max_abs_err)
                break;
              if (err_ext <= max_abs_err && 10 * correc >= max_abs_err)
                break;
            }
        }
      if (iteration == limit)
        error_type = MAX_ITER_ERROR;
      if (err_ext == s_max)
        goto compute_result;
      err_ext += 10 * correc;
      result = res_ext;
      abserr = err_ext;
      if (error_type == NO_ERROR)
        return {result, abserr};
      if (res_ext != Tp{0} && area != Tp{0})
        {
          if (err_ext / std::abs(res_ext) > errsum / std::abs(area))
            goto compute_result;
        }
      else if (err_ext > errsum)
        goto compute_result;
      else if (area == Tp{0})
        goto return_error;
      if (error_type == EXTRAP_ROUNDOFF_ERROR)
        err_ext += truncation_error;
      goto return_error;
    compute_result:
      result = area;
      abserr = total_error;
      if (error_type == NO_ERROR)
        return {result, abserr};
    return_error:
      check_error(__func__, error_type, result, abserr);
      throw integration_error("qawf_integrate: Unknown error.", UNKNOWN_ERROR,
                              result, abserr);
    }
References emsr::extrapolation_table< AreaTp, AbsAreaTp >::append(), check_error(), compute_result(), EXTRAP_ROUNDOFF_ERROR, emsr::extrapolation_table< AreaTp, AbsAreaTp >::get_nn(), MAX_ITER_ERROR, NO_ERROR, qagiu_integrate(), qawo_integrate(), emsr::extrapolation_table< AreaTp, AbsAreaTp >::qelg(), Tp, and UNKNOWN_ERROR.
qawo_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qawo_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, oscillatory_integration_table< Tp > & wf, FuncTp func, const Tp lower, const Tp max_abs_err, const Tp max_rel_err) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
Definition at line 46 of file qawo_integrate.tcc.
    {
      using AreaTp = std::invoke_result_t<FuncTp, Tp>;
      using AbsAreaTp = decltype(std::abs(AreaTp{}));
      const auto s_max = std::numeric_limits<Tp>::max();
      const auto s_eps = std::numeric_limits<Tp>::epsilon();
      const auto limit = workspace.capacity();
      // Try to adjust tests for varing precision. 10^{-5.3} for double.
      const auto s_rel_err = std::pow(Tp{10},
                                 -std::numeric_limits<Tp>::digits / Tp{10});
      bool extrapolate = false;
      bool extall = false;
      bool allow_extrapolation = true;
      workspace.clear();
      //wf.clear();
      extrapolation_table<AreaTp, AbsAreaTp> table;
      const auto upper = lower + wf.get_length();
      const auto abs_omega = std::abs(wf.omega);
      auto result = Tp{0};
      auto abserr = Tp{0};
      if (!valid_tolerances(max_abs_err, max_rel_err))
        {
          std::ostringstream msg;
          msg << "qawo_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << max_abs_err << ") and relative ("
                << max_rel_err << ") error limits.";
          throw std::runtime_error(msg.str().c_str());
        }
      // Perform the first integration.
      auto [result0, abserr0, resabs0, resasc0]
        = qc25f(wf, func, lower, upper, 0);
      workspace.append(lower, upper, result0, abserr0);
      auto tolerance = std::max(max_abs_err,
                                  max_rel_err * std::abs(result0));
      if (abserr0 <= Tp{100} * s_eps * resabs0
          && abserr0 > tolerance)
        throw integration_error("qawo_integrate: "
                                "Cannot reach tolerance because "
                                "of roundoff error on first attempt",
                                ROUNDOFF_ERROR, result0, abserr0);
      else if ((abserr0 <= tolerance && abserr0 != resasc0)
                || abserr0 == Tp{0})
        return {result0, abserr0};
      else if (limit == 1)
        throw integration_error("qawo_integrate: "
                                "A maximum of one iteration was insufficient",
                                MAX_ITER_ERROR, result0, abserr0);
      if (0.5 * abs_omega * std::abs(upper - lower) <= Tp{2})
        {
          table.append(result0);
          extall = true;
        }
      auto res_ext = result0;
      auto err_ext = s_max;
      auto area = result0;
      auto errsum = abserr0;
      auto iteration = 1u;
      auto ktmin = 0u;
      auto ertest = Tp{0};
      auto error_over_large_intervals = Tp{0};
      auto correc = Tp{0};
      int roundoff_type1 = 0, roundoff_type2 = 0, roundoff_type3 = 0;
      int error_type = NO_ERROR, error_type2 = NO_ERROR;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& curr = workspace.retrieve();
          const auto current_depth = workspace.curr_depth() + 1;
          if (current_depth >= wf.n)
            {
              error_type = -1; // exceeded limit of table.
              break;
            }
          const auto a1 = curr.lower_lim;
          const auto mid = (curr.lower_lim + curr.upper_lim) / Tp{2};
          const auto a2 = mid;
          const auto b2 = curr.upper_lim;
          ++iteration;
          auto [area1, error1, resabs1, resasc1]
            = qc25f(wf, func, a1, mid, current_depth);
          auto [area2, error2, resabs2, resasc2]
            = qc25f(wf, func, a2, b2, current_depth);
          const auto area12 = area1 + area2;
          const auto error12 = error1 + error2;
          const auto last_e_i = curr.abs_error;
          // Improve previous approximations to the integral and test
          // for accuracy.
          area += area12 - curr.result;
          errsum += error12 - curr.abs_error;
          tolerance = std::max(max_abs_err,
                                 max_rel_err * std::abs(area));
          if (resasc1 != error1 && resasc2 != error2)
            {
              const auto delta = curr.result - area12;
              if (std::abs(delta) <= s_rel_err * std::abs(area12)
                         && error12 >= Tp{0.99} * curr.abs_error)
                {
                  if (!extrapolate)
                    ++roundoff_type1;
                  else
                    ++roundoff_type2;
                }
              if (iteration > 10 && error12 > curr.abs_error)
                ++roundoff_type3;
            }
          // Test for roundoff and eventually set error flag.
          if (roundoff_type1 + roundoff_type2 >= 10
           || roundoff_type3 >= 20)
            error_type = ROUNDOFF_ERROR;
          if (roundoff_type2 >= 5)
            error_type2 = MAX_ITER_ERROR;
          // Set error flag in the case of bad integrand behaviour at
          // a point of the integration range.
          if (workspace.subinterval_too_small(a1, a2, b2))
            error_type = EXTRAP_ROUNDOFF_ERROR;
          // Split the current interval in two.
          workspace.split(mid, area1, error1, area2, error2);
          if (errsum <= tolerance)
            {
              result = workspace.total_integral();
              abserr = errsum;
              check_error(__func__, error_type, result, abserr);
              return {result, abserr};
            }
          if (error_type != NO_ERROR)
            break;
          if (iteration >= limit - 1)
            {
              error_type = MAX_ITER_ERROR;
              break;
            }
          // Set up variables on first iteration.
          if (iteration == 2 && extall)
            {
              error_over_large_intervals = errsum;
              ertest = tolerance;
              table.append(area);
              continue;
            }
          if (!allow_extrapolation)
            continue;
          if (extall)
            {
              error_over_large_intervals -= last_e_i;
              if (current_depth < workspace.max_depth())
                error_over_large_intervals += error12;
              if (extrapolate)
                if (error_type2 != NO_ERROR
                 && error_over_large_intervals > ertest)
                  if (workspace.increment_curr_index())
                    continue;
            }
          if (workspace.large_interval())
            continue;
          if (extall)
            {
              extrapolate = true;
              workspace.increment_curr_index();
            }
          else
            {
              // Test whether the interval to be bisected next is the
              // smallest interval.
              auto width = workspace.upper_lim() - workspace.lower_lim();
              if (0.25 * std::abs(width) * abs_omega > Tp{2})
                continue;
              extall = true;
              error_over_large_intervals = errsum;
              ertest = tolerance;
              continue;
            }
          if (error_type2 != NO_ERROR
           && error_over_large_intervals > ertest)
            if (workspace.increment_curr_index())
              continue;
          // Perform extrapolation.
          table.append(area);
          if (table.get_nn() < 3)
            {
              workspace.reset_curr_index();
              extrapolate = false;
              error_over_large_intervals = errsum;
              continue;
            }
          Tp reseps, abseps;
          std::tie(reseps, abseps) = table.qelg();
          ++ktmin;
          if (ktmin > 5 && err_ext < 0.001 * errsum)
            error_type = DIVERGENCE_ERROR;
          if (abseps < err_ext)
            {
              ktmin = 0;
              err_ext = abseps;
              res_ext = reseps;
              correc = error_over_large_intervals;
              ertest = std::max(max_abs_err, max_rel_err * std::abs(reseps));
              if (err_ext <= ertest)
                break;
            }
          // Prepare bisection of the smallest interval.
          if (table.get_nn() == 1)
            allow_extrapolation = false;
          if (error_type == DIVERGENCE_ERROR)
            break;
          // Work on interval with largest error.
          workspace.reset_curr_index();
          extrapolate = false;
          error_over_large_intervals = errsum;
        }
      while (iteration < limit);
      result = res_ext;
      abserr = err_ext;
      if (err_ext == s_max)
        {
          result = workspace.total_integral();
          abserr = errsum;
          check_error(__func__, error_type, result, abserr);
          return {result, abserr};
        }
      if (error_type != NO_ERROR || error_type2 != NO_ERROR)
        {
          if (error_type2 != NO_ERROR)
            err_ext += correc;
          if (error_type == NO_ERROR)
            error_type = SINGULAR_ERROR;
          if (result != 0 && area != 0)
            {
              if (err_ext / std::abs(res_ext) > errsum / std::abs(area))
                {
                  result = workspace.total_integral();
                  abserr = errsum;
                  check_error(__func__, error_type, result, abserr);
                  return {result, abserr};
                }
            }
          else if (err_ext > errsum)
            {
              result = workspace.total_integral();
              abserr = errsum;
              check_error(__func__, error_type, result, abserr);
              return {result, abserr};
            }
          else if (area == Tp{0})
            {
              check_error(__func__, error_type, result, abserr);
              return {result, abserr};
            }
        }
      // Test on divergence.
      bool positive_integrand = test_positivity(result0, resabs0);
      auto max_area = std::max(std::abs(res_ext), std::abs(area));
      if (!positive_integrand && max_area < Tp{0.01} * resabs0)
        {
          check_error(__func__, error_type, result, abserr);
          return {result, abserr};
        }
      auto ratio = res_ext / area;
      if (ratio < Tp{0.01} || ratio > Tp{100}
          || errsum > std::abs(area))
        error_type = UNKNOWN_ERROR;
      check_error(__func__, error_type, result, abserr);
      return {result, abserr};
    }
References emsr::extrapolation_table< AreaTp, AbsAreaTp >::append(), check_error(), DIVERGENCE_ERROR, EXTRAP_ROUNDOFF_ERROR, emsr::extrapolation_table< AreaTp, AbsAreaTp >::get_nn(), MAX_ITER_ERROR, NO_ERROR, qc25f(), emsr::extrapolation_table< AreaTp, AbsAreaTp >::qelg(), ROUNDOFF_ERROR, SINGULAR_ERROR, test_positivity(), Tp, UNKNOWN_ERROR, and valid_tolerances().
Referenced by qawf_integrate().
qaws_integrate()
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto emsr::qaws_integrate (integration_workspace< Tp, std::invoke_result_t< FuncTp, Tp >> & workspace, qaws_integration_table< Tp > & table, FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err, Integrator quad = gauss_kronrod_integral<Tp>(Kronrod_15)) -> adaptive_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
The singular weight function is defined by:
 W(x) = (x-a)^\alpha (b-x)^\beta log^\mu (x-a) log^\nu (b-x) 
 where $ \alpha > -1 $, $ \beta > -1 $, and $ \mu = 0 $, 1, $ \nu = 0, 1 $.
The weight function can take four different forms depending on the values of \mu and \nu,
 W(x) = (x-a)^\alpha (b-x)^\beta (\mu = 0, \nu = 0) W(x) = (x-a)^\alpha (b-x)^\beta log(x-a) (\mu = 1, \nu = 0) W(x) = (x-a)^\alpha (b-x)^\beta log(b-x) (\mu = 0, \nu = 1) W(x) = (x-a)^\alpha (b-x)^\beta log(x-a) log(b-x) (\mu = 1, \nu = 1) 
The QAWS algorithm is designed for integrands with algebraic-logarithmic singularities at the end-points of an integration region.
In order to work efficiently the algorithm requires a precomputed table of Chebyshev moments.
Definition at line 88 of file qaws_integrate.tcc.
    {
      // Try to adjust tests for varing precision.
      const auto m_rel_err = std::pow(Tp{10},
                                 -std::numeric_limits<Tp>::digits / Tp{10});
      if (upper <= lower)
        throw std::runtime_error("qaws_integrate: "
                                   "Limits must form an ascending sequence");
      if (!valid_tolerances(max_abs_err, max_rel_err))
        {
          std::ostringstream msg;
          msg << "qaws_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << max_abs_err << ") and relative ("
                << max_rel_err << ") error limits.";
          throw std::runtime_error(msg.str().c_str());
        }
      const auto limit = workspace.capacity();
      workspace.clear();
      // Perform the first integration.
      Tp result0, abserr0;
      {
        const auto a1 = lower;
        const auto mid = (lower + upper) / Tp{2};
        const auto b2 = upper;
        auto [area1, error1, err_reliable1]
          = qc25s(table, func, lower, upper, a1, mid, quad);
        workspace.append(a1, mid, area1, error1);
        auto [area2, error2, err_reliable2]
          = qc25s(table, func, lower, upper, mid, b2, quad);
        workspace.append(mid, b2, area2, error2);
        result0 = area1 + area2;
        abserr0 = error1 + error2;
      }
      // Test on accuracy; Use 0.01 relative error as an extra safety
      // margin on the first iteration (ignored for subsequent iterations).
      auto tolerance = std::max(max_abs_err, max_rel_err * std::abs(result0));
      if (abserr0 < tolerance && abserr0
          < Tp{0.01} * std::abs(result0))
        return {result0, abserr0};
      else if (limit == 1)
        throw integration_error("qaws_integrate: "
                                "A maximum of one iteration was insufficient",
                                MAX_ITER_ERROR, result0, abserr0);
      auto area = result0;
      auto errsum = abserr0;
      auto iteration = 2u;
      int error_type = NO_ERROR;
      int roundoff_type1 = 0, roundoff_type2 = 0;
      do
        {
          // Bisect the subinterval with the largest error estimate.
          const auto& curr = workspace.retrieve();
          const auto a1 = curr.lower_lim;
          const auto mid = (curr.lower_lim + curr.upper_lim) / Tp{2};
          const auto b2 = curr.upper_lim;
          auto [area1, error1, err_reliable1]
            = qc25s(table, func, lower, upper, a1, mid, quad);
          auto [area2, error2, err_reliable2]
            = qc25s(table, func, lower, upper, mid, b2, quad);
          const auto area12 = area1 + area2;
          const auto error12 = error1 + error2;
          errsum += error12 - curr.abs_error;
          area += area12 - curr.result;
          if (err_reliable1 && err_reliable2)
            {
              const auto delta = curr.result - area12;
              if (std::abs (delta) <= m_rel_err * std::abs(area12)
                 && error12 >= 0.99 * curr.abs_error)
                ++roundoff_type1;
              if (iteration >= 10 && error12 > curr.abs_error)
                ++roundoff_type2;
            }
          tolerance = std::max(max_abs_err, max_rel_err * std::abs(area));
          if (errsum > tolerance)
            {
              if (roundoff_type1 >= 6 || roundoff_type2 >= 20)
                error_type = ROUNDOFF_ERROR;
              // set error flag in the case of bad integrand behaviour at
              // a point of the integration range
              if (workspace.subinterval_too_small(a1, mid, b2))
                error_type = SINGULAR_ERROR;
            }
          workspace.split(mid, area1, error1, area2, error2);
          ++iteration;
        }
      while (iteration < limit && !error_type && errsum > tolerance);
      const auto result = workspace.total_integral();
      const auto abserr = errsum;
      if (iteration == limit)
        error_type = MAX_SUBDIV_ERROR;
      if (errsum <= tolerance)
        return {result, abserr};
      if (error_type == NO_ERROR)
        return {result, abserr};
      check_error(__func__, error_type, result, abserr);
      throw integration_error("qaws_integrate: Unknown error.",
                              UNKNOWN_ERROR, result, abserr);
    }
References check_error(), MAX_ITER_ERROR, MAX_SUBDIV_ERROR, NO_ERROR, qc25s(), ROUNDOFF_ERROR, SINGULAR_ERROR, Tp, UNKNOWN_ERROR, and valid_tolerances().
qc25c()
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
auto emsr::qc25c (FuncTp func, Tp lower, Tp upper, Tp center, Integrator quad) -> std::tuple< decltype(Tp{} *func(Tp{})), Tp, bool >
Adaptive integration for Cauchy principal values:
 I = \int_a^b dx f(x) / (x - c) 
 The adaptive bisection algorithm of QAG is used, with modifications to ensure that subdivisions do not occur at the singular point x = c. When a subinterval contains the point x = c or is close to it then a special 25-point modified Clenshaw-Curtis rule is used to control the singularity. Further away from the singularity the algorithm uses a user-supplied integration rule.
Definition at line 214 of file qawc_integrate.tcc.
                           {} * func(Tp{})), Tp, bool>
    {
      using RetTp = std::invoke_result_t<FuncTp, Tp>;
      using AreaTp = decltype(RetTp{} * Tp{});
      using AbsAreaTp = decltype(std::abs(AreaTp{}));
      bool err_reliable;
      auto result = AreaTp{};
      auto abserr = AbsAreaTp{};
      const auto cc = (Tp{2} * center - upper - lower)
                      / (upper - lower);
      if (std::abs(cc) > Tp{1.1})
        {
          auto func_cauchy = [func, center](Tp x)
                                -> Tp
                                { return func(x) / (x - center); };
          auto [result, abserr, resabs, resasc]
            = quad(func_cauchy, lower, upper);
          if (abserr == resasc)
            err_reliable = false;
          else
            err_reliable = true;
          return std::make_tuple(result, abserr, err_reliable);
        }
      else
        {
          auto [cheb12, cheb24] = qcheb_integrate(func, lower, upper);
          const auto moment = compute_moments(cheb24.size(), cc);
          auto res12 = AreaTp{0};
          for (size_t i = 0u; i < cheb12.size(); ++i)
            res12 += cheb12[i] * moment[i];
          auto res24 = AreaTp{0};
          for (size_t i = 0u; i < cheb24.size(); ++i)
            res24 += cheb24[i] * moment[i];
          result = res24;
          abserr = std::abs(res24 - res12);
          err_reliable = false;
          return std::make_tuple(result, abserr, err_reliable);
        }
    }
Referenced by qawc_integrate().
qc25f()
template<typename Tp , typename FuncTp >
auto emsr::qc25f (oscillatory_integration_table< Tp > & wf, FuncTp func, Tp lower, Tp upper, std::size_t depth) -> gauss_kronrod_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
Definition at line 378 of file qawo_integrate.tcc.
    {
      const auto s_max = std::numeric_limits<Tp>::max();
      const auto center = (lower + upper) / Tp{2};
      const auto half_length = (upper - lower) / Tp{2};
      const auto omega = wf.omega;
      const auto par = omega * half_length;
      if (std::abs(par) < Tp{2})
        {
          if (wf.circfun == oscillatory_integration_table<Tp>::INTEG_SINE)
            {
              auto wfun = [func, omega](Tp x)
                            ->Tp
                            { return std::sin(omega * x) * func(x); };
              return qk_integrate(wfun, lower, upper, Kronrod_15);
            }
          else
            {
              auto wfun = [func, omega](Tp x)
                            ->Tp
                            { return std::cos(omega * x) * func(x); };
              return qk_integrate(wfun, lower, upper, Kronrod_15);
            }
        }
      else
        {
          auto chout = qcheb_integrate(func, lower, upper);
          const auto& cheb12 = chout.cheb12;
          const auto& cheb24 = chout.cheb24;
          if (depth >= wf.n)
            {
              // Table overflow should not happen, check before calling.
              throw std::runtime_error("Table overflow in internal function");
            }
          const auto& moment = wf.get_moments(depth);
          auto res12_cos = cheb12[12] * moment[12];
          auto res12_sin = Tp{0};
          for (int i = 0; i < 6; ++i)
            {
              const std::size_t k = 10 - 2 * i;
              res12_cos += cheb12[k] * moment[k];
              res12_sin += cheb12[k + 1] * moment[k + 1];
            }
          auto res24_cos = cheb24[24] * moment[24];
          auto res24_sin = Tp{0};
          auto result_abs = std::abs(cheb24[24]);
          for (int i = 0; i < 12; ++i)
            {
              const std::size_t k = 22 - 2 * i;
              res24_cos += cheb24[k] * moment[k];
              res24_sin += cheb24[k + 1] * moment[k + 1];
              result_abs += std::abs(cheb24[k])
                          + std::abs(cheb24[k + 1]);
            }
          const auto est_cos = std::abs(res24_cos - res12_cos);
          const auto est_sin = std::abs(res24_sin - res12_sin);
          const auto c = half_length * std::cos(center * omega);
          const auto s = half_length * std::sin(center * omega);
          Tp result, abserr, resabs, resasc;
          if (wf.circfun == oscillatory_integration_table<Tp>::INTEG_SINE)
            {
              result = c * res24_sin + s * res24_cos;
              abserr = std::abs(c * est_sin) + std::abs(s * est_cos);
            }
          else
            {
              result = c * res24_cos - s * res24_sin;
              abserr = std::abs(c * est_cos) + std::abs(s * est_sin);
            }
          resabs = result_abs * half_length;
          resasc = s_max;
          return {result, abserr, resabs, resasc};
        }
    }
References qcheb_integrate(), qk_integrate(), and Tp.
Referenced by qawo_integrate().
qc25s()
template<typename Tp , typename FuncTp , typename Integrator = gauss_kronrod_integral<Tp>>
std::tuple< Tp, Tp, bool > emsr::qc25s (qaws_integration_table< Tp > & t, FuncTp func, Tp lower, Tp upper, Tp a1, Tp mid, Integrator quad = gauss_kronrod_integral<Tp>(Kronrod_15))
Definition at line 224 of file qaws_integrate.tcc.
    {
      fn_qaws<Tp, FuncTp> fqaws(&t, func, lower, upper);
      if (a1 == lower && (t.alpha != Tp{0} || t.mu != 0))
        {
          const auto factor
            = std::pow(0.5 * (b1 - a1), t.alpha + Tp{1});
          auto f = [fqaws](Tp x)
                     -> Tp { return fqaws.eval_right(x); };
          auto chout = qcheb_integrate(f, a1, b1);
          const auto& cheb12 = chout.cheb12;
          const auto& cheb24 = chout.cheb24;
          if (t.mu == 0)
            {
              const auto u = factor;
              auto [res12, res24]
                = compute_result(t.ri, cheb12, cheb24);
              const auto result = u * res24;
              const auto abserr = std::abs(u * (res24 - res12));
              return std::make_tuple(result, abserr, false);
            }
          else
            {
              const auto u = factor * std::log(b1 - a1);
              const auto v = factor;
              auto [res12a, res24a]
                = compute_result(t.ri, cheb12, cheb24);
              auto [res12b, res24b]
                = compute_result(t.rg, cheb12, cheb24);
              const auto result = u * res24a + v * res24b;
              const auto abserr = std::abs(u * (res24a - res12a))
                                  + std::abs(v * (res24b - res12b));
              return std::make_tuple(result, abserr, false);
            }
        }
      else if (b1 == upper && (t.beta != Tp{0} || t.nu != 0))
        {
          auto factor = std::pow(0.5 * (b1 - a1), t.beta + Tp{1});
          auto f = [fqaws](Tp x)
                     -> Tp { return fqaws.eval_left(x); };
          auto chout = qcheb_integrate(f, a1, b1);
          const auto& cheb12 = chout.cheb12;
          const auto& cheb24 = chout.cheb24;
          if (t.nu == 0)
            {
              const auto u = factor;
              auto [res12, res24]
                = compute_result(t.rj, cheb12, cheb24);
              const auto result = u * res24;
              const auto abserr = std::abs(u * (res24 - res12));
              return std::make_tuple(result, abserr, false);
            }
          else
            {
              const auto u = factor * std::log(b1 - a1);
              const auto v = factor;
              auto [res12a, res24a]
                = compute_result(t.rj, cheb12, cheb24);
              auto [res12b, res24b]
                = compute_result(t.rh, cheb12, cheb24);
              const auto result = u * res24a + v * res24b;
              const auto abserr = std::abs(u * (res24a - res12a))
                                  + std::abs(v * (res24b - res12b));
              return std::make_tuple(result, abserr, false);
            }
        }
      else
        {
          auto f = [fqaws](Tp x)
                     ->Tp
                     { return fqaws.eval_middle(x); };
          auto [result, abserr, resabs, resasc]
            = quad(f, a1, b1);
          bool err_reliable;
          if (abserr == resasc)
            err_reliable = false;
          else
            err_reliable = true;
          return std::make_tuple(result, abserr, err_reliable);
        }
    }
References emsr::qaws_integration_table< Tp >::alpha, emsr::qaws_integration_table< Tp >::beta, compute_result(), emsr::fn_qaws< Tp, FuncTp >::eval_left(), emsr::fn_qaws< Tp, FuncTp >::eval_middle(), emsr::fn_qaws< Tp, FuncTp >::eval_right(), emsr::qaws_integration_table< Tp >::mu, emsr::qaws_integration_table< Tp >::nu, qcheb_integrate(), emsr::qaws_integration_table< Tp >::rg, emsr::qaws_integration_table< Tp >::rh, emsr::qaws_integration_table< Tp >::ri, emsr::qaws_integration_table< Tp >::rj, and Tp.
Referenced by qaws_integrate().
qcheb_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qcheb_integrate (FuncTp func, Tp lower, Tp upper) -> chebyshev_integral_t<std::invoke_result_t<FuncTp, Tp>>
Definition at line 38 of file qcheb_integrate.tcc.
    {
      using RetTp = std::invoke_result_t<FuncTp, Tp>;
      chebyshev_integral_t<RetTp> out;
      auto& cheb12 = out.cheb12;
      auto& cheb24 = out.cheb24;
      RetTp fval[25], v[12];
      // These are the values of cos(pi*k/24) for k=1..11 needed for the
      // Chebyshev expansion of f(x). These are the zeros of the Chebyshev
      // function of the second kind of order 23: U_23(x).
      constexpr Tp
      x[11]
      {
        9.914448613738104111442846968605486e-01L,
        9.659258262890682867486612158530536e-01L,
        9.238795325112867561257834975394469e-01L,
        8.660254037844386467595427060757126e-01L,
        7.933533402912351645734146973742314e-01L,
        7.071067811865475243919762573395221e-01L,
        6.087614290087206394044894932434070e-01L,
        4.999999999999999999855184455596035e-01L,
        3.826834323650897717110798781478690e-01L,
        2.588190451025207623287087436359508e-01L,
        1.305261922200515915256103766723547e-01L,
      };
      const auto center = (upper + lower) / Tp{2};
      const auto half_length = (upper - lower) / Tp{2};
      fval[0] = func(upper) / Tp{2};
      fval[12] = func(center);
      fval[24] = func(lower) / Tp{2};
      for (int i = 1; i < 12; ++i)
        {
          const std::size_t j = 24 - i;
          const auto u = half_length * x[i - 1];
          fval[i] = func(center + u);
          fval[j] = func(center - u);
        }
      for (int i = 0; i < 12; ++i)
        {
          const std::size_t j = 24 - i;
          v[i] = fval[i] - fval[j];
          fval[i] = fval[i] + fval[j];
        }
      {
        const auto alam1 = v[0] - v[8];
        const auto alam2 = x[5] * (v[2] - v[6] - v[10]);
        cheb12[3] = alam1 + alam2;
        cheb12[9] = alam1 - alam2;
      }
      {
        const auto alam1 = v[1] - v[7] - v[9];
        const auto alam2 = v[3] - v[5] - v[11];
        {
          const auto alam = x[2] * alam1 + x[8] * alam2;
          cheb24[3] = cheb12[3] + alam;
          cheb24[21] = cheb12[3] - alam;
        }
        {
          const auto alam = x[8] * alam1 - x[2] * alam2;
          cheb24[9] = cheb12[9] + alam;
          cheb24[15] = cheb12[9] - alam;
        }
      }
      {
        const auto part1 = x[3] * v[4];
        const auto part2 = x[7] * v[8];
        const auto part3 = x[5] * v[6];
        {
          const auto alam1 = v[0] + part1 + part2;
          const auto alam2 = x[1] * v[2] + part3 + x[9] * v[10];
          cheb12[1] = alam1 + alam2;
          cheb12[11] = alam1 - alam2;
        }
        {
          const Tp alam1 = v[0] - part1 + part2;
          const Tp alam2 = x[9] * v[2] - part3 + x[1] * v[10];
          cheb12[5] = alam1 + alam2;
          cheb12[7] = alam1 - alam2;
        }
      }
      {
        const auto alam = (x[0] * v[1] + x[2] * v[3]
                          + x[4] * v[5] + x[6] * v[7]
                          + x[8] * v[9] + x[10] * v[11]);
        cheb24[1] = cheb12[1] + alam;
        cheb24[23] = cheb12[1] - alam;
      }
      {
        const auto alam = (x[10] * v[1] - x[8] * v[3]
                          + x[6] * v[5] - x[4] * v[7]
                          + x[2] * v[9] - x[0] * v[11]);
        cheb24[11] = cheb12[11] + alam;
        cheb24[13] = cheb12[11] - alam;
      }
      {
        const auto alam = (x[4] * v[1] - x[8] * v[3]
                          - x[0] * v[5] - x[10] * v[7]
                          + x[2] * v[9] + x[6] * v[11]);
        cheb24[5] = cheb12[5] + alam;
        cheb24[19] = cheb12[5] - alam;
      }
      {
        const auto alam = (x[6] * v[1] - x[2] * v[3]
                          - x[10] * v[5] + x[0] * v[7]
                          - x[8] * v[9] - x[4] * v[11]);
        cheb24[7] = cheb12[7] + alam;
        cheb24[17] = cheb12[7] - alam;
      }
      for (int i = 0; i < 6; ++i)
        {
          const std::size_t j = 12 - i;
          v[i] = fval[i] - fval[j];
          fval[i] = fval[i] + fval[j];
        }
      {
        const auto alam1 = v[0] + x[7] * v[4];
        const auto alam2 = x[3] * v[2];
        cheb12[2] = alam1 + alam2;
        cheb12[10] = alam1 - alam2;
      }
      cheb12[6] = v[0] - v[4];
      {
        const auto alam = x[1] * v[1] + x[5] * v[3] + x[9] * v[5];
        cheb24[2] = cheb12[2] + alam;
        cheb24[22] = cheb12[2] - alam;
      }
      {
        const auto alam = x[5] * (v[1] - v[3] - v[5]);
        cheb24[6] = cheb12[6] + alam;
        cheb24[18] = cheb12[6] - alam;
      }
      {
        const auto alam = x[9] * v[1] - x[5] * v[3] + x[1] * v[5];
        cheb24[10] = cheb12[10] + alam;
        cheb24[14] = cheb12[10] - alam;
      }
      for (int i = 0; i < 3; ++i)
        {
          const std::size_t j = 6 - i;
          v[i] = fval[i] - fval[j];
          fval[i] = fval[i] + fval[j];
        }
      cheb12[4] = v[0] + x[7] * v[2];
      cheb12[8] = fval[0] - x[7] * fval[2];
      {
        const auto alam = x[3] * v[1];
        cheb24[4] = cheb12[4] + alam;
        cheb24[20] = cheb12[4] - alam;
      }
      {
        const auto alam = x[7] * fval[1] - fval[3];
        cheb24[8] = cheb12[8] + alam;
        cheb24[16] = cheb12[8] - alam;
      }
      cheb12[0] = fval[0] + fval[2];
      {
        const auto alam = fval[1] + fval[3];
        cheb24[0] = cheb12[0] + alam;
        cheb24[24] = cheb12[0] - alam;
      }
      cheb12[12] = v[0] - v[2];
      cheb24[12] = cheb12[12];
      for (int i = 1; i < 12; ++i)
        cheb12[i] *= Tp{1} / Tp{6};
      cheb12[0] *= Tp{1} / Tp{12};
      cheb12[12] *= Tp{1} / Tp{12};
      for (int i = 1; i < 24; ++i)
        cheb24[i] *= Tp{1} / Tp{12};
      cheb24[0] *= Tp{1} / Tp{24};
      cheb24[24] *= Tp{1} / Tp{24};
      return out;
    }
References emsr::chebyshev_integral_t< RetTp >::cheb12, emsr::chebyshev_integral_t< RetTp >::cheb24, and Tp.
Referenced by qc25f(), and qc25s().
qk_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qk_integrate (FuncTp func, Tp lower, Tp upper, Kronrod_Rule qkintrule) -> gauss_kronrod_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
Definition at line 495 of file gauss_kronrod_integral.tcc.
    {
      gauss_kronrod_integral<Tp> gk_integ(qkintrule);
      return gk_integ.integrate(func, lower, upper);
    }
Referenced by qc25f().
qng_integrate()
template<typename Tp , typename FuncTp >
auto emsr::qng_integrate (FuncTp func, Tp lower, Tp upper, Tp max_abs_err, Tp max_rel_err) -> gauss_kronrod_integral_t<Tp, std::invoke_result_t<FuncTp, Tp>>
Definition at line 229 of file qng_integrate.tcc.
    {
      using RetTp = std::invoke_result_t<FuncTp, Tp>;
      using AreaTp = decltype(RetTp{} * Tp{});
      RetTp fv1[5], fv2[5], fv3[5], fv4[5];
      RetTp savfun[21];
      const auto half_length = (upper - lower) / Tp{2};
      const auto abs_half_length = std::abs(half_length);
      const auto center = (upper + lower) / Tp{2};
      const auto f_center = func(center);
      if (!valid_tolerances(max_abs_err, max_rel_err))
        {
          std::ostringstream msg;
          msg << "qng_integrate: Tolerance cannot be achieved with given "
                   "absolute (" << max_abs_err << ") and relative ("
                << max_rel_err << ") error limits.";
          throw std::runtime_error(msg.str().c_str());
        }
      // Compute the integral using the 10- and 21-point formula.
      auto res10 = AreaTp{0};
      auto res21 = Tp(qng_w21b[5]) * f_center;
      // Approximation to the integral of abs(f)
      auto resabs = Tp(qng_w21b[5]) * std::abs(f_center);
      for (int k = 0; k < 5; ++k)
        {
          const auto abscissa = half_length * Tp(qng_x1[k]);
          const auto fval1 = func(center + abscissa);
          const auto fval2 = func(center - abscissa);
          const auto fval = fval1 + fval2;
          res10 += Tp(qng_w10[k]) * fval;
          res21 += Tp(qng_w21a[k]) * fval;
          resabs += Tp(qng_w21a[k])
                    * (std::abs(fval1) + std::abs(fval2));
          savfun[k] = fval;
          fv1[k] = fval1;
          fv2[k] = fval2;
        }
      for (int k = 0; k < 5; ++k)
        {
          const auto abscissa = half_length * Tp(qng_x2[k]);
          const auto fval1 = func(center + abscissa);
          const auto fval2 = func(center - abscissa);
          const auto fval = fval1 + fval2;
          res21 += Tp(qng_w21b[k]) * fval;
          resabs += Tp(qng_w21b[k])
                    * (std::abs(fval1) + std::abs(fval2));
          savfun[k + 5] = fval;
          fv3[k] = fval1;
          fv4[k] = fval2;
        }
      resabs *= abs_half_length;
      // Approximation to the integral of abs(f-I/(b-a)).
      const auto mean = Tp{0.5L} * res21;
      auto resasc = Tp(qng_w21b[5]) * std::abs(f_center - mean);
      for (int k = 0; k < 5; ++k)
        {
          resasc +=
            (Tp(qng_w21a[k]) * (std::abs(fv1[k] - mean)
                                 + std::abs(fv2[k] - mean))
           + Tp(qng_w21b[k]) * (std::abs(fv3[k] - mean)
                                 + std::abs(fv4[k] - mean)));
        }
      resasc *= abs_half_length;
      // Test for convergence.
      auto result_kronrod = res21 * half_length;
      auto err = rescale_error((res21 - res10) * half_length,
                                 resabs, resasc);
      if (err < max_abs_err
       || err < max_rel_err * std::abs(result_kronrod))
        return {result_kronrod, err, resabs, resasc};
      // Compute the integral using the 43-point formula.
      auto res43 = Tp(qng_w43b[11]) * f_center;
      for (int k = 0; k < 10; ++k)
        res43 += savfun[k] * Tp(qng_w43a[k]);
      for (int k = 0; k < 11; ++k)
        {
          const auto abscissa = half_length * Tp(qng_x3[k]);
          const auto fval = func(center + abscissa)
                            + func(center - abscissa);
          res43 += fval * Tp(qng_w43b[k]);
          savfun[k + 10] = fval;
        }
      // Test for convergence.
      result_kronrod = res43 * half_length;
      err = rescale_error((res43 - res21) * half_length,
                            resabs, resasc);
      if (err < max_abs_err
       || err < max_rel_err * std::abs(result_kronrod))
        return {result_kronrod, err, resabs, resasc};
      // Compute the integral using the 87-point formula.
      auto res87 = Tp(qng_w87b[22]) * f_center;
      for (int k = 0; k < 21; ++k)
        res87 += savfun[k] * Tp(qng_w87a[k]);
      for (int k = 0; k < 22; ++k)
        {
          const auto abscissa = half_length * Tp(qng_x4[k]);
          res87 += Tp(qng_w87b[k]) * (func(center + abscissa)
                                         + func(center - abscissa));
        }
      // Test for convergence.
      result_kronrod = res87 * half_length;
      err = rescale_error((res87 - res43) * half_length,
                            resabs, resasc);
      if (err < max_abs_err
       || err < max_rel_err * std::abs(result_kronrod))
        return {result_kronrod, err, resabs, resasc};
      // Failed to converge.
      throw integration_error("qng_integrate: "
                              "Failed to reach tolerance with highest-order rule",
                              TOLERANCE_ERROR, result_kronrod, err);
    }
References rescale_error(), TOLERANCE_ERROR, Tp, and valid_tolerances().
rescale_error()
template<typename AreaTp , typename AbsAreaTp >
AbsAreaTp emsr::rescale_error (AreaTp err, const AbsAreaTp result_abs, const AbsAreaTp result_asc)
Definition at line 126 of file integration_error.h.
    {
      const auto s_eps = std::numeric_limits<AbsAreaTp>::epsilon();
      const auto s_min = std::numeric_limits<AbsAreaTp>::min();
      AbsAreaTp abserr = std::abs(err);
      if (result_asc != AbsAreaTp{} && abserr != AbsAreaTp{})
        {
          auto scale = std::pow((AbsAreaTp{200} * abserr / result_asc), AbsAreaTp{1.5});
          if (scale < AbsAreaTp{1})
            abserr = result_asc * scale;
          else
            abserr = result_asc;
        }
      if (result_abs > s_min / (AbsAreaTp{50} * s_eps))
        {
          auto min_err = AbsAreaTp{50} * s_eps * result_abs;
          if (min_err > abserr)
            abserr = min_err;
        }
      return abserr;
    }
Referenced by qng_integrate().
s_tridiag() [1/2]
template<typename RandAccIter , typename RandAccIterRHS >
int emsr::s_tridiag (size_t n, RandAccIter supd, RandAccIter diag, RandAccIter subd, RandAccIterRHS rhs)
Solve a tridiagonal system A x = b:
Parameters
 in supd The superdiagonal of the matrix in [0, n - 2]
 in diag The diagonal of the matrix in [0, n - 1]
 in subd The subdiagonal of the matrix in [1, n - 1]
 out rhs The right hand side in [0, n - 1], replaced by the solution vector x
Definition at line 39 of file matrix.tcc.
    {
      using Tp = std::decay_t<decltype(subd[0])>;
      subd[0] = diag[0];
      if (n == 0)
        return 0;
      if (n == 1)
        {
          rhs[0] /= diag[0];
          return 0;
        }
      diag[0] = supd[0];
      supd[0] = Tp{0};
      supd[n - 1] = Tp{0};
      for (auto k = 0u; k < n - 1; ++k)
        {
          const auto k1 = k + 1;
          if (std::abs(subd[k1]) >= std::abs(subd[k]))
            {
              std::swap(subd[k1], subd[k]);
              std::swap(diag[k1], diag[k]);
              std::swap(supd[k1], supd[k]);
              std::swap(rhs[k1], rhs[k]);
            }
          if (subd[k] == Tp{0})
            return 1;
          {
            const auto t = -subd[k1] / subd[k];
            subd[k1] = diag[k1] + t * diag[k];
            diag[k1] = supd[k1] + t * supd[k];
            supd[k1] = Tp{0};
            rhs[k1] = rhs[k1] + t * rhs[k];
          }
        }
      if (subd[n - 1] == Tp{0})
        return 1;
      rhs[n - 1] = rhs[n - 1] / subd[n - 1];
      rhs[n - 2] = (rhs[n - 2] - diag[n - 2] * rhs[n - 1])
                     / subd[n - 2];
      for (std::ptrdiff_t k = n ; k > 2; --k)
        {
          const auto kb = k - 3;
          rhs[kb] = (rhs[kb] - diag[kb] * rhs[kb + 1]
                     - supd[kb] * rhs[kb + 2]) / subd[kb];
        }
      return 0;
    }
References Tp.
s_tridiag() [2/2]
template<typename RandAccIter , typename RandAccIterRHS >
int emsr::s_tridiag (std::size_t n, RandAccIter supd, RandAccIter diag, RandAccIter subd, RandAccIterRHS rhs)
s_tridiag_symm()
template<typename RandAccIter , typename RandAccIterRHS >
int emsr::s_tridiag_symm (std::size_t n, RandAccIter & diag, RandAccIter & subd, RandAccIterRHS & rhs)
Diagonalize a symmetric tridiagonal matrix.
This routine is a slightly modified version of the EISPACK routine to perform the implicit QL algorithm on a symmetric tridiagonal matrix.
It has been modified to produce the product Q' * Z, where Z is an input vector and Q is the orthogonal matrix diagonalizing the input matrix.
 The changes consist (essentialy) of applying the orthogonal transformations directly to Z as they are generated.
Original C++ version by John Burkardt (GPL).
See also
Sylvan Elhay, Jaroslav Kautsky, Algorithm 655: IQPACK, FORTRAN Subroutines for the Weights of Interpolatory Quadrature, ACM Transactions on Mathematical Software, Volume 13, Number 4, December 1987, pages 399-415.
Roger Martin, James Wilkinson, The Implicit QL Algorithm, Numerische Mathematik, Volume 12, Number 5, December 1968, pages 377-383.
Parameters
 in n The order of the matrix.
 in,out diag The diagonal entries [0, n-1] of the matrix. On output, the information in diag is overwritten.
 in,out subd The subdiagonal entries of the matrix, in entries [0, n-2]. On output, the information in subd is overwritten.
 in,out rhs On input, a vector. On output, the value of Q' * Z, where Q is the matrix that diagonalizes the input symmetric tridiagonal matrix.
Definition at line 139 of file matrix.tcc.
    {
      using Tp = std::decay_t<decltype(subd[0])>;
      const int max_iter = 50;
      int upper = 0;
      const auto prec = std::numeric_limits<Tp>::epsilon();
      if (n == 1)
        return 0;
      subd[n - 1] = Tp{0};
      for (int lower = 1; lower <= int(n); ++lower)
        {
          int j = 0;
          while (true)
            {
              for (upper = lower; upper <= int(n); ++upper)
                {
                  if (upper == int(n))
                    break;
                  if (std::abs(subd[upper - 1])
                        <= prec * (std::abs(diag[upper - 1])
                                   + std::abs(diag[upper])))
                    break;
                }
              auto p = diag[lower - 1];
              if (upper == lower)
                break;
              if (max_iter <= j)
                throw std::runtime_error("s_tridiag_symm:"
                                           " Iteration limit exceeded");
              ++j;
              auto g = (diag[lower] - p)
                         / (Tp{2} * subd[lower - 1]);
              auto r = std::sqrt(g * g + Tp{1});
              g = diag[upper - 1] - p
                  + subd[lower - 1]
                        / (g + std::copysign(std::abs(r), g));
              auto s = Tp{1};
              auto c = Tp{1};
              p = Tp{0};
              const auto mml = upper - lower;
              for (int ii = 1; ii <= mml; ii++)
                {
                  const auto i = upper - ii;
                  auto f = s * subd[i - 1];
                  auto b = c * subd[i - 1];
                  if (std::abs(g) <= std::abs(f))
                    {
                      c = g / f;
                      r = std::sqrt(c * c + Tp{1});
                      subd[i] = f * r;
                      s = Tp{1} / r;
                      c *= s;
                    }
                  else
                    {
                      s = f / g;
                      r = std::sqrt(s * s + Tp{1});
                      subd[i] = g * r;
                      c = Tp{1} / r;
                      s *= c;
                    }
                  g = diag[i] - p;
                  r = (diag[i - 1] - g) * s + Tp{2} * c * b;
                  p = s * r;
                  diag[i] = g + p;
                  g = c * r - b;
                  f = rhs[i];
                  rhs[i] = s * rhs[i - 1] + c * f;
                  rhs[i - 1] = c * rhs[i - 1] - s * f;
                }
              diag[lower - 1] = diag[lower - 1] - p;
              subd[lower - 1] = g;
              subd[upper - 1] = Tp{0};
            }
        }
      // Sorting.
      for (int ii = 2; ii <= upper; ++ii)
        {
          int i = ii - 1;
          int k = i;
          auto p = diag[i - 1];
          for (int j = ii; j <= int(n); ++j)
            if (diag[j - 1] < p)
              {
                k = j;
                p = diag[j - 1];
              }
          if (k != i)
            {
              diag[k - 1] = diag[i - 1];
              diag[i - 1] = p;
              std::swap(rhs[i - 1], rhs[k - 1]);
            }
        }
      return 0;
    }
References Tp.
Referenced by emsr::detail::golub_welsch().
test_positivity()
template<typename AreaTp , typename AbsAreaTp >
bool emsr::test_positivity (AreaTp result, AbsAreaTp resabs) [inline]
Definition at line 54 of file gauss_kronrod_integral.tcc.
    {
      return(std::abs(result)
          >= (1 - 50 * std::numeric_limits<AbsAreaTp>::epsilon()) * resabs);
    }
Referenced by qagp_integrate(), qags_integrate(), and qawo_integrate().
valid_tolerances()
template<typename Tp >
bool emsr::valid_tolerances (Tp max_abs_err, Tp max_rel_err) [inline]
Definition at line 141 of file integration.h.
    {
      return error_tolerance_t<Tp>::
             s_valid_tolerances(max_abs_err, max_rel_err);
    }
References emsr::error_tolerance_t< Tp >::s_valid_tolerances().
Referenced by qag_integrate(), qagp_integrate(), qags_integrate(), qawc_integrate(), qawo_integrate(), qaws_integrate(), and qng_integrate().
Vinvfx()
template<typename RetTp >
void emsr::Vinvfx (const std::array< RetTp, 33 > & fx, RetTp * coeff, const int depth)
Compute the product of the fx with one of the inverse Vandermonde-like matrices.
Definition at line 44 of file cquad_integrate.tcc.
    {
      switch (depth)
        {
        case 0:
          for (int i = 0; i <= 4; ++i)
            {
              coeff[i] = RetTp{0};
              for (int j = 0; j <= 4; ++j)
                coeff[i] += RetTp(V1inv[i * 5 + j]) * fx[j * 8];
            }
          break;
        case 1:
          for (int i = 0; i <= 8; ++i)
            {
              coeff[i] = RetTp{0};
              for (int j = 0; j <= 8; ++j)
                coeff[i] += RetTp(V2inv[i * 9 + j]) * fx[j * 4];
            }
          break;
        case 2:
          for (int i = 0; i <= 16; ++i)
            {
              coeff[i] = RetTp{0};
              for (int j = 0; j <= 16; ++j)
                coeff[i] += RetTp(V3inv[i * 17 + j]) * fx[j * 2];
            }
          break;
        case 3:
          for (int i = 0; i <= 32; ++i)
            {
              coeff[i] = RetTp{0};
              for (int j = 0; j <= 32; ++j)
                coeff[i] += RetTp(V4inv[i * 33 + j]) * fx[j];
            }
          break;
        }
    }
References V1inv, V2inv, V3inv, and V4inv.
Referenced by cquad_integrate().
wrap_func()
template<typename Tp , typename FuncTp >
std::invoke_result_t<FuncTp, Tp> emsr::wrap_func (FuncTp func, Tp x)
Chances are, if the function returns Nan or inf, we stepped on a pole.
Definition at line 77 of file trapezoid_integral.tcc.
    {
      auto y = func(x);
      if (std::isnan(y) || std::isinf(y))
        return Tp{0};
      else
        return y;
    }
References Tp.
Variable Documentation
bee
constexpr long double emsr::bee[68] [constexpr]
Initial value:
{
   0.00000000000000e+00L, 2.28868854108532e-01L, 0.00000000000000e+00L,
  -8.15740215243451e-01L, 0.00000000000000e+00L, 5.31212715259731e-01L,
   0.00000000000000e+00L, 1.38538036812454e-02L, 0.00000000000000e+00L,
   3.74405228908818e-02L, 0.00000000000000e+00L, 2.12224115039342e-01L,
   0.00000000000000e+00L, -8.16362644507898e-01L, 0.00000000000000e+00L,
   5.35648426691481e-01L, 0.00000000000000e+00L, 1.52417902753662e-03L,
   0.00000000000000e+00L, 2.63058840550873e-03L, 0.00000000000000e+00L,
   4.15292106318904e-03L, 0.00000000000000e+00L, 6.97106011119775e-03L,
   0.00000000000000e+00L, 1.35535708431058e-02L, 0.00000000000000e+00L,
   3.52132898424856e-02L, 0.00000000000000e+00L, 2.06946714741884e-01L,
   0.00000000000000e+00L, -8.15674251283876e-01L, 0.00000000000000e+00L,
   5.38841175520580e-01L, 0.00000000000000e+00L, 1.84909689577590e-04L,
   0.00000000000000e+00L, 2.90936325007499e-04L, 0.00000000000000e+00L,
   3.84877750950089e-04L, 0.00000000000000e+00L, 4.86436656735046e-04L,
   0.00000000000000e+00L, 6.08688640346879e-04L, 0.00000000000000e+00L,
   7.66732830740331e-04L, 0.00000000000000e+00L, 9.82753336104205e-04L,
   0.00000000000000e+00L, 1.29359957505615e-03L, 0.00000000000000e+00L,
   1.76616363801885e-03L, 0.00000000000000e+00L, 2.53323433039089e-03L,
   0.00000000000000e+00L, 3.88872172121956e-03L, 0.00000000000000e+00L,
   6.58635106468291e-03L, 0.00000000000000e+00L, 1.30326736343254e-02L,
   0.00000000000000e+00L, 3.44353850696714e-02L, 0.00000000000000e+00L,
   2.05025409531915e-01L, 0.00000000000000e+00L, -8.14985893995401e-01L,
   0.00000000000000e+00L, 5.40679930965238e-01L,
}
Definition at line 55 of file cquad_const.tcc.
Referenced by downdate().
gauss_hermite_integrate
template<typename Tp , typename Func >
decltype(std::invoke_result_t<Func, Tp>{} * Tp{} emsr::gauss_hermite_integrate) (Func func, unsigned int n) (Func func, unsigned int n)
Definition at line 32 of file gauss_hermite_integrate.h.
  {
    using RetTp = std::invoke_result_t<Func, Tp>;
    using AreaTp = decltype(RetTp{} * Tp{});
    if(n == 0)
      throw std::domain_error("gauss_hermite_integrate: "
                                "Hermite order must be greater than 0");
    else
     {
        const auto rule = hermite_zeros<Tp>(n);
        auto sum = AreaTp{};
        for (const auto& pt : rule)
          {
            const auto x = pt.point;
            const auto w = pt.weight;
            sum += w * func(x);
          }
        return sum;
      }
  }
gauss_laguerre_integrate
template<typename Tp , typename Func >
decltype(std::invoke_result_t<Func, Tp>{} * Tp{} emsr::gauss_laguerre_integrate) (Func func, unsigned int n, Tp alpha) (Func func, unsigned int n, Tp alpha)
Definition at line 32 of file gauss_laguerre_integrate.h.
  {
    using RetTp = std::invoke_result_t<Func, Tp>;
    using AreaTp = decltype(RetTp{} * Tp{});
    //using AbsAreaTp = decltype(std::abs(AreaTp{}));
    if(n == 0)
      throw std::domain_error("gauss_laguerre_integrate: "
                                "laguerre order must be greater than 0");
    else if (std::isnan(alpha))
      return AreaTp{} * std::numeric_limits<Tp>::quiet_NaN();
    else
     {
        auto rule = laguerre_zeros(n, alpha);
        auto sum = AreaTp{};
        for (const auto& pt : rule)
          {
            auto x = pt.point;
            auto w = pt.weight;
            sum += w * func(x);
          }
        return sum;
      }
  }
gauss_legendre_precomp
const gauss_legendre_table<long double> emsr::gauss_legendre_precomp[]
Initial value:
{
    gauss_legendre_table<long double>(2, x2, w2, true),
    gauss_legendre_table<long double>(3, x3, w3, true),
    gauss_legendre_table<long double>(4, x4, w4, true),
    gauss_legendre_table<long double>(5, x5, w5, true),
    gauss_legendre_table<long double>(6, x6, w6, true),
    gauss_legendre_table<long double>(7, x7, w7, true),
    gauss_legendre_table<long double>(8, x8, w8, true),
    gauss_legendre_table<long double>(9, x9, w9, true),
    gauss_legendre_table<long double>(10, x10, w10, true),
    gauss_legendre_table<long double>(11, x11, w11, true),
    gauss_legendre_table<long double>(12, x12, w12, true),
    gauss_legendre_table<long double>(13, x13, w13, true),
    gauss_legendre_table<long double>(14, x14, w14, true),
    gauss_legendre_table<long double>(15, x15, w15, true),
    gauss_legendre_table<long double>(16, x16, w16, true),
    gauss_legendre_table<long double>(17, x17, w17, true),
    gauss_legendre_table<long double>(18, x18, w18, true),
    gauss_legendre_table<long double>(19, x19, w19, true),
    gauss_legendre_table<long double>(20, x20, w20, true),
    gauss_legendre_table<long double>(32, x32, w32, true),
    gauss_legendre_table<long double>(64, x64, w64, true),
    gauss_legendre_table<long double>(96, x96, w96, true),
    gauss_legendre_table<long double>(100, x100, w100, true),
    gauss_legendre_table<long double>(128, x128, w128, true),
    gauss_legendre_table<long double>(256, x256, w256, true),
    gauss_legendre_table<long double>(512, x512, w512, true),
    gauss_legendre_table<long double>(1024, x1024, w1024, true),
  }
Definition at line 2794 of file gauss_legendre_table.h.
Referenced by emsr::gauss_legendre_table< Tp >::gauss_legendre_table(), emsr::gauss_legendre_table< Tp >::pt(), and emsr::gauss_legendre_table< Tp >::wt().
glfixed_integrate
template<typename Tp , typename FuncTp >
decltype(std::invoke_result_t<FuncTp, Tp>{} * Tp{} emsr::glfixed_integrate) (const gauss_legendre_table< Tp > &t, FuncTp func, Tp lower, Tp upper) (const gauss_legendre_table< Tp > & t, FuncTp func, Tp lower, Tp upper)
Definition at line 33 of file glfixed_integrate.tcc.
    {
      using RetTp = std::invoke_result_t<FuncTp, Tp>;
      using AreaTp = decltype(RetTp{} * Tp{});
      const int n = t.order;
      auto m = (n + 1) >> 1;
      auto A = (upper - lower) / Tp{2};
      auto B = (upper + lower) / Tp{2};
      if (n & 1) // n is odd.
        {
          auto sum = t.wt(0) * func(B);
          for (int i = 1; i < m; ++i)
            {
              auto Ax = A * t.pt(i);
              sum += t.wt(i) * (func(B + Ax) + func(B - Ax));
            }
          return A * sum;
        }
      else // n is even.
        {
          auto sum = AreaTp{0};
          for (int i = 0; i < m; ++i)
            {
              auto Ax = A * t.pt(i);
              sum += t.wt(i) * (func(B + Ax) + func(B - Ax));
            }
          return A * sum;
        }
    }
Lalpha
constexpr long double emsr::Lalpha[33] [constexpr]
Initial value:
{
   5.77350269189626e-01L, 5.16397779494322e-01L, 5.07092552837110e-01L,
   5.03952630678970e-01L, 5.02518907629606e-01L, 5.01745206004255e-01L,
   5.01280411827603e-01L, 5.00979432868120e-01L, 5.00773395667191e-01L,
   5.00626174321759e-01L, 5.00517330712619e-01L, 5.00434593736979e-01L,
   5.00370233297676e-01L, 5.00319182924304e-01L, 5.00278009473803e-01L,
   5.00244319584578e-01L, 5.00216403386025e-01L, 5.00193012939056e-01L,
   5.00173220168024e-01L, 5.00156323280355e-01L, 5.00141783641018e-01L,
   5.00129182278347e-01L, 5.00118189340972e-01L, 5.00108542278496e-01L,
   5.00100030010004e-01L, 5.00092481273333e-01L, 5.00085755939229e-01L,
   5.00079738458365e-01L, 5.00074332862969e-01L, 5.00069458915387e-01L,
   5.00065049112355e-01L, 5.00061046334395e-01L, 5.00057401986298e-01L,
}
Definition at line 83 of file cquad_const.tcc.
Referenced by downdate().
Lgamma
constexpr long double emsr::Lgamma[33] [constexpr]
Initial value:
{
   0.0L, 0.0L, 5.16397779494322e-01L,
   5.07092552837110e-01L, 5.03952630678970e-01L,
   5.02518907629606e-01L, 5.01745206004255e-01L, 5.01280411827603e-01L,
   5.00979432868120e-01L, 5.00773395667191e-01L, 5.00626174321759e-01L,
   5.00517330712619e-01L, 5.00434593736979e-01L, 5.00370233297676e-01L,
   5.00319182924304e-01L, 5.00278009473803e-01L, 5.00244319584578e-01L,
   5.00216403386025e-01L, 5.00193012939056e-01L, 5.00173220168024e-01L,
   5.00156323280355e-01L, 5.00141783641018e-01L, 5.00129182278347e-01L,
   5.00118189340972e-01L, 5.00108542278496e-01L, 5.00100030010003e-01L,
   5.00092481273333e-01L, 5.00085755939229e-01L, 5.00079738458365e-01L,
   5.00074332862969e-01L, 5.00069458915387e-01L, 5.00065049112355e-01L,
   5.00061046334395e-01L,
}
Definition at line 99 of file cquad_const.tcc.
Referenced by downdate().
num_gauss_legendre_precomp
const std::size_t emsr::num_gauss_legendre_precomp
Initial value:
= sizeof(gauss_legendre_precomp)
                      / sizeof(gauss_legendre_precomp[0])
Definition at line 2824 of file gauss_legendre_table.h.
Referenced by emsr::gauss_legendre_table< Tp >::gauss_legendre_table().
Tleft
constexpr long double emsr::Tleft[33 *33] [constexpr]
Definition at line 931 of file cquad_const.tcc.
Tright
constexpr long double emsr::Tright[33 *33] [constexpr]
Definition at line 1323 of file cquad_const.tcc.
V1inv
constexpr long double emsr::V1inv[5 *5] [constexpr]
Initial value:
{
   0.47140452079103168293e-1L, 0.37712361663282534635L,
   0.56568542494923801952L,
   0.37712361663282534635L, 0.47140452079103168293e-1L,
  -0.81649658092772603273e-1L, -0.46188021535170061160L, 0.0L,
   0.46188021535170061160L, 0.81649658092772603273e-1L,
   0.15058465048420853962L,
   0.12046772038736683169L, -0.54210474174315074262L, 0.12046772038736683169L,
   0.15058465048420853962L, -0.21380899352993950775L, 0.30237157840738178177L,
  -0.0L,
  -0.30237157840738178177L, 0.21380899352993950775L, 0.10774960475223581324L,
  -0.21549920950447162648L, 0.21549920950447162648L, -0.21549920950447162648L,
   0.10774960475223581324L,
}
Definition at line 116 of file cquad_const.tcc.
Referenced by Vinvfx().
V2inv
constexpr long double emsr::V2inv[9 *9] [constexpr]
Definition at line 133 of file cquad_const.tcc.
Referenced by Vinvfx().
V3inv
constexpr long double emsr::V3inv[17 *17] [constexpr]
Definition at line 185 of file cquad_const.tcc.
Referenced by Vinvfx().
V4inv
constexpr long double emsr::V4inv[33 *33] [constexpr]
Definition at line 352 of file cquad_const.tcc.
Referenced by Vinvfx().
w10
constexpr long double emsr::w10[5] [constexpr]
Initial value:
{
    0.2955242247147528701738930L,
    0.2692667193099963550912269L,
    0.2190863625159820439955349L,
    0.1494513491505805931457763L,
    0.0666713443086881375935688L,
  }
Definition at line 164 of file gauss_legendre_table.h.
w100
constexpr long double emsr::w100[50] [constexpr]
Definition at line 581 of file gauss_legendre_table.h.
w1024
constexpr long double emsr::w1024[512] [constexpr]
Definition at line 2079 of file gauss_legendre_table.h.
w11
constexpr long double emsr::w11[6] [constexpr]
Initial value:
{
    0.2729250867779006307144835L,
    0.2628045445102466621806889L,
    0.2331937645919904799185237L,
    0.1862902109277342514260976L,
    0.1255803694649046246346943L,
    0.0556685671161736664827537L,
  }
Definition at line 2675 of file gauss_legendre_table.h.
w12
constexpr long double emsr::w12[6] [constexpr]
Initial value:
{
    0.2491470458134027850005624L,
    0.2334925365383548087608499L,
    0.2031674267230659217490645L,
    0.1600783285433462263346525L,
    0.1069393259953184309602547L,
    0.0471753363865118271946160L,
  }
Definition at line 185 of file gauss_legendre_table.h.
w128
constexpr long double emsr::w128[64] [constexpr]
Definition at line 705 of file gauss_legendre_table.h.
w13
constexpr long double emsr::w13[7] [constexpr]
Initial value:
{
    0.2325515532308739101945895L,
    0.2262831802628972384120902L,
    0.2078160475368885023125232L,
    0.1781459807619457382800467L,
    0.1388735102197872384636018L,
    0.0921214998377284479144218L,
    0.0404840047653158795200216L,
  }
Definition at line 2698 of file gauss_legendre_table.h.
w14
constexpr long double emsr::w14[7] [constexpr]
Initial value:
{
    0.2152638534631577901958764L,
    0.2051984637212956039659241L,
    0.1855383974779378137417166L,
    0.1572031671581935345696019L,
    0.1215185706879031846894148L,
    0.0801580871597602098056333L,
    0.0351194603317518630318329L,
  }
Definition at line 208 of file gauss_legendre_table.h.
w15
constexpr long double emsr::w15[8] [constexpr]
Initial value:
{
    0.2025782419255612728806202L,
    0.1984314853271115764561183L,
    0.1861610000155622110268006L,
    0.1662692058169939335532009L,
    0.1395706779261543144478048L,
    0.1071592204671719350118695L,
    0.0703660474881081247092674L,
    0.0307532419961172683546284L,
  }
Definition at line 2723 of file gauss_legendre_table.h.
w16
constexpr long double emsr::w16[8] [constexpr]
Initial value:
{
    0.1894506104550684962853967L,
    0.1826034150449235888667637L,
    0.1691565193950025381893121L,
    0.1495959888165767320815017L,
    0.1246289712555338720524763L,
    0.0951585116824927848099251L,
    0.0622535239386478928628438L,
    0.0271524594117540948517806L,
  }
Definition at line 233 of file gauss_legendre_table.h.
w17
constexpr long double emsr::w17[9] [constexpr]
Initial value:
{
    0.1794464703562065254582656L,
    0.1765627053669926463252710L,
    0.1680041021564500445099707L,
    0.1540457610768102880814316L,
    0.1351363684685254732863200L,
    0.1118838471934039710947884L,
    0.0850361483171791808835354L,
    0.0554595293739872011294402L,
    0.0241483028685479319601100L,
  }
Definition at line 2750 of file gauss_legendre_table.h.
w18
constexpr long double emsr::w18[9] [constexpr]
Initial value:
{
    0.1691423829631435918406565L,
    0.1642764837458327229860538L,
    0.1546846751262652449254180L,
    0.1406429146706506512047313L,
    0.1225552067114784601845191L,
    0.1009420441062871655628140L,
    0.0764257302548890565291297L,
    0.0497145488949697964533349L,
    0.0216160135264833103133427L,
  }
Definition at line 260 of file gauss_legendre_table.h.
w19
constexpr long double emsr::w19[10] [constexpr]
Initial value:
{
    0.1610544498487836959791636L,
    0.1589688433939543476499564L,
    0.1527660420658596667788554L,
    0.1426067021736066117757461L,
    0.1287539625393362276755158L,
    0.1115666455473339947160239L,
    0.0914900216224499994644621L,
    0.0690445427376412265807083L,
    0.0448142267656996003328382L,
    0.0194617882297264770363120L,
  }
Definition at line 2779 of file gauss_legendre_table.h.
w2
constexpr long double emsr::w2[1] [constexpr]
Initial value:
{
    1.0000000000000000000000000L,
  }
Definition at line 100 of file gauss_legendre_table.h.
w20
constexpr long double emsr::w20[10] [constexpr]
Initial value:
{
    0.1527533871307258506980843L,
    0.1491729864726037467878287L,
    0.1420961093183820513292983L,
    0.1316886384491766268984945L,
    0.1181945319615184173123774L,
    0.1019301198172404350367501L,
    0.0832767415767047487247581L,
    0.0626720483341090635695065L,
    0.0406014298003869413310400L,
    0.0176140071391521183118620L,
  }
Definition at line 289 of file gauss_legendre_table.h.
w256
constexpr long double emsr::w256[128] [constexpr]
Definition at line 907 of file gauss_legendre_table.h.
w3
constexpr long double emsr::w3[2] [constexpr]
Initial value:
{
    0.8888888888888888888888889L,
    0.5555555555555555555555556L,
  }
Definition at line 2603 of file gauss_legendre_table.h.
w32
constexpr long double emsr::w32[16] [constexpr]
Initial value:
{
    0.0965400885147278005667648L,
    0.0956387200792748594190820L,
    0.0938443990808045656391802L,
    0.0911738786957638847128686L,
    0.0876520930044038111427715L,
    0.0833119242269467552221991L,
    0.0781938957870703064717409L,
    0.0723457941088485062253994L,
    0.0658222227763618468376501L,
    0.0586840934785355471452836L,
    0.0509980592623761761961632L,
    0.0428358980222266806568786L,
    0.0342738629130214331026877L,
    0.0253920653092620594557526L,
    0.0162743947309056706051706L,
    0.0070186100094700966004071L,
  }
Definition at line 325 of file gauss_legendre_table.h.
w4
constexpr long double emsr::w4[2] [constexpr]
Initial value:
{
    0.6521451548625461426269361L,
    0.3478548451374538573730639L,
  }
Definition at line 113 of file gauss_legendre_table.h.
w5
constexpr long double emsr::w5[3] [constexpr]
Initial value:
{
    0.5688888888888888888888889L,
    0.4786286704993664680412915L,
    0.2369268850561890875142640L,
  }
Definition at line 2618 of file gauss_legendre_table.h.
w512
constexpr long double emsr::w512[256] [constexpr]
Definition at line 1301 of file gauss_legendre_table.h.
w6
constexpr long double emsr::w6[3] [constexpr]
Initial value:
{
    0.4679139345726910473898703L,
    0.3607615730481386075698335L,
    0.1713244923791703450402961L,
  }
Definition at line 128 of file gauss_legendre_table.h.
w64
constexpr long double emsr::w64[32] [constexpr]
Definition at line 383 of file gauss_legendre_table.h.
w7
constexpr long double emsr::w7[4] [constexpr]
Initial value:
{
    0.4179591836734693877551020L,
    0.3818300505051189449503698L,
    0.2797053914892766679014678L,
    0.1294849661688696932706114L,
  }
Definition at line 2635 of file gauss_legendre_table.h.
w8
constexpr long double emsr::w8[4] [constexpr]
Initial value:
{
    0.3626837833783619829651504L,
    0.3137066458778872873379622L,
    0.2223810344533744705443560L,
    0.1012285362903762591525314L,
  }
Definition at line 145 of file gauss_legendre_table.h.
w9
constexpr long double emsr::w9[5] [constexpr]
Initial value:
{
    0.3302393550012597631645251L,
    0.3123470770400028400686304L,
    0.2606106964029354623187429L,
    0.1806481606948574040584720L,
    0.0812743883615744119718922L,
  }
Definition at line 2654 of file gauss_legendre_table.h.
w96
constexpr long double emsr::w96[48] [constexpr]
Definition at line 473 of file gauss_legendre_table.h.
x10
constexpr long double emsr::x10[5] [constexpr]
Initial value:
{
    0.1488743389816312108848260L,
    0.4333953941292471907992659L,
    0.6794095682990244062343274L,
    0.8650633666889845107320967L,
    0.9739065285171717200779640L,
  }
Definition at line 155 of file gauss_legendre_table.h.
x100
constexpr long double emsr::x100[50] [constexpr]
Definition at line 527 of file gauss_legendre_table.h.
x1024
constexpr long double emsr::x1024[512] [constexpr]
Definition at line 1563 of file gauss_legendre_table.h.
x11
constexpr long double emsr::x11[6] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.2695431559523449723315320L,
    0.5190961292068118159257257L,
    0.7301520055740493240934163L,
    0.8870625997680952990751578L,
    0.9782286581460569928039380L,
  }
Definition at line 2665 of file gauss_legendre_table.h.
x12
constexpr long double emsr::x12[6] [constexpr]
Initial value:
{
    0.1252334085114689154724414L,
    0.3678314989981801937526915L,
    0.5873179542866174472967024L,
    0.7699026741943046870368938L,
    0.9041172563704748566784659L,
    0.9815606342467192506905491L,
  }
Definition at line 175 of file gauss_legendre_table.h.
x128
constexpr long double emsr::x128[64] [constexpr]
Definition at line 637 of file gauss_legendre_table.h.
x13
constexpr long double emsr::x13[7] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.2304583159551347940655281L,
    0.4484927510364468528779129L,
    0.6423493394403402206439846L,
    0.8015780907333099127942065L,
    0.9175983992229779652065478L,
    0.9841830547185881494728294L,
  }
Definition at line 2687 of file gauss_legendre_table.h.
x14
constexpr long double emsr::x14[7] [constexpr]
Initial value:
{
    0.1080549487073436620662447L,
    0.3191123689278897604356718L,
    0.5152486363581540919652907L,
    0.6872929048116854701480198L,
    0.8272013150697649931897947L,
    0.9284348836635735173363911L,
    0.9862838086968123388415973L,
  }
Definition at line 197 of file gauss_legendre_table.h.
x15
constexpr long double emsr::x15[8] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.2011940939974345223006283L,
    0.3941513470775633698972074L,
    0.5709721726085388475372267L,
    0.7244177313601700474161861L,
    0.8482065834104272162006483L,
    0.9372733924007059043077589L,
    0.9879925180204854284895657L,
  }
Definition at line 2711 of file gauss_legendre_table.h.
x16
constexpr long double emsr::x16[8] [constexpr]
Initial value:
{
    0.0950125098376374401853193L,
    0.2816035507792589132304605L,
    0.4580167776572273863424194L,
    0.6178762444026437484466718L,
    0.7554044083550030338951012L,
    0.8656312023878317438804679L,
    0.9445750230732325760779884L,
    0.9894009349916499325961542L,
  }
Definition at line 221 of file gauss_legendre_table.h.
x17
constexpr long double emsr::x17[9] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.1784841814958478558506775L,
    0.3512317634538763152971855L,
    0.5126905370864769678862466L,
    0.6576711592166907658503022L,
    0.7815140038968014069252301L,
    0.8802391537269859021229557L,
    0.9506755217687677612227170L,
    0.9905754753144173356754340L,
  }
Definition at line 2737 of file gauss_legendre_table.h.
x18
constexpr long double emsr::x18[9] [constexpr]
Initial value:
{
    0.0847750130417353012422619L,
    0.2518862256915055095889729L,
    0.4117511614628426460359318L,
    0.5597708310739475346078715L,
    0.6916870430603532078748911L,
    0.8037049589725231156824175L,
    0.8926024664975557392060606L,
    0.9558239495713977551811959L,
    0.9915651684209309467300160L,
  }
Definition at line 247 of file gauss_legendre_table.h.
x19
constexpr long double emsr::x19[10] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.1603586456402253758680961L,
    0.3165640999636298319901173L,
    0.4645707413759609457172671L,
    0.6005453046616810234696382L,
    0.7209661773352293786170959L,
    0.8227146565371428249789225L,
    0.9031559036148179016426609L,
    0.9602081521348300308527788L,
    0.9924068438435844031890177L,
  }
Definition at line 2765 of file gauss_legendre_table.h.
x2
constexpr long double emsr::x2[1] [constexpr]
Initial value:
{
    0.5773502691896257645091488L,
  }
Definition at line 95 of file gauss_legendre_table.h.
Referenced by integrate_tanh_sinh().
x20
constexpr long double emsr::x20[10] [constexpr]
Initial value:
{
    0.0765265211334973337546404L,
    0.2277858511416450780804962L,
    0.3737060887154195606725482L,
    0.5108670019508270980043641L,
    0.6360536807265150254528367L,
    0.7463319064601507926143051L,
    0.8391169718222188233945291L,
    0.9122344282513259058677524L,
    0.9639719272779137912676661L,
    0.9931285991850949247861224L,
  }
Definition at line 275 of file gauss_legendre_table.h.
x256
constexpr long double emsr::x256[128] [constexpr]
Definition at line 775 of file gauss_legendre_table.h.
x3
constexpr long double emsr::x3[2] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.7745966692414833770358531L,
  }
Definition at line 2597 of file gauss_legendre_table.h.
x32
constexpr long double emsr::x32[16] [constexpr]
Initial value:
{
    0.0483076656877383162348126L,
    0.1444719615827964934851864L,
    0.2392873622521370745446032L,
    0.3318686022821276497799168L,
    0.4213512761306353453641194L,
    0.5068999089322293900237475L,
    0.5877157572407623290407455L,
    0.6630442669302152009751152L,
    0.7321821187402896803874267L,
    0.7944837959679424069630973L,
    0.8493676137325699701336930L,
    0.8963211557660521239653072L,
    0.9349060759377396891709191L,
    0.9647622555875064307738119L,
    0.9856115115452683354001750L,
    0.9972638618494815635449811L,
  }
Definition at line 305 of file gauss_legendre_table.h.
x4
constexpr long double emsr::x4[2] [constexpr]
Initial value:
{
    0.3399810435848562648026658L,
    0.8611363115940525752239465L,
  }
Definition at line 107 of file gauss_legendre_table.h.
x5
constexpr long double emsr::x5[3] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.5384693101056830910363144L,
    0.9061798459386639927976269L,
  }
Definition at line 2611 of file gauss_legendre_table.h.
x512
constexpr long double emsr::x512[256] [constexpr]
Definition at line 1041 of file gauss_legendre_table.h.
x6
constexpr long double emsr::x6[3] [constexpr]
Initial value:
{
    0.2386191860831969086305017L,
    0.6612093864662645136613996L,
    0.9324695142031520278123016L,
  }
Definition at line 121 of file gauss_legendre_table.h.
x64
constexpr long double emsr::x64[32] [constexpr]
Definition at line 347 of file gauss_legendre_table.h.
x7
constexpr long double emsr::x7[4] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.4058451513773971669066064L,
    0.7415311855993944398638648L,
    0.9491079123427585245261897L,
  }
Definition at line 2627 of file gauss_legendre_table.h.
x8
constexpr long double emsr::x8[4] [constexpr]
Initial value:
{
    0.1834346424956498049394761L,
    0.5255324099163289858177390L,
    0.7966664774136267395915539L,
    0.9602898564975362316835609L,
  }
Definition at line 137 of file gauss_legendre_table.h.
x9
constexpr long double emsr::x9[5] [constexpr]
Initial value:
{
    0.0000000000000000000000000L,
    0.3242534234038089290385380L,
    0.6133714327005903973087020L,
    0.8360311073266357942994298L,
    0.9681602395076260898355762L,
  }
Definition at line 2645 of file gauss_legendre_table.h.
x96
constexpr long double emsr::x96[48] [constexpr]
Definition at line 421 of file gauss_legendre_table.h.
xi
constexpr long double emsr::xi[33] [constexpr]
Initial value:
{
  -1.0L, -0.99518472667219688624L,
  -0.98078528040323044912L, -0.95694033573220886493L,
  -0.92387953251128675612L, -0.88192126434835502970L,
  -0.83146961230254523708L, -0.77301045336273696082L,
  -0.70710678118654752440L, -0.63439328416364549822L,
  -0.55557023301960222475L, -0.47139673682599764857L,
  -0.38268343236508977173L, -0.29028467725446236764L,
  -0.19509032201612826785L, -0.098017140329560601995L,
   0.0L, 0.098017140329560601995L,
   0.19509032201612826785L, 0.29028467725446236764L,
   0.38268343236508977173L, 0.47139673682599764857L,
   0.55557023301960222475L, 0.63439328416364549822L,
   0.70710678118654752440L, 0.77301045336273696082L,
   0.83146961230254523708L, 0.88192126434835502970L,
   0.92387953251128675612L, 0.95694033573220886493L,
   0.98078528040323044912L, 0.99518472667219688624L,
   1.0L,
}
Definition at line 33 of file cquad_const.tcc.
Referenced by cquad_integrate(), downdate(), and emsr::gauss_legendre_table< Tp >::get_point().