__gnu_cxx::fn_qaws< _Tp, _FuncTp > Struct Template Reference
Public Types
using _AreaTp = decltype(_RetTp{} *_Tp{})
using _RetTp = std::invoke_result_t< _FuncTp, _Tp >
Public Member Functions
fn_qaws (const qaws_integration_table< _Tp > *__tab, _FuncTp __func, _Tp __a_in, _Tp __b_in)
_RetTp eval_left (_Tp) const
_RetTp eval_middle (_Tp) const
_RetTp eval_right (_Tp) const
Public Attributes
_Tp a
_Tp b
_FuncTp func
const qaws_integration_table< _Tp > * table
Detailed Description
template<typename _Tp, typename _FuncTp>
struct __gnu_cxx::fn_qaws< _Tp, _FuncTp >
Definition at line 39 of file qaws_integrate.tcc.
Member Typedef Documentation
_AreaTp
template<typename _Tp, typename _FuncTp>
using __gnu_cxx::fn_qaws< _Tp, _FuncTp >::_AreaTp = decltype(_RetTp{} * _Tp{})
Definition at line 331 of file qaws_integrate.tcc.
_RetTp
template<typename _Tp, typename _FuncTp>
using __gnu_cxx::fn_qaws< _Tp, _FuncTp >::_RetTp = std::invoke_result_t<_FuncTp, _Tp>
Definition at line 330 of file qaws_integrate.tcc.
Constructor & Destructor Documentation
fn_qaws()
template<typename _Tp, typename _FuncTp>
__gnu_cxx::fn_qaws< _Tp, _FuncTp >::fn_qaws (const qaws_integration_table< _Tp > * __tab, _FuncTp __func, _Tp __a_in, _Tp __b_in) [inline]
Definition at line 338 of file qaws_integrate.tcc.
      : table(__tab),
        func(__func), a(__a_in), b(__b_in)
      { }
Member Function Documentation
eval_left()
template<typename _Tp , typename _FuncTp >
std::invoke_result_t< _FuncTp, _Tp > __gnu_cxx::fn_qaws< _Tp, _FuncTp >::eval_left (_Tp __x) const
Definition at line 372 of file qaws_integrate.tcc.
Referenced by __gnu_cxx::qc25s().
    {
      auto __factor = _Tp{1};
      if (this->table->alpha != _Tp{0})
        __factor *= std::pow(__x - this->a, this->table->alpha);
      if (this->table->mu == 1)
        __factor *= std::log(__x - this->a);
      return __factor * this->func(__x);
    }
eval_middle()
template<typename _Tp , typename _FuncTp >
std::invoke_result_t< _FuncTp, _Tp > __gnu_cxx::fn_qaws< _Tp, _FuncTp >::eval_middle (_Tp __x) const
Definition at line 351 of file qaws_integrate.tcc.
Referenced by __gnu_cxx::qc25s().
    {
      auto __factor = _Tp{1};
      if (this->table->alpha != _Tp{0})
        __factor *= std::pow(__x - this->a, this->table->alpha);
      if (table->mu == 1)
        __factor *= std::log(__x - this->a);
      if (this->table->beta != _Tp{0})
        __factor *= std::pow(this->b - __x, this->table->beta);
      if (table->nu == 1)
        __factor *= std::log(this->b - __x);
      return __factor * this->func(__x);
    }
eval_right()
template<typename _Tp , typename _FuncTp >
std::invoke_result_t< _FuncTp, _Tp > __gnu_cxx::fn_qaws< _Tp, _FuncTp >::eval_right (_Tp __x) const
Definition at line 387 of file qaws_integrate.tcc.
References __gnu_cxx::compute_result_t< _AreaTp >::__res12, __gnu_cxx::compute_result_t< _AreaTp >::__res24, and __gnu_cxx::compute_result().
Referenced by __gnu_cxx::qc25s().
    {
      auto __factor = _Tp{1};
      if (this->table->beta != _Tp{0})
        __factor *= std::pow(this->b - __x, this->table->beta);
      if (this->table->nu == 1)
        __factor *= std::log(this->b - __x);
      return __factor * this->func(__x);
    }
Member Data Documentation
a
template<typename _Tp, typename _FuncTp>
_Tp __gnu_cxx::fn_qaws< _Tp, _FuncTp >::a
Definition at line 335 of file qaws_integrate.tcc.
b
template<typename _Tp, typename _FuncTp>
_Tp __gnu_cxx::fn_qaws< _Tp, _FuncTp >::b
Definition at line 336 of file qaws_integrate.tcc.
func
template<typename _Tp, typename _FuncTp>
_FuncTp __gnu_cxx::fn_qaws< _Tp, _FuncTp >::func
Definition at line 334 of file qaws_integrate.tcc.
table
template<typename _Tp, typename _FuncTp>
const qaws_integration_table<_Tp>* __gnu_cxx::fn_qaws< _Tp, _FuncTp >::table
Definition at line 333 of file qaws_integrate.tcc.
The documentation for this struct was generated from the following file:
include/ext/qaws_integrate.tcc