__gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp > Struct Template Reference
#include <gauss_quadrature.h>
Public Member Functions
fixed_gauss_chebyshev_v_integral (int __n)
Public Attributes
template<typename _FuncTp >
decltype(std::invoke_result_t< _FuncTp, _Tp >{} *_Tp{} operator())(_FuncTp __func, _Tp __a, _Tp __b) const
int order
Detailed Description
template<typename _Tp>
struct __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >
Majid Tavassoli Kajani, Adem KJlJçman, and Mohammad Maleki The Rational Third-Kind Chebyshev Pseudospectral Method for the Solution of the Thomas-Fermi Equation over Infinite Interval
Definition at line 94 of file gauss_quadrature.h.
Constructor & Destructor Documentation
fixed_gauss_chebyshev_v_integral()
template<typename _Tp >
__gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::fixed_gauss_chebyshev_v_integral (int __n) [explicit]
Construct a Gauss-Chebyshev-V rule of order n.
Interval: $ (-1, +1) $ Weight function: $ [(x-a)/(b-x)]^{1/2} $ Jacobi parameter: $ \alpha = +1/2 $ Jacobi parameter: $ \beta = -1/2 $
Definition at line 269 of file gauss_quadrature.tcc.
References __gnu_cxx::__func(), __gnu_cxx::__detail::__golub_welsch(), __gnu_cxx::_RetTp, __gnu_cxx::_Tp, __gnu_cxx::fixed_gauss_chebyshev_w_integral< _Tp >::fixed_gauss_chebyshev_w_integral(), and __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::order.
Referenced by __gnu_cxx::fixed_gauss_chebyshev_u_integral< _Tp >::fixed_gauss_chebyshev_u_integral().
    : order(__n),
      point(__n),
      weight(__n)
    {
      const auto __mu_0 = __gnu_cxx::math::__pi_v<_Tp>;
      std::vector<_Tp> __diag(this->order, _Tp{0});
      std::vector<_Tp> __subd(this->order, _Tp{0.5L});
      __diag[0] = _Tp{-0.5L};
      __subd[0] = std::sqrt(_Tp{2});
      __detail::__golub_welsch(__mu_0, this->order, __diag, __subd,
                               this->point, this->weight);
    }
Member Data Documentation
operator()
template<typename _Tp>
template<typename _FuncTp >
decltype(std::invoke_result_t<_FuncTp, _Tp>{} * _Tp{} __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::operator()) (_FuncTp __func, _Tp __a, _Tp __b) const
Definition at line 102 of file gauss_quadrature.h.
order
template<typename _Tp>
int __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::order
Definition at line 96 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_chebyshev_v_integral< _Tp >::fixed_gauss_chebyshev_v_integral().
The documentation for this struct was generated from the following files:
include/ext/gauss_quadrature.h
include/ext/gauss_quadrature.tcc