__gnu_cxx::fixed_gauss_jacobi_integral< _Tp > Struct Template Reference
#include <gauss_quadrature.h>
Public Member Functions
fixed_gauss_jacobi_integral (int __n, _Tp __alf, _Tp __bet)
Public Attributes
_Tp alpha
_Tp beta
template<typename _FuncTp >
decltype(std::invoke_result_t< _FuncTp, _Tp >{} *_Tp{} operator())(_FuncTp __func, _Tp __a, _Tp __b) const
int order
Detailed Description
template<typename _Tp>
struct __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >
Definition at line 152 of file gauss_quadrature.h.
Constructor & Destructor Documentation
fixed_gauss_jacobi_integral()
template<typename _Tp >
__gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral (int __n, _Tp __alf, _Tp __bet) [explicit]
Construct a Gauss-Jacobi rule of order n.
Interval: $ (-1, +1) $ Weight function: $ (1-x)^\alpha (1+x)^\beta $ Constraints: $ \alpha, \beta > -1 $
Definition at line 461 of file gauss_quadrature.tcc.
References __gnu_cxx::__func(), __gnu_cxx::__detail::__golub_welsch(), __gnu_cxx::_RetTp, __gnu_cxx::_Tp, __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::alpha, __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::beta, __gnu_cxx::fixed_gauss_laguerre_integral< _Tp >::fixed_gauss_laguerre_integral(), and __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::order.
Referenced by __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::fixed_gauss_gegenbauer_integral().
    : order(__n),
      alpha(__alf),
      beta(__bet),
      point(__n),
      weight(__n)
    {
      const auto __ab = this->alpha + this->beta;
      auto __abp2i = __ab + _Tp{2};
      const auto __mu_0 = std::pow(_Tp{2}, __ab + _Tp{1})
                        * std::tgamma(this->alpha + _Tp{1})
                        * std::tgamma(this->beta + _Tp{1})
                        / std::tgamma(__abp2i);
      std::vector<_Tp> __diag(this->order);
      std::vector<_Tp> __subd(this->order);
      __diag[0] = (this->beta - this->alpha) / __abp2i;
      __subd[0] = _Tp{2} * std::sqrt((this->alpha + _Tp{1})
                                   * (this->beta + _Tp{1})
                                   / (__abp2i + _Tp{1})) / __abp2i;
      const auto a2mb2 = (this->beta - this->alpha)
                        * (this->beta + this->alpha);
      for (int __i = 1; __i < this->order; ++__i)
        {
          const auto abp2ip2 = __abp2i + _Tp{2};
          __diag[__i] = a2mb2 / __abp2i / abp2ip2;
          const auto __ip1 = _Tp(__i + 1);
          __subd[__i] = std::sqrt(_Tp(4 * __ip1) * (this->alpha + __ip1)
                                  * (this->beta + __ip1) * (__ab + __ip1)
                                  / (abp2ip2 * abp2ip2 - _Tp{1})) / abp2ip2;
          __abp2i += _Tp{2};
        }
      __detail::__golub_welsch(__mu_0, this->order, __diag, __subd,
                               this->point, this->weight);
    }
Member Data Documentation
alpha
template<typename _Tp>
_Tp __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::alpha
Definition at line 155 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral().
beta
template<typename _Tp>
_Tp __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::beta
Definition at line 156 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral().
operator()
template<typename _Tp>
template<typename _FuncTp >
decltype(std::invoke_result_t<_FuncTp, _Tp>{} * _Tp{} __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::operator()) (_FuncTp __func, _Tp __a, _Tp __b) const
Definition at line 162 of file gauss_quadrature.h.
order
template<typename _Tp>
int __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::order
Definition at line 154 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral().
The documentation for this struct was generated from the following files:
include/ext/gauss_quadrature.h
include/ext/gauss_quadrature.tcc