jac_quadrature< _Tp > Struct Template Reference
Struct used to store information and memory on the quadrature.
#include <jacobi.h>
Public Member Functions
jac_quadrature (gauss_quad_type qtype, int nq, _Tp a, _Tp b)
~jac_quadrature ()=default
template<typename _Func >
_Tp integrate (_Func fun)
Calculates the integral of a function with values at quadrature points given by f with quadrature weights w.
Public Attributes
_Tp alpha
Alpha weight of the quadrature.
_Tp beta
Beta weight of the quadrature.
int Q
Number of quadrature points.
enum gauss_quad_type type
Quadrature type.
Detailed Description
template<typename _Tp>
struct jac_quadrature< _Tp >
Struct used to store information and memory on the quadrature.
This strucuture is used to store data about the quadrature. It can be later used to integrate, derive or interpolate functions. It should be created using the jac_quadrature_alloc function.
Definition at line 64 of file jacobi.h.
Constructor & Destructor Documentation
jac_quadrature()
template<typename _Tp >
jac_quadrature< _Tp >::jac_quadrature (gauss_quad_type qtype, int nq, _Tp a, _Tp b) [inline]
Definition at line 78 of file jacobi.h.
References __gnu_cxx::_Tp, jac_quadrature< _Tp >::integrate(), and jac_quadrature< _Tp >::~jac_quadrature().
    : type(qtype), Q(nq), alpha(a), beta(b),
      x(nq), w(nq), D(nq),
      xp{}, imat{}
    {
      this->quadrature_zwd();
    }
 jac_quadrature()
template<typename _Tp >
jac_quadrature< _Tp >::~jac_quadrature () [default]
Referenced by jac_quadrature< _Tp >::jac_quadrature().
Member Function Documentation
integrate()
template<typename _Tp >
template<typename _Func >
_Tp jac_quadrature< _Tp >::integrate (_Func fun)
Calculates the integral of a function with values at quadrature points given by f with quadrature weights w.
Aproximates the integral of a function using a a quadrature.
 \int_{-1}^1 f(x) dx \approx \sum_{i=0}^{Q-1} w_i f(x_i) 
Where $x_i$ and $w_i$ are given by the quadrature method emplyed.
Parameters
quad A structure containing quadrature information
f Value of function at quadrature points
Returns
$\int_{-1}^{1} f(x) dx \approx \sum_{i=0}^{Q-1} w_i f(x_i)$
Definition at line 220 of file gauss_jacobi_interface.tcc.
References __gnu_cxx::_Tp, and matvec().
Referenced by jac_quadrature< _Tp >::jac_quadrature().
    {
      std::vector<_Tp> f(this->Q);
      for (int i = 0; i < this->Q; ++i)
        f[i] = fun(this->x[i]);
      return std::inner_product(std::begin(this->w), std::end(this->w),
                                std::begin(f), _Tp{0});
    }
Member Data Documentation
alpha
template<typename _Tp >
_Tp jac_quadrature< _Tp >::alpha
Alpha weight of the quadrature.
Definition at line 73 of file jacobi.h.
beta
template<typename _Tp >
_Tp jac_quadrature< _Tp >::beta
Beta weight of the quadrature.
Definition at line 76 of file jacobi.h.
Q
template<typename _Tp >
int jac_quadrature< _Tp >::Q
Number of quadrature points.
Definition at line 70 of file jacobi.h.
type
template<typename _Tp >
enum gauss_quad_type jac_quadrature< _Tp >::type
Quadrature type.
Definition at line 67 of file jacobi.h.
The documentation for this struct was generated from the following files:
include/ext/jacobi.h
include/ext/gauss_jacobi_integrate.tcc
include/ext/gauss_jacobi_interface.tcc