emsr::fn_qaws< Tp, FuncTp > Struct Template Reference
Public Types
using AreaTp = decltype(RetTp{} *Tp{})
using RetTp = std::invoke_result_t< FuncTp, Tp >
Public Member Functions
fn_qaws (const qaws_integration_table< Tp > *tab, FuncTp func, Tp a_in, Tp b_in)
RetTp eval_left (Tp) const
RetTp eval_middle (Tp) const
RetTp eval_right (Tp) const
Public Attributes
Tp a
Tp b
FuncTp func
const qaws_integration_table< Tp > * table
Detailed Description
template<typename Tp, typename FuncTp>
struct emsr::fn_qaws< Tp, FuncTp >
Definition at line 328 of file qaws_integrate.tcc.
Member Typedef Documentation
AreaTp
template<typename Tp , typename FuncTp >
using emsr::fn_qaws< Tp, FuncTp >::AreaTp = decltype(RetTp{} * Tp{})
Definition at line 331 of file qaws_integrate.tcc.
RetTp
template<typename Tp , typename FuncTp >
using emsr::fn_qaws< Tp, FuncTp >::RetTp = std::invoke_result_t<FuncTp, Tp>
Definition at line 330 of file qaws_integrate.tcc.
Constructor & Destructor Documentation
fn_qaws()
template<typename Tp , typename FuncTp >
emsr::fn_qaws< Tp, FuncTp >::fn_qaws (const qaws_integration_table< Tp > * tab, FuncTp func, Tp a_in, Tp b_in) [inline]
Definition at line 338 of file qaws_integrate.tcc.
      : table(tab),
        func(func), a(a_in), b(b_in)
      { }
Member Function Documentation
eval_left()
template<typename Tp , typename FuncTp >
std::invoke_result_t< FuncTp, Tp > emsr::fn_qaws< Tp, FuncTp >::eval_left (Tp x) const
Definition at line 372 of file qaws_integrate.tcc.
    {
      auto factor = Tp{1};
      if (this->table->alpha != Tp{0})
        factor *= std::pow(x - this->a, this->table->alpha);
      if (this->table->mu == 1)
        factor *= std::log(x - this->a);
      return factor * this->func(x);
    }
References emsr::qaws_integration_table< Tp >::alpha, emsr::qaws_integration_table< Tp >::mu, and Tp.
Referenced by emsr::qc25s().
eval_middle()
template<typename Tp , typename FuncTp >
std::invoke_result_t< FuncTp, Tp > emsr::fn_qaws< Tp, FuncTp >::eval_middle (Tp x) const
Definition at line 351 of file qaws_integrate.tcc.
    {
      auto factor = Tp{1};
      if (this->table->alpha != Tp{0})
        factor *= std::pow(x - this->a, this->table->alpha);
      if (table->mu == 1)
        factor *= std::log(x - this->a);
      if (this->table->beta != Tp{0})
        factor *= std::pow(this->b - x, this->table->beta);
      if (table->nu == 1)
        factor *= std::log(this->b - x);
      return factor * this->func(x);
    }
References emsr::qaws_integration_table< Tp >::alpha, emsr::qaws_integration_table< Tp >::beta, emsr::qaws_integration_table< Tp >::mu, emsr::qaws_integration_table< Tp >::nu, and Tp.
Referenced by emsr::qc25s().
eval_right()
template<typename Tp , typename FuncTp >
std::invoke_result_t< FuncTp, Tp > emsr::fn_qaws< Tp, FuncTp >::eval_right (Tp x) const
Definition at line 387 of file qaws_integrate.tcc.
    {
      auto factor = Tp{1};
      if (this->table->beta != Tp{0})
        factor *= std::pow(this->b - x, this->table->beta);
      if (this->table->nu == 1)
        factor *= std::log(this->b - x);
      return factor * this->func(x);
    }
References emsr::qaws_integration_table< Tp >::beta, emsr::qaws_integration_table< Tp >::nu, and Tp.
Referenced by emsr::qc25s().
Member Data Documentation
a
template<typename Tp , typename FuncTp >
Tp emsr::fn_qaws< Tp, FuncTp >::a
Definition at line 335 of file qaws_integrate.tcc.
b
template<typename Tp , typename FuncTp >
Tp emsr::fn_qaws< Tp, FuncTp >::b
Definition at line 336 of file qaws_integrate.tcc.
func
template<typename Tp , typename FuncTp >
FuncTp emsr::fn_qaws< Tp, FuncTp >::func
Definition at line 334 of file qaws_integrate.tcc.
table
template<typename Tp , typename FuncTp >
const qaws_integration_table<Tp>* emsr::fn_qaws< Tp, FuncTp >::table
Definition at line 333 of file qaws_integrate.tcc.
The documentation for this struct was generated from the following file:
include/emsr/qaws_integrate.tcc