__gnu_cxx::gauss_legendre_table< _Tp > Struct Template Reference
#include <gauss_legendre_table.h>
Public Member Functions
gauss_legendre_table (std::size_t __n, const _Tp *__pt, const _Tp *__wt, bool __precomp)
gauss_legendre_table (std::size_t n)
std::tuple< _Tp, _Tp > get_point (_Tp __a, _Tp __b, std::size_t __i) const
_Tp pt (std::size_t __i) const
_Tp wt (std::size_t __i) const
Public Attributes
std::size_t i_precomp = -1
std::size_t order
const _Tp * point
bool precomputed = false
std::vector< __gnu_cxx::__quadrature_point_t< _Tp > > rule
const _Tp * weight
Detailed Description
template<typename _Tp>
struct __gnu_cxx::gauss_legendre_table< _Tp >
Definition at line 66 of file gauss_legendre_table.h.
Constructor & Destructor Documentation
gauss_legendre_table() [1/2]
template<typename _Tp>
__gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table (std::size_t __n, const _Tp * __pt, const _Tp * __wt, bool __precomp) [inline]
Definition at line 75 of file gauss_legendre_table.h.
References __gnu_cxx::_Tp, __gnu_cxx::gauss_legendre_table< _Tp >::get_point(), __gnu_cxx::gauss_legendre_table< _Tp >::pt(), __gnu_cxx::gauss_legendre_table< _Tp >::wt(), and __gnu_cxx::x2.
      : order(__n),
        point(__pt),
        weight(__wt),
        precomputed(__precomp),
        i_precomp(-1),
        rule()
      { }
gauss_legendre_table() [2/2]
template<typename _Tp >
__gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table (std::size_t n) [explicit]
Definition at line 38 of file gauss_legendre_table.tcc.
References __gnu_cxx::gauss_legendre_precomp, __gnu_cxx::gauss_legendre_table< _Tp >::i_precomp, __gnu_cxx::num_gauss_legendre_precomp, __gnu_cxx::gauss_legendre_table< _Tp >::order, __gnu_cxx::gauss_legendre_table< _Tp >::precomputed, and __gnu_cxx::gauss_legendre_table< _Tp >::rule.
      : order(__n),
        point(nullptr),
        weight(nullptr),
        precomputed(false),
        i_precomp(-1),
        rule()
      {
        using __prec_t = decltype(gauss_legendre_precomp[0]);
        auto __prec_beg = gauss_legendre_precomp;
        auto __prec_end = gauss_legendre_precomp +
      num_gauss_legendre_precomp;
        auto __prec = std::find_if(__prec_beg, __prec_end,
                                   [this, __n](__prec_t __tab)
                                   { return __tab.order == this->order; });
        if (__prec == __prec_end)
          this->rule = std::__detail::__legendre_zeros<_Tp>(this->order);
        else
          {
            this->precomputed = true;
            this->i_precomp = __prec - __prec_beg;
          }
      }
Member Function Documentation
get_point()
template<typename _Tp>
std::tuple< _Tp, _Tp > __gnu_cxx::gauss_legendre_table< _Tp >::get_point (_Tp __a, _Tp __b, std::size_t __i) const
Routine to retrieve the i-th Gauss-Legendre point and weight. Useful when the caller wishes to access the information stored in the high-precision gauss_legendre_table struct. Points are indexed and presented in increasing order to the caller.
Definition at line 69 of file gauss_legendre_table.tcc.
References __gnu_cxx::_Tp, __gnu_cxx::gauss_legendre_table< _Tp >::order, __gnu_cxx::gauss_legendre_table< _Tp >::pt(), and __gnu_cxx::gauss_legendre_table< _Tp >::wt().
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table().
    {
      const auto __hwidth = (__upper - __lower) / _Tp{2};
      const auto __midpt = (__lower + __upper) / _Tp{2};
      if (__i >= this->order)
        std::__throw_domain_error("gauss_legendre_table: i must be less than n");
      // See comments above gauss_legendre_table for struct's x, w layout.
      // Simply unpack that layout into a sorted set of points, weights.
      _Tp __xi, __wi;
      if (this->order & 1) // n is odd
        {
          const auto __k = int(__i) - int(this->order) / 2;
          const auto sign = (__k < 0 ? -1 : +1);
          __xi = __midpt + sign * __hwidth * this->pt(sign * __k);
          __wi = __hwidth * this->wt(sign * __k);
        }
      else if (/* n is even && */ __i < this->order / 2)
        {
          __i = int(this->order) / 2 - 1 - int(__i);
          __xi = __midpt - __hwidth * this->pt(__i);
          __wi = __hwidth * this->wt(__i);
        }
      else // n is even and __i >= n / 2
        {
          __i -= this->order / 2;
          __xi = __midpt + __hwidth * this->pt(__i);
          __wi = __hwidth * this->wt(__i);
        }
      return std::make_tuple(__xi, __wi);
    }
pt()
template<typename _Tp>
_Tp __gnu_cxx::gauss_legendre_table< _Tp >::pt (std::size_t __i) const
Definition at line 106 of file gauss_legendre_table.tcc.
References __gnu_cxx::_Tp, __gnu_cxx::gauss_legendre_precomp, __gnu_cxx::gauss_legendre_table< _Tp >::i_precomp, __gnu_cxx::gauss_legendre_table< _Tp >::order, __gnu_cxx::gauss_legendre_table< _Tp >::point, __gnu_cxx::gauss_legendre_table< _Tp >::precomputed, and __gnu_cxx::gauss_legendre_table< _Tp >::rule.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table(), and __gnu_cxx::gauss_legendre_table< _Tp >::get_point().
    {
      if (this->precomputed)
        if (this->i_precomp == std::size_t(-1))
          return this->point[__i];
        else
          return _Tp(gauss_legendre_precomp[this->
      i_precomp].point[__i]);
      else
        return this->rule[__i + this->order / 2].__point;
    }
wt()
template<typename _Tp>
_Tp __gnu_cxx::gauss_legendre_table< _Tp >::wt (std::size_t __i) const
Definition at line 119 of file gauss_legendre_table.tcc.
References __gnu_cxx::_Tp, __gnu_cxx::gauss_legendre_precomp, __gnu_cxx::gauss_legendre_table< _Tp >::i_precomp, __gnu_cxx::gauss_legendre_table< _Tp >::order, __gnu_cxx::gauss_legendre_table< _Tp >::precomputed, __gnu_cxx::gauss_legendre_table< _Tp >::rule, and __gnu_cxx::gauss_legendre_table< _Tp >::weight.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table(), and __gnu_cxx::gauss_legendre_table< _Tp >::get_point().
    {
      if (this->precomputed)
        if (this->i_precomp == std::size_t(-1))
          return this->weight[__i];
        else
          return _Tp(gauss_legendre_precomp[this->
      i_precomp].weight[__i]);
      else
        return this->rule[__i + this->order / 2].__weight;
    }
Member Data Documentation
i_precomp
template<typename _Tp>
std::size_t __gnu_cxx::gauss_legendre_table< _Tp >::i_precomp = -1
Definition at line 72 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table(), __gnu_cxx::gauss_legendre_table< _Tp >::pt(), and __gnu_cxx::gauss_legendre_table< _Tp >::wt().
order
template<typename _Tp>
std::size_t __gnu_cxx::gauss_legendre_table< _Tp >::order
Definition at line 68 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table(), __gnu_cxx::gauss_legendre_table< _Tp >::get_point(), __gnu_cxx::gauss_legendre_table< _Tp >::pt(), and __gnu_cxx::gauss_legendre_table< _Tp >::wt().
point
template<typename _Tp>
const _Tp* __gnu_cxx::gauss_legendre_table< _Tp >::point
Definition at line 69 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::pt().
precomputed
template<typename _Tp>
bool __gnu_cxx::gauss_legendre_table< _Tp >::precomputed = false
Definition at line 71 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table(), __gnu_cxx::gauss_legendre_table< _Tp >::pt(), and __gnu_cxx::gauss_legendre_table< _Tp >::wt().
rule
template<typename _Tp>
std::vector<__gnu_cxx::__quadrature_point_t<_Tp> > __gnu_cxx::gauss_legendre_table< _Tp >::rule
Definition at line 73 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::gauss_legendre_table(), __gnu_cxx::gauss_legendre_table< _Tp >::pt(), and __gnu_cxx::gauss_legendre_table< _Tp >::wt().
weight
template<typename _Tp>
const _Tp* __gnu_cxx::gauss_legendre_table< _Tp >::weight
Definition at line 70 of file gauss_legendre_table.h.
Referenced by __gnu_cxx::gauss_legendre_table< _Tp >::wt().
The documentation for this struct was generated from the following files:
include/ext/gauss_legendre_table.h
include/ext/gauss_legendre_table.tcc