__gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp > Struct Template Reference
#include <gauss_quadrature.h>
Public Member Functions
fixed_gauss_gegenbauer_integral (int __n, _Tp __lam)
Public Attributes
_Tp lambda
template<typename _FuncTp >
decltype(std::invoke_result_t< _FuncTp, _Tp >{} *_Tp{} operator())(_FuncTp __func, _Tp __a, _Tp __b) const
int order
Detailed Description
template<typename _Tp>
struct __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >
Definition at line 132 of file gauss_quadrature.h.
Constructor & Destructor Documentation
fixed_gauss_gegenbauer_integral()
template<typename _Tp >
__gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::fixed_gauss_gegenbauer_integral (int __n, _Tp __lam) [explicit]
Construct a Gauss-Gegenbauer rule of order n.
Weight function: $ [(b-x)(x-a)]^\lambda $ Constraints: $ \lambda > -1 $
Definition at line 392 of file gauss_quadrature.tcc.
References __gnu_cxx::__func(), __gnu_cxx::__detail::__golub_welsch(), __gnu_cxx::_RetTp, __gnu_cxx::_Tp, __gnu_cxx::fixed_gauss_jacobi_integral< _Tp >::fixed_gauss_jacobi_integral(), __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::lambda, and __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::order.
Referenced by __gnu_cxx::fixed_gauss_chebyshev_w_integral< _Tp >::fixed_gauss_chebyshev_w_integral().
    : order(__n),
      lambda(__lam),
      point(__n),
      weight(__n)
    {
      const auto __ab = _Tp{2} * this->lambda;
      const auto __gam = std::tgamma(this->lambda + _Tp{1});
      const auto __mu_0 = std::pow(_Tp{2}, __ab + _Tp{1})
                        * __gam * __gam / std::tgamma(__ab + _Tp{2});
      std::vector<_Tp> __diag(this->order, _Tp{0});
      std::vector<_Tp> __subd(this->order);
      __subd[0] = std::sqrt(_Tp{1} / (_Tp{2} * this->lambda + _Tp{3}));
      for (int __i = 2; __i <= this->order; ++__i)
        __subd[__i - 1] = std::sqrt(_Tp(__i) * (__ab + _Tp(__i))
                        / (_Tp{4}
                          * std::pow(this->lambda + _Tp(__i), _Tp{2}) -
      _Tp{1}));
      __detail::__golub_welsch(__mu_0, this->order, __diag, __subd,
                               this->point, this->weight);
    }
Member Data Documentation
lambda
template<typename _Tp>
_Tp __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::lambda
Definition at line 135 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::fixed_gauss_gegenbauer_integral().
operator()
template<typename _Tp>
template<typename _FuncTp >
decltype(std::invoke_result_t<_FuncTp, _Tp>{} * _Tp{} __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::operator()) (_FuncTp __func, _Tp __a, _Tp __b) const
Definition at line 141 of file gauss_quadrature.h.
order
template<typename _Tp>
int __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::order
Definition at line 134 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_gegenbauer_integral< _Tp >::fixed_gauss_gegenbauer_integral().
The documentation for this struct was generated from the following files:
include/ext/gauss_quadrature.h
include/ext/gauss_quadrature.tcc