__gnu_cxx::fixed_gauss_exponential_integral< _Tp > Struct Template Reference
#include <gauss_quadrature.h>
Public Member Functions
fixed_gauss_exponential_integral (int __n, _Tp __alf)
Public Attributes
_Tp alpha
template<typename _FuncTp >
decltype(std::invoke_result_t< _FuncTp, _Tp >{} *_Tp{} operator())(_FuncTp __func, _Tp __a, _Tp __b) const
int order
Detailed Description
template<typename _Tp>
struct __gnu_cxx::fixed_gauss_exponential_integral< _Tp >
Definition at line 213 of file gauss_quadrature.h.
Constructor & Destructor Documentation
fixed_gauss_exponential_integral()
template<typename _Tp >
__gnu_cxx::fixed_gauss_exponential_integral< _Tp >::fixed_gauss_exponential_integral (int __n, _Tp __alf) [explicit]
Construct a Generalized Gauss-Exponential rule of order n.
Interval: $ (a, b) $ Weight function: $ |x - (a + b) / 2|^\alpha $ Constraints: $ \alpha > -1 $
Definition at line 660 of file gauss_quadrature.tcc.
References __gnu_cxx::__func(), __gnu_cxx::__detail::__golub_welsch(), __gnu_cxx::_RetTp, __gnu_cxx::_Tp, __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::alpha, __gnu_cxx::fixed_gauss_rational_integral< _Tp >::fixed_gauss_rational_integral(), and __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::order.
Referenced by __gnu_cxx::fixed_gauss_hermite_integral< _Tp >::fixed_gauss_hermite_integral().
    : order(__n),
      alpha(__alf),
      point(__n),
      weight(__n)
    {
      const auto __mu_0 = _Tp{2} / (this->alpha + _Tp{1});
      std::vector<_Tp> __diag(this->order, _Tp{0});
      std::vector<_Tp> __subd(this->order);
      auto __ap2i = this->alpha;
      for (int __i = 1; __i <= this->order; ++__i)
        {
          __ap2i += _Tp{2};
          __subd[__i - 1] = (_Tp(__i) + _Tp(__i % 2) * this->alpha)
                          / std::sqrt((__ap2i * __ap2i - _Tp{1}));
        }
      __detail::__golub_welsch(__mu_0, this->order, __diag, __subd,
                               this->point, this->weight);
    }
Member Data Documentation
alpha
template<typename _Tp>
_Tp __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::alpha
Definition at line 216 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::fixed_gauss_exponential_integral().
operator()
template<typename _Tp>
template<typename _FuncTp >
decltype(std::invoke_result_t<_FuncTp, _Tp>{} * _Tp{} __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::operator()) (_FuncTp __func, _Tp __a, _Tp __b) const
Definition at line 222 of file gauss_quadrature.h.
order
template<typename _Tp>
int __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::order
Definition at line 215 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_exponential_integral< _Tp >::fixed_gauss_exponential_integral().
The documentation for this struct was generated from the following files:
include/ext/gauss_quadrature.h
include/ext/gauss_quadrature.tcc