__gnu_cxx::fixed_gauss_legendre_integral< _Tp > Struct Template Reference
#include <gauss_quadrature.h>
Public Member Functions
fixed_gauss_legendre_integral (int __n)
Public Attributes
template<typename _FuncTp >
decltype(std::invoke_result_t< _FuncTp, _Tp >{} *_Tp{} operator())(_FuncTp __func, _Tp __a, _Tp __b) const
int order
Detailed Description
template<typename _Tp>
struct __gnu_cxx::fixed_gauss_legendre_integral< _Tp >
Build the absiscae and weights of a Gauss quadrature rule from a symmetric tridiagonal Jacobi matrix.
Definition at line 34 of file gauss_quadrature.h.
Constructor & Destructor Documentation
fixed_gauss_legendre_integral()
template<typename _Tp >
__gnu_cxx::fixed_gauss_legendre_integral< _Tp >::fixed_gauss_legendre_integral (int __n) [explicit]
Construct a Gauss-Legendre rule of order n.
Weight function: $ 1 $ Constraints: $ b > a $
Definition at line 88 of file gauss_quadrature.tcc.
References __gnu_cxx::__func(), __gnu_cxx::__detail::__golub_welsch(), __gnu_cxx::_RetTp, __gnu_cxx::_Tp, __gnu_cxx::fixed_gauss_chebyshev_t_integral< _Tp >::fixed_gauss_chebyshev_t_integral(), and __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::order.
Referenced by __gnu_cxx::__detail::__golub_welsch().
    : order(__n),
      point(__n),
      weight(__n)
    {
      const auto __mu_0 = _Tp{2};
      std::vector<_Tp> __diag(this->order, _Tp{0});
      std::vector<_Tp> __subd(this->order);
      for (int __i = 1; __i <= this->order; ++__i)
        __subd[__i - 1] = _Tp(__i) / std::sqrt(_Tp(4 * __i * __i - 1));
      __detail::__golub_welsch(__mu_0, this->order, __diag, __subd,
                               this->point, this->weight);
    }
Member Data Documentation
operator()
template<typename _Tp>
template<typename _FuncTp >
decltype(std::invoke_result_t<_FuncTp, _Tp>{} * _Tp{} __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::operator()) (_FuncTp __func, _Tp __a, _Tp __b) const
Definition at line 42 of file gauss_quadrature.h.
order
template<typename _Tp>
int __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::order
Definition at line 36 of file gauss_quadrature.h.
Referenced by __gnu_cxx::fixed_gauss_legendre_integral< _Tp >::fixed_gauss_legendre_integral().
The documentation for this struct was generated from the following files:
include/ext/gauss_quadrature.h
include/ext/gauss_quadrature.tcc